### ISSUE TITLE
	on the web ui startTime  auto refresh?

### ISSUE THREAD

**Issue by xjr100419** [apache/incubator-skywalking#1004]
![0 zptg nppv 48wygpw 4](https://user-images.githubusercontent.com/8691355/38133283-2be998a2-3441-11e8-94c7-40d98f5b375e.png)
![54rvnn yk0zfwq ynv uqau](https://user-images.githubusercontent.com/8691355/38133294-3176a936-3441-11e8-8d20-bad9e6c86d4d.png)

Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug

___
### Question
- What do you want to know?

	on the webui startTime  auto refresh?

**Comment by peng-yongsheng** [comment]
@hanahmily I tested the `queryBasicTraces` service, the result returned from collector is correct.

**Comment by candyleer** [comment]
@xjr100419 this bug has been fixed in skywalking-ui module in [https://github.com/apache/incubator-skywalking-ui/pull/156](https://github.com/apache/incubator-skywalking-ui/pull/156)

**Comment by wu-sheng** [comment]
Fixed and closing this.

**Comment by xjr100419** [comment]
![tim 20180418155007](https://user-images.githubusercontent.com/8691355/38918436-44730988-4320-11e8-982c-76c31209ae63.png)

startTime is not auto refresh now
but There is no correct ordering

**Comment by xjr100419** [comment]
https://github.com/apache/incubator-skywalking-ui
i git the master branch  and run 
npm install
npm run build
npm run start:no-mock



![tim 20180418155435](https://user-images.githubusercontent.com/8691355/38918616-d7a2c086-4320-11e8-8d17-d1f64aefa7de.png)


it Trigger other exceptions

@candyleer

**Comment by candyleer** [comment]
@xjr100419  what's your version of server ?

**Comment by xjr100419** [comment]
@candyleer 
apache-skywalking-apm-incubating-5.0.0-alpha.zip
