### ISSUE TITLE
Provide dependencies management in collector root pom

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1009]
Because there are a lot of libraries used in collector, and some PRs may add more, in order to manage those well, I proposal to use maven dependencyManagement to list all used libraries and their versions in collector root pom.

All modules in collector-* are not allowed to dependency an existed library with given version. Update version should be taken seriously.

I hope this could be provided at least before #871 merging.

**Comment by peng-yongsheng** [comment]
OK, I finish this tomorrow.

**Comment by wu-sheng** [comment]
Provided, closing.
