### ISSUE TITLE
Adjust source release document

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1010]
The `Build and sign the source code package` section of release document, should be adjust based on IPMC vote discussion.

https://lists.apache.org/thread.html/91a9f8d720d26426631b9bb91d698d106cab5b5a32addee12ab7163b@%3Cgeneral.incubator.apache.org%3E

Don't build the source code from the preview staging codes, which includes `mvn package`(mvn test, too). 

Please consider to use a new folder to run `git clone .... --recurse-submodules` by @johnament suggestion.

**Comment by peng-yongsheng** [comment]
OK, from that mail, we can do it step by step such as:
1. Cloning into 'incubator-skywalking'
1. Submodule 'apm-protocol/apm-network/src/main/proto'
1. Submodule 'skywalking-ui'
1. packed

**Comment by peng-yongsheng** [comment]
Done
