### ISSUE TITLE
Ask some helps for Chinese document

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1024]
Based on Apache requirements, we provided all documents in English as default. But we have a lot of Chinese end users, so, we are always looking for people to help us sync our official documents.

**Comment by smartwuwei** [comment]
请问吴工，我想跟踪RPC服务之间的上下行参数应该怎么去做？目前sw不支持，麻烦给一个大致的思路

**Comment by wu-sheng** [comment]
> 请问吴工，我想跟踪RPC服务之间的上下行参数应该怎么去做？目前sw不支持，麻烦给一个大致的思路

English issue only. For the different issue, submit new to discuss.

**Comment by smartwuwei** [comment]
Excuse me, Mr Wu , how do I want to track the upper and lower parameters between RPC services? At present, SW does not support. Give me a rough ideam, thanks

**Comment by wu-sheng** [comment]
> Excuse me, Mr Wu , how do I want to track the upper and lower parameters between RPC services? At present, SW does not support. Give me a rough ideam, thanks

Again, submit a new issue to discuss this.
