### ISSUE TITLE
Unable to attach source

### ISSUE THREAD

**Issue by zone1511** [apache/incubator-skywalking#1025]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- checkstyle violation occurs if added source:jar as one of maven goal. If source:jar is omitted, no source jar is installed to local repository.

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- adding  <sourceDirectory>${project.build.sourceDirectory}</sourceDirectory> in checkstyle plugin can resolve the issue.

**Comment by wu-sheng** [comment]
@zone1511 I am not familiar with your question and error. Can you provide more logs? What is happening?

**Comment by wu-sheng** [comment]
I got `BUILD SUCCESS` after I run `mvn source:jar`. Do you run this in `master` branch? From my experience, our Apache release already includes the source code jars. This should work.
