### ISSUE TITLE
Collector performance optimization

### ISSUE THREAD

**Issue by peng-yongsheng** [apache/incubator-skywalking#1032]
1. Use collector instrument module to collect performance metrics report.
2. Improve the segment parse action's performance.

**Comment by peng-yongsheng** [comment]
### Report digest
```
metric name: /persistence, avg: 372859, rate: 0, calls: 100039, total: 37(s)
metric name: /segment/parse, avg: 274427, rate: 0, calls: 56000, total: 15(s)
metric name: /persistence/get, avg: 2828750, rate: 0, calls: 4464, total: 12(s)
```
Those points could be a source of performance bottlenecks.

### Performance optimization
#### Segment parse
- Change cache component from Guava to Caffeine, [ Caffeine's Benchmarks](https://github.com/ben-manes/caffeine/wiki/Benchmarks#read-100)

**Comment by wu-sheng** [comment]
Done. Please consider post the backend performance report. Maybe we could post that in InfoQ.
