### ISSUE TITLE
Download page must include links to KEYS, sigs, hashes

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-skywalking#1033]
The download page:
http://skywalking.apache.org/downloads/
must include links to KEYS, sigs and hashes and should indicate how to verify downloads.
Please see:
http://www.apache.org/dev/release-distribution#sigs-and-sums

**Comment by wu-sheng** [comment]
Download page updated.

![image](https://user-images.githubusercontent.com/5441976/38310590-8c38491c-384f-11e8-8968-086cd29b60e4.png)

**Comment by sebbASF** [comment]
Sorry, but the KEYS, sigs and hashes URLs must not use dist.apache.org. That host is not intended for public use; it is only for ASF developers when staging releases.

As per the next section on the same page:
http://www.apache.org/dev/release-distribution#download-links

"All links to checksums, detached signatures and public keys MUST reference www.apache.org/dist/ using https:// (TLS)."

For example:

https://www.apache.org/dist/incubator/skywalking/5.0.0-alpha/KEYS

Also the KEYS file must contain the keys for all releases, so it should be in the parent directory, i.e.

https://www.apache.org/dist/incubator/skywalking/KEYS

**Comment by wu-sheng** [comment]
Following adjustments done.

- KEYS file has been moved
- URLs of  KEYS, sigs and hashes URLs targets to `https://www.apache.org/dist/incubator/skywalking/****`

**Comment by sebbASF** [comment]
The page should also describe how to verify downloads

**Comment by sebbASF** [comment]
Thanks for the prompt attention to this
