### ISSUE TITLE
Website must have incubation disclaimer and standard copyright footer

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-skywalking#1035]
All podling websites must have an incubation disclaimer.

They must also have a standard copyright footer.

**Comment by wu-sheng** [comment]
@sebbASF Any example about the standard copyright footer?

**Comment by sebbASF** [comment]
This is a question for your mentors

**Comment by michaelsembwever** [comment]
@wu-sheng, the text in the DISCLAIMER file you have in git should also be on the website, more info at https://incubator.apache.org/guides/branding.html#disclaimers

And under that text should be a copyright statement. something like:
```
"Copyright © 2018, The Apache Software Foundation
Apache SkyWalking, SkyWalking, Apache, the Apache feather, and the Apache SkyWalking project logo are either registered trademarks or trademarks of the Apache Software Foundation. "
```

This would go on the bottom where you currently have `© 2018 Apache SkyWalking (incubating)`, replacing it with the disclaimer and the longer copyright sentence.

There's also more info at https://www.apache.org/foundation/marks/pmcs

**Comment by sebbASF** [comment]
Thanks for the prompt attention to this
