### ISSUE TITLE
Refactor the collector configuration initialization.

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1047]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

Right now, the collector configuration initialization is based on properties from yaml, which is cool, but the type of each setting is based on yaml config too. And this cause some problems when I want to override some setting from system properties. In order not to trigger type cast exception, we have to set the default value in yaml, but expected to override, which is very weird.

The second problem of current mechanism is we are using a lot of `x_y_z` in yaml, which is good if only yaml considered. But when we want to override from system env (failed before), we can't find the proper char to separate `module#provider#settingKey`. In system env, `_` is a tradition, so we need remove all `_` in existed settings, and forbid that in the future. 

I think if we use Setting-Object mapping mechanism would helps. Create an object and individual class for each provider, all fields use CamelCase naming and type sensitive .

**Comment by peng-yongsheng** [comment]
Done
