### ISSUE TITLE
Add a FAQ about SkyWalking upgrade

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1050]
Many people (ex #1029) face the SkyWalking upgrade, but miss an important point, which is ES types should be created, all data need to remove.

I hope @peng-yongsheng could provide a document to description this.

**Comment by peng-yongsheng** [comment]
Create a new file named `Upgrade.md`, describe all the upgrade FAQ in this file. Create a new section with the title of our project version and use subsection to separate UI, agent, collector when this version have some notices about upgrading.

**Comment by peng-yongsheng** [comment]
Done
