### ISSUE TITLE
log toolkit may do not take effect in some case 

### ISSUE THREAD

**Issue by candyleer** [apache/incubator-skywalking#1055]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
#### Question
 when i start an app (called `test_app`) in IDE,i configure the logback file by following this [instruction](https://github.com/apache/incubator-skywalking/blob/master/docs/en/Application-toolkit-logback-1.x.md),but i found it didn't take effect.
i debug this question step by step in `agent` jar. i found the class `org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout` didn't been transformed.this seems to be strange.what is it happened?
then  i put an `break point` in this place, 
![image](https://user-images.githubusercontent.com/11530760/38506954-e09e8a0a-3c4d-11e8-9694-b6bcee17320b.png)
and see the `debug` stack trace in ide ,Suddenly I understand.
![image](https://user-images.githubusercontent.com/11530760/38507096-246a5dae-3c4e-11e8-98a0-76d6dd81edc8.png)
from this picture, we can see that the `TraceIdPatternLogbackLayout` class was loaded in `premain` method,and invoke by `boot` method.but at that time,the `byte buddy instrument` didn't work.because the code is
```
...
 ServiceManager.INSTANCE.boot();
...
 new AgentBuilder.Default()...
.installOn(instrumentation);
```
that is the class `TraceIdPatternLogbackLayout` loaded is before `instrumentation`.
**this only happens when application code is loaded by `AppClassLoader`,because the `logback.xml` in this classpath.**

in other cases,this code work fine cause their classloader is redefined like `spring boot` or `tomcat` etc. in this cases,the class `TraceIdPatternLogbackLayout` will be loaded only by app code invoke `logger` ,when `agent` started by `AppClassLoader`,it can not see the `logback.xml` config file thus he dont know the class `TraceIdPatternLogbackLayout`,

#### Solution
To resolve this problem ,the simplest way is to change the order of 
```
...
 ServiceManager.INSTANCE.boot();
...
 new AgentBuilder.Default()...
.installOn(instrumentation);
```
to 
```
...
 new AgentBuilder.Default()...
.installOn(instrumentation);
...
 ServiceManager.INSTANCE.boot();
```
that is first invoke `instrumentation` then boot all service in case of the boot service contains some method need to be enhanced.
but i dont know if there has some other problem will be caused?
so please check
i test  logback only , but follow this train of thought,`log4j` and `log4j2` may have the same issue
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Ha, @candyleer I think your analysis is right. This is caused by dependencies of dependencies. Changing the boot sequence looks good for me. All existed boot services are only about timer or listener register.
![image](https://user-images.githubusercontent.com/5441976/38530360-95c9a952-3c9c-11e8-868b-a406c3befc15.png)

For `log4j2`, I think it is another thing need to check. If none of our dependencies used it, it is good for now. 

Please follow your thoughts, and send a pull request to fix this. And I will ask @ascrutae to run the automatic test in SkyWalking infra, to recheck it in real applications.
