### ISSUE TITLE
Log is a conflict

### ISSUE THREAD

**Issue by 906827215** [apache/incubator-skywalking#1056]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ 1] Bug
- [ ] Requirement
- [ 1] Feature or performance improvement

___
### Question
- What do you want to know?
On the conflict of log
___
### Bug
- Which version of SkyWalking, OS and JRE?
sky 3.2.6 
- Which company or project?

- What happen?
When I used skywalking 3.2.6, I saw that TID is N/A in log. At first, I thought the probe was not activated, and then eliminated it one by one. Try a variety of possibilities, excluding the possibility that the probe is not activated (on my UI and the TID on collerctor), and later found that the cause of this error is that there is a conflict of log packets, for example I use hibernate-validator-5.1.3.Final.jar, which depends on log.
![640ypn3 ic 2ar3fnc 2 7](https://user-images.githubusercontent.com/24824256/38532438-6f47a99a-3ca7-11e8-8300-9fe90dbd42c1.png)
![rru y c93bkb 1o_q3 x2n3](https://user-images.githubusercontent.com/24824256/38532439-6f938e96-3ca7-11e8-9b0b-458a3ac1453c.png)

There is also a logkit-1.0.1.jar conflict problem. I am verifying it.___
### Requirement or improvement
The most important thing about sky is about the use of logs, or we expect to have a perfect log jar conflict solution. Thanks.

**Comment by 906827215** [comment]
@wu-sheng Hi, the reasons for more specific conflicts are not clear now. I only know that when I used it, it was because there were multiple log frameworks in my application that caused TID N/A in the log, but TID was correct when I removed the redundant log framework. But my application has to rely on the previous log framework, so there is a mistake. That's why we hope that we can have a good solution to this problem in the future. Above

**Comment by wu-sheng** [comment]
@906827215 Oh, that is a very complex scenario, I have a guess, which is maybe our toolkit depends a log library, that has conflicts with your existed libs. This is only my suggestion.

Also, recommend you to review #1055 , which has similar situation. May be helpful. FYI @candyleer
