### ISSUE TITLE
agent_gRPC这里是不是得配置成自己的外网IP？

### ISSUE THREAD

**Issue by gMan1990** [apache/incubator-skywalking#1065]
https://github.com/apache/incubator-skywalking/blob/03824c2f8f43d55746ac466f0252bd78c1b48363/apm-collector/apm-collector-boot/src/main/resources/application.yml#L16
在日志里看到报错，找到程序里有个地方会请求如下的地址：
```
curl http://<your_ip>:10800/agent/gRPC
返回: ["<your_config>:11800"]
```

**Comment by wu-sheng** [comment]
Closing this.
