### ISSUE TITLE
skywalking.org has been hacked

### ISSUE THREAD

**Issue by tiffon** [apache/incubator-skywalking#1077]
Looks like http://skywalking.org/ has been hacked.

For instance, it just redirected me to: http://www.memevibe.com/2017/05/01/top-10-handsome-men-usa/

**Comment by wu-sheng** [comment]
Hi, skywalking.org has not been used by ours. Becausing of moving into apache, we only keep skywalking.io and skywalking.apache.org 

Is there any place still pointing to skywalking.org ?

**Comment by tiffon** [comment]
I see, thanks.

I'm only aware of the [OpenTracing](http://opentracing.io) site.

Ref: opentracing/opentracing.io#265
