### ISSUE TITLE
Refactor ServerTypeDefine and ComponentsDefine to be more extendable

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1078]
ServerTypeDefine and ComponentsDefine are now defined in SkyWalking project as Java file. In before, this is good, but now, our community grows. From @liuhaoyang 's .NET SDK experiences,  he need to extend these two to support .NET ecosystem.

So, I proposal to change the defines to be in file, and provide a document to describe it, which is easier to understand find and extend.

Hope anyone has time to contribute this feature. And provide this in 5.0.0-beta and binding with .NET agent 0.1

**Comment by wu-sheng** [comment]
FYI @ascrutae @peng-yongsheng

**Comment by peng-yongsheng** [comment]
My schedule is full during the improve feature of 5.0.0-beta.

**Comment by wu-sheng** [comment]
Working on this. Provide extention to any language implementor.

**Comment by wu-sheng** [comment]
Supported. @liuhaoyang and @ascrutae you can send your .NET and nodejs components now. 

I proposal to reserve 1000-2000 to .NET, and 2000-3000 to nodejs, but if you are using the same components as Java, e.g. mysql, please consider to add languages under MySQL, rather than add a new one.

**Comment by ascrutae** [comment]
got it, Thanks
