### ISSUE TITLE
oracle.10-x.plugin failure                      oracle.jdbc.driver.T4CPreparedStatement    java.lang.NullPointerException

### ISSUE THREAD

**Issue by wikiios** [apache/incubator-skywalking#1084]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
I was using skywalking-5.0.0-alpha to improve my web-app(SSM,DB---oracle)
but  oracle.10-x.plugin cause a failure.

logs show:

ERROR [timestamp]  InstMethodsInter   :   class[oracle.jdbc.driver.T4CPreparedStatement ]  after method[execute] intercept failure
 java.lang.NullPointerException
         org.apache.skywalking.apm.plugin.jdbc.oracle.PreparedStatementExecuteMethodsInterceptor.afterMethod(PreparedStatementExecuteMethodsInterceptor
___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0
JRE 1.8
Linux

- Which company or project?
PingAn Tecnology School

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ascrutae** [comment]
yeah. maybe some cases have not been tested.  Could you post me simple demo or the version about oracle driver ?

**Comment by ascrutae** [comment]
I cannot reproduce this issue And here is my test environment.

| environment| version|
|:---|:---|
|Agent| 5.0.0-alpha|
|Oracle jdbc driver|11.2.0.4|
|Oracle version| 12c|

 Could you post me a demo to reproduce this issue?

**Comment by ni-ze** [comment]
Is this problem solved?  It  seems to be  the same bug in 5.0.0-GA.

**Comment by wu-sheng** [comment]
Nothing update. And oracle plugin has been moved to openskywalking to release for license issue.
