### ISSUE TITLE
Incorrect order of spans in UI trace graphql

### ISSUE THREAD

**Issue by hanahmily** [apache/incubator-skywalking#1097]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ x ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0-alpha

- What happen?

The `queryTrace` query returns an incorrect order of spans. Due to https://github.com/apache/incubator-skywalking-ui/issues/139  description, the Kafka consumer span was placed at the first place where the chart could not draw the arrow.

**Comment by wu-sheng** [comment]
@peng-yongsheng New trace query has been canceled in beta. Please fix this.
