### ISSUE TITLE
Look for SkyWalking PHP support

### ISSUE THREAD

**Issue by NorthWindTR** [apache/incubator-skywalking#1143]
Hi, I want to ask is there a plan to support PHP?
If no, It's difficult to implement it by ourselves?

------------------------------------------------------

如题
php也有个zend引擎层，貌似好像也可以做零侵入，请问后续有相关的计划么？
我们的服务主体还是java实现的，部分业务逻辑用php实现，如果使用php的话，假如没有零侵入方案，可以自己实现采集上报么，不知道这个逻辑实现起来代码大不大？

非常感谢

**Comment by wu-sheng** [comment]
Hi, @NorthWindTR I hope you could update your issue into English for more people could know what you are asking.

**Comment by liuhaoyang** [comment]
@NorthWindTR About PHP SDK, you can refer to https://github.com/SkywalkingContrib/skywalking-php-sdk

**Comment by wu-sheng** [comment]
And there is a PHP SDK, provided by @songzhian (dangdang.com), which should be a half-auto instrument way.

But sadly, it only support 3.2.6 by its 2.0. I didn't find any project or team to work on 5.x support. @songzhian are you going to update?

**Comment by NorthWindTR** [comment]
Thank you for your answer

I would change it to English

**Comment by wu-sheng** [comment]
See #1567 . I hope molten's SkyWalking version could be open sourced and released soon. FYI @tincopper you will have several funs.
