### ISSUE TITLE
Add unknown node image 404 error handler

### ISSUE THREAD

**Issue by hanahmily** [apache/incubator-skywalking#1160]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- What happen?
![](https://user-images.githubusercontent.com/10701915/39585311-12450dfe-4f27-11e8-9a4c-9c091db7aca6.png)

There is no image for unknown node type.

**Comment by wu-sheng** [comment]
This feature moves into beta2. And ask community contributor to help. FYI @liuhaoyang
