### ISSUE TITLE
Clean buffer files by default when restart collector.

### ISSUE THREAD

**Issue by peng-yongsheng** [apache/incubator-skywalking#1162]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Bug
___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0-alpha

- What happen?
Somebody restart collector after clean elastic search indexes. But they do not clean buffer files then  they can see so many exception message in collector log files.

**Comment by wu-sheng** [comment]
Fixed.
