### ISSUE TITLE
improvement：hope skywalking ui support multi environment data viewing

### ISSUE THREAD

**Issue by HouZhiHouJue** [apache/incubator-skywalking#1172]
for users ,this is more convenient,thanks.

**Comment by wu-sheng** [comment]
What do you mean `multi environment data viewing`? I am not following.

**Comment by HouZhiHouJue** [comment]
for example ,you have two environment ,so you will deploy two clusters of collector ,and also elasticsearch. but for ui,  I  want to deploy just one cluster, and there is a drop box ,which can switch environment  to view diffrent data in diffrent elasticsearch clusters.

**Comment by wu-sheng** [comment]
Oh, I see. This is a complex requirement. I doubt the UI team will be interested in this feature. 

ping @hanahmily What do you thing?

**Comment by wu-sheng** [comment]
Multiple tenancies will not be supported I think.
