### ISSUE TITLE
Hope to Add application name in service search view

### ISSUE THREAD

**Issue by candyleer** [apache/incubator-skywalking#1176]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

in service view,if I have same service name in different application, like this
![image](https://user-images.githubusercontent.com/11530760/39664313-e1925110-50b3-11e8-91cd-b7826ab2a39e.png)
I cannot figure out which is my target.

**Comment by wu-sheng** [comment]
Yes, it is. It is on the roadmap.

**Comment by wu-sheng** [comment]
Add new query service based on applicationId. And redesign the service view.

**Comment by wu-sheng** [comment]
@hanahmily @peng-yongsheng Both sides are provided and merged, I am closing this.
