### ISSUE TITLE
Provide dynamic refresh file in agent

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1181]
This requirement came from the upgrade, SkyWalking's agent and protocol are stable enough, and didn't need to update for a long time. But considering right now, there are a lot of buffer in agent, so end users must reboot the monitored applications to upgrade backend, which caused by backend upgrade is not forward-compatible.

I proposal to provide a dynamic flush like this:
```properties
# false by default, change to `true` if need runtime refresh.
# After refresh happends, agent will rewrite this to true.
need_refresh=false
# default value is reboot time. After refresh happends, agent will rewrite this timestamp
last_refresh_time = xxxxx
```

By having this feature, the backend break upgrade should be:
1. Stop all backends.
1. Clear the ElasticSearch data.
1. Set all flush file to **true**, and wait all agents refreshed and updated the new refresh time.
1. Start up new version collector.

FYI @hanahmily @peng-yongsheng @liuhaoyang @yuleyule66

**Comment by ascrutae** [comment]
Get it.
