### ISSUE TITLE
Span detail in trace view should be in message box 

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1188]
In Beta, we change the span in the bottom of the trace view, some one give us the feedback:

> If the trace contains a lot of spans, let's say more than 50, the span detail is out of explorer visible area. User has to scroll the screen. It is not convenience.

**Comment by liuhaoyang** [comment]
Is it possible to support spans to collapse and expand based on dependencies? 
Just like zipkin:
![image](https://user-images.githubusercontent.com/10701915/39747488-04e7cea0-52e0-11e8-8dcf-98fbead2c9eb.png)

**Comment by wu-sheng** [comment]
I and @hanahmily have some aggressive ideas, but we are afraid may effect the stable. So may choose an easy but better way to fix this. 

Then we can release our 5.0.0-GA. I think the community really need this version.

**Comment by hanahmily** [comment]
@wu-sheng I agree with your idea. We should support this feature in next major version which is not 5.0.0.

**Comment by wu-sheng** [comment]
Not in 5.x
