### ISSUE TITLE
Invalid calls in Service topology query

### ISSUE THREAD

**Issue by hanahmily** [apache/incubator-skywalking#1195]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- Which version of SkyWalking, OS and JRE?

5.0.0-alpha

- What happen?

Invalid calls in `getServiceTopology` (refer to https://github.com/apache/incubator-skywalking-ui/issues/141)

**Comment by wu-sheng** [comment]
I confirmed with the users, they clear collector but don't reboot the application. So no node register and calls between unexist nodes still happen. Which could trigger this problem.

@peng-yongsheng We may need to consider to check application instance id when we receive data. 

If the check mechanism provided, agent may provide a re-register mechanism after receive invalid instance id, and all local caches could be removed. We need to remove the blocking in these uncompatible upgrade.

What do you think?

**Comment by peng-yongsheng** [comment]
We can add a new service to check application id and instance id when agent reconnect to collector.
Flow is: 
```
connect -> check
if(found){
   return true then agent send segments to collector.
}else{
   return false then 
   1. agent clean all the registered id cache
   2. re-register application, instance
   3. replace ids in segments or give up
}
```

**Comment by wu-sheng** [comment]
This recheck service works for me. And I highly recommend we support this in beta2. @hanahmily @ascrutae @liuhaoyang @candyleer thoughts?

**Comment by liuhaoyang** [comment]
I will support this in .NET Agent v0.3.

**Comment by peng-yongsheng** [comment]
Add check method into agent-collector protocol to avoid system exception when users clean all of the data in storage. It seems not the best solution. 
Why users clean all of the data?
1.  Upgrade collector
1. Reset system

The best solution is:
1. [Agent dynamic refresh](https://github.com/apache/incubator-skywalking/issues/1181)
1. Display all the agents which connecting to the collector in UI, and by click the `Reset` button to reset agents.
1. Better documentation.
