### ISSUE TITLE
NetworkAddress serverType and spanLayer may be not right

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1198]
This is a high priority and blocking bug before 5.0.0-beta release. When I and @peng-yongsheng  check the data in our demo env, we found MQ and DB numbers in overview page are not right, sometime.

Dive into the es data, we found the `SpanIdExchanger#exchange(SpanDecorator standardBuilder, int applicationId)` didn't work as expected, The address is created, but serverType and spanLayer are not updated, at least didn't right.

FYI @candyleer you may be interested in finding this bug with us.

**Comment by wu-sheng** [comment]
Also related #1199 bug.

**Comment by candyleer** [comment]
get it

**Comment by wu-sheng** [comment]
This is caused by @ascrutae 's deployment mistakes. In the demo env, the buffer folders of two collector instance are same. As the result, collector can't read the buffer file correctly. I will submit a new requirement for add a `.lock` file to the buffer folder to avoid this situation.
