### ISSUE TITLE
[New concept] Proposal for Manual Span

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1200]
Consider of #1196 and #1044 , also more and more RPC frameworks are using async in their core, I want to proposal a new type of span, Concept: **Manual Span**

# Manual Span
Manual span is not following the tracing context's stack based management, when the span created, it will not be added into the stack, instead, the creator is in charge of their life cycle.

## Span in the stack
All existed spans in current stack management will not be effect by the manual span. The manual span's parent will be the active span in the stack if existed.

## Create the child of manual span
There should be two ways to create the child spans, new APIs should be provided.
1. Create another manual span by given manual span. 
1. Create a traditional(Entry, Exit or Local) span, and use `span#setParent` to override its default parent.

## Cross thread
Even manual span could deal some cross thread scenario, but it definitely doesn't fit all. So ACROSS_THREAD ref has its duty. Please don't consider use this to replace it.

The difference between manual span and cross thread is
- Manual span for recording duration, op and event cross thread, but with in a single plugin or framework.
- Cross thread ref is about context propagation, new tracing context created.

In many manual instrument SDK, such as Zipkin, these two are the same thing. But SkyWalking is an auto instrument agent, so no context can propagate manually or explicitly. That is a big diff.

## TracingContext finish event
TracingContext finish event based on active span stack, if support Manual Span concept, we should provide a TracingContext half-finished buffer for hold the segments, and wait for the all manual spans in the context notify they finished.

## For backend
The sequence of spans in segment will be more unreliable. You can't count on that, only the parent-child relationship could be trust. 

___
This is my new proposal for SkyWalking 5.1 . This will be a big change, and any plugin uses this mechanism should be careful. 

I hope we should discuss on this. I definitely believe it may help plugin implementor for async framework.

FYI @liuhaoyang @candyleer @ascrutae

**Comment by wu-sheng** [comment]
hi, @liuhaoyang @ascrutae @candyleer @peng-yongsheng @hanahmily I will finish this concept in beta2 for making the Java API can support more scenarios in async module library.

**Comment by ascrutae** [comment]
@wu-sheng  I think that the `RuntimeContext` mechanism cloud make this feature better. The `RuntimeContext` can carrier some runtime object when the trace propagate within the same JVM, and it does not participate in serialization when the trace send to collector, it just for run time.

**Comment by wu-sheng** [comment]
@ascrutae You should know, RuntimeContext is for the same thread too. Why does this help you? Also, I think that should be discussed in a separated issue.

**Comment by ascrutae** [comment]
oh, agree that. I will create an new issue for `RuntimeContext` feature.

**Comment by wu-sheng** [comment]
I will remove the milestone, I have finish some prototype codes of this(branch manual-span), also make context-switchable(branch context-switchable)

Manual span APIs looks like every complex to use, and cost a lot to wait for the segment finish status.

So I have some doubts whether we should provide this. I will wait for more explicit requirements for both of them.

**Comment by wu-sheng** [comment]
Closing this, try to use #1284
