### ISSUE TITLE
Tracking ignores need to be enhanced

### ISSUE THREAD

**Issue by SevenPointOld** [apache/incubator-skywalking#1203]
There is a need to ignore some special requests for applications, such as pulling services from the registry, pulling configurations  from the configuration centers, heartbeat requests, etc.

**Comment by wu-sheng** [comment]
I agree that. And I think we are welcome to discuss and accept this filter mechanism as an optional plugin.

**Comment by wu-sheng** [comment]
Merged. Thank you @SevenPointOld . Let's post a blog soon :) I think many people like this.
