### ISSUE TITLE
turn off the agent log

### ISSUE THREAD

**Issue by mosesyou** [apache/incubator-skywalking#1205]
- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Question
- What do you want to know?
Can i turn off the agent log? Our application is in docker, before application load agent that should  copy agent directory  to the application docker image. To prevent the log from being to large that affect running application, we need turn off the agent log. Is there any way to turn off the agent log?
Or are there other better solutions？
___

**Comment by wu-sheng** [comment]
You could set the log level to **OFF**.
```
# Logging level
logging.level=OFF
```
