### ISSUE TITLE
The same operation has a duplicate globalTraceID；

### ISSUE THREAD

**Issue by wfs0902** [apache/incubator-skywalking#1211]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement![image](https://user-
___
### Question
- What do you want to know?
 
![image](https://user-images.githubusercontent.com/30229523/39908316-2572b742-5520-11e8-8a4e-0ce1399f4c30.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wfs0902** [comment]
定位不到问题发生的原因；

**Comment by peng-yongsheng** [comment]
This is known issues by the version 3.2.6, suggest upgrade to version 5.0.0-alpha.
And 5.0.0-beta version is in releasing process.

**Comment by wfs0902** [comment]
Thank  you very much，Its generation rules are difficult to replicate in theory, and why the same timestamp is generated at different time periods.
