### ISSUE TITLE
The topology of the application interconnects with each other to display the number stack@version3.2.6

### ISSUE THREAD

**Issue by wfs0902** [apache/incubator-skywalking#1214]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
![image](https://user-images.githubusercontent.com/30229523/39914831-c910554a-5538-11e8-8755-fb383ef75145.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean about stack number? The whole project is working on 5.x series. Especially beta releases soon, maybe you want to try that.
