### ISSUE TITLE
 Some doubts about the ui

### ISSUE THREAD

**Issue by Rainbowboys** [apache/incubator-skywalking#1223]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Can the trace results of the search be sorted by the time of initiation?
- When I use TraceId search, the result is a irrelevant result?
- Span info -log fileds can't adapt to size

**Comment by wu-sheng** [comment]
- Sort will optimize in beta.
- Please provide more details.
- log can be changed. @hanahmily

**Comment by Rainbowboys** [comment]
ok thanks ! There are some questions ,I know use apm-toolkit-opentracing set up Log and tags,But i when i use apm-toolkit-trace,find it only for tag ,it mean want to set up log ,i must use opentracing?

**Comment by wu-sheng** [comment]
The internal toolkit is only for tag, now. You can send pull request to support log, if you want.

**Comment by Rainbowboys** [comment]
![2018-05-16 10 49 42](https://user-images.githubusercontent.com/15340190/40093947-fd0cb48a-58f6-11e8-9b32-8b1e71a4fb0e.png)
Do you consider adding state filtering！！！！

**Comment by wu-sheng** [comment]
@Rainbowboys I have just submitted the issue about this: #1231  and you can do this by yourself.

**Comment by wu-sheng** [comment]
> Do you consider adding state filtering！！！！

This has been contributed by @ajanthan in #172 . 

> log can be changed.

@hanahmily , this requirement left. Need to provide in beta2.

**Comment by wu-sheng** [comment]
Closing this.
