### ISSUE TITLE
5.0 configuration issues.

### ISSUE THREAD

**Issue by wfs0902** [apache/incubator-skywalking#1225]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

The IP of the version 5.0 configuration file application.yml was changed to physical IP, and the UI management side had 505 errors. Only if the IP was changed to 0.0.0.0, the UI side could be accessed normally.
The configuration and the UI
![image](https://user-images.githubusercontent.com/30229523/39991976-d4b89836-57a3-11e8-9fbb-17c41babf4f8.png)

![image](https://user-images.githubusercontent.com/30229523/39991914-a8bd9420-57a3-11e8-9b3a-172d36b072ad.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wfs0902** [comment]
The 5.0 operation document is not updated accordingly.

**Comment by wu-sheng** [comment]
Yes, need a 0.0.0.0 by default. Please send a pr to fix. But beta is under release, can't change at this momeny, considering this is a critical issue.

**Comment by wfs0902** [comment]
Thanks very much for your quick reply,In cluster mode, the IP that all nodes publish is 0.0.0.0, which affects the service load?

**Comment by wu-sheng** [comment]
Cluster and remote deploy need your real IPs.

**Comment by wfs0902** [comment]
Remote use real IP,There is an error,the following
"DEBUG 2018-05-15 08:36:36 DiscoveryRestServiceClient :  GRPC server list remain unchanged: [0.0.0.0:11800] 
ERROR 2018-05-15 08:36:37 AppAndServiceRegisterClient :  AppAndServiceRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNAVAILABLE"
"org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: 0.0.0.0/0.0.0.0:11800"

**Comment by wu-sheng** [comment]
This logs how your IPs in collector are not real IPs, still 0.0.0.0  Do you miss some IPs?
