### ISSUE TITLE
bug:remote agent.config use real collector IP  that happens connection exception

### ISSUE THREAD

**Issue by wfs0902** [apache/incubator-skywalking#1228]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
collector's application.yml is the following,
**naming:
  jetty:
    host: 0.0.0.0
    port: 10800
    context_path: /
remote:
  gRPC:
    host: 0.0.0.0
    port: 11800
agent_gRPC:
  gRPC:
    host: 0.0.0.0
    port: 11800
agent_jetty:
  jetty:
    host: 0.0.0.0
    port: 12800
    context_path: /
analysis_register:
  default:
analysis_jvm:
  default:
analysis_segment_parser:
  default:
    buffer_file_path: ../buffer/
    buffer_offset_max_file_size: 10M
    buffer_segment_max_file_size: 500M
ui:
  jetty:
    host: 0.0.0.0
    port: 12800
    context_path: /
storage:
  elasticsearch:
    cluster_name: CollectorDBCluster
    cluster_transport_sniffer: true
    cluster_nodes: 192.168.6.71:9300**
Remote tomcat'agent use real IP,
   **collector.servers=192.168.6.71:10800**
There is an error,the following
"DEBUG 2018-05-15 08:36:36 DiscoveryRestServiceClient : GRPC server list remain unchanged: [0.0.0.0:11800]
ERROR 2018-05-15 08:36:37 AppAndServiceRegisterClient : AppAndServiceRegisterClient execute fail.
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNAVAILABLE"
"org.apache.skywalking.apm.dependencies.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: 0.0.0.0/0.0.0.0:11800"
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
All IPs exception UI/Jetty, need to be changed into real IPs.

**Comment by wfs0902** [comment]
Thanks so much,Configure as you say,There is no error log,but there is no application in WEBUI;
![image](https://user-images.githubusercontent.com/30229523/40037211-a0111e6e-583e-11e8-9960-90af69ac730f.png)
