### ISSUE TITLE
Segment buffer pre read failure

### ISSUE THREAD

**Issue by dinggel** [apache/incubator-skywalking#1229]
### Question
I have a problem when i restart the collector.I clear es data and buffer, but I can't start it.
2018-05-15 14:05:41,163 - org.apache.skywalking.apm.collector.analysis.segment.parser.provider.buffer.SegmentBufferReader -7345 [pool-4-thread-1] ERROR [] - Segment buffer pre read failure.

org.apache.skywalking.apm.collector.core.UnexpectedException: Received an instance heart beat message under instance id= 9 , which doesn't exist.

**Comment by wu-sheng** [comment]
> org.apache.skywalking.apm.collector.core.UnexpectedException: Received an instance heart beat message under instance id= 9 , which doesn't exist.

Agent is still running in old context. Instance ID and many other IDs are cached in agent sides. 

So my suggestion is, if you want to upgrade the backend or clear all data, make sure all agents shut down.
