### ISSUE TITLE
请问有告警相关的文档吗？

### ISSUE THREAD

**Issue by tangmingming** [apache/incubator-skywalking#1234]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
看到有告警相关的功能，却不知道如何配置

**Comment by wu-sheng** [comment]
Issue must be in English.

**Comment by rayzeng** [comment]
https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/backend/backend-alarm.md
