### ISSUE TITLE
file name too long on windows7 when i checkout 5.0.0-beta

### ISSUE THREAD

**Issue by leilianjie** [apache/incubator-skywalking#1239]
unable to create file apm-collector/apm-collector-analysis/analysis-metric/metric-provider/src/main/java/org/apache/skywalking/apm/collector/analysis/metric/provider/worker/application/refmetric/ApplicationReferenceMinuteMetricAggregationWorker.java (Filename too long)
		unable to create file apm-collector/apm-collector-analysis/analysis-metric/metric-provider/src/main/java/org/apache/skywalking/apm/collector/analysis/metric/provider/worker/application/refmetric/ApplicationReferenceMinuteMetricPersistenceWorker.java (Filename too long)
		unable to create file apm-collector/apm-collector-analysis/analysis-metric/metric-provider/src/main/java/org/apache/skywalking/apm/collector/analysis/metric/provider/worker/application/refmetric/ApplicationReferenceMonthMetricPersistenceWorker.java (Filename too long)

**Comment by wu-sheng** [comment]
This is a Windows issue. I think you can set your register. @liuhaoyang @candyleer Have any of you done this in local? Maybe we could provide a FAQ for this. @peng-yongsheng @ascrutae @hanahmily and me are all using Mac all the time...

**Comment by candyleer** [comment]
I haven't compile in windows...

**Comment by wu-sheng** [comment]
@leilianjie I am closing this. Run some search in Baidu or Google. There should be some solution for this. If you resolved this, please consider to provide FAQ doc.

**Comment by coki230** [comment]
i have the same error. i fix it with the commad: git config --global core.longpaths true.
the reason i found in web is: git can create 4096 len filename, but the windows max len is 260. git use old windows api.
more detail : https://blog.csdn.net/liuxiao723846/article/details/78329223
