### ISSUE TITLE
TraceId is invalid in Logback AsyncAppender

### ISSUE THREAD

**Issue by candyleer** [apache/incubator-skywalking#1241]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  beta
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

if we use async appender in logback,the traceId will be not printed,config
```xml
<configuration scan="true" scanPeriod=" 5 seconds">
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
                <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%tid]  %logger{56} --- %msg%n
                </pattern>
            </layout>
        </encoder>
    </appender>

    <appender name="ASYNC_PRINT" class="ch.qos.logback.classic.AsyncAppender">
        <discardingThreshold>0</discardingThreshold>
        <queueSize>1024</queueSize>
        <neverBlock>true</neverBlock>
        <appender-ref ref="STDOUT"/>
    </appender>

    <root level="INFO">
        <appender-ref ref="ASYNC_PRINT"/>
    </root>
</configuration>
```

some log example,the log are in trace context
```
2018-05-18 14:35:19.501 [http-nio-8081-exec-1] INFO  [TID:N/A] 47 com.example.test.TestApplication ---  set jedis success:nn
2018-05-18 14:35:19.501 [http-nio-8081-exec-1] INFO  [TID:N/A] 47 com.example.test.TestApplication --- set jedis success:null
```

I am working to resolve this problem cause async appender is widely used for log performance.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
`AsyncAppender ` is definitely a total different story.

**Comment by wu-sheng** [comment]
And I will tag this as `enhancement`, because I didn't support that. before.

**Comment by candyleer** [comment]
Ok, maybe should put traceId in MDC to support Async

**Comment by wu-sheng** [comment]
> Ok, maybe should put traceId in MDC to support Async

Yes. I just don't use MDC often. But you can do that.

**Comment by candyleer** [comment]
I am making this automatically for both sync and async ,but i found this has been discussed in https://github.com/apache/incubator-skywalking/pull/567,  I making the usage by `%X{tid}`
```
<configuration scan="true" scanPeriod=" 5 seconds">
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="ch.qos.logback.classic.PatternLayout">
                <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{56} [%X{tid}] --- %msg%n</pattern>
            </layout>
        </encoder>
    </appender>

    <appender name="ASYNC_PRINT" class="ch.qos.logback.classic.AsyncAppender">
        <discardingThreshold>0</discardingThreshold>
        <queueSize>1024</queueSize>
        <neverBlock>true</neverBlock>
        <appender-ref ref="STDOUT"/>
    </appender>

    <root level="INFO">
        <appender-ref ref="ASYNC_PRINT"/>
    </root>
</configuration>
```
so i only just make this work in our internal team.

**Comment by wu-sheng** [comment]
Yes, we didn't want any uncertain influence to end user. So, manual setting is better.

BTW, look like your team or company is using the project, can you submit your user case to the project?

**Comment by candyleer** [comment]
OK,I will submit when we use SW in production
