### ISSUE TITLE
support RuntimeContext feature

### ISSUE THREAD

**Issue by ascrutae** [apache/incubator-skywalking#1243]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

The `RuntimeContext` carrier some runtime object for assist  to create the trace.  but it doesn't participate in serialization when the trace data send to collector.

**Comment by wu-sheng** [comment]
Provided and merged.
