### ISSUE TITLE
Hope to add hostname or ip to traceSegment or span

### ISSUE THREAD

**Issue by candyleer** [apache/incubator-skywalking#1248]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

Now,I have an application and it is slow in some machine, but i don't know which machine, so Do we need add `hostname` or other info to traceSegment or add tag to span?

**Comment by wu-sheng** [comment]
> Now,I have an application and it is slow in some machine, but i don't know which machine, so Do we need add hostname or other info to traceSegment or add tag to span?

There is an application id and instance id in every segment, which include application code, machine info, such as ip, hostname, processid.

I think I can move this into a query requirement for trace, to discuss whether could we provide this in beta2.

**Comment by wu-sheng** [comment]
@hanahmily @peng-yongsheng What do you think about this in beta2? It makes sense in some cases. I am just not sure about the milestone.

**Comment by wu-sheng** [comment]
From the application instance id, backend knows already. No need to adjust any plugin.
