### ISSUE TITLE
Segment buffer pre read failure

### ISSUE THREAD

**Issue by dinggel** [apache/incubator-skywalking#1258]
__
### Question
- What do you want to know?
Make a mistake every three seconds：
2018-05-23 10:44:37,174 - org.apache.skywalking.apm.collector.analysis.segment.parser.provider.buffer.SegmentBufferReader -60152610 [pool-4-thr
ead-1] ERROR [] - Segment buffer pre read failure.
org.apache.skywalking.apm.collector.core.UnexpectedException: This segment contains multiple entry span.

**Comment by ascrutae** [comment]
Cloud you describe you demo more detail? It is important to help us to locate this issue.

**Comment by wu-sheng** [comment]
@peng-yongsheng could you consider to ignore and abandon traces can't be analysis? And just log it.

**Comment by peng-yongsheng** [comment]
Single segment contains multiple entry span planning support in 5.0.0-beta2 version. So ignore this exception.

**Comment by wu-sheng** [comment]
@dinggel I really think this is a bug or enhancement. I am reopening this issue for track.

**Comment by peng-yongsheng** [comment]
Done
