### ISSUE TITLE
NoNodeAvailableException starting collector (when connecting to Elasticsearch

### ISSUE THREAD

**Issue by RajKumarBalaiya** [apache/incubator-skywalking#1277]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking Alpha 5.0
Java 8
Elasticseach 6.2.4
- Which company or project?

- What happen?
I get the following in collector log and it does not start. i verified Elasticsearch transport responding on 9300
[skywalking-collector-server.log](https://github.com/apache/incubator-skywalking/files/2047071/skywalking-collector-server.log)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
@RajKumarBalaiya You are not following out documents:  https://github.com/apache/incubator-skywalking/blob/master/docs/en/Deploy-backend-in-cluster-mode.md

ElasticSearch 5.x is required.
