### ISSUE TITLE
H2 Storage Implementation

### ISSUE THREAD

**Issue by ajanthan** [apache/incubator-skywalking#1281]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I wanted to use H2 storage backed during the dev/testing. Is this feature stable enough to use?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I have put some words in standalone mode startup doc:
> H2 storage implementation is not provided in 5.0.0-alpha, so you must deploy ElasticSearch before try to start backend

It is still undone. Welcome contribution. 

See here: https://github.com/apache/incubator-skywalking/blob/master/docs/en/Deploy-backend-in-standalone-mode.md
