### ISSUE TITLE
hystrix plugin bug

### ISSUE THREAD

**Issue by xyydcoo** [apache/incubator-skywalking#1285]
When I started at spring boot, there was an exception when I invoked other services through CommandLineRunner using feign, causing the service startup failure.  Feign opened the hystrix. After removing the agent-hystrix-plugin, the service is restored to normal start.

spring boot 1.5.10
spring cloud Dalston.SR5
[log.txt](https://github.com/apache/incubator-skywalking/files/2053186/log.txt)

**Comment by wu-sheng** [comment]
@ascrutae If the hytrix makes more complex than we expected, please consider #1284 as an option. I don't want we deal too much about the across thread

**Comment by wu-sheng** [comment]
@xyydcoo I think this should be fixed by #1293 If you want this now, please compile the source codes from master branch, and copy this plugin.jar to your place. Attention: don't use the whole master distribution.
