### ISSUE TITLE
kafka exception

### ISSUE THREAD

**Issue by xyydcoo** [apache/incubator-skywalking#1287]
When I use the log4j2 output log to Kafka to produce an exception

spring-kafka.version:1.1.7.RELEASE
[agent-log.txt](https://github.com/apache/incubator-skywalking/files/2053261/agent-log.txt)

**Comment by ascrutae** [comment]
which version of kafka plugin do you used?

**Comment by wu-sheng** [comment]
@ascrutae I don't think you make yourself clear either here or in pr. Even I can't understand why.

**Comment by xyydcoo** [comment]
kafka veriosn 0.10.1.1

**Comment by wu-sheng** [comment]
I think there is no good way to trace kafka 0.10, if we don't do some assumptions or set some rules. No kafka header, no way to propagation. 

If and only if kafka consumer and producer are monitored, and always under monitoring. We can do an optional plugin for low versions. Even you have that, you can't install or uninstall agent, if kafka has data. You need to wipe data in it.

See our suppoted versions doc.

**Comment by wu-sheng** [comment]
So, you should understand @ascrutae PR is not for supporting 0.10, is for avoiding exception in log. 0.10 kafka is still not under tracing.

**Comment by xyydcoo** [comment]
ok,thanks!

**Comment by wu-sheng** [comment]
Could we close this issue? Or do you want to discuss optional kafka plugin?

**Comment by xyydcoo** [comment]
close
