### ISSUE TITLE
[Collector] Crash down by OutOfMemoryError exception.

### ISSUE THREAD

**Issue by peng-yongsheng** [apache/incubator-skywalking#1291]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Aggregate workers and persistence workers own two cache collections. One of the their use to cache the data merged by streaming data. The other one is waiting to export aggregated when persistence timer scanning. But if persistence speed can not catch streaming speed, the cache collection's size will increased too large. Collector will crash down when all the workers cached huge data.

**Comment by peng-yongsheng** [comment]
Solution: Block the workers which cache collection's size exceed the setting.

Add a configuration item: 
```
configuration:
  default:
      workerCacheSizeThreshold: 10000
```

**Comment by wu-sheng** [comment]
@peng-yongsheng My suggestion, you should be care of the gRPC buffer too. And do you confirm you want to do this in beta2?

**Comment by peng-yongsheng** [comment]
gRPC will blocked cause by the workers blocked which gRPC invoked.

**Comment by wu-sheng** [comment]
> gRPC will blocked cause by the workers blocked which gRPC invoked.

Agent has a time out mechanism. If you are going to block at server side, we need to review the mechanism again. The server side safe may trigger agent out of memory. That will be a bigger issue/concern for end users.

**Comment by wu-sheng** [comment]
Fixed.
