### ISSUE TITLE
There's a bit of doubt about the way springMVC gets the operationName

### ISSUE THREAD

**Issue by SevenPointOld** [apache/incubator-skywalking#1302]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Like this,
![image](https://user-images.githubusercontent.com/12181207/40895678-5c00cbde-67e3-11e8-98e4-8899ee1917dd.png)
the `RequestMappingMethodInterceptor#getRequestURL` just get the `RequestMapping` annotation's `path` or `value` as operationName, I think maybe I need the parsed path as operationName.

**Comment by wu-sheng** [comment]
Yes. only use path pattern as the operation name, the backend will aggregate and analysis the metrics for the service(based on operation name).

**Comment by wu-sheng** [comment]
I guess `parsed path pattern`, you mean the real URL? 

- Pattern: ${spring.application.name}/access/page
- URI: application-xxx/access/page

Right? If yes, try to thing some one will put userid, accountid in the url, the patter looks like `/prod/order/${orderid}`. Then you can image what happens... Metrics will be useless..

**Comment by SevenPointOld** [comment]
Thanks, I get it.
