### ISSUE TITLE
UNIMPLEMENTED: Method not found: ApplicationRegisterService/applicationCodeRegister

### ISSUE THREAD

**Issue by taoer** [apache/incubator-skywalking#1304]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
-  Question or discussion

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
Agent  Error
DEBUG 2018-06-04 14:41:51 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:CONNECTED. 
ERROR 2018-06-04 14:41:51 AppAndServiceRegisterClient :  AppAndServiceRegisterClient execute fail. 
org.apache.skywalking.apm.dependencies.io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: ApplicationRegisterService/applicationCodeRegister
	at org.apache.skywalking.apm.dependencies.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)

**Comment by wu-sheng** [comment]
Are you using our release versions? I have no idea. These services must be implemented by our collector.

**Comment by taoer** [comment]
skywalking-5.0.0-alpha

Thank you very much!

**Comment by taoer** [comment]
naming:
  jetty:
    host: ip
remote:
  gRPC:
    host: ip
    port: 11800
-------------------------------
If IP is changed with 'localhost', local  application can be collected.
If IP is changed with 0.0.0.0, all Agent reports this wrong.
If IP is replaced with real IP, the wrong( Cannot assign requested address)

**Comment by wu-sheng** [comment]
> If IP is changed with 'localhost', local application can be collected.

Mean our release version is correct, and work well.

> If IP is changed with 0.0.0.0, all Agent reports this wrong.

Is the collector still running in local? I assume no.

> If IP is replaced with real IP, the wrong( Cannot assign requested address)

That is caused by your machine settings. Your real IPs is not real as you thought, the OS didn't allow you to bind this IP. You should deal with this through adjusting your OS settings.

**Comment by taoer** [comment]
Thank you very much. My server is Aliyun. The server is the VPC host of the proprietary network. If other servers want to access, it can only be configured as 0.0.0.0. But IP must be reported  as 0.0.0.0.

**Comment by wu-sheng** [comment]
If you want or have to use 0.0.0.0, please follow direct link doc. And can't run in clus mode. 

I think you use IP in VPC for collector, and agent uses direct link to connect. This is what I am using.

**Comment by peng-yongsheng** [comment]
If agent and collector both in the same VPC, you can use the LAN address. Why you choose Internet address to bind?

**Comment by wu-sheng** [comment]
> If agent and collector both in the same VPC, you can use the LAN address. Why you choose Internet address to bind?

Same question from me. You should have those IPs.
