### ISSUE TITLE
org.apache.skywalking.apm.collector.agent.grpc.provider.handler.TraceSegmentServiceHandler

### ISSUE THREAD

**Issue by youtsea** [apache/incubator-skywalking#1309]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug

- Which version of SkyWalking, OS and JRE?

version: apache-skywalking-apm-incubating-5.0.0-beta
OS: Windows Server 2012 R2
JRE: Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

- What happen?
Browsing each link, the collector's console will show these:

```
六月 05, 2018 9:32:24 上午 io.grpc.internal.SerializingExecutor run
严重: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToAppli
cationThreadServerStreamListener$1Closed@7fcbc7d6
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
        at io.grpc.Status.asRuntimeException(Status.java:517)
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(Ser
verCalls.java:356)
        at org.apache.skywalking.apm.collector.agent.grpc.provider.handler.Trace
SegmentServiceHandler$1.onError(TraceSegmentServiceHandler.java:60)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCa
llListener.onCancel(ServerCalls.java:269)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(Serve
rCallImpl.java:282)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListen
er$1Closed.runInContext(ServerImpl.java:684)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123
)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by peng-yongsheng** [comment]
What agent language do you use? Java or .Net?

**Comment by peng-yongsheng** [comment]
This error message cause of agent terminate the gRPC's connection. 
1. Kill -9 agent
2. Firewall terminate connect

**Comment by youtsea** [comment]
.NET Core 2

**Comment by peng-yongsheng** [comment]
@liuhaoyang Please help me to check gRPC connection close mechanism.

**Comment by wu-sheng** [comment]
@liuhaoyang Could you help on this one?

**Comment by liuhaoyang** [comment]
I cannot reproduce this problem. 
Test environment: 
 SkyWalking Collector&UI version: `5.0-beta` 
SkyWalking.AspNetCore version: `0.2`
web server:`Kestrel`  


@youtsea Can you give me more information? Such as, does the application exit abnormally? Which web server is used to host the application?

**Comment by youtsea** [comment]
Test environment:
.NET Core 2
SkyWalking Collector&UI version: 5.0-beta
SkyWalking.AspNetCore version: 0.2
web server:Kestrel

Production Environment:
.NET Core 2.1
SkyWalking Collector&UI version: 5.0-beta
SkyWalking.AspNetCore version: 0.2
web server:Kestrel

This problem is in both test and production.
In test environment, i new a base mvc's project which just add these code:

```
services.AddSkyWalking(option =>
            {
                // Application code is showed in sky-walking-ui
                option.ApplicationCode = "Test_ApplicationName";

                //Collector agent_gRPC/grpc service addresses.
                option.DirectServers = "192.168.6.240:11800";

            });
```

![image](https://user-images.githubusercontent.com/9941834/41030107-228d3a80-69b0-11e8-9b9c-cd2e5fd998dc.png)


For example:
When I click `About` and `Contact`, the collector's console will show this problem,but all service(collector, sw ui, web) is working.

**Comment by liuhaoyang** [comment]
I will fix this issue in .NET Core Agent v0.3  https://github.com/OpenSkywalking/skywalking-netcore/pull/52 .
