### ISSUE TITLE
Another question about getting operation name  from @RequestMapping

### ISSUE THREAD

**Issue by SevenPointOld** [apache/incubator-skywalking#1313]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?
If the `@RequestMapping(path="root")` annotation on Class type, and  `@RequestMapping(path="path")` annotation on Method type,  skywalking will take `rootpath` as operation name , but the SpringMVC will add `/` automatically, like `/root/path`

**Comment by SevenPointOld** [comment]
I've saw the code,  it's just a `+` operation

**Comment by wu-sheng** [comment]
Yes, would do send a pr to fix this?

**Comment by SevenPointOld** [comment]
I'll try

**Comment by wu-sheng** [comment]
Merged.
