### ISSUE TITLE
The same configuration file exists in two places

### ISSUE THREAD

**Issue by yrjjf** [apache/incubator-skywalking#1316]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The documents component-libraries.yml  exist in all two places。When you need to make changes, you have to modify two places.
apache-skywalking-apm-incubating/config/component-libraries.yml
apache-skywalking-apm-incubating/collector-libs/apm-collector-boot-5.0.0-beta2-SNAPSHOT.jar/component-libraries.yml

___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0.beta
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Merge two configuration files, so that the program reads configuration files from only one place.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ascrutae** [comment]
This issue has fix in PR #1318
