### ISSUE TITLE
Will skywalking 5.0 support Elasticsearch 6.x  ?

### ISSUE THREAD

**Issue by clorxd** [apache/incubator-skywalking#1319]
Please answer these questions before submitting your issue.

### Why do you submit this issue?
 Requirement
 Feature or performance improvement
___

### Question
- What do you want to know?

Will skywalking 5.0 support Elasticsearch 6.x ？
If it will not , can you give me some advise on how to do it by myself ?
___

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

My company want's to use skywalking but we have already used Elasticsearch 6.x . We can't build another environment for skywalking so I need some support.

**Comment by wu-sheng** [comment]
> My company want's to use skywalking but we have already used Elasticsearch 6.x . We can't build another environment for skywalking so I need some support.

I prefer you do the upgrade by yourself. This upgrade will bring many potential uncompatible issues. I think we have no plan to update the version, at least before 5.0.0-GA. FYI @peng-yongsheng 

If you will/can provide the ES6 version storage implementation module, that will be great. SkyWalking collector is based on modulization design, so easy to change the dependency though application.yml
