### ISSUE TITLE
Add Client version when agent register instance

### ISSUE THREAD

**Issue by candyleer** [apache/incubator-skywalking#1322]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
sometimes in a company  may have hundreds of applications and they may use different agent version, if we fix some agent bug in current version, we want to know who is using this version to notify them to upgrade.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> sometimes in a company may have hundreds of applications and they may use different agent version, if we fix some agent bug in current version, we want to know who is using this version to notify them to upgrade.

Agree first, that is the real situation you need to face. If you want to support that, we need to work on some UI pages about agent status. Do you have any drafts and intentions to implement these requirements.

Now in UI, we can have Monitor and Trace. I think you are proposing *Settings*.

If you want to do this, we can do discussion, start with the UI draft. I think the agent info should be group by application codes and instances.

**Comment by wu-sheng** [comment]
FYI @peng-yongsheng @hanahmily @ascrutae

**Comment by candyleer** [comment]
ok,I read current code,we should add a field `agent_version` in `instance` index when instance registered,
ui show in this place
![image](https://user-images.githubusercontent.com/11530760/41143621-85f782c4-6b2c-11e8-8eff-7012194c1643.png)

**Comment by wu-sheng** [comment]
> ok,I read current code,we should add a field agent_version in instance index when instance registered,
ui show in this place

That is an easy way. Even you do so, you have to face there are so many agents in the cluster. Let's say at least thousands of them. That is why we should add a new group, named `Settings`，an `Agent status` page under that group. By that, you could see the status of all, and group them by application codes, IP, or version.

**Comment by peng-yongsheng** [comment]
> Show in `Running Server` page

I propose recall why show agent version to user? what problem need to by solved? 
The keywords ` hundreds of applications` in your description. User will hardly to find which agent version is different from each others.

**Comment by wu-sheng** [comment]
No update for a long term.
