### ISSUE TITLE
Application Avg Throughput Issue

### ISSUE THREAD

**Issue by candyleer** [apache/incubator-skywalking#1327]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
 beta2 
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/11530760/41143307-5cdbf01a-6b2b-11e8-9965-cb226f2e6bfc.png)

it seems the throughput is not get from server but it is calculated by the avg trend,does it need to be modified?
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
It is calculated by UI component, I think. Is it a problem for you?

**Comment by wu-sheng** [comment]
@peng-yongsheng Could you give some explanation about how does the collector calculate the throughputs of server? 

The UI did a very simple calculatio: ** avg = (t1.avg + t2.avg + .... tn.avg ) / n**. The most possible error is the last time bucket, Tn is not finished.
