### ISSUE TITLE
trace detail ui：enable span detail panel always visible when there are lots of trace spans

### ISSUE THREAD

**Issue by zpf1989** [apache/incubator-skywalking#1332]
Hello,I'm using incubator-skywalking 5.0-beta.
I have a request contains many spans(almost 40),and in the trace detail page,the trace view of all the spans has no limit height,and my browser can't display the span panel when I select one to see the details data at the bottom.
As shown below:
![1](https://user-images.githubusercontent.com/16696623/41149854-33d2403e-6b3f-11e8-87bc-ea0a0a62a368.jpg)
![2](https://user-images.githubusercontent.com/16696623/41149862-39173e14-6b3f-11e8-9118-3beb3e2d7779.jpg)
![3](https://user-images.githubusercontent.com/16696623/41149868-3b7e447c-6b3f-11e8-82c2-765470b322c7.jpg)

Now if I try to see the span details at the bottom,I must scroll the right bar to the bottom.
And after check the span details and scroll back up,I can hardly find which span I just selected.
————————————————————————————————————————————
So,could you think about making the span detail visible all the time?
And making the trace view above scrollable itself?
This may cause height reduce of the trace view above,we can make the span detail panel be able to hide/show by hand.
————————————————————————————————————————————
If I don't clear my meaning,you can contact the member in your QQ group,who's name is **Rider**.
Thanks!

**Comment by wu-sheng** [comment]
I understood and received this feedback before. @hanahmily Please make the decision when will you support this requirement?

**Comment by wu-sheng** [comment]
Moved to UI issue already.
