### ISSUE TITLE
the latest code ui bugs

### ISSUE THREAD

**Issue by haotian2015** [apache/incubator-skywalking#1339]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Bug
___
### Bug
When I update to the latest code ， in dashboard service is 0 
![image](https://user-images.githubusercontent.com/13880099/41228389-d0713ae0-6daa-11e8-930a-12efd6853894.png)

![image](https://user-images.githubusercontent.com/13880099/41228401-d9b4f39e-6daa-11e8-8090-26897e18344e.png)

**Comment by wu-sheng** [comment]
FYI @peng-yongsheng @hanahmily This may be a potential bug for our develop version. Keep this open until we finish the integration test. And you may think, what is going on.

**Comment by haotian2015** [comment]
You may have some code that is not submitted. 
![image](https://user-images.githubusercontent.com/13880099/41344430-b26a579a-6f33-11e8-8672-e3b930fd4740.png)
![image](https://user-images.githubusercontent.com/13880099/41344480-d5b93e00-6f33-11e8-92c1-ee5c7b3a3560.png)
![image](https://user-images.githubusercontent.com/13880099/41344528-f06eea1a-6f33-11e8-917b-b36379b00a2e.png)

**Comment by haotian2015** [comment]
@wu-sheng Thank you. I will try 5.0.0.beta.
