### ISSUE TITLE
关于namespace的问题

### ISSUE THREAD

**Issue by AaronChenlin** [apache/incubator-skywalking#1344]
___
### Question
- 你好，我们正在使用skywalking，我们有不同的环境。然后看到了namespace可以根据不同的环境进行隔离，我看了相关的介绍并尝试自己试试，但是并不成功，这或许是我不了解 namespace所导致的，我想求助一下。

**Comment by wu-sheng** [comment]
All issues need be in English. And you need to describe how you are using.
