### ISSUE TITLE
Questions about namespace

### ISSUE THREAD

**Issue by AaronChenlin** [apache/incubator-skywalking#1345]
___
### Question
- Hello, we are using skywalking and we have different environments. Then I saw the namespace can be isolated according to different environments, I read the relevant introduction and try to try it yourself, but it was not successful, this may be caused by I do not understand the namespace, I would like to ask for help. The configuration of the agent (environment 1: agent.namespace=test, environment 2: agent.namespace=dev), application.yml configuration (configuration.default.namespace= test
) My expectation is that the dev environment should be isolated. However, this is not the case.

**Comment by wu-sheng** [comment]
I don't provide version. If beta2, see this: https://github.com/apache/incubator-skywalking/pull/1276
