### ISSUE TITLE
找不到类MemoryPool

### ISSUE THREAD

**Issue by wangxingjian2004** [apache/incubator-skywalking#1346]
ERROR] /G:/other-git/skywalking-5.0.0-beta/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/jvm/memorypool/MemoryPoolModule.java:[26,47] 程序包org.apache.skywalking.apm.network.proto不存在
[ERROR] /G:/other-git/skywalking-5.0.0-beta/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/jvm/memorypool/MemoryPoolModule.java:[27,47] 程序包org.apache.skywalking.apm.network.proto不存在
[ERROR] /G:/other-git/skywalking-5.0.0-beta/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/jvm/memorypool/MemoryPoolMetricAccessor.java:[23,47] 程序包org.apache.skywalking.apm.network.proto不存在
[ERROR] /G:/other-git/skywalking-5.0.0-beta/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/jvm/memorypool/MemoryPoolModule.java:[40,17] 找不到符号
  符号:   类 MemoryPool
  位置: 类 org.apache.skywalking.apm.agent.core.jvm.memorypool.MemoryPoolModule

**Comment by wu-sheng** [comment]
Please read document. And issue must be in English.
