### ISSUE TITLE
Alarm UI error

### ISSUE THREAD

**Issue by xyydcoo** [apache/incubator-skywalking#1348]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0beta
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/29936988/41288654-a9d79f9e-6e79-11e8-9fa2-6370cce5d2fd.png)
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We have tested for beta2 release. No such issue occurs. If you can provide more details. We can move on.
