### ISSUE TITLE
collector always print errro logs

### ISSUE THREAD

**Issue by sky-syk** [apache/incubator-skywalking#1349]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
someone who can help me solve this  problem
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
collector always print err logs ,why
![image](https://user-images.githubusercontent.com/18712087/41392474-3ad90064-6fd3-11e8-8f02-17c1946062a3.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Check your ElasticSearch version, status, and connection. This means data can't be written into.

**Comment by sky-syk** [comment]
my ElasticSearch  version is 5.2.2  ，but there are some data has already be written in  ,Why would this be a problem

**Comment by sky-syk** [comment]
![image](https://user-images.githubusercontent.com/18712087/41394613-30115ca8-6fdd-11e8-8836-0d2fdd0fce46.png)
Does the cause of this is the same to befor ?

**Comment by wu-sheng** [comment]
Could you try to upgrade your ElasticSearch to 5.5+? We have no experience in dealing with problems like this.

**Comment by wu-sheng** [comment]
If you even removed ElasticSearch Data, please reboot your application.

**Comment by sky-syk** [comment]
i have solved this problem  ,the cause of  is  the configure of  ElasticSearch  , threadpool.bulk.size is too small
