### ISSUE TITLE
H2 storage implementation

### ISSUE THREAD

**Issue by peng-yongsheng** [apache/incubator-skywalking#1352]
Thanks to @chidaodezhongsheng for PR #1347 which is the storage implementation of ShardingJDBC.
 
ShardingJDBC is using mysql driver based on the SQL grammar. H2 database also supported it by the JDBC API. I prefer use the ShardingJDBC-Storage-DAO instead of current implementation of H2 storage. We can reduce a lot of development and testing for the H2 storage implementation.

Two ways:
1. H2's DAO extends ShardingJDBC's DAO.
2. Move ShardingJDBC's DAO into H2's package then make ShardingJDBC's DAO extends H2's DAO

FYI @wu-sheng @chidaodezhongsheng

**Comment by wu-sheng** [comment]
The question is, whether are ShardingJDBC(MySQL core) and H2 compatible in SQL level?

**Comment by peng-yongsheng** [comment]
> Compatibility modes for IBM DB2, Apache Derby, HSQLDB, MS SQL Server, MySQL, Oracle, and PostgreSQL. [Original](http://www.h2database.com/html/features.html#feature_list)

This is the h2's official description.

**Comment by peng-yongsheng** [comment]
We can compare the data type and SQL grammar between ShardingJDBC and H2 first. Then make a decision about this finally.

**Comment by chidaodezhongsheng** [comment]
Shardingjdbc support SQL grammar,not support mysql dialect,for example “case when”.I have checked the sqls In h2 storage,Shardingjdbc not support keyword “in” only.

**Comment by wu-sheng** [comment]
My proposal is, evaluate could use shardingjdbc implementor sql in H2, without change required. @chidaodezhongsheng What do you think?

**Comment by wu-sheng** [comment]
> Shardingjdbc support SQL grammar,not support mysql dialect,for example “case when”.I have checked the sqls In h2 storage,Shardingjdbc not support keyword “or” only.

So I assume if the SQLs in ShardingSphere implementor, it should also work in H2 implementor. Do you know any risk or problem?

**Comment by chidaodezhongsheng** [comment]
I checked the SQLs in H2 implementor, the keyword "or" that Shardingjdbc not support.Besides, it not support read meta data of DB.
In Shardingjdbc implementor, I use two sqls instead of the keyword "or". However, I cannot check the column meta data of table, I still not found the instead way.

**Comment by wu-sheng** [comment]
If so, I prefer to separate the two implementors, don't depend on that. If compatible is not so good, codes will make people think strange.

**Comment by wu-sheng** [comment]
I have supported H2, MySQL, TiDB in 6-beta release.
