### ISSUE TITLE
Look volunteers to translate(sync) English documents to Chinese

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1360]
We want to find some volunteers to help us to sync and translate new English documents to Chinese. They are out of date now.

**Comment by wu-sheng** [comment]
Welcome for helping us. The Documents about deployment, optional plugins and incubating features have changed. You can see it from last several merges.

**Comment by wu-sheng** [comment]
@brucewu-fly If you have time, could you finish the doc-sync in these two days. We are going to release beta2 soon. Thanks.

**Comment by kezhenxu94** [comment]
The task is a good start for those who are new to SkyWalking and are interested in translating (like me :), but it may take a long time to finish and need patience, do you prefer contributor to open a single PR after translating the whole documents or one PR per some files step by step @wu-sheng

**Comment by wu-sheng** [comment]
@kezhenxu94 Yes, we used to have part document, which misguide users to read. They think, SkyWalking don't have full and well provided documents, but we have, just in English. 

So 2 days ago, that part of document has been removed #2315 . If you want to contribute in that part, I prefer we host it somewhere else, such as here, https://github.com/SkyAPM . If you want to help, I could create a repo and invite you as a collaborator.

**Comment by kezhenxu94** [comment]
@wu-sheng I'd like to work on this, and study SkyWalking further by this chance, but again, the translation work might take some time, thanks

**Comment by wu-sheng** [comment]
@kezhenxu94 Invite you to https://github.com/SkyAPM/document-cn-translation-of-skywalking

**Comment by wu-sheng** [comment]
If you want to publish it as GitHub Pages page, let me known.

**Comment by kezhenxu94** [comment]
@wu-sheng yes that's my thought, many open-sourced projects have a separate repo to hold their documents which are deployed as GitHub pages, what do you think

**Comment by wu-sheng** [comment]
@kezhenxu94 Make sense to me. You have the `admin` role in that repo, go for it. Also, please consider, we need to consider to provide documents for each release. If we post documents on GItHub pages, then maybe different folders for different version document?

**Comment by kezhenxu94** [comment]
> we need to consider to provide documents for each release.

@wu-sheng provident opinion, I'll inspect some doc generators and will discuss here, thanks

**Comment by wu-sheng** [comment]
Sure. Feel free to discuss here or on dev@skywalking.apache.org ml. I noticed you are an Apache committer(of Dubbo project) already, so ML should be familiar with you and good for you further contribution in Apache(Suggestion only)

**Comment by kezhenxu94** [comment]
@wu-sheng of course I wil :) I've subscribe to the ML and just receive the celebration of 100th contributor :)

**Comment by JaredTan95** [comment]
@kezhenxu94 Hi, Glad to hear that you have interests in helping the community to build doc or site. Looking forward to the discussion or progress.

**Comment by wu-sheng** [comment]
> of course I wil :) I've subscribe to the ML and just receive the celebration of 100th contributor :)

Actually, you are the 100th contributor :) Congrats. Welcome to reply that mail.

**Comment by wu-sheng** [comment]
@kezhenxu94 Do we have some progress? Do you know we have the DevCon at May.(maybe), do we have a chance to announce the Chinese documents available at that moment?

**Comment by kezhenxu94** [comment]
> @kezhenxu94 Do we have some progress?

Yes

- I've translated the **concepts-and-designs** part in the past week(maybe a little bit slow because of work and other stuff), 

- and do some research on versioning documentation generator, and it seems that there is no perfect solution, I've send feature request txd-team/docsite/issues/24 , and +1 mkdocs/mkdocs/issues/193 . [ReadTheDoc](https://readthedocs.org) seems to support versioning doc but it's not hosted as GitHub pages.

> Do you know we have the DevCon at May.(maybe), do we have a chance to announce the Chinese documents available at that moment?

Yes I know and fill the form already(though I can't attend (maybe)), but I'm not sure whether the docs can be finished by that time(though I'll try my best to guarantee both efficiency and quality), so no promise I can give you now, and I'll try to synchronize the progress here :) thanks @wu-sheng

**Comment by wu-sheng** [comment]
Thanks. Take your time. If can't be ready at that moment, then let it be.
