### ISSUE TITLE
HTTPS Req/Responses are not getting traced

### ISSUE THREAD

**Issue by asivanadi** [apache/incubator-skywalking#1367]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [-] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
HTTPS Req/Responses are not getting traced
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If you are using SpringMVC or Struts, there should not relate to HTTPs. If not, just servlet, maybe.

**Comment by asivanadi** [comment]
I use SpingBoot standalone and sprinboot+embedded tomcat

**Comment by wu-sheng** [comment]
I am asking about `SpringMVC`, do you use that?

**Comment by asivanadi** [comment]
Nop

**Comment by wu-sheng** [comment]
> I use SpingBoot standalone and sprinboot+embedded tomcat

Tomcat should be traced, and our demo is based on embed Tomcat. Do you have a simple example?

**Comment by wu-sheng** [comment]
No update
