### ISSUE TITLE
[Collector][ShardingJDBC Storage] Support multiple service names in segment duration table

### ISSUE THREAD

**Issue by peng-yongsheng** [apache/incubator-skywalking#1376]
- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X] Feature or performance improvement

Related Issue: #1206 
Related PR: #1372 

The storage implementation of ShardingJDBC must change along. 
Sample:
1. Persistence DAO: 
```
target.put(SegmentDurationTable.SERVICE_NAME.getName(), gson.toJson(data.getServiceName()));
```
2. UI DAO
```
String serviceNameJsonStr = (String)searchHit.getSource().get(SegmentDurationTable.SERVICE_NAME.getName());
            if (StringUtils.isNotEmpty(serviceNameJsonStr)) {
                List serviceNames = gson.fromJson(serviceNameJsonStr, LinkedList.class);
                basicTrace.getOperationName().addAll(serviceNames);
            }
```

Or you can save service name into another table and make this table and segment duration table to be the many to one relationship. 
@chidaodezhongsheng

**Comment by wu-sheng** [comment]
Merged. Closing.
