### ISSUE TITLE
Number of statistics interface calls

### ISSUE THREAD

**Issue by sky-syk** [apache/incubator-skywalking#1378]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how to count the Number of interface calls?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean about `Number of interface calls`? I am not following.

**Comment by sky-syk** [comment]
invoking times of interface...接口调用次数..

**Comment by wu-sheng** [comment]
> invoking times of interface...接口调用次数..

The service page is about that.

**Comment by sky-syk** [comment]
![image](https://user-images.githubusercontent.com/18712087/41755043-e6ae510c-7607-11e8-88ad-4915fbaaa78b.png)
if i select last 2 days ,there is nothing show .. i want to know the Avg Throughput  is how to calculate

**Comment by wu-sheng** [comment]
Do you want to know the total throughputs? If so, and considering your throughput is low, less than 1 cpm in the whole day, you can't know that. 

If low throughput, don't try to choose the long duration. Because, in avg level, there is also zero.
