### ISSUE TITLE
The application name couldn't be found in the Trace menu

### ISSUE THREAD

**Issue by zhaoxunyong** [apache/incubator-skywalking#1389]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The application couldn't be found in the Trace menu, but I can find it in the Topology menu. 
We have 10 applications, but we only found 9 in the drop-down of the application. Is there a limit to the number of drop-down options?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  5.0.0-beta2-SNAPSHOT/centos7/jdk1.8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
No error log
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
No, no limit there.

**Comment by zhaoxunyong** [comment]
I can found it  in the trace list, but I can't found it in the drop-down of the application.

**Comment by zhaoxunyong** [comment]
It's name is lms-webapp, but I can't found it in the application items.

![Uploading aaa.png…]()
<img width="268" alt="b" src="https://user-images.githubusercontent.com/8733266/41889757-ca913a40-793e-11e8-8925-41cbece05bfb.png">

**Comment by wu-sheng** [comment]
Is it still active for the duration?

**Comment by zhaoxunyong** [comment]
Yes. It's a negative number in the trace list, is that possible?

![a](https://user-images.githubusercontent.com/8733266/41891455-0eda70e2-7947-11e8-9afa-6846e1f70c72.png)

**Comment by zhaoxunyong** [comment]
We deployed it in the docker.There's another application, it's very strange: there's only one application, but I can find two hosts? 

<img width="559" alt="a" src="https://user-images.githubusercontent.com/8733266/41891749-3f1a26a2-7948-11e8-8a6b-7639bb90554c.png">

**Comment by zhaoxunyong** [comment]
In addition, our applications share one agent. Is that ok?

**Comment by zhaoxunyong** [comment]
After I clear all datas of the elasticsearch ,and restart skywalking, I can see that in the application items!
In the previous datas, I saw the timestamp of the trace list was negative, could that be the reason?

Similar to the following position:
<img width="213" alt="c" src="https://user-images.githubusercontent.com/8733266/41947827-76354e56-79ec-11e8-81bd-c251d7818dcb.png">

**Comment by wu-sheng** [comment]
I don't think that shouldn't be a problem. More likely some data removed, but agents weren't reboot.
