### ISSUE TITLE
Mistake of NIWSServerListClassName in webapp's application.yml

### ISSUE THREAD

**Issue by jjtyro** [apache/incubator-skywalking#1390]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
   master branch.  CentOS 7.4 OpenJDK 1.8.0

- Which company or project?
   GitTech

- What happen?
   In apm-webapp/src/main/resource/application.yml, the parameter NIWSServerListClassName have a mistake. The Class should be 'org.apache.skywalking.apm.webapp.proxy.CollectorServerList' .

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
@jjtyro Would do intend to send a pull request?

**Comment by jjtyro** [comment]
Ok!  I try to do it.

**Comment by wu-sheng** [comment]
Fixed by @hanahmily
