### ISSUE TITLE
In the Service menu: Validation error of type MissingFieldArgument: Missing field argument applicationId

### ISSUE THREAD

**Issue by zhaoxunyong** [apache/incubator-skywalking#1394]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When entering the service menu, the following error occurs:
Validation error of type MissingFieldArgument: Missing field argument applicationId
___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0-beta2-SNAPSHOT/centos7/jdk1.8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by zhaoxunyong** [comment]
screenshot as follows:

<img width="944" alt="c" src="https://user-images.githubusercontent.com/8733266/41948448-6e1e170e-79ef-11e8-875c-893ece05a7a7.png">

**Comment by zhaoxunyong** [comment]
screenshot:

<img width="944" alt="c" src="https://user-images.githubusercontent.com/8733266/41948493-9d71fac0-79ef-11e8-89de-1f8fd1e1d974.png">

**Comment by zhaoxunyong** [comment]
I can see the content through click the slow service, but There are no any urls from the dropdown option.

<img width="512" alt="d" src="https://user-images.githubusercontent.com/8733266/41948692-7da23b14-79f0-11e8-9177-2c60c9263079.png">

**Comment by wu-sheng** [comment]
From your screenshot, I am sure you are not using the right codes. Please be advised, the beta2 is a developing version. So we will not guarantee anything. You can try the latest. Please use gitter to instead of the issue to discuss the developing version. I have to close it, because this will confuse the end users of releases.
