### ISSUE TITLE
Can you increase support for rabbitmq？

### ISSUE THREAD

**Issue by wuuuyy** [apache/incubator-skywalking#1401]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ √] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can you increase support for rabbitmq？
___
### Bug
- Which version of SkyWalking, OS and JRE?
no
- Which company or project?
Take on the police
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
no
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Can you increase support for rabbitmq？

**Comment by wu-sheng** [comment]
You can do this by yourself easily, and contribute to the community by learning from Kafka or RocketMQ existed plugins.

**Comment by clevertension** [comment]
is the rabbitmq-5.x support avaliable? if not, i will provide one

**Comment by wu-sheng** [comment]
From the document, I think we have now. https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/Supported-list.md
