### ISSUE TITLE
the component-libraries.yml file changes do not take effect

### ISSUE THREAD

**Issue by beckhampu** [apache/incubator-skywalking#1404]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [√ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0-beta

- Which company or project?
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

   I need to add own component when using opentracing.So i edit /config/component-libraries.yml, but i found it does not take effect.  Because the file already exists in the apm-collector-boot-5.0.0-beta.jar package.
   when assemble:
      ```
  <fileSet>
            <directory>src/main/resources</directory>
            <includes>
                <include>application.yml</include>
                <include>log4j2.xml</include>
                <include>component-libraries.yml</include>
            </includes>
            <outputDirectory>/config</outputDirectory>
        </fileSet>
```
     
    when jar build(**missing exclude component-libraries.yml**):
         ```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <excludes>
                        <exclude>application.yml</exclude>
                        <exclude>log4j2.xml</exclude>
                    </excludes>
                </configuration>
           </plugin>
```

**Comment by wu-sheng** [comment]
Yes. This is a confirmed and fixed issue. See #1316 . In beta release, you can simply remove the file in jar file.

**Comment by beckhampu** [comment]
ok , thanks!
