### ISSUE TITLE
Skywalking 3.x is compatible with JDK 1.6?

### ISSUE THREAD

**Issue by lintghi** [apache/incubator-skywalking#1418]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
-  Skywalking 3.x is compatible with JDK 1.6?

**Comment by wu-sheng** [comment]
Yes. All agents in 3.x and 5.x should be JDK 1.6 compatible.
