### ISSUE TITLE
service support  95line and 99line response time

### ISSUE THREAD

**Issue by HouZhiHouJue** [apache/incubator-skywalking#1419]
Please answer these questions before submitting your issue.

### Requirement or improvement
- service support  95line and 99line response time for better  interface pressure test

**Comment by wu-sheng** [comment]
Do you mean p99 or p95? If so, we could discuss this in 6 series. Join us meetup, we can discuss features in long term.

**Comment by HouZhiHouJue** [comment]
yes. thank you for your attention :-)

**Comment by wu-sheng** [comment]
Provided in v6. Will be there when release happens.
