### ISSUE TITLE
The GC value graph of each instance is always 0 

### ISSUE THREAD

**Issue by ascrutae** [apache/incubator-skywalking#1425]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

Here is the screen snapshot:
<img width="1045" alt="wx20180704-003006 2x" src="https://user-images.githubusercontent.com/12436447/42232584-6e33ba00-7f21-11e8-9d86-dae3e19ce0a5.png">

**Comment by wu-sheng** [comment]
@peng-yongsheng Please recheck the backend. the beta2 release is still ongoing, considering this is not an important feature. But we should fix this soon, and include this in RC. OK?

**Comment by peng-yongsheng** [comment]
Done
