### ISSUE TITLE
C#/.NET instrument agent  support RabbitMQ or Kafka

### ISSUE THREAD

**Issue by yiyiqian** [apache/incubator-skywalking#1428]
A large number of offline services in our current project are using rabbitMQ. Now C#/.NET instrument agent does not support common queues. I hope skywalking's netcore agent can support this.

**Comment by wu-sheng** [comment]
I think this issue belongs to .net agent repo. Could you move this?

**Comment by yiyiqian** [comment]
ok, I have changed it.
