### ISSUE TITLE
Do we support non microservice standalone java applications?

### ISSUE THREAD

**Issue by asivanadi** [apache/incubator-skywalking#1432]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [-] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean about `non microservice standalone java applications`? I am not following. Desktop application? or something?

**Comment by asivanadi** [comment]
A simple java application that does not have any rest apis exposed.

**Comment by wu-sheng** [comment]
> A simple java application that does not have any rest apis exposed.

Then what do you want an APM to do for that application? Tracing SQL access maybe?

**Comment by asivanadi** [comment]
to trace all the outbound http/https/sql/no-sql calls

**Comment by wu-sheng** [comment]
> to trace all the outbound http/https/sql/no-sql calls

If the application doesn't exit after the calls, because we are using async sending mechanism, it definitely can trace those outgoing RPC calls.

**Comment by asivanadi** [comment]
yes traces are available, but we are not able to see the topology of the application

**Comment by wu-sheng** [comment]
> yes traces are available, but we are not able to see the topology of the application

You should. From this application to other remotes nodes in normal cases.

**Comment by asivanadi** [comment]
any sample spring-boot standalone java app to test?

**Comment by wu-sheng** [comment]
> any sample spring-boot standalone java app to test?

We haven't. Sorry. But in theory, it should be. Because in SkyWalking core, topology is from the every RPC, no matter it is incoming or outgoing.
