### ISSUE TITLE
in web ui  dashbaord, service num Display error

### ISSUE THREAD

**Issue by idealspark** [apache/incubator-skywalking#1433]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [-] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
 **5.0.0-beta2**
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
**in web ui  dashbaord, service count always show the number within 9 hours  ,not according to params 
 such as 15 minutes,2 days beacuse hard code ,my english is poor show your code ,in class OverViewLayerQuery  111 line not pass duration,
```
public ClusterBrief getClusterBrief(Duration duration) {
        long startSecondTimeBucket = DurationUtils.INSTANCE.startTimeDurationToSecondTimeBucket(duration.getStep(), duration.getStart());
        long endSecondTimeBucket = DurationUtils.INSTANCE.endTimeDurationToSecondTimeBucket(duration.getStep(), duration.getEnd());

        ClusterBrief clusterBrief = new ClusterBrief();
        clusterBrief.setNumOfApplication(getApplicationService().getApplications(startSecondTimeBucket, endSecondTimeBucket).size());
        clusterBrief.setNumOfDatabase(getNetworkAddressService().getNumOfDatabase());
        clusterBrief.setNumOfCache(getNetworkAddressService().getNumOfCache());
        clusterBrief.setNumOfMQ(getNetworkAddressService().getNumOfMQ());

//not pass duration
        clusterBrief.setNumOfService(getServiceNameService().getCount());
        return clusterBrief;
    }
```
in class ServiceNameService 62 line call method startTimeMillis() ,but One second equals 1000 milliseconds,in code is 100 milliseconds
```
private long startTimeMillis() {
        int minuteMetricDataTTL = configService.minuteMetricDataTTL();
        return System.currentTimeMillis() - minuteMetricDataTTL * 60 * 60 * 100;
    }
```
**
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
For startTimeMillis, could do send a pull request to fix?

**Comment by wu-sheng** [comment]
Please don't close before pr mergrd. This is for track.

**Comment by idealspark** [comment]
I have send a pull request
