### ISSUE TITLE
Exception: Shadow tracing context. Thread dump

### ISSUE THREAD

**Issue by xyydcoo** [apache/incubator-skywalking#1451]
version: 5.0beta2
log:
[exception.log](https://github.com/apache/incubator-skywalking/files/2190875/exception.log)

**Comment by ascrutae** [comment]
This is the protection mechanism of Skywalking and this error show us that there are more than the value of the `agent.span_limit_per_segment` configuration item(default: 300) in one trace.

**Comment by ascrutae** [comment]
Could you give me the demo to reproduce this issue?

**Comment by xyydcoo** [comment]
@ascrutae   I can't provide demo now. Because it's been too long.@wu-sheng  i think so.

**Comment by wu-sheng** [comment]
Look like as same as #1549 . Closing for now. If this still stays, reopen a new one, and provide us a demo to reproduce. Thanks @xyydcoo
