### ISSUE TITLE
Why having no Application Topology?

### ISSUE THREAD

**Issue by weenyaimac** [apache/incubator-skywalking#1456]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [-] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The error has not occurred from looking into skywalking-collector-server.log and webapp.log, but the collector has not received any application topology and throughput data. What result to this?
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking beta, CentOS 7.2, JRE 1.8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/8892967/42740326-96b71164-88d8-11e8-97d4-e6b5560c32cb.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions

.

**Comment by wu-sheng** [comment]
You need to find out:
1. Does the agent  collect trace? Does agent register work?
1. Does the collector receive the data?

Your question is impossible to answer. And not topology data, just trace.
