### ISSUE TITLE
How to build skywalking-ui?

### ISSUE THREAD

**Issue by zhenjing** [apache/incubator-skywalking#1457]
编译skywalking整个项目时，skywalking-ui无法编译成功。 请问应该如何编译？

从GitHub下载代码编译，编译流程如下： 
 准备环境: git, jdk8，Maven 
 git clone https://github.com/apache/incubator-skywalking.git 
 cd incubator-skywalking/ 
 切换到tag git checkout [tagname] (可选，当需要编译发行版本时，请是切换到指定分支) 
 git submodule init 
 git submodule update 
 执行mvn clean package -DskipTests 
 生成包在/dist目录下（.tar.gz是linux环境，.zip是windows环境） 

报错日志：
[INFO] Running 'npm install --registry=https://registry.npm.taobao.org/' in /XXX/workspace/thirdparty/incubator-skywalking/skywalking-ui
[WARNING] npm WARN saveError ENOENT: no such file or directory, open '/XXX/workspace/thirdparty/incubator-skywalking/skywalking-ui/package.json'
[WARNING] npm WARN enoent ENOENT: no such file or directory, open '/XXX/workspace/thirdparty/incubator-skywalking/skywalking-ui/package.json'
[WARNING] npm WARN skywalking-ui No description
[WARNING] npm WARN skywalking-ui No repository field.
[WARNING] npm WARN skywalking-ui No README data
[WARNING] npm WARN skywalking-ui No license field.
[ERROR]
[INFO] added 4 packages in 2.901s
[INFO]
[INFO] --- frontend-maven-plugin:1.6:npm (npm run build) @ apm-webapp ---
[INFO] Running 'npm run build' in /XXX/workspace/thirdparty/incubator-skywalking/skywalking-ui
[ERROR] npm ERR! path /XXX/workspace/thirdparty/incubator-skywalking/skywalking-ui/package.json
[ERROR] npm ERR! code ENOENT
[ERROR] npm ERR! errno -2
[ERROR] npm ERR! syscall open
[ERROR] npm ERR! enoent ENOENT: no such file or directory, open '/XXX/workspace/thirdparty/incubator-skywalking/skywalking-ui/package.json'
[ERROR] npm ERR! enoent This is related to npm not being able to find a file.
[ERROR] npm ERR! enoent

**Comment by wu-sheng** [comment]
First, you can find we are running the CI(travis-ci) all the time. You can find the build log from here: https://travis-ci.org/apache/incubator-skywalking

I don't think the codes have any issue to trigger this problem. Please check your network, this is a big project, need download a lot of things.

**Comment by zhenjing** [comment]
incubator-skywalking-ui 代码没下载导致的。

执行：git submodule update
