### ISSUE TITLE
[BUG]The Application can not be found

### ISSUE THREAD

**Issue by cyj0122** [apache/incubator-skywalking#1459]
### Bug
SkyWalking:5.0.0-beta2

i add agent into 2 apps, the one on windows displayed, but the other on linux dose't.
i find the data of application is in elastiscsearch.
![image](https://user-images.githubusercontent.com/26588578/42747835-8299880a-8910-11e8-86e5-2b3f915fc842.png)

but ui has no application.
![image](https://user-images.githubusercontent.com/26588578/42747792-64abb7d2-8910-11e8-9be2-ab22756b631e.png)

![image](https://user-images.githubusercontent.com/26588578/42747783-59e08864-8910-11e8-819f-b4213ed3343a.png)

**Comment by wu-sheng** [comment]
We can't accept this kind of issue. You need to find what happens in the agent. The visualization can't tell us anything.

**Comment by cyj0122** [comment]
![image](https://user-images.githubusercontent.com/26588578/42749193-7e543542-8915-11e8-967d-577d221e03bd.png)


Is nothing wrong in skywalking-api.log
Because es has data, I think this issue is not agent's problem.

**Comment by wu-sheng** [comment]
I mean, your descriptions are helpless for us. We can't provide any info for you. You can easily debug the data in collector, and find out why it doesn't show up in elasticsearch. After you have something, we can discuss more.
