### ISSUE TITLE
RestTemplate:The port component of a URI is -1

### ISSUE THREAD

**Issue by neeuq** [apache/incubator-skywalking#1463]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [-] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Question
- What do you want to know?
Test of Spring RestTemplate.
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalk - beta2
OS - windows
JRE - 8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

There is some problom when upload image,for example
- peer:http://baidu.com:443
- url:http://baidu.com:-1
I read the code in [RestExecuteInterceptor](https://github.com/apache/incubator-skywalking/blob/master/apm-sniffer/apm-sdk-plugin/spring-plugins/resttemplate-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/resttemplate/async/RestExecuteInterceptor.java).And I can't understand why there is different beteent PEER and URL.

        String remotePeer = requestURL.getHost() + ":" + (requestURL.getPort() > 0 ? requestURL.getPort() : "https".equalsIgnoreCase(requestURL.getScheme()) ? 443 : 80);
        AbstractSpan span = ContextManager.createExitSpan(requestURL.getPath(), contextCarrier, remotePeer);

        span.setComponent(ComponentsDefine.SPRING_REST_TEMPLATE);
        Tags.URL.set(span, requestURL.getScheme() + "://" + requestURL.getHost() + ":" + requestURL.getPort() + requestURL.getPath());

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Peer doesn't include the endpoint path. Such as:
- peer:  127.0.0.1:8080
- URL: http://127.0.0.1:8080/abc/def

**Comment by neeuq** [comment]
I mean the port between peer and url is different.And if you don't set port in URI , the value is -1.

- peer:`(requestURL.getPort() > 0 ? requestURL.getPort():"https".equalsIgnoreCase(requestURL.getScheme()) ? 443 : 80)`

- URL:`requestURL.getHost()`

**Comment by wu-sheng** [comment]
I see. You can submit a pr to make URL right. In theory, these two needn't be the same as always. But the URL definitely needs the port.
