### ISSUE TITLE
求一份靠谱的单机调试环境搭建

### ISSUE THREAD

**Issue by nize1989** [apache/incubator-skywalking#1481]
Please answer these questions before submitting your issue.

想在自己电脑上安装个skywalking单机版，
环境：
win10
skywalking版本：5.0.0-beta2
idea
jdk：1.6、1.8
maven
打算启动步骤：
1、启动 SkyWalking Collector
2、启动 SkyWalking Agent
3、启动 SkyWalking Web UI
但是第一步按照https://github.com/apache/incubator-skywalking/blob/v5.0.0-alpha/docs/cn/How-to-build-CN.md建议怎么都执行不过执行mvn compile -Dmaven.test.skip=true进行编译，中间各种报错，你们启动手册也太简略了点。
能否给一份靠谱的调试环境搭建手册啊，万分感谢！

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The build doc is used by the whole community. Please follow all steps. And use good network env. This is a big project, which you need a lot of things.
