### ISSUE TITLE
when I execute ./startup.sh ,Log shows that connection is not possible to http://ip:10800

### ISSUE THREAD

**Issue by hustcxx** [apache/incubator-skywalking#1482]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking beta2
os:linxu suse
jre:8
- Which company or project?

- What happen?
kywaling-collector-server.log file ：
main ERROR:field named ac in application index not found .
caused by:org.apache.skywalking.apm.collector.storage.StorageInstallException::field named ac in application index not found .

**Comment by wu-sheng** [comment]
This is not about connection. This fail means, your elastic search table(type) existed, but don't include the right field(column). Most likely, you have used this es for the early version and didn't clear that.
