### ISSUE TITLE
Define a plugin and the component of Tags say: N/A

### ISSUE THREAD

**Issue by cloudgc** [apache/incubator-skywalking#1486]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
-  i want write plugin about springboot use **undertow-1.4.X**
so I define **UNDERTOW** in ：
org.apache.skywalking.apm.network.trace.component.ComponentsDefine
**public static final OfficialComponent UNDERTOW =  new OfficialComponent(45, "UNDERTOW");**

so  I get compile pass and package success 

then  I test on webapp 

___
### Info
here the web ui 

![sky](https://user-images.githubusercontent.com/34081704/43063871-d53e6420-8e8f-11e8-9b5d-960e993fbace.jpg)

and [**This** ](https://github.com/cloudgc/incubator-skywalking/tree/master/apm-sniffer/apm-sdk-plugin/underdow-1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/undertow1x) is my fork
 
is any other file need to modify???

___
### Other issue
when I test springmvc plugin in springboot 
and the web UI cann`t show the icon .
so whats wrong ?

![1234](https://user-images.githubusercontent.com/34081704/43065719-3ec33272-8e95-11e8-9782-f1e694a350b9.jpg)

the data
{
  "data": {
    "getClusterTopology": {
      "nodes": [
        {"id": "-2", "name": "admincommon", "type": "N/A", "sla": 100, "cpm": 4, "avgResponseTime": 77, "apdex": 100, "isAlarm": false, "numOfServer": 2, "numOfServerAlarm": 0, "numOfServiceAlarm": 0},
        {"id": "-1", "name": "clientdemo", "type": "SpringMVC", "sla": 100, "cpm": 4, "avgResponseTime": 17, "apdex": 100, "isAlarm": false, "numOfServer": 1, "numOfServerAlarm": 0, "numOfServiceAlarm": 0},
        {"id": "1", "name": "User", "type": "USER"}
      ],
      "calls": [
        {"source": "-2", "target": "-1", "isAlert": false, "callType": "Feign", "cpm": 3, "avgResponseTime": 7},
        {"source": "1", "target": "-2", "isAlert": false, "callType": "", "cpm": 4, "avgResponseTime": 72},
        {"source": "1", "target": "-1", "isAlert": false, "callType": "", "cpm": 0, "avgResponseTime": 85}
      ]
    }
  }
}

The **N/A**  come from my plugin

**Comment by wu-sheng** [comment]
There is a setting file in collector site. See component-libraries.

**Comment by cloudgc** [comment]
org.apache.skywalking.apm.collector.configuration.service.ComponentLibraryCatalogService
and the file name is  **_incubator-skywalking\apm-collector\apm-collector-configuration\collector-configuration-provider\src\test\resources\component-libraries.yml_**
