### ISSUE TITLE
GloableIDGenerator may produce duplicate ids?

### ISSUE THREAD

**Issue by Yuanxiangz** [apache/incubator-skywalking#1504]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I read the GlobalIdGenerator code, the global id is made of three parts:  applicationid which is mapping to application code, threadid, and timespan+squencenum

if an application has more than one machines, from the ApplicationIDService they will get the same applicationid right? so there's small chance to get a duplicate globalid?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I think you misunderstand the codes. Read again. This is not application id, it is application instance id.
```
        return new ID(
            RemoteDownstreamConfig.Agent.APPLICATION_INSTANCE_ID,
            Thread.currentThread().getId(),
            context.nextSeq()
        );
```

**Comment by Yuanxiangz** [comment]
You're right. Thanks for you correction!
