### ISSUE TITLE
How to create a new component

### ISSUE THREAD

**Issue by tangsiyuan** [apache/incubator-skywalking#1509]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to register a new component such as mysql or MQ.
I want to create a plugin, but I didn't find out how to register the component for plugin in doc

**Comment by wu-sheng** [comment]
We have already provided the document: https://github.com/apache/incubator-skywalking/blob/master/docs/en/Component-libraries-extend.md
