### ISSUE TITLE
Question:How Skywalking handles ES deep paging problems？

### ISSUE THREAD

**Issue by ZhaoRuidong** [apache/incubator-skywalking#1510]
In such a case , collector collected more than 10000 data，when I jump to 1000+ page. Skywalking search work incorrectly.

**Comment by wu-sheng** [comment]
1. Why do you try to jump to 1000 pages? This is an unusual usage.
1. What do you mean `incorrectly`? Too slow or something else?

**Comment by ZhaoRuidong** [comment]
I just try to jump to 1001 page, and the web ui give me error notice.
Msg:
UI
- Exception while fetching data (/queryBasicTraces) : all shards failed

**Comment by ZhaoRuidong** [comment]
It should be restrictions on ES ,due to "start + size " large than 10000

**Comment by wu-sheng** [comment]
> It should be restrictions on ES ,due to "start + size " larger than 10000

In most cases, this means ES can't support this payload. If you have more ES shardings, or you have the more powerful machine, maybe work out.
