### ISSUE TITLE
[Question] about sampling

### ISSUE THREAD

**Issue by Yuanxiangz** [apache/incubator-skywalking#1517]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

If we use sampling, the indicator "Avg Throughput" will not affect the real throughput right? I find the ignorecontext will be dropped, so we will not get the real throughput.

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> If we use sampling, the indicator "Avg Throughput" will not affect the real throughput right? I find the ignorecontext will be dropped, so we will not get the real throughput.

Yes. You will not. That is a different story about metric not from traces. In v6(not first version), we may support running in that way.
