### ISSUE TITLE
Undertow plugin finish local test, request  component Id 

### ISSUE THREAD

**Issue by cloudgc** [apache/incubator-skywalking#1518]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [x] Feature or performance improvement

___
### Question
- I have alredy finish Undertow plugin localtest  
 my plugin use component Id is 

public static final OfficialComponent UNDERTOW =  new OfficialComponent(45, "Undertow");

I want pull a request , So , should remain this id

**Comment by wu-sheng** [comment]
The ID value is not important. I think you could include this value in your PR should be good enough.
