### ISSUE TITLE
How to defined application name in skywalking web ui?

### ISSUE THREAD

**Issue by flysqrlboy** [apache/incubator-skywalking#1520]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I launched skywalking in my mac, and started several spingboot processes in the same mac. After I issued some requests, I signed in the web dashboard. I found out that the application name is "Your_ApplicationName". (As below pic shows)I want to know how to defined the applicaion name .

![image](https://user-images.githubusercontent.com/7646548/43640326-1d597ef0-9752-11e8-9d1b-cecccfe866b3.png)

##### version of SkyWalking
   5.0.0-beta2
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Please follow the documents. The agent has settings about the applciation_code.
