### ISSUE TITLE
collectorService.sh running  error

### ISSUE THREAD

**Issue by xinzhuxiansheng** [apache/incubator-skywalking#1527]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking: 5.0.0.RC
- Which company or project?

- What happen?
1. read  "How to build project.md"  and reference these steps . 
2. mvn clean package -DskipTests
3. deploy local package
4. run collectorService.sh
startup failed.

log info:
[root@ bin]# ./collectorService.sh 
: command not foundsh: line 16: 
: command not foundsh: line 18: 
/..: No such file or directory: cd: .
: command not foundsh: line 22: 
: command not foundsh: line 25: 
'/collectorService.sh: line 35: syntax error near unexpected token `do
'/collectorService.sh: line 35: `do

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
No one reported this kind of error. Could you try to fix this in your local? Or provide more detailed info, such as your JVM version, OS version, etc.

**Comment by xinzhuxiansheng** [comment]
thx,晟哥，  I get it，about file encoding ... ，use dos2unix  command。[dos2unix filename] .
