### ISSUE TITLE
getClusterTopology error

### ISSUE THREAD

**Issue by Yuanxiangz** [apache/incubator-skywalking#1532]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 5.0.0.RC   OS: centos6.9
- Which company or project?

- What happen?
please see the attachment. UI error: Cannot return null for non-nullable type: 'String' within parent 'Call' (/getClusterTopology/calls[147]/callType)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
![getclustertopology](https://user-images.githubusercontent.com/11549125/43830703-89288d3e-9b34-11e8-9b17-91d2623de14e.png)

**Comment by wu-sheng** [comment]
You need to provide the UI request and response for this particular  HTTP request.

**Comment by Yuanxiangz** [comment]
hi sheng, i didn't save the error request and response. from the code it seems call.setCallType(nodeCompMap.get(referenceMetric.getTarget())); the calltype is null sometime in ClusterTopologyService.getClusterTopology. I just found our es run into some problems before. maybe that's because some docs are missing during the es problem. not sure yet. i will update it if issue persist.

**Comment by wu-sheng** [comment]
Ok. Reopen this when you have problem.
