### ISSUE TITLE
Request to add application names to the slow service list

### ISSUE THREAD

**Issue by windywang** [apache/incubator-skywalking#1533]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [* ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
Can you add the application name in the slow service list of home page?When you find the problem service, you can quickly find out which application it is. Sometimes developer konws，but Operations do not。

**Comment by wu-sheng** [comment]
You just need to click the service, then in the `service` page, `application name` shows that page.
