### ISSUE TITLE
Not able to view traces for service calls

### ISSUE THREAD

**Issue by saji-v** [apache/incubator-skywalking#1538]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- I had configured Skywalking as specified in the documentation. The version was 5.0.0-beta . I had seen the traces also once but then after that the traces are not coming up. Any idea what could have gone wrong or the logs I should see? I can see that 

1. there are no error logs in agent. 
2. Agent is able to connect as seen in logs
3. No errors in collector logs

**Comment by wu-sheng** [comment]
Do you see anything in other pages? Like topology, traces, application views?

**Comment by saji-v** [comment]
Well I don't see anything in any page. I am new to skywalking so I am suspecting a wrong configuration somewhere. When I make a new service request, all I can see is the service count gets incremented in dashboard. But in services tab, there is one empty entry. But I can select it. And it throws error saying `Variable 'applicationId' has coerced Null value for NonNull type 'ID!'`

**Comment by wu-sheng** [comment]
First, make sure there are requests to your monitored services. Then, check whether this is data in ES. Last, make sure your machine(VM) time and timezone settings are right.

**Comment by saji-v** [comment]
- There are requests I am making to my monitored service
- Elastic I can see lots of indices created. Not sure which one specifically should I check
- Since my application and collector are on same host for now, I hope I can rule out the possibility of timezone setting

**Comment by wu-sheng** [comment]
> Elastic I can see lots of indices created. Not sure which one specifically should I check

See `application_*`, `jvm*`.

> Since my application and collector are on same host for now, I hope I can rule out the possibility of timezone setting

Is the host your local machine? Browser should be in the same time zone.

**Comment by saji-v** [comment]
Thanks wu-sheng. That helped. After some time the data came up. I hope the issue was the browser and the deployment machines were not same. The works after some time. One more issue I am facing is, now the pplication/service and topology tabs are now getting populated. I can see individual traces though

**Comment by wu-sheng** [comment]
Could you provide the trace screenshot? In most cases, you need to try to pinpoint the cause.
