### ISSUE TITLE
Application Map and Topology not getting populated

### ISSUE THREAD

**Issue by saji-v** [apache/incubator-skywalking#1542]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
___
### Question
- My application map and Topology not getting populated even though traces are getting recorded. Any clues?

**Comment by wu-sheng** [comment]
> My application map and Topology not getting populated even though traces are getting recorded. Any clues?

In most cases, we have known, because the timezones of VM and browser. Nothing else.
