### ISSUE TITLE
Is motan rpc supported from skywaking version 5.x?

### ISSUE THREAD

**Issue by hepyu** [apache/incubator-skywalking#1545]
Hi. Is motan rpc supported from skywaking version 5.x?

Because 5.x is not stable version, I download the version 3.2.6, but not found the motan support. Then I looked over the issue history, it seems motan rpc is not supported before skywalking version 5.x according to the issue timestamp.

Expect to your answer, 3q much.

**Comment by hepyu** [comment]
BTW, is there some docs about how to integrate motan rpc into skywalking? I still not found the motan config in application.yml from apache-skywalking-apm-incubating-5.0.0-beta2.tar.gz that the latest version, or I am in the wrong way?

**Comment by wu-sheng** [comment]
I think 5.0.0-beta2 is stable enough. Feel free to use that. And for SkyWalking auto instrument, no need to set anything particular for motan, just follow documents to set agent, the motan will effect automatically.

:P Magic part of auto instrument agent.

**Comment by hepyu** [comment]
Actually, I still want to know if skywalking version 3.2.6 support motan rpc, sorry to disturb you again, I am the obsession...3q~

**Comment by wu-sheng** [comment]
I can't remember that. You can switch to that tag, if no plugin source codes, that is the answer.

**Comment by hepyu** [comment]
I looked over the code according to your advice, version 3.2.6 support motan, and deploy it to validate, it works. 3QS a lot~~

**Comment by wu-sheng** [comment]
You are welcome. Have fun in APM world.

**Comment by wu-sheng** [comment]
After you used in your product or test env, welcome to share the user info with us. It is important to the project and community.
