### ISSUE TITLE
-javaagent方式springboot无法加载主类

### ISSUE THREAD

**Issue by jiashiwen** [apache/incubator-skywalking#1548]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
skywalking 如何与springboot联合使用我使用 java -javaagent:/path/skywalking-agent.jar app1-0.0.1-SNAPSHOT.jar报找不到或无法加载主类错误
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only. Javaagent can't boot by itself. It is an attachment for you main.

**Comment by sc750531323** [comment]
i have the same question that main class not found when my springboot appliction start, how to use skywalking  when i start a springboot application?

**Comment by wu-sheng** [comment]
Main class depends on your startup script. There is nothing SkyWalking did relate to it.

**Comment by JanYunkai** [comment]
so how can i fix it?
nohup $JAVA_HOME/bin/java $JAVA_OPTS -cp conf:lib/* xxx.xxx.ApiMarketGwApplication >/dev/null 2>&1 &

**Comment by kspine** [comment]
你好，当应用经过字节码加密之后，SkyWalking是否仍然适用呢
