### ISSUE TITLE
the source code is not complete!!!!!!!!!1

### ISSUE THREAD

**Issue by antizhou** [apache/incubator-skywalking#1556]
please answer my question, the branch of master does not have complete source code.,e.g.(org.apache.skywalking.apm.network.proto.SpanObject,org.apache.skywalking.apm.network.proto.TraceSegmentObject... and so on), could you please check it?

**Comment by wu-sheng** [comment]
If you don't follow this document, I can't make sure anything. https://github.com/apache/incubator-skywalking/blob/master/docs/en/How-to-build.md

The CI check build status. Please read the document.
