### ISSUE TITLE
When are you releasing a new version v6.0 ?

### ISSUE THREAD

**Issue by imlaotse** [apache/incubator-skywalking#1563]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
`When are you releasing a new version v6.0 ?`
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Why do you want us to release 6.0? It is a very new version, just open to contributors or feature discussion.

**Comment by imlaotse** [comment]
or: When are you releasing a new version v5.0, not bate or snapshot ?

**Comment by wu-sheng** [comment]
Rc will release in this week or next. Beta2 is stable enough for me.
