### ISSUE TITLE
does skywalking support trace redisson?

### ISSUE THREAD

**Issue by 18378333917** [apache/incubator-skywalking#1564]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
No. But we are welcome the contribution. Add a new plugin shouldn't be too hard

**Comment by wu-sheng** [comment]
I will keep this open, someone may be interested in contributing to this plugin. I look forward to that.

**Comment by zhaoyuguang** [comment]
My company is also using redisson component(3.6.0). I'll finish it at https://github.com/apache/incubator-skywalking/pull/2083
