### ISSUE TITLE
Is there a plan to support PHP agent?

### ISSUE THREAD

**Issue by bgping** [apache/incubator-skywalking#1567]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Requirement
___
### Question
- What do you want to know?

is there a plan to support PHP agent，if there is,When?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

gauzi.com

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

we need php agent.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I just know someone in the community is using molten as codebases, wants to switch it to SkyWalking core. But I am not sure whether it is done or open sourced.

Let's keep this issue open.

**Comment by tincopper** [comment]
Yes, I am currently developing a php agent based on the secondary development of open source molten, which is used to collect data reported to skywalking. The current progress has been completed for tracking single process links, and is currently under development for cross-process. 
When I finish this part of the development I will open it up.

ps: it supports php5 and php7.1 versions.

**Comment by wu-sheng** [comment]
@tincopper Thanks for sharing this with us. You could ping @zzusoftboy after you open sourced the project. He is good at C and PHP both.

**Comment by bgping** [comment]
also need go agent！
our company use java php go python~

**Comment by wu-sheng** [comment]
Go auto instrument agent is too hard for me. I think i am not the right one to do so. The SkyWalking go sdk is not finished. If there is any volunteer to offer helps, it can continue.

**Comment by wu-sheng** [comment]
See https://github.com/SkyAPM/SkyAPM-php-sdk
