### ISSUE TITLE
Incorrect class names of Motan plugin

### ISSUE THREAD

**Issue by hepyu** [apache/incubator-skywalking#1573]
Is skywalking version 3.2.6 support motan verson 1.1.1?

I notice that skywalking version 3.2.6 only support motan 1.1.0 and below, according to doc https://github.com/apache/incubator-skywalking/blob/master/docs/Supported-list.md.

**Comment by wu-sheng** [comment]
We don't know :)  You can run some tests on your own env. I guess it is yes.

**Comment by hepyu** [comment]
Yes, it did.

I checked code from motan1.1.0-1.1.1 to skywalking-3.2.6.
Then I think the key is : the process of these classes is same in motan that from 1.1.0 to 1.1.1 as below:

private static final String ENHANCE_CLASS = "com.weibo.api.motan.transport.ProviderMessageRouter";
private static final String ENHANCE_CLASS = "com.weibo.api.motan.rpc.AbstractReferer";

So it works, is this reason? Of course , I had run on my own env, it did work.

BTW, the java classes named in skywalking is some weird, I mean,
MotanProviderInstrumentation-->com.weibo.api.motan.rpc.AbstractReferer
MotanConsumerInstrumentation-->com.weibo.api.motan.transport.ProviderMessageRouter
It seems named reverse.

**Comment by wu-sheng** [comment]
Yes. That is the reason. @ascrutae could you confirm whether the naming is wrong?

**Comment by ascrutae** [comment]
Yes. the class name is incorrect. Maybe you can send an PR to resolve this problem. @hepyu

**Comment by wu-sheng** [comment]
@hepyu Please help us to fix this in 5.0(master branch)

**Comment by wu-sheng** [comment]
Even no functional issue, naming is making people confused. Need to be fixed in RC release.

**Comment by hepyu** [comment]
Thanks, I'm Interested. This weekend I'll have a try.

**Comment by wu-sheng** [comment]
I will do release at Monday. Please, didn't be late.

**Comment by hepyu** [comment]
Oh, I'm sorry, the time is tight, because my go experience is little, need much time to adjust env.

Although this change is very simple, I think only rename relative class name is ok.
![image](https://user-images.githubusercontent.com/3917749/44527233-d2a6ca80-a718-11e8-8fff-1931212f99c4.png)

But I have some obsession, still want to validate in my own running env, the time is not enough.

So maybe this change need your team fixing, sorry a lot.

**Comment by wu-sheng** [comment]
We also encourage the community to fix the issue. This is an issue, but don't hurt anyone at runtime. So if you want to fix this, I can move this to GA, which will release one month later. Should be better?

You are right, every PR should be checked in your local env. :) Don't worry, you are doing the right thing.

**Comment by wu-sheng** [comment]
Milestone changed. So don't worry about time.
