### ISSUE TITLE
怎么让展示界面支持uri方式？

### ISSUE THREAD

**Issue by mliu111477** [apache/incubator-skywalking#1591]
我们希望在前端界面进行操作时，可以将参数信息保存到URI中。当其他人需要查看相关信息时，直接拷贝URL地址即可。这个要怎么做才能实现？
比如分页时，将分页条件在地址栏中显示。比如搜索调用信息时，将查询条件在地址栏中显示。

**Comment by wu-sheng** [comment]
English only please. Secondary decelopment needs you know the project well, then we discuss. We are impossible to guide you to code line by line.

**Comment by wu-sheng** [comment]
You could proposal your design, then we can review and help you based on that.
