### ISSUE TITLE
skywalking 支持play2框架项目吗？

### ISSUE THREAD

**Issue by qiuwenxiang** [apache/incubator-skywalking#1594]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion

- What happen?
日志打印 Caused by: java.lang.NoClassDefFoundError: org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/InstanceMethodsAroundInterceptor
类似  #1449 
___
### Requirement or improvement
有没有支持play2项目的案例？
谢谢

**Comment by wu-sheng** [comment]
English, please. For your question, we don't support, we need community volunteer to do that, or you contribute that by yourself.

Try #1449 if this is similar. But I don't know what is happening.
