### ISSUE TITLE
How to config es index generated by date? (version3.2.6)

### ISSUE THREAD

**Issue by hepyu** [apache/incubator-skywalking#1595]
skywalking 3.2.6.

How to config es index generated by date in the skywalking-collector? Because in the product env, the data is huge amount, we need deleting data by date cyclely, Its very simple and efficiency to delete old data.

**Comment by hepyu** [comment]
Is this config will be work? I just try.

![image](https://user-images.githubusercontent.com/3917749/44703906-02b0ed80-aacc-11e8-8e63-4d9b85093fbd.png)

**Comment by wu-sheng** [comment]
We don't have such mechanism, even in 5.x, we only provided data delete, but not es index sharding by time bucket. In 6, I think @peng-yongsheng proposed to do so.

**Comment by wu-sheng** [comment]
That config is for 5.x only. Especially in RC and beta2.

**Comment by wu-sheng** [comment]
> These codes are existed in the version 3.2.6, and it seems just only to define the expired time of trace date in the es, rather than the index generated by time according to the code.

I don't remember we have that. :) Sorry. more than 1 year ago.
