### ISSUE TITLE
Discussion about namespace

### ISSUE THREAD

**Issue by deguste** [apache/incubator-skywalking#1597]
### Requirement or improvement
I  found on the skywalking 5.0.0-RC provided a new feature called 'namespace' to isolate different environments. But int the collector instance just can handle one namespace and config it in the yml file. Is there any solution to let the  collector instance handle several namespace for reuse server resource, I think this feature called "multi-tenancy" ？

**Comment by wu-sheng** [comment]
No, you could use namespace to implement `multi-tenancy`, but it is the same. We don't have tenancy info, backend aggregation isn't designed for supporting that too. 

For backend, if you deploy more than one skywalking cluster, but share zookeeper and ElasticSearch, that is the namespace for.
