### ISSUE TITLE
北京力码科技采用Skywalking

### ISSUE THREAD

**Issue by wqr2016** [apache/incubator-skywalking#1600]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Comment in this issue please, https://github.com/apache/incubator-skywalking/issues/443 Thanks for sharing.
