### ISSUE TITLE
Over 100 instances of HystrixRequestVariable are being stored. This is likely the sign of a memory leak caused by using unique instances of HystrixConcurrencyStrategy instead of a single instance.

### ISSUE THREAD

**Issue by chenpengfei** [apache/incubator-skywalking#1604]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ * ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

5.0.0-RC-SNAPSHOT

- Which company or project?

[chehejia](https://www.chehejia.com/)

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

app print log info: Over 100 instances of HystrixRequestVariable are being stored. This is likely the sign of a memory leak caused by using unique instances of HystrixConcurrencyStrategy instead of a single instance.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Could you provide a PR to us for fixing this?

**Comment by wu-sheng** [comment]
> caused by using unique instances of HystrixConcurrencyStrategy instead of a single instance.

I am confused by this. Caused by singleton or no-singleton?

**Comment by wu-sheng** [comment]
#1610 fixed, and already released in 5.0.0-RC2
