### ISSUE TITLE
斑马网络 https://www.hellobanma.com/

### ISSUE THREAD

**Issue by sc750531323** [apache/incubator-skywalking#1609]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Thanks for sharing the case. Could you send the pull request to https://github.com/apache/incubator-skywalking/blob/6.0/docs/powered-by.md ?

**Comment by wu-sheng** [comment]
Relate to #443
