### ISSUE TITLE
post address "server:12800/instance/heartbeat" 405 error occurred

### ISSUE THREAD

**Issue by elegance** [apache/incubator-skywalking#1630]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
apache-skywalking-apm-incubating-5.0.0-beta2
Linux ubuntu-xenial 4.4.0-133-generic #159-Ubuntu SMP Fri Aug 10 07:31:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
java version "1.8.0_144"

- What happen?
![heartbear-err](https://user-images.githubusercontent.com/1735811/45091145-261b0e80-b144-11e8-8013-66c752f270db.png)

**Comment by wu-sheng** [comment]
See #1589 RC release is on going.
