### ISSUE TITLE
Try to send 1500 trace segments to collector, with unexpected exception

### ISSUE THREAD

**Issue by bgping** [apache/incubator-skywalking#1639]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ 1] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

5.0

- Which company or project?

maodou.com
guazi.com

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

**after some error log, the agent hangs there .don't send any log anymore

so can't find app on the application list any more**

___
![wechatimg53](https://user-images.githubusercontent.com/22489975/45194111-3508da80-b284-11e8-9dae-b53c38748643.jpeg)

[xinche_operate_java_rest.log](https://github.com/apache/incubator-skywalking/files/2359231/xinche_operate_java_rest.log)

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
For me, look like a gRPC internal error. We have processed this error

```
            StreamObserver<UpstreamSegment> upstreamSegmentStreamObserver = serviceStub.collect(new StreamObserver<Downstream>() {
                @Override
                public void onNext(Downstream downstream) {

                }

                @Override
                public void onError(Throwable throwable) {
                    status.finished();
                    if (logger.isErrorEnable()) {
                        logger.error(throwable, "Send UpstreamSegment to collector fail with a grpc internal exception.");
                    }
                    ServiceManager.INSTANCE.findService(GRPCChannelManager.class).reportError(throwable);
                }

                @Override
                public void onCompleted() {
                    status.finished();
                }
            });
```

In `onError`, status is tagged as finished, so send should continue. But this is an internal error, not a network error(see #reportError method), I am not sure what is happening,

Have you tried the RC2 tag? (Release is on the way). We upgrade gRPC to latest version, but don't know whether fix this or not.

**Comment by bgping** [comment]
we have 17 applications ，and more  will use sky-walking this month，we found sometimes , an application  lost a machine(two of all)，sometimes an application disappear. all because come error like this.
I'll try to upgrade verison to see if the problem is still there.
thanks a lot.
