### ISSUE TITLE
mvnw clean package -DskipTests error

### ISSUE THREAD

**Issue by cyrus-kang** [apache/incubator-skywalking#1642]
### Question
RC2-release  run  mvn clean package -DskipTests 

[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile-custom (default) on project collector-remote-grpc-provider: Unable to copy the file to D:\skywalking\apm-collector\apm-collector-remote\collector-remote-grpc-provider\target\protoc-plugins: D:\skywalking\apm-collector\apm-collector-remote\collector-remote-grpc-provider\target\protoc-plugins\protoc-3.3.0-windows-x86_64.exe (请求的操作无法在使用用户映射区域打开的文件上执行。) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :collector-remote-grpc-provider

**Comment by wu-sheng** [comment]
I am sorry to say, this is common error for protoc running in Windows. Try to reboot your IDE or machine to fix this.

I haven't better solution. You could google for this. :)
