### ISSUE TITLE
Why zookeeper instead of Consul ?

### ISSUE THREAD

**Issue by lamoce** [apache/incubator-skywalking#1650]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Should we introduce Consul to replace zookeeper?

**Comment by wu-sheng** [comment]
This is a switch, only a replacement. Of course, you could provide Consul as another implementor.
