### ISSUE TITLE
Can I download "Skywalking-agent.jar" from the Maven central respiratory?

### ISSUE THREAD

**Issue by BillBearXiong** [apache/incubator-skywalking#1651]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1 ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by BillBearXiong** [comment]
please look to the title  and why don't have Chinese documents？

**Comment by wu-sheng** [comment]
Of source, you can. Master branch is for 6.x, no one provides Chinese document. You can go to branch 5.x to see the released versions.
