### ISSUE TITLE
Update component name since ShardingJDBC has changed its name to Sharding-Sphere

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-skywalking#1658]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement
___
### Requirement or improvement
Request to change component name in component-libraries.yml:
ShardingJDBC -> Sharding-Sphere

Also, Sharding-Sphere will show better appearance when use Mysql icon. So we request to add:
Sharding-Sphere: Mysql 
in Component-Server-Mappings.

**Comment by wu-sheng** [comment]
Send your pull request if you want to change that in this way. My only question, is putting MySQL as your server side name  a good idea?

**Comment by wu-sheng** [comment]
No update in long term.
