### ISSUE TITLE
org.apache.skywalking.apm.network.language.agent doesn't exist

### ISSUE THREAD

**Issue by fang-yan-peng** [apache/incubator-skywalking#1662]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by fang-yan-peng** [comment]
org.apache.skywalking.apm.network.language.agent不存在

**Comment by wu-sheng** [comment]
What do you mean not exist? CI passed, all status look like right.

**Comment by wu-sheng** [comment]
If you are compiling the project, read the document.

**Comment by vanjikumaran** [comment]
For the record initing the submodule will solve this issue.
https://github.com/apache/skywalking/blob/master/docs/en/guides/How-to-build.md
