### ISSUE TITLE
Huge memory is used when using skywalking-agent.

### ISSUE THREAD

**Issue by hepyu** [apache/incubator-skywalking#1666]
I'm confused by this case, little requests, but huge memory is used when using skywalking-agent. 

Does skywalking-agent trace the motanStatsLog? Do lots of work to record info about motanStatsLog into ringbuffer?

![image](https://user-images.githubusercontent.com/3917749/45417286-62a2b900-b6b4-11e8-8a8e-c1e98f88d1aa.png)

**Comment by wu-sheng** [comment]
> Does skywalking-agent trace the motanStatsLog?

I don't remember we did that. You can read the motan plugin codes, it is very simple. We just use motan header to propagation across processes, that is all.

**Comment by hepyu** [comment]
Its code is simple. I noticed skywalking using bytebuddy to do bytecode injection. Does bytebuddy used huge memroy? It seems doesn't use memory of xmx, xms.

If I change jdk1.8 to jdk1.7, the memory delta added will become much less.

**Comment by wu-sheng** [comment]
> Does bytebuddy used huge memroy?

No, it will not. Byte Buddy is stable libs. Of course, code manipulation has risk. The cost should be perm size or meta space in different JDK.

**Comment by wu-sheng** [comment]
One possible reason is are you using some dynamic class mechanism? Or motan using?

I have known, some debug tool could trigger this issue, such as Spring dev tool.

**Comment by hepyu** [comment]
I used gperftools to have a analysis like this:

first is using skywalking-agent:

![image](https://user-images.githubusercontent.com/3917749/45431973-449c7f00-b6db-11e8-9469-099921c42d4e.png)

second is not using skywalking-agent:
![image](https://user-images.githubusercontent.com/3917749/45432010-5bdb6c80-b6db-11e8-97db-491118a8514b.png)

Tomorrow I will try btrace to print stack to have a look.

**Comment by hepyu** [comment]
It Seems these had memory leak below:

![image](https://user-images.githubusercontent.com/3917749/45432558-bb864780-b6dc-11e8-90f2-c23af76fc60c.png)

![image](https://user-images.githubusercontent.com/3917749/45432572-c345ec00-b6dc-11e8-900d-de5e9d9119f7.png)

**Comment by wu-sheng** [comment]
Try to do the thread dump to find out who makes the leak.

**Comment by wu-sheng** [comment]
I will keep this open with no milestone. Let's see what is going on.

**Comment by hepyu** [comment]
memory malloc is huge.

![image](https://user-images.githubusercontent.com/3917749/45465176-9f1ef500-b746-11e8-8bcc-45b552356910.png)

**Comment by wu-sheng** [comment]
Could you take a look, which objects cause the leak?

**Comment by wu-sheng** [comment]
From I known, we didn't.

@raphw Do you know anything in byte-buddy could trigger this?

**Comment by raphw** [comment]
If I can have a heap dump, I can have a look. Potentially, some class loader does not clean up its resources when Byte Buddy requests class files.

**Comment by hepyu** [comment]
Are these the reasons as below? It seems very similar as what I met.

https://dzone.com/articles/native-memory-leak-example

https://docs.oracle.com/javase/8/docs/api/java/lang/instrument/ClassFileTransformer.html#transform-java.lang.ClassLoader-java.lang.String-java.lang.Class-java.security.ProtectionDomain-byte:A-

![image](https://user-images.githubusercontent.com/3917749/45472272-4f502600-b766-11e8-9841-4e1e176fc5f1.png)

**Comment by wu-sheng** [comment]
@hepyu Could you upload a dump file here? @raphw is the byte-buddy author, he knows much more things about class loaders and byte codes than me.

**Comment by hepyu** [comment]
How I provided the dump file? email or something else?

**Comment by wu-sheng** [comment]
@raphw Do you have any prefer place to go?

**Comment by hepyu** [comment]
@raphw @wu-sheng here is dump file that only dump live objects.

https://github.com/hepyu/tech-docs/blob/master/skywalking/heap-dump-live-lbs-6G-DisableExplicitGC-JDK1.8.bin

Do you need all objects dumped file? its large, 1.7G, I just try upload to git now.

**Comment by hepyu** [comment]
@raphw The dump file that contains all object is too large, much more than up limitation of git. Could you please provide email or some other way if you need to analysis.

I just remove sensitive codes from project, later will upload to git to help to locate problem.

**Comment by wu-sheng** [comment]
> I just remove sensitive codes from project, later will upload to git to help to locate problem.

I think demo codes and a guide to reproduce the error should be helpful.

**Comment by hepyu** [comment]
@wu-sheng @raphw the example project is : https://github.com/hepyu/bird

the method to start is:
![image](https://user-images.githubusercontent.com/3917749/45480457-9f85b300-b77b-11e8-91c9-f9a5bfd148b1.png)

Its just start com-bird-lbs-service only, with javaagent skywalking-agent, its enough to check over.

@raphw I'm so sorry, because china network fire wall, its so slow to upload file to dropbox even I used vpn, I has tried twice, all failed. May I transfer the dump file directly to your gmail?

**Comment by wu-sheng** [comment]
That is hard to say. If they load too many classes in dynamic, Byte Buddy will make the situation worse. 

@raphw do you have time to check the dump?

**Comment by hepyu** [comment]
@wu-sheng 

We checked motan code again, its only support jdk dynamic way, like this:

![image](https://user-images.githubusercontent.com/3917749/45607190-2ccb4f00-ba7d-11e8-889e-b9c9fd0e19af.png)

I attend a tech-meeting yesterday, have a deep communication with JiaQi Lin that from dangdang, your friend. I noticed that dangdang used skywalking so deeply.

So I still want to find a low coost way to solve this problem to use skywalking-agent.

So we checked the dubbo code, dubbo both support javassist and jdk dynamic load.
If we draw lessons from dubbo to implement a javassit for motan , is it a efficiency way? Because we could use dubbo code about javassist.

what do you think?

I really want to have some advices from you, thanks a lot.

**Comment by wu-sheng** [comment]
Glad to hear you have a good chat.  Dangdang and its arch team support our project from a long time ago. 

From what you have found, could you consider to upgrade jre for your application? I assume that is the safest and easiest way, unless @raphw found the root cause.

Do javaassist stuffs should help, what I am not sure how the motan team think about this.

**Comment by raphw** [comment]
I have planned to look into it this evening.

**Comment by wu-sheng** [comment]
> I have planned to look into it this evening.

Thanks. @raphw

**Comment by hepyu** [comment]
@wu-sheng 

Upgrade jre version maybe not appropriate, because we have used JDK8, the thing happen. When degrade to JDK7, it works much better. Upgrade jre to more higher version is not in our plan, just be cautious.

In order to avoid the useless work, we of course will have a try using dubbo that running in the javassist model to validate the key.

About motan team thing, We checked their issue and code, although they didn't provide other way except jdk dynamic implement, but they provide spi mechanism to support other proxy mechanism implements.
referer:
https://github.com/weibocom/motan/issues/612
https://github.com/weibocom/motan/blob/092aabca33108cbe6970776dd506b44681ae8e32/motan-core/src/main/java/com/weibo/api/motan/proxy/spi/JdkProxyFactory.java

**Comment by wu-sheng** [comment]
how about trying to upgrade the minor version? just for test.

**Comment by hepyu** [comment]
@raphw I have processed, please receive again.3Q a lot.

**Comment by hepyu** [comment]
> how about trying to upgrade the minor version? just for test.

Yeah, you are right, I'll try!

**Comment by hepyu** [comment]
> @hepyu Could you invite me to the repository again? I misclicked.

There are two service, lbs-service is motan-rpc-provider, and lbs-web is motan-rpc-consumer.

The bad thing only occur in the lbs-web. 

Because motan-provider only use static proxy, it works much better, memory only added 100M~200M if xmx=xms=6000M, using JDK8.

**Comment by hepyu** [comment]
@raphw please git pull again, there exists some error about shell start scripts.

like this:
![image](https://user-images.githubusercontent.com/3917749/45621791-345a1a80-bab4-11e8-8c92-46760b373d0a.png)

this url could used to validate:
http://your-lbs-web-ip:9082/lbs/currentLocation/55
and result like this:
![image](https://user-images.githubusercontent.com/3917749/45621822-62d7f580-bab4-11e8-88e0-eb8e4fe3af34.png)

in start shell, only default jvm param, if replay the scene，should use large xmx and xms, I used this:
-XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -Xms6000M -Xmx6000M
JDK8 of course.

If memory is not enough, I advice that use default jvm mem param for lbs-service starting, and large mem jvm param for  lbs-web starting.

**Comment by raphw** [comment]
I thought you had a dump in the repo. Do I need to run the app? Preferably, I would just look at the dump. You can mail me at rafael(dot)wth(at)gmail.com if that is easier.

**Comment by hepyu** [comment]
@raphw 
I think that it seems need to run app. Because dump is so small. I doubt the native mem leak.

@wu-sheng 

upgrade minor version to the latest version: 1.8.0_181-b13, the problem is still exist. I will try JDK9 and JDK10 tomorrow.

**Comment by hepyu** [comment]
@wu-sheng 

I discussed with the author of motan. It seems the  most likely reason, coincide with gperftools analysis result.
https://github.com/weibocom/motan/issues/756

**Comment by wu-sheng** [comment]
@rayzhang0603  Glad to see you join the discussion.

**Comment by wu-sheng** [comment]
@raphw Thanks for the analysis.

For exclusion namespaces, I definitely could choose some. Stage monitor's settings help.

> It is important for performance and for reducing memory consumption, to cache type descriptions by defining a custom type strategy that applies some caching. 

Could you point out how to define `a custom type strategy`? I am not sure

**Comment by wu-sheng** [comment]
@raphw Also, what is this ignore for? https://github.com/stagemonitor/stagemonitor/blob/6804a0fe506c3f7fd210f8c05332d9648fbf3fce/stagemonitor-core/src/main/java/org/stagemonitor/core/instrument/AgentAttacher.java#L238

**Comment by wu-sheng** [comment]
I set the agent in this way first. https://github.com/apache/incubator-skywalking/commit/433cf3a8fdebbcdbc4a6a4c0316c22c49b814933 

@hepyu Could you try cherry-pick to your branch to give a try?

**Comment by hepyu** [comment]
@raphw 3Q a lot ~

@wu-sheng 3Q a lot either, I will try!

**Comment by hepyu** [comment]
@wu-sheng 

We had tried skywalking-3.2.6 in dubbo-2.5.3, its phenomenon most likely motan with skywalking-3.2.6.

But considered with dangdang using scale about skywalking, deep performance test, and deep investigation about skywalking&motan&dubbo.

We had decided that still to use skywalking-3.2.6 as trace facilities. 

About extra overhead memory cost, even to 3.2.6, performance test and underlying implementation has proved that its just acceptable and almost constant, just increase acceptable mem to fix it. We really don't want to invade into the code level even if one letter.

Especially dangdang scale practice give us much more confidence, they had proved the stability and usability in the product env about scale.

**Comment by wu-sheng** [comment]
@hepyu Choose any version you like, that is totally your choice.:)  Just we still could work on your scenario to avoid too many memory costs.

**Comment by hepyu** [comment]
> @hepyu Choose any version you like, that is totally your choice.:) Just we still could work on your scenario to avoid too many memory costs.

Of course, the latest master code has been deployed on our test env, we hope to keep watching the newest progress of skywalking, we are very interested in the lots of practical features.

**Comment by wu-sheng** [comment]
> Of course, the latest master code has been deployed on our test env, we hope to keep watching the newest progress of skywalking, we are very interested in the lots of practical features.

Good to know. `the latest master code` is the latest 5.x codes? Do you cherry-pick my PR to your running codes? That PR is still open, in another branch.

**Comment by hepyu** [comment]
> Good to know. `the latest master code` is the latest 5.x codes? Do you cherry-pick my PR to your running codes? That PR is still open, in another branch.

Yes, 5.x. I noticed that master now is 6.x, I had not upgrade.

I just did a base benchmark about delta mem cost using bird project in different jdk version, from jdk8(contains two minor versions) to jdk10.

https://github.com/hepyu/tech-docs/blob/master/skywalking/skywalking-3.2.6-with-jdkversion-mem-cost-base-referer.doc

**Comment by hepyu** [comment]
> I set the agent in this way first. #1682
> 
> @hepyu Could you try cherry-pick to your branch to give a try?

How could I use this pr? Did it has pushed the master? 

Should I use like this:
I git pull the latest master and compile, then use the skywalking-agent.jar?

**Comment by hepyu** [comment]
> @hepyu Which company are you at now?

Coohua company.

**Comment by hepyu** [comment]
> > I set the agent in this way first. #1682
> > @hepyu Could you try cherry-pick to your branch to give a try?
> 
> How could I use this pr? Did it have pushed the master?
> 
> Should I use like this? If not right, then how, I just work first like this way.....
> I git pull the latest master and compile, then use the skywalking-agent.jar?

Is this branch?
![image](https://user-images.githubusercontent.com/3917749/45736157-b7968000-bc1c-11e8-8d89-5c52eebcb8cb.png)

**Comment by raphw** [comment]
@wu-sheng I meant binary locator, not type locator. It is really mostly about avoiding IO as it generates a bunch of garbage, especially on older VMs. The ignore matcher you refer to is exluding any type that is loaded by a class loader that fulfills a certain condition. Excluding by class loader is done before even looking at the type, therefore such exclusing is very effective. If a class loader is known to not generate any types of interest, this is a good exclusion. It will not alter the result but lead to higher performance. Especially Groovy is problematic here as it needs to generate a lot of boring filler byte code to implement its dynamic features.

**Comment by hepyu** [comment]
the result with skywalking-agent-6.0.0-alpha-adjust-agent-setting.

![image](https://user-images.githubusercontent.com/3917749/45751144-09063580-bc44-11e8-8dbe-1d89b963a5a6.png)

jdk version is:
![image](https://user-images.githubusercontent.com/3917749/45751352-b37e5880-bc44-11e8-9ea7-185551c0d23e.png)

It seems the method to validate is not correct. I read the response from @raphw again, considered with the opportunity of actual "leak".

In my understanding, Its not the real leak as generally speaking. Its occur just because huge native call when transform jar files from local disc, and remaining os mem is not enough to continue before app recycled them.

It seems the correct method contains two dimensions.

1. Replay the actual scenes(weibocom/motan#756) with using skywalking-agent 3.2.6 and 6.0.0-alpha-adjust-agent-setting. If it is not killed when using skywalking-6.0.0-alpha, it will be proved worked.
"weibocom/motan#756" in english, its main idea is that when jvm heap and remaining os mem is small, the os/kubernetes will kill the "jvm instance"/"docker instance".

2.In the machine that owns enough mem to run gperftools to analysis the result again, compare with below:
![image](https://user-images.githubusercontent.com/3917749/45751759-e412c200-bc45-11e8-8994-ff3dd87234ec.png)
If the key of result below is much less than above, it will be proved worked.
like Java_java_util_zip_xxx
![image](https://user-images.githubusercontent.com/3917749/45751866-44a1ff00-bc46-11e8-8295-3070ca969a92.png)
![image](https://user-images.githubusercontent.com/3917749/45751914-6b603580-bc46-11e8-90a7-408363764c14.png)

Am I right about above two dimensions to validate? @raphw @wu-sheng .

**Comment by hepyu** [comment]
Because jvm heap never occur mem leak, just native mem leak occur before jvm gc because os remaining mem is not enough to help classload to load the remaining classes. Usually validate method is invalid in my understanding.

Is my uderstanding correct?

**Comment by hepyu** [comment]
Yeah, the gperftools result seems validate my first dimension point.

jvm version:
![image](https://user-images.githubusercontent.com/3917749/45754214-9c903400-bc4d-11e8-843d-887ecfa2a03a.png)

the result of gperftools with skywalking-agent-6.0.0-alpha:
![image](https://user-images.githubusercontent.com/3917749/45754350-0c062380-bc4e-11e8-8b87-b83f4d2f96c4.png)

the result of gperftools with skywalking-agent-3.2.6:
![image](https://user-images.githubusercontent.com/3917749/45754568-8f277980-bc4e-11e8-9b4c-bab86c9edd88.png)

It seems the key is Java_java_util_zip_Inflater_init.

The premise of two test is the same:
export LD_PRELOAD=/app/3rd/gperftools/lib/libtcmalloc.so
export HEAP_PROFILE_TIME_INTERVAL=10

And print heap per 10 seconds, and fetch eleventh heap as above.

**Comment by wu-sheng** [comment]
Do the new codes work or not? Can you make yourself more clear? Look like it works.

**Comment by hepyu** [comment]
> Do the new codes work or not? Can you make yourself more clear? Look like it works.

I mean the new codes won't reaction to java heap.

And new codes works according to the gperftools analysis.

I will test it on the k8s&docker env to replay the original scene.

**Comment by wu-sheng** [comment]
> I mean the new codes won't react to java heap.

Yes, that is sure. I am thinking about clearing type pool through some timeout mechanism.

**Comment by hepyu** [comment]
> > I mean the new codes won't react to java heap.
> 
> Yes, that is sure. I am thinking about clearing type pool through some timeout mechanism.

I have some question, if type is not used, just not used, why do some timeout mechanism?

**Comment by wu-sheng** [comment]
> I have some question, if type is not used, then not used. why do some timeout mechanism?

I mean type pool in byte-buddy. @felixbarny suggests me to do so. Just same as @raphw mentioned, binary locator, https://github.com/stagemonitor/stagemonitor/blob/6804a0fe506c3f7fd210f8c05332d9648fbf3fce/stagemonitor-core/src/main/java/org/stagemonitor/core/instrument/AutoEvictingCachingBinaryLocator.java#L34

**Comment by hepyu** [comment]
> > I have some question, if type is not used, then not used. why do some timeout mechanism?
> 
> I mean type pool in byte-buddy. @felixbarny suggests me to do so. Just same as @raphw mentioned, binary locator, https://github.com/stagemonitor/stagemonitor/blob/6804a0fe506c3f7fd210f8c05332d9648fbf3fce/stagemonitor-core/src/main/java/org/stagemonitor/core/instrument/AutoEvictingCachingBinaryLocator.java#L34

Got it, 3Q a lot, I will learn it ~~

**Comment by hepyu** [comment]
First, The new codes worked, improved a lot.

The evidence：
Java_java_util_zip_Inflater_init from gperftools decreased from 
"0.6   0.6%  99.9%     47.9  52.3% Java_java_util_zip_Inflater_init"
to
"0.0   0.0%  99.9%      2.0   1.8% Java_java_util_zip_Inflater_init"

The change above means many irrelevant class is ignored.

The columns desc:
![image](https://user-images.githubusercontent.com/3917749/45811993-29e09080-bd01-11e8-91b9-c16c19fddb9b.png)

I had backup the gperftoos, in order to check after.
https://github.com/hepyu/tech-docs/tree/master/skywalking/issue-1666

Second, I tried to restore failed scene in our k8s env, failed. Because we had upgraded the resources. This problem ought to occur in some extreme case: when io, mem resources arrived at some critical point.

**Comment by hepyu** [comment]
> I intend to use it to reduce the perm size after most code weaver works done. 
Yeah, this is very useful ! It will kill many potential risks. I love it~

**Comment by wu-sheng** [comment]
GA will be the codes you have tested. The timeout needs more tests than ignore. 

Do you have any solution about your k8s env? I am sure what happens there. If ignore works, should not cause too many memory costs.

**Comment by hepyu** [comment]
> Do you have any solution about your k8s env? I am sure what happens there. If ignore works, should not cause too many memory costs.

Do you want me to have a test in the k8s env?If agent-3.2.6 fail, and agent-6.0.0 success, then validate ok.Is this mean?

If it is, I had done these things, but couldn't restore, becuase we have upgraded the k8s env, from one machine to two machine, even restore to the same resource, both agent-3.2.6 and agent-6.0.0 are ok, none will be failed.

like this as I wrote:
![image](https://user-images.githubusercontent.com/3917749/45815844-7aa9b680-bd0c-11e8-817d-85a2980e581c.png)

**Comment by hepyu** [comment]
@wu-sheng 

I mean its cost is too expensive, about k8s and docker, we are just try to use, they are only used in the test env. Just have a try, we are not very familiar with them, I just learn to use them.

And all test app are deployed in the k8s, if I restore to the original crime scene, it will cost too time. Because the k8s are used and dockers are deployed every day, its hard to restore to original scene.

And another reason is that it will have a big influence to our business development progress, and cost several colleague time, at least one day.The worst is that maybe still have no chance to restore it.
Because I guess:
This problem ought to occur in some extreme case: when io, mem resources arrived at some critical point.
It becomes much more difficult to restore it.

And in the other word, In china, especially for not big startup company, its so expensive. 
Especially we almost confirm where it is and delta resources are limited in a constant range.

So I think we could confirm effect with gperftools analysis result instead.I think this is the efficiency way to solve the problem.

**Comment by wu-sheng** [comment]
If the current code version works, that is good. I am ok if you are inconvenient. I think we have some conclusions already.

The ignore is definitely good. Right? If all test cases are passed in our env, I will merge the PR and cherry pick it to 5.x. 5.0.0 GA will release next week.

**Comment by hepyu** [comment]
In an occasional cause, we found the reason why jvm instance in k8s would be crashed.

Because the resource of k8s cluster in our dev/test env is so few especially the cpu resources, then processing speed of jvm instance would be substantially reduced. 
Eventually lead to data were piled up in the memory, then crashed. Old version of skywalking accelerated this process.
