### ISSUE TITLE
LocalAsyncWorkerRef throw NullPointerException

### ISSUE THREAD

**Issue by KyrieYan** [apache/incubator-skywalking#1670]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [1] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
What the reason about this exception and how to resolve ?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 5.0
os linux
jre 1.8

- Which company or project?
guazi.com
maodou.com

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
___

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
![wechatimg3](https://user-images.githubusercontent.com/37646663/45478070-ac070d00-b775-11e8-95b4-71a46ff07c27.png)
![wechatimg4](https://user-images.githubusercontent.com/37646663/45478071-ac9fa380-b775-11e8-898f-d8b90f8fe85c.png)

**Comment by wu-sheng** [comment]
NPEs happen in alarm module. Some have been fixed in RC2, and one in this PR, https://github.com/apache/incubator-skywalking/pull/1661
