### ISSUE TITLE
can not run agent

### ISSUE THREAD

**Issue by chtel** [apache/incubator-skywalking#1688]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
use 127.0.0.1 or localhost or real ip, bring different errors,not easy to use!!!!!!!!!!!
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
First run it locally. No need to worry about ip things. Then read architecture document, you will understand. Don't try to guess, read the documents.
