### ISSUE TITLE
Where is enum SpanType?

### ISSUE THREAD

**Issue by wangxiang5050** [apache/incubator-skywalking#1705]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- Question or discussion

___
### Question
我下载了5.0.0-RC2的源代码，想对它进行修改使其支持6.*版本的ES，但由于无法找到枚举org.apache.skywalking.apm.network.proto.SpanType，编译失败，请问我可以从哪里找到这个枚举呢？

**Comment by wu-sheng** [comment]
Read compiling document. You will have everything you need.

**Comment by wangxiang5050** [comment]
Wow, it just looks error, now i compiled successfully, thanks!
