### ISSUE TITLE
ContextManager.continued NPE

### ISSUE THREAD

**Issue by otyyyywangwenbin** [apache/incubator-skywalking#1707]
I'm try writing a netty plugin and have a cross threads problem

I read doc

1. https://github.com/apache/incubator-skywalking/blob/5.x/docs/cn/Plugin-Development-Guide-CN.md#%E4%B8%89-contextsnapshot
2. https://github.com/apache/incubator-skywalking/blob/5.x/docs/en/Plugin-Development-Guide.md#contextsnapshot

Capture a ContextSnapshot in another thread and continued ContextSnapshot in below codes:
```java
    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, MethodInterceptResult result) throws Throwable {
        ChannelHandlerContext context = (ChannelHandlerContext) allArguments[0];
        Object msg = allArguments[1];
        if (msg instanceof HttpRequest) { // Client Request
            System.out.println(">> " + Thread.currentThread().getId() + ":" + context.channel().hashCode());
            Attribute<ContextSnapshot> attr = context.channel().attr(KEY_CONTEXT_SNAPSHOT);
            ContextSnapshot contextSnapshot = attr.get();
            attr.set(null);
            if (contextSnapshot == null) {
                return;
            }
            ContextManager.continued(contextSnapshot);  (Line: 45)
            HttpRequest request = (HttpRequest) msg;
            ContextCarrier contextCarrier = new ContextCarrier();
            String uri = request.uri();
            AbstractSpan span = ContextManager.createExitSpan(uri, contextCarrier, String.valueOf(context.channel().remoteAddress()));
            Tags.URL.set(span, request.uri());
            Tags.HTTP.METHOD.set(span, request.method().name());
            span.setComponent(COMPONENT_NETTY_HTTP_CLIENT);
            SpanLayer.asHttp(span);
            CarrierItem next = contextCarrier.items();
            while (next.hasNext()) {
                next = next.next();
                request.headers().set(next.getHeadKey(), next.getHeadValue());
            }
            context.channel().attr(KEY_CONTEXT_SNAPSHOT).set(ContextManager.capture());

            System.out.println("===> encode client request $$$$$$$$ " + Thread.currentThread().getId() + ":" + context.channel().hashCode());
        }
        return;
    }
```

skywalking-api.log ：
```
ERROR 2018-09-26 17:29:56:913 InstMethodsInter :  class[class io.netty.handler.codec.http.HttpClientCodec$Encoder] before method[encode] intercept failure
java.lang.NullPointerException
	at org.apache.skywalking.apm.agent.core.context.ContextManager.capture(ContextManager.java:143)
	at org.apache.skywalking.apm.agent.core.context.ContextSnapshot.isFromCurrent(ContextSnapshot.java:119)
	at org.apache.skywalking.apm.agent.core.context.ContextManager.continued(ContextManager.java:150)
	at org.apache.skywalking.apm.plugin.netty.EncodeInterceptor.beforeMethod(EncodeInterceptor.java:45)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
```

how to resolve this situation？
skywalking 5.0.0-rc2

**Comment by wu-sheng** [comment]
Your stack shows the npe is in capture stage, not continued.

**Comment by otyyyywangwenbin** [comment]
cause by org.apache.skywalking.apm.agent.core.context.ContextManager.continued(ContextManager.java:150)
and check snapshot isFromCurrent error
why check error, is my code error ?

**Comment by otyyyywangwenbin** [comment]
cause by org.apache.skywalking.apm.agent.core.context.ContextManager.continued(ContextManager.java:150)
and check snapshot isFromCurrent error
why check error, is my code error ?

**Comment by wu-sheng** [comment]
I am not following. Which one is right? The log shows capture. Capture is impossible caused by continued.

**Comment by otyyyywangwenbin** [comment]
I saw the codes:
```
public boolean isFromCurrent() {
        return traceSegmentId.equals(ContextManager.capture().getTraceSegmentId());
    }
}
```
if directly continued conxtsnapshot in a new thread，it must be throws npe.

**Comment by wu-sheng** [comment]
OK, get that. So if you don't have the context in the new thread, how to continue? **Continued** means, current context continues from the Snapshot. So you could see the current context should be existed always.

**Comment by otyyyywangwenbin** [comment]
OK,  I wrote below codes at the beginning. like asynchttpclient plugin
```
 ContextManager.createLocalSpan("netty-http-client/local");

ContextManager.continued(contextSnapshot);
```
but the result is not my expect……
i will try it again

**Comment by wu-sheng** [comment]
> OK, I wrote below codes at the beginning. like asynchttpclient plugin

That codes look good to me. Should work. If not, consider affected by other things.

**Comment by otyyyywangwenbin** [comment]
OK, it works!   
<img width="1295" alt="screen shot 2018-09-27 at 08 33 28" src="https://user-images.githubusercontent.com/6299773/46116755-33ea1e00-c230-11e8-8a6a-328b71c17063.png">

another question is  i found localspan (netty-http-client/send-request) is display in traces list , the localspan(netty-http-client/send-request) and entryspan(/api/ping) have same trace id,  i don't know is it correct? 
<img width="1267" alt="1" src="https://user-images.githubusercontent.com/6299773/46116916-03ef4a80-c231-11e8-958f-673bfd65126e.png">

**Comment by wu-sheng** [comment]
If so, those are in the same thread. Please be sure what do your codes suppose to do. You have read the codes, if they are in same thread, capture/continue will not work, even you called.

**Comment by otyyyywangwenbin** [comment]
```
                           My codes logic looks like:

                                   UserRequest
                                   |       /|\ 
                                   |        |
                                  \|/       |
                                NettyServerIOThread  
                                   |       /|\
                 createEntrySpan   |        |  stopEntrySpan    
                     (/api/ping)   |        |   
                                   |        |
                 captureSnapshot   |        |        
                                  \|/       |
                                NettyClientIOThread  
                                   |       /|\
                   createLocalSpan |        |  stopLocalSpan      
  (netty-http-client/send-request) |        |
                                   |        |
                 continuedSnapshot |        |
                                   |        |       
                    createExitSpan |        |  stopExitSpan
                       (/api/ping) |        |
                                  \|/       |
                                 Ping/PongService
```

> 1. createEntrySpan(/api/ping) , captureSnapshot, stopEntrySpan  in a thread.
> 2. createLocalSpan(netty-http-client/send-request), continuedSnapshot, createExitSpan(/api/ping), stopExitSpan, stopLocalSpan in another thread.

I think the continuedSnapshot is worked
the below png is after comment `ContextManager.continued(contextSnapshot);` the localspan(netty-http-client/send-request) and entryspan(/api/ping) have different trace id,
maybe i describe not correct, they are not called `localspan(netty-http-client/send-request)`,`entryspan(/api/ping)` in trace list
<img width="970" alt="screen shot 2018-09-27 at 09 53 48" src="https://user-images.githubusercontent.com/6299773/46118988-972d7d80-c23b-11e8-96b8-67c4d731f847.png">
and trace is not complete, only one span, it looks like 

<img width="1244" alt="screen shot 2018-09-27 at 10 00 23" src="https://user-images.githubusercontent.com/6299773/46119245-b1b42680-c23c-11e8-91d1-e8c645e6440f.png">

**Comment by wu-sheng** [comment]
If Trace IDs are not the same, it means, `continued` doesn't work as expected. See `TracingContext#continued`. The `this.segment.relatedGlobalTraces` in that method shows you how continue works.

**Comment by otyyyywangwenbin** [comment]
https://github.com/apache/incubator-skywalking/issues/1707#issuecomment-424933082  is comment code `ContextManager.continued(contextSnapshot); `

https://github.com/apache/incubator-skywalking/issues/1707#issuecomment-424917742 is uncomment code `ContextManager.continued(contextSnapshot); `
in this case,  Trace IDs are the same,  but localspan is dispaly in traces list, I don't know if that's correct?

**Comment by wu-sheng** [comment]
> in this case, Trace IDs are the same, but localspan is dispaly in traces list, I don't know if that's correct?

Ah, I think I get your point this time. The list showing there is trace segment list, not trace. So, if a trace across two threads, two segments are expected. The simple answer is YES, that is correct.
