### ISSUE TITLE
Got null when  method parameter is modified by @RequestBody,in a controller method.

### ISSUE THREAD

**Issue by ni-ze** [apache/incubator-skywalking#1724]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion 
- [ ] Bug
    yes
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  5.0.0-RC2 ,OS and windos,  jdk 1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
in the SpringBoot project,when a parameter is  modified by @RequestBody,the value of parameter well be lost, and become to null.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ascrutae** [comment]
Could you post more detail about this problem. and you can post an demo if possible.

**Comment by nize1989** [comment]
![without skywalking](https://user-images.githubusercontent.com/31175234/46246995-c01a6200-c437-11e8-9473-d6c0a14a2966.jpg)
![without skywalking_postman](https://user-images.githubusercontent.com/31175234/46246997-c0b2f880-c437-11e8-8d78-637419b2e835.jpg)
![with skywalking](https://user-images.githubusercontent.com/31175234/46246999-c7417000-c437-11e8-81de-643d7f021130.jpg)
![with skywalking_postman](https://user-images.githubusercontent.com/31175234/46247000-c7da0680-c437-11e8-99a3-77a1a5339622.jpg)

**Comment by nize1989** [comment]
supplement:
the requset is send to TokenControllerV2, whicd extends TokenController . it has a  annotation @RequestMapping(value = "oauth/v2.0").
it work if my url  is localhost:8080/cmtoken/oauth/**v1.0**/login.

**Comment by nize1989** [comment]
@ascrutae

**Comment by wu-sheng** [comment]
Fix in #1914
