### ISSUE TITLE
How it monitor for multiple projects

### ISSUE THREAD

**Issue by eoeac** [apache/incubator-skywalking#1725]
It is have any tag for project if I have multiple project need to be monitored？thx！

**Comment by wu-sheng** [comment]
Tag for what? Multiple jvms are supported by app code.

**Comment by eoeac** [comment]
Tag for different System.
And where can I find agent.namespace info in web-ui? thx.

**Comment by wu-sheng** [comment]
Namespace is for system isolation. Multiple business clusters wouldn't be supported in one skywalking backend and ui cluster.
