### ISSUE TITLE
can't build the skywalking project

### ISSUE THREAD

**Issue by DylanLees** [apache/incubator-skywalking#1743]
Mr.wu,i just pull the skywalking from github,and build it according to offical document in IntelliJ,but it occurs a problem as following.
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (validate) on project apm-spring-cloud-feign-1.x-plugin: Failed during checkstyle configuration: Exception was thrown while
 processing E:\openSources\apache-skywalking-apm-incubating-5.0.0-RC2-src\apache-skywalking-apm-incubating-5.0.0-RC2\apm-sniffer\apm-sdk-plugin\spring-plugins\spring-cloud\netflix-plugins\spring-cloud-feign-1.x-plug
in\src\main\java\org\apache\skywalking\apm\plugin\spring\cloud\PaxHeader\NetflixFeignInstrumentation.java: NoViableAltException occurred during the analysis of file E:\openSources\apache-skywalking-apm-incubating-5.
0.0-RC2-src\apache-skywalking-apm-incubating-5.0.0-RC2\apm-sniffer\apm-sdk-plugin\spring-plugins\spring-cloud\netflix-plugins\spring-cloud-feign-1.x-plugin\src\main\java\org\apache\skywalking\apm\plugin\spring\cloud
\PaxHeader\NetflixFeignInstrumentation.java. unexpected token: 271 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apm-spring-cloud-feign-1.x-plugin
`

**Comment by wu-sheng** [comment]
First, our compile is tested for each release by Travis CI, https://travis-ci.org/apache/incubator-skywalking  . No compiling issue. Considering you are in Windows, make sure you have all codes. Some one reported, windows git clone may have some issues with long file path.

**Comment by cdoewew** [comment]
> 吴先生，我只是从github上拉出天空，并根据的IntelliJ中的官方文档构建它，但它出现了如下问题。
> `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (validate) on project apm-spring-cloud-feign-1.x-plugin: Failed during checkstyle configuration: Exception was thrown while processing E:\openSources\apache-skywalking-apm-incubating-5.0.0-RC2-src\apache-skywalking-apm-incubating-5.0.0-RC2\apm-sniffer\apm-sdk-plugin\spring-plugins\spring-cloud\netflix-plugins\spring-cloud-feign-1.x-plug in\src\main\java\org\apache\skywalking\apm\plugin\spring\cloud\PaxHeader\NetflixFeignInstrumentation.java: NoViableAltException occurred during the analysis of file E:\openSources\apache-skywalking-apm-incubating-5. 0.0-RC2-src\apache-skywalking-apm-incubating-5.0.0-RC2\apm-sniffer\apm-sdk-plugin\spring-plugins\spring-cloud\netflix-plugins\spring-cloud-feign-1.x-plugin\src\main\java\org\apache\skywalking\apm\plugin\spring\cloud \PaxHeader\NetflixFeignInstrumentation.java. unexpected token: 271 -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException [ERROR] [ERROR] After correcting the problems, you can resume the build with the command [ERROR] mvn <goals> -rf :apm-spring-cloud-feign-1.x-plugin`

have you solved it?

**Comment by wu-sheng** [comment]
That usually because some codes are changed in your local, and style check failure.
