### ISSUE TITLE
trace topology is sometimes incorrect.

### ISSUE THREAD

**Issue by caowenyan** [apache/incubator-skywalking#1744]
Now I deploy the skywalking into the produce environment, topologies are mostly correct, but occasionally are incorrect, as shown in Figure . What causes this, and how should I check the data? According to the printed log traceid, the process is correct.

<img width="1434" alt="trace_error" src="https://user-images.githubusercontent.com/9078468/46721919-d7aee180-cca6-11e8-99c7-05ad2b30dfe3.png">

**Comment by caowenyan** [comment]
{"data":{"queryTrace":{"spans":[{"traceId":"42.10116.15391555981510157","segmentId":"56.398.15391555982158248","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"42.10116.15391555981510157","parentSegmentId":"51.66.15391555982132768","parentSpanId":1,"type":"CROSS_PROCESS"}],"applicationCode":"wx-business-provider","startTime":1539155598215,"endTime":1539155598227,"operationName":"com.cloudyoung.wx.business.api.service.WXMessageResponseApi.saveUserBehavior(WxUser,int,String)","type":"Entry","peer":"","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.121:20882/com.cloudyoung.wx.business.api.service.WXMessageResponseApi.saveUserBehavior(WxUser,int,String)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"56.398.15391555982158248","spanId":1,"parentSpanId":0,"refs":[],"applicationCode":"wx-business-provider","startTime":1539155598215,"endTime":1539155598218,"operationName":"Mysql/JDBI/PreparedStatement/execute","type":"Exit","peer":"192.168.50.131:3306","component":"mysql-connector-java","isError":false,"layer":"Database","tags":[{"key":"db.type","value":"sql"},{"key":"db.instance","value":"wx_business"},{"key":"db.statement","value":"select  \n    menu_id, authorizer_appid, menu_is_parent, wx_menu_id, unique_key, menu_category, \n    creation_time, name, status, type, menu_match_rule, extra_content, ord, miniprogram_appid, \n    miniprogram_pagepath, last_modify_time, media_type\n    from wx_menu where status=1 and extra_content = ?\n    and authorizer_appid = ? order by creation_time desc limit 1"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"56.398.15391555982158248","spanId":2,"parentSpanId":0,"refs":[],"applicationCode":"wx-business-provider","startTime":1539155598220,"endTime":1539155598222,"operationName":"Mysql/JDBI/PreparedStatement/execute","type":"Exit","peer":"192.168.50.131:3306","component":"mysql-connector-java","isError":false,"layer":"Database","tags":[{"key":"db.type","value":"sql"},{"key":"db.instance","value":"wx_business"},{"key":"db.statement","value":"select  \n    menu_publish_record_id, authorizer_appid, menu_json_content, status, publish_status, \n    create_time, publish_time, last_modify_time, modify_user_id\n    from wx_menu_publish_record where \n  \tauthorizer_appid = ? and status = 1 and publish_status = 1 order by publish_time desc limit 1"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"56.398.15391555982158248","spanId":3,"parentSpanId":0,"refs":[],"applicationCode":"wx-business-provider","startTime":1539155598223,"endTime":1539155598227,"operationName":"Mysql/JDBI/PreparedStatement/execute","type":"Exit","peer":"192.168.50.131:3306","component":"mysql-connector-java","isError":false,"layer":"Database","tags":[{"key":"db.type","value":"sql"},{"key":"db.instance","value":"wx_business"},{"key":"db.statement","value":"insert into wx_user_behavior (user_behavior_id, authorizer_appid, wx_user_id, \n      behavior_type_name, creation_time, behavior_content, \n      last_modify_time, status,bussiness_id)\n    values (?, ?, ?, \n      ?, ?, ?, \n      ?, ?, ?)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"42.10116.15391555981510156","spanId":0,"parentSpanId":-1,"refs":[],"applicationCode":"wx-authorize-api","startTime":1539155598151,"endTime":1539155598217,"operationName":"/common/platfrom/{appid}/{openPlatformAppId}/handleMessage","type":"Entry","peer":"","component":"SpringMVC","isError":false,"layer":"Http","tags":[{"key":"url","value":"http://ec.web.sgmw.cloud-young.cn/wxauth/common/platfrom/wx7fff11837244a6db/3/handleMessage"},{"key":"http.method","value":"POST"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"42.10116.15391555981510156","spanId":1,"parentSpanId":0,"refs":[],"applicationCode":"wx-authorize-api","startTime":1539155598151,"endTime":1539155598156,"operationName":"com.cloudyoung.wx.api.service.WXOpenPlatformConfigApi.getOpenPlatformThirdAppConfig(Integer)","type":"Exit","peer":"10.0.0.184:20881","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.184:20881/com.cloudyoung.wx.api.service.WXOpenPlatformConfigApi.getOpenPlatformThirdAppConfig(Integer)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"43.407.15391555981521428","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"42.10116.15391555981510157","parentSegmentId":"42.10116.15391555981510156","parentSpanId":1,"type":"CROSS_PROCESS"}],"applicationCode":"wx-auth-provider","startTime":1539155598152,"endTime":1539155598155,"operationName":"com.cloudyoung.wx.api.service.WXOpenPlatformConfigApi.getOpenPlatformThirdAppConfig(Integer)","type":"Entry","peer":"","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.184:20881/com.cloudyoung.wx.api.service.WXOpenPlatformConfigApi.getOpenPlatformThirdAppConfig(Integer)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"43.407.15391555981521428","spanId":1,"parentSpanId":0,"refs":[],"applicationCode":"wx-auth-provider","startTime":1539155598153,"endTime":1539155598154,"operationName":"Mysql/JDBI/PreparedStatement/execute","type":"Exit","peer":"192.168.50.131:3306","component":"mysql-connector-java","isError":false,"layer":"Database","tags":[{"key":"db.type","value":"sql"},{"key":"db.instance","value":"wx_platform"},{"key":"db.statement","value":"select \n     \n    third_application_config_id, open_platform_app_id, component_app_id, component_app_secret, \n    open_platform_token, aes_key, create_time, develop_domain, wechat_applet_domain, white_ip_address,mini_program_service_domain\n   \n    from open_platform_third_application_config\n    where open_platform_app_id = ?"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"42.10116.15391555981510156","spanId":2,"parentSpanId":0,"refs":[],"applicationCode":"wx-authorize-api","startTime":1539155598178,"endTime":1539155598181,"operationName":"Redisson/get","type":"Exit","peer":"192.168.50.131:6379","component":"Redisson","isError":false,"layer":"Cache","tags":[{"key":"db.type","value":"Redis"},{"key":"db.statement","value":"get WX_MESSAGE_EXCLUDE_REPEAT_oF17hslGzhyrYgZc5EvYNDpOG96Q_1539155598"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"42.10116.15391555981510156","spanId":3,"parentSpanId":0,"refs":[],"applicationCode":"wx-authorize-api","startTime":1539155598181,"endTime":1539155598182,"operationName":"Redisson/setnx","type":"Exit","peer":"192.168.50.131:6379","component":"Redisson","isError":false,"layer":"Cache","tags":[{"key":"db.type","value":"Redis"},{"key":"db.statement","value":"setnx WX_MESSAGE_EXCLUDE_REPEAT_oF17hslGzhyrYgZc5EvYNDpOG96Q_1539155598 oF17hslGzhyrYgZc5EvYNDpOG96Q 300 SECONDS"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"42.10116.15391555981510156","spanId":4,"parentSpanId":0,"refs":[],"applicationCode":"wx-authorize-api","startTime":1539155598183,"endTime":1539155598187,"operationName":"com.cloudyoung.wx.api.service.WXOpenPlatformAuthApi.getAuthorizerAccessToken(String)","type":"Exit","peer":"10.0.0.184:20881","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.184:20881/com.cloudyoung.wx.api.service.WXOpenPlatformAuthApi.getAuthorizerAccessToken(String)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"43.407.15391555981841430","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"42.10116.15391555981510157","parentSegmentId":"42.10116.15391555981510156","parentSpanId":4,"type":"CROSS_PROCESS"}],"applicationCode":"wx-auth-provider","startTime":1539155598184,"endTime":1539155598186,"operationName":"com.cloudyoung.wx.api.service.WXOpenPlatformAuthApi.getAuthorizerAccessToken(String)","type":"Entry","peer":"","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.184:20881/com.cloudyoung.wx.api.service.WXOpenPlatformAuthApi.getAuthorizerAccessToken(String)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"43.407.15391555981841430","spanId":1,"parentSpanId":0,"refs":[],"applicationCode":"wx-auth-provider","startTime":1539155598184,"endTime":1539155598186,"operationName":"Redisson/get","type":"Exit","peer":"192.168.50.131:6379","component":"Redisson","isError":false,"layer":"Cache","tags":[{"key":"db.type","value":"Redis"},{"key":"db.statement","value":"get WX_OPEN_PLATFORM_AUTHORIZER_ACCESS_TOKEN_wx7fff11837244a6db"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"42.10116.15391555981510156","spanId":5,"parentSpanId":0,"refs":[],"applicationCode":"wx-authorize-api","startTime":1539155598187,"endTime":1539155598195,"operationName":"com.cloudyoung.wx.business.api.service.WXUserTagApi.selectWXUserByOpenid(List)","type":"Exit","peer":"10.0.0.121:20882","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.121:20882/com.cloudyoung.wx.business.api.service.WXUserTagApi.selectWXUserByOpenid(List)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"56.387.15391555981959700","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"42.10116.15391555981510157","parentSegmentId":"42.10116.15391555981510156","parentSpanId":5,"type":"CROSS_PROCESS"}],"applicationCode":"wx-business-provider","startTime":1539155598195,"endTime":1539155598200,"operationName":"com.cloudyoung.wx.business.api.service.WXUserTagApi.selectWXUserByOpenid(List)","type":"Entry","peer":"","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.121:20882/com.cloudyoung.wx.business.api.service.WXUserTagApi.selectWXUserByOpenid(List)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"56.387.15391555981959700","spanId":1,"parentSpanId":0,"refs":[],"applicationCode":"wx-business-provider","startTime":1539155598196,"endTime":1539155598198,"operationName":"Mysql/JDBI/PreparedStatement/execute","type":"Exit","peer":"192.168.50.131:3306","component":"mysql-connector-java","isError":false,"layer":"Database","tags":[{"key":"db.type","value":"sql"},{"key":"db.instance","value":"wx_business"},{"key":"db.statement","value":"select\n\t\t \n\t\twx_user_id, open_platform_app_id, authorizer_appid,\n\t\tb_user_id, union_id, open_id,\n\t\tsubscribe, nick_name, group_id, sex,\n\t\tcity, country, sales_user_id,\n\t\tprovince, user_language,\n\t\thead_img_url,\n\t\tsubscribe_time, remark, is_black, user_identity, user_tel,\n\t\tcreation_time,\n\t\tlast_modify_time, status\n\t \n\t\tfrom wx_user\n\t\twhere open_id in \n\t\t (  \n\t\t\t?\n\t\t )"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"42.10116.15391555981510156","spanId":6,"parentSpanId":0,"refs":[],"applicationCode":"wx-authorize-api","startTime":1539155598196,"endTime":1539155598201,"operationName":"com.cloudyoung.wx.business.api.service.WXRuleApi.getRuleListByActionType(String,int)","type":"Exit","peer":"10.0.0.121:20882","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.121:20882/com.cloudyoung.wx.business.api.service.WXRuleApi.getRuleListByActionType(String,int)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"56.387.15391555982049702","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"42.10116.15391555981510157","parentSegmentId":"42.10116.15391555981510156","parentSpanId":6,"type":"CROSS_PROCESS"}],"applicationCode":"wx-business-provider","startTime":1539155598204,"endTime":1539155598206,"operationName":"com.cloudyoung.wx.business.api.service.WXRuleApi.getRuleListByActionType(String,int)","type":"Entry","peer":"","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.121:20882/com.cloudyoung.wx.business.api.service.WXRuleApi.getRuleListByActionType(String,int)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"56.387.15391555982049702","spanId":1,"parentSpanId":0,"refs":[],"applicationCode":"wx-business-provider","startTime":1539155598204,"endTime":1539155598206,"operationName":"Mysql/JDBI/PreparedStatement/execute","type":"Exit","peer":"192.168.50.131:3306","component":"mysql-connector-java","isError":false,"layer":"Database","tags":[{"key":"db.type","value":"sql"},{"key":"db.instance","value":"wx_business"},{"key":"db.statement","value":"select\n\t\t \n\t\trule_id, authorizer_appid, rule_name, rule_rank,\n\t\trule_status, match_condition,\n\t\taction_type,\n\t\taction_value, creation_time,\n\t\tlast_modify_time, status,total_time\n\t \n\t\tfrom wx_rule\n\t\twhere action_type = ?\n\t\tand authorizer_appid = ? \n\t\tand status = 1 and rule_status = 1\n\t\torder by rule_rank DESC"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"42.10116.15391555981510156","spanId":7,"parentSpanId":0,"refs":[],"applicationCode":"wx-authorize-api","startTime":1539155598201,"endTime":1539155598204,"operationName":"com.cloudyoung.wx.queue.api.MenuMessageProducerApi.produceMenuMessage(QueueJob)","type":"Exit","peer":"10.0.0.97:20884","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.97:20884/com.cloudyoung.wx.queue.api.MenuMessageProducerApi.produceMenuMessage(QueueJob)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"42.10116.15391555981510156","spanId":8,"parentSpanId":0,"refs":[],"applicationCode":"wx-authorize-api","startTime":1539155598204,"endTime":1539155598206,"operationName":"com.cloudyoung.wx.queue.api.BehaviorMessageProducerApi.produceBehaviorMessage(QueueJob)","type":"Exit","peer":"10.0.0.97:20884","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.97:20884/com.cloudyoung.wx.queue.api.BehaviorMessageProducerApi.produceBehaviorMessage(QueueJob)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"42.10116.15391555981510156","spanId":9,"parentSpanId":0,"refs":[],"applicationCode":"wx-authorize-api","startTime":1539155598206,"endTime":1539155598210,"operationName":"com.cloudyoung.wx.queue.api.OperationMessageProducerApi.produceOperationMessage(QueueJob)","type":"Exit","peer":"10.0.0.97:20884","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.97:20884/com.cloudyoung.wx.queue.api.OperationMessageProducerApi.produceOperationMessage(QueueJob)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"51.423.15391555982155540","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"42.10116.15391555981510157","parentSegmentId":"42.10116.15391555981510156","parentSpanId":9,"type":"CROSS_PROCESS"}],"applicationCode":"wx-queue-provider","startTime":1539155598215,"endTime":1539155598215,"operationName":"com.cloudyoung.wx.queue.api.OperationMessageProducerApi.produceOperationMessage(QueueJob)","type":"Entry","peer":"","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.97:20884/com.cloudyoung.wx.queue.api.OperationMessageProducerApi.produceOperationMessage(QueueJob)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"51.423.15391555982155540","spanId":1,"parentSpanId":0,"refs":[],"applicationCode":"wx-queue-provider","startTime":1539155598215,"endTime":1539155598215,"operationName":"RabbitMQ/Producer","type":"Exit","peer":"amqp://wxadmin@10.0.0.35:5672/wx_host","component":"rabbitMQ-producer","isError":false,"layer":"MQ","tags":[{"key":"mq.broker","value":"10.0.0.35"},{"key":"mq.queue","value":"exchange:wx.business.exchange / routingKey:wx.operation.key"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"51.64.15391555982175416","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"42.10116.15391555981510157","parentSegmentId":"51.423.15391555982155540","parentSpanId":1,"type":"CROSS_PROCESS"}],"applicationCode":"wx-queue-provider","startTime":1539155598217,"endTime":1539155598240,"operationName":"RabbitMQ/Consumer/","type":"Entry","peer":"","component":"rabbitMQ-consumer","isError":false,"layer":"MQ","tags":[{"key":"mq.broker","value":"10.0.0.35"},{"key":"mq.queue","value":"wx.operation.queue"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"51.64.15391555982175416","spanId":1,"parentSpanId":0,"refs":[],"applicationCode":"wx-queue-provider","startTime":1539155598217,"endTime":1539155598240,"operationName":"com.cloudyoung.wx.business.api.service.WXMessageResponseApi.updateUserOperation(String,Long)","type":"Exit","peer":"10.0.0.121:20882","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.121:20882/com.cloudyoung.wx.business.api.service.WXMessageResponseApi.updateUserOperation(String,Long)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"56.410.15391555982186320","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"42.10116.15391555981510157","parentSegmentId":"51.64.15391555982175416","parentSpanId":1,"type":"CROSS_PROCESS"}],"applicationCode":"wx-business-provider","startTime":1539155598218,"endTime":1539155598239,"operationName":"com.cloudyoung.wx.business.api.service.WXMessageResponseApi.updateUserOperation(String,Long)","type":"Entry","peer":"","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.121:20882/com.cloudyoung.wx.business.api.service.WXMessageResponseApi.updateUserOperation(String,Long)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"56.410.15391555982186320","spanId":1,"parentSpanId":0,"refs":[],"applicationCode":"wx-business-provider","startTime":1539155598219,"endTime":1539155598234,"operationName":"Mysql/JDBI/PreparedStatement/execute","type":"Exit","peer":"192.168.50.131:3306","component":"mysql-connector-java","isError":false,"layer":"Database","tags":[{"key":"db.type","value":"sql"},{"key":"db.instance","value":"wx_business"},{"key":"db.statement","value":"select \n     \n    user_operation_id, authorizer_appid, wx_user_id, interaction_total, last_interaction_time, \n    last_unattention_time, user_status, last_attention_time, last_attention_from, creation_time, \n    last_modify_time,scan_qrcode_id\n   \n    from wx_user_operation\n    where authorizer_appid = ?\n    and wx_user_id = ?"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"56.410.15391555982186320","spanId":2,"parentSpanId":0,"refs":[],"applicationCode":"wx-business-provider","startTime":1539155598235,"endTime":1539155598239,"operationName":"Mysql/JDBI/PreparedStatement/execute","type":"Exit","peer":"192.168.50.131:3306","component":"mysql-connector-java","isError":false,"layer":"Database","tags":[{"key":"db.type","value":"sql"},{"key":"db.instance","value":"wx_business"},{"key":"db.statement","value":"update wx_user_operation\n     SET authorizer_appid = ?,\n      \n      \n        wx_user_id = ?,\n      \n      \n        interaction_total = ?,\n      \n      \n        last_interaction_time = ?,\n      \n      \n      \n        user_status = ?,\n      \n      \n        last_attention_time = ?,\n      \n      \n        last_attention_from = ?,\n      \n      \n        creation_time = ?,\n      \n      \n        last_modify_time = ?,\n      \n      \n        scan_qrcode_id = ? \n    where user_operation_id = ?"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"42.10116.15391555981510156","spanId":10,"parentSpanId":0,"refs":[],"applicationCode":"wx-authorize-api","startTime":1539155598211,"endTime":1539155598215,"operationName":"com.cloudyoung.wx.api.service.WXOpenPlatformAuthApi.replyTextMessage(Integer,String,String,String,String,boolean)","type":"Exit","peer":"10.0.0.184:20881","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.184:20881/com.cloudyoung.wx.api.service.WXOpenPlatformAuthApi.replyTextMessage(Integer,String,String,String,String,boolean)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"43.407.15391555982111432","spanId":0,"parentSpanId":-1,"refs":[{"traceId":"42.10116.15391555981510157","parentSegmentId":"42.10116.15391555981510156","parentSpanId":10,"type":"CROSS_PROCESS"}],"applicationCode":"wx-auth-provider","startTime":1539155598211,"endTime":1539155598214,"operationName":"com.cloudyoung.wx.api.service.WXOpenPlatformAuthApi.replyTextMessage(Integer,String,String,String,String,boolean)","type":"Entry","peer":"","component":"Dubbo","isError":false,"layer":"RPCFramework","tags":[{"key":"url","value":"dubbo://10.0.0.184:20881/com.cloudyoung.wx.api.service.WXOpenPlatformAuthApi.replyTextMessage(Integer,String,String,String,String,boolean)"}],"logs":[]},{"traceId":"42.10116.15391555981510157","segmentId":"43.407.15391555982111432","spanId":1,"parentSpanId":0,"refs":[],"applicationCode":"wx-auth-provider","startTime":1539155598212,"endTime":1539155598213,"operationName":"Mysql/JDBI/PreparedStatement/execute","type":"Exit","peer":"192.168.50.131:3306","component":"mysql-connector-java","isError":false,"layer":"Database","tags":[{"key":"db.type","value":"sql"},{"key":"db.instance","value":"wx_platform"},{"key":"db.statement","value":"select \n     \n    third_application_config_id, open_platform_app_id, component_app_id, component_app_secret, \n    open_platform_token, aes_key, create_time, develop_domain, wechat_applet_domain, white_ip_address,mini_program_service_domain\n   \n    from open_platform_third_application_config\n    where open_platform_app_id = ?"}],"logs":[]}]}}}

**Comment by wu-sheng** [comment]
I mean Topology query, the right one and wrong way. I can't find any issue about your trace data.

**Comment by caowenyan** [comment]
this is current topology:
![image](https://user-images.githubusercontent.com/9078468/46737500-33d92c00-ccce-11e8-929f-76a647cb95ff.png)

the incurrent topology have more different types,example:
![image](https://user-images.githubusercontent.com/9078468/46721919-d7aee180-cca6-11e8-99c7-05ad2b30dfe3.png)
![image](https://user-images.githubusercontent.com/9078468/46737594-7995f480-ccce-11e8-9d1f-5c0bdb5c81b1.png)
![image](https://user-images.githubusercontent.com/9078468/46737620-8dd9f180-ccce-11e8-8819-a5f18e867f59.png)
and so on.

**Comment by caowenyan** [comment]
![image](https://user-images.githubusercontent.com/9078468/46852198-c1cb2900-ce2c-11e8-88e2-9c3db2b11eb5.png)
如图所示，《1》没有和拓扑树连在一块，单独出来了，
其实他应该和《2》联系在一块的，但是少了n个segement，导致链路断裂，比较明显的错误是：
1）红色项目调用方法《2》的consumer，
2）红色项目调用方法《1》的provider，
然后就和《1》联系在一块了；
《3》所示的调用链完全丢失了；
《4》4所示的调用链是正常的，其实《2》《3》的结构应该和4一样，但是却出现了错误。

**Comment by wangnanyang** [comment]
![default](https://user-images.githubusercontent.com/44340523/47776802-31e31580-dd2e-11e8-8486-1299a1d783d5.png)

 I have encountered similar problems. How to solve them?

**Comment by wu-sheng** [comment]
You all must have to dive in your running context. Find out 
1. Did span create and closed right?
1. Is there any async process mode?

**Comment by wangnanyang** [comment]
can you tell me how to configure  span created and closed right ?

**Comment by WentHao** [comment]
mark. the same question with 5.0.0-GA

**Comment by wu-sheng** [comment]
> can you tell me how to configure span created and closed right ?
 
This is based on plugin. You need to be sure, each plugin works well. Especially the plugins related to your missing spans.
