### ISSUE TITLE
Request Error 500: http://xxxxx:8080/api/dashboard Server error

### ISSUE THREAD

**Issue by cdoewew** [apache/incubator-skywalking#1759]
After deployment, what's the problem? bosses

**Comment by wu-sheng** [comment]
See collector's logs, you will know why. From your prev question, maybe wrong es version.

**Comment by cdoewew** [comment]
Ok, thank you

**Comment by cdoewew** [comment]
> 查看收集器的日志，您将知道原因。从您的上一个问题，也许是错误的ES版本。

Ok, thank you
