### ISSUE TITLE
UI trace topology is lose,disorderly and incorrect

### ISSUE THREAD

**Issue by caowenyan** [apache/incubator-skywalking#1762]
![2](https://user-images.githubusercontent.com/9078468/46852198-c1cb2900-ce2c-11e8-88e2-9c3db2b11eb5.png)

如图所示，《1》没有和拓扑树连在一块，单独出来了，
其实他应该和《2》联系在一块的，但是少了n个segement，导致链路断裂，比较明显的错误是：
1）红色项目调用方法《2》的consumer，
2）红色项目调用方法《1》的provider，
然后就和《1》联系在一块了；
《3》所示的调用链完全丢失了；
《4》4所示的调用链是正常的，其实《2》《3》的结构应该和4一样，但是却出现了错误。

**Comment by caowenyan** [comment]
(1) A lot of cases have happens, so it can't be caused by missing in some time
![错误的链路图1](https://user-images.githubusercontent.com/9078468/46737594-7995f480-ccce-11e8-9d1f-5c0bdb5c81b1.png)
![错误的链路图2](https://user-images.githubusercontent.com/9078468/46737620-8dd9f180-ccce-11e8-8819-a5f18e867f59.png)
(2) f my segment is not completed, there is no possibility of a complete link. But now there is a complete link, as shown below.
![正确的链路图](https://user-images.githubusercontent.com/9078468/46737500-33d92c00-ccce-11e8-929f-76a647cb95ff.png)

I noticed that when I needed to intercept very few projects (two), there was no problem with the trace topology. but when I added another project monitor, there were almost incomplete trace topology, so I wondered if  something wrong in project.

**Comment by wu-sheng** [comment]
> I noticed that when I needed to intercept very few projects (two), there was no problem with the trace topology. but when I added another project monitor, there were almost incomplete trace topology, so I wondered if something wrong in project.

Have you checked the ElasticSearch and Backend payloads? If Backend is in high throughputs, it will trigger agents to ignore traces.

**Comment by caowenyan** [comment]
It also has the problem in the local test for single testing. 
If the load is a problem, how much is the load on the line?

**Comment by wu-sheng** [comment]
> It also has the problem in the local test for single testing.

That should be easy to address. Try to learn remote debug, then you could know why a single request causes some missing segments.

**Comment by wu-sheng** [comment]
> If the load is a problem, how much is the load on the line?

CPU and disk write are important metrics for backend and ElasticSearch

**Comment by caowenyan** [comment]
Can you give me some guidance on how to do it? Now I don't know where to start. I don't know the source code, so I don't know where to debug it.
