### ISSUE TITLE
about support list

### ISSUE THREAD

**Issue by yunqianglee** [apache/incubator-skywalking#1763]
### Question
-Is skywalking support undertow ,or has plan ?

**Comment by wu-sheng** [comment]
Undertow 2.x is already in the list, https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/Supported-list.md

And undertow 1.x PR is still open, https://github.com/apache/incubator-skywalking/pull/1519, ping the contributor @cloudgc
