### ISSUE TITLE
[DISCUSS] Heading to graduation

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1768]
With the SkyWalking 5.0.0 alpha, beta, beta2, and RC release officially out.
GA is under voting in IPMC already
We believe it is time to discuss what requirements remain to consider
graduation to the TLP.

http://skywalking.incubator.apache.org/

Apache SkyWalking entered incubation in December of 2017, SkyWalking
community learned a lot about how to do things in Apache ways.
Now we are a very helpful and engaged community, ready to help on all
questions from the SkyWalking Community.
We are making consensus decisions through the discussion in the mailing
list, voted 1 new committer, also voted 1 new PPMC member.
We managed delivered 4 releases of source codes and binary already
, now we can do self-driving releases in good cadence.

Please check out the maturity assessment doc[1] for more information.

[1]https://cwiki.apache.org/confluence/display/SKYWALKING/Apache+Maturity+Model+Assessment+for+SkyWalking

Any thoughts? And welcome advice from SkyWalking Mentors? @apache/skywalking-committers 

Also I sent a copy of this to dev@skywalking.a.o ml to keep 

Regards

**Comment by andydreaming** [comment]
nice

**Comment by xuziw** [comment]
+1

**Comment by lzpfmh** [comment]
+1 SkyWalking keep up the good work!

**Comment by wu-sheng** [comment]
Here are the same status of project and community.

1. 30+ Companies using, announced in public #443 and [powered-by](https://github.com/apache/incubator-skywalking/blob/master/docs/powered-by.md) page
1. ~70 Code Contributors in GitHub
1. More than 100 Contributors supports us for blogs, meetup, public speech and conference
1. 4500+ stars in GitHub (only main repo). Forgive me, I love number game, this is not an Apache requirement.
1. 800+ issues (including questions) been solved in incubating stage.
1. DotNetCore, NodeJS, PHP agents provided by community

**Comment by JaredTan95** [comment]
+1 Great！

**Comment by WithLin** [comment]
+1

**Comment by 50168383** [comment]
+1

**Comment by landonzeng** [comment]
+1

**Comment by IluckySi** [comment]
Apache Skywalking is a powerful APM complete solution, and its emergence will also have an impact on commercial APM products, I believe he will be better and better ~

**Comment by zhangkewei** [comment]
+1

**Comment by zhangkewei** [comment]
Sorry for my mistake.

**Comment by SoberChina** [comment]
+1 Great work!

**Comment by mircoteam** [comment]
+1 Great job

**Comment by 3zamn** [comment]
+1 Great job

**Comment by wu-sheng** [comment]
**Community** is the most important thing at Incubator, Apache highly values that. For us, it is a good sign too. As I mentioned before, `~70 Code Contributors in GitHub`, the more info is

Just in the [main repo](https://github.com/apache/incubator-skywalking), our code contributor grows from 18 to **64**. I am very exciting about this growing.

**Comment by liguobao** [comment]
+1 Great job

**Comment by oatiz** [comment]
:thumbsup::thumbsup::thumbsup:

**Comment by anlem12** [comment]
+1 Great job

**Comment by xfworld** [comment]
+1

**Comment by lqnasa** [comment]
+1

**Comment by chirdxing** [comment]
+1

**Comment by objectjava** [comment]
+1

**Comment by q1245242450** [comment]
+1

**Comment by yang-dw** [comment]
liubi  +1

**Comment by dongfo** [comment]
+1

**Comment by wintermin** [comment]
+1

**Comment by MuCoder** [comment]
+1

**Comment by Johor03** [comment]
+1

**Comment by yuanxb** [comment]
good job

**Comment by WillemJiang** [comment]
> Here are the same status of project and community.
> 
> 1. 30+ Companies using, announced in public #443 and [powered-by](https://github.com/apache/incubator-skywalking/blob/master/docs/powered-by.md) page
> 2. ~70 Code Contributors in GitHub
> 3. More than 100 Contributors supports us for blogs, meetup, public speech and conference
> 4. 4500+ stars in GitHub (only main repo). Forgive me, I love number game, this is not an Apache requirement.
> 5. 800+ issues (including questions) been solved in incubating stage.
> 6. DotNetCore, NodeJS, PHP agents provided by community

This is quite impressive information, please add these into the proposal.

**Comment by WillemJiang** [comment]
> This is the apache [Guide to Successful Graduation](https://incubator.apache.org/guides/graduation.html), every one who want to know the graduation conditions can take a look.
> 
> We can discuss based on this article. Check every graduation requirements then discuss them. Not +1 only.

There is no specific requirement for graduation except the community maturity model assessment that WuSheng already did.  Once you have a lively community, I cannot find out any other reason to stop your graduation.

**Comment by liuhaoyang** [comment]
As a new committer, I am honored to be able to promote the popularity of SkyWalking in the community. We helped the .NET Core community provide APM solution that can be used in production, and we also got more and more [feedback](https://github.com/OpenSkywalking/Community#community) from the community.

**Comment by littlehuihui** [comment]
Great

**Comment by IanCao** [comment]
nice job

**Comment by wu-sheng** [comment]
I am happy to share, our 5.0.0-GA just passed the IPMC vote, I am processing the release now.

**Comment by candyleer** [comment]
+1

**Comment by landonzeng** [comment]
+1

**Comment by wu-sheng** [comment]
Another sign of an open and diverse community around Apache SkyWalking. http://daocloud.io  open sourced a whole new design UI compatible with SkyWalking 5 backend. The repo is here https://github.com/TinyAllen/rocketbot From my perspective, it is super cool. Here are the screenshots

![img_2875](https://user-images.githubusercontent.com/5441976/47086304-afe1ef80-d24b-11e8-9b5e-f33cdac38211.JPG)
![img_2874](https://user-images.githubusercontent.com/5441976/47086305-b07a8600-d24b-11e8-9e9b-59193e3d91d8.JPG)
![img_2873](https://user-images.githubusercontent.com/5441976/47086307-b07a8600-d24b-11e8-963f-903b04b925b9.JPG)
![img_2872](https://user-images.githubusercontent.com/5441976/47086308-b07a8600-d24b-11e8-96cd-2cb50df3c610.JPG)

**Comment by chidaodezhongsheng** [comment]
I am honored to be able to promote the popularity of SkyWalking in the community. We provided the PHP agent to the community, and we also provided the sharding database storage by shardingjdbc, and its emergence will also have an impact on commercial APM products, I believe it will be better after graduation.

**Comment by peng-yongsheng** [comment]
A year of hard work has not been wasted, I can't wait to see SkyWalking become part of the Apache's TLP project. Thanks to all the PPMC members, Committers and our users.

**Comment by wu-sheng** [comment]
I am closing this issue. And move on the voting of graduation. Thank you all.

**Comment by wu-sheng** [comment]
As we are going to discuss the TLP graduation, open this again. We are going to try this again.

**Comment by dongfo** [comment]
+1

**Comment by joeyYL** [comment]
+1

**Comment by zhangsean** [comment]
+1 Great job!

**Comment by 446690578** [comment]
congrats

**Comment by chirdxing** [comment]
+1

**Comment by slankka** [comment]
+1 great job.

**Comment by chidaodezhongsheng** [comment]
+1

**Comment by liwooood** [comment]
+1

**Comment by myblur** [comment]
great job

**Comment by zhijianfree** [comment]
we are waiting for this job! ^-^

**Comment by cheetah012** [comment]
+1 great job.

**Comment by CallOfCode** [comment]
+1 great job!

**Comment by zhaoyuguang** [comment]
+1 great job!

**Comment by wu-sheng** [comment]
In the incubator, we have
1. 65 open users, https://github.com/apache/incubator-skywalking/blob/master/docs/powered-by.md
2. 9 committers, 3 PPMC selected from the nearly 100 contributors(94 in main repo at this moment).
3. 8 releases passed. 5 to 5-GA, 3 to 6-GA.

**Comment by harvies** [comment]
greeting

**Comment by candyleer** [comment]
+1 👍

**Comment by guojie0701** [comment]
thanks for giving us so good apm choice, good job.

**Comment by langyan1022** [comment]
thanks for wu-sheng ，Powerful support

**Comment by wu-sheng** [comment]
> thanks for wu-sheng ，Powerful support

@langyan1022 I just do my best, it is the power from the whole community. See our 100 contributions do, far more than I could do.

**Comment by 7040210** [comment]
+1 great job!

**Comment by songmy** [comment]
nice��

**Comment by zhangkewei** [comment]
+1

**Comment by wu-sheng** [comment]
We passed the community vote and Incubator vote. We are waiting for the ASF board final resolution.

I think we could close this discussion for now. Thank you all for supporting the project, and welcome everyone in the community.
