### ISSUE TITLE
Conflict with some mechanism in Dubbo 2.6.2

### ISSUE THREAD

**Issue by 3zamn** [apache/incubator-skywalking#1769]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?
extension.SpringExtensionFactory -  [DUBBO] No spring extension(bean) named:skyWalkingDynamicField, try to find an extension(bean) of type java.lang.Object, dubbo version: oss, current host: 192.168.0.3
ERROR extension.ExtensionLoader -  [DUBBO] fail to inject via method setSkyWalkingDynamicField of interface com.alibaba.dubbo.rpc.Filter:
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking5.6.0、dubbo2.6.2、jre1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
dubbo2.6.0- is ok、but dubbo2.6.2+ didn't support
___
### Requirement or improvement
 Please support dubbo2.6.2+

**Comment by wu-sheng** [comment]
@ascrutae please take a look at this.

**Comment by IcebergXTY** [comment]
@wu-sheng Hey, I also met this problem and I found the reason. Because Skywalking will add `setSkyWalkingDynamicField(Object)` to class MonitorFilter and this conflicts with dubbo's spi extention mechanism. 
```java
/*
 * com.alibaba.dubbo.monitor.support.MonitorFilter
 * Here dubbo's spi extention mechanism will traverse all the public set method
 */
private T injectExtension(T instance) {
    try {
        if (objectFactory != null) {
            for (Method method : instance.getClass().getMethods()) {
                if (method.getName().startsWith("set")
                        && method.getParameterTypes().length == 1
                        && Modifier.isPublic(method.getModifiers())) {
                    Class<?> pt = method.getParameterTypes()[0];
                    try {
                        String property = method.getName().length() > 3 ? method.getName().substring(3, 4).toLowerCase() + method.getName().substring(4) : "";
                        Object object = objectFactory.getExtension(pt, property);
                        if (object != null) {
                            method.invoke(instance, object);
                        }
                    } catch (Exception e) {
                        logger.error("fail to inject via method " + method.getName()
                                + " of interface " + type.getName() + ": " + e.getMessage(), e);
                    }
                }
            }
        }
    } catch (Exception e) {
        logger.error(e.getMessage(), e);
    }
    return instance;
}
```
Before dubbo 2.6.3, the extentionFactory just get bean by name, so there is no errro.
```java
/*
 * com.alibaba.dubbo.config.spring.extension.SpringExtensionFactory
 */
@Override
@SuppressWarnings("unchecked")
public <T> T getExtension(Class<T> type, String name) {
    for (ApplicationContext context : contexts) {
        if (context.containsBean(name)) {
            Object bean = context.getBean(name);
            if (type.isInstance(bean)) {
                return (T) bean;
            }
        }
    }
    return null;
}
```
After, dubbo monify the code, it also get bean by type and this throw the exception.
```java
@Override
@SuppressWarnings("unchecked")
public <T> T getExtension(Class<T> type, String name) {
    for (ApplicationContext context : contexts) {
        if (context.containsBean(name)) {
            Object bean = context.getBean(name);
            if (type.isInstance(bean)) {
                return (T) bean;
            }
        }
    }

    logger.warn("No spring extension(bean) named:" + name + ", try to find an extension(bean) of type " + type.getName());

    for (ApplicationContext context : contexts) {
        try {
            return context.getBean(type);
        } catch (NoUniqueBeanDefinitionException multiBeanExe) {
            //here will throw exception because setSkyWalkingDynamicField() type is Object and spring will find many beans
            throw multiBeanExe;
        } catch (NoSuchBeanDefinitionException noBeanExe) {
            if (logger.isDebugEnabled()) {
                logger.debug("Error when get spring extension(bean) for type:" + type.getName(), noBeanExe);
            }
        }
    }

    logger.warn("No spring extension(bean) named:" + name + ", type:" + type.getName() + " found, stop get bean.");

    return null;
}
```
Emmm....Maybe you can communicate with dubbo....

**Comment by wu-sheng** [comment]
@IcebergXTY Thanks for the feedback. I already dropped an request in Dubbo mail list, https://lists.apache.org/thread.html/ed79a0284fddfedc53c96e5666a059617693cd4d7628c32de2935ea4@%3Cdev.dubbo.apache.org%3E . Let's wait and see what are they going to response, and we could work from here.

**Comment by chickenlj** [comment]
Sure, I am here on it.

I guess the newly added method `setSkyWalkingDynamicField(Object)` from SkyWalking is not expected to be automatically injected by Dubbo framework. To make Dubbo more adaptable, I think we  should do the following:
1. A method level annotation to enable auto-injection or not.
2. Special handling for generic Object parameter type.

**Comment by chickenlj** [comment]
@IcebergXTY @wu-sheng Do you think this will solve your problem?

**Comment by wu-sheng** [comment]
> A method level annotation to enable auto-injection or not.

@chickenlj I hope the default is not :) SkyWalking will add this method to all enhanced classes, we can't add an annotation belongs to Dubbo only, may trigger ClassNotFound in other scenarios.

Or, when could not find the inject way, just ignore. The auto set should not be active always from my perspective.

**Comment by chickenlj** [comment]
> > A method level annotation to enable auto-injection or not.
> 
> @chickenlj I hope the default is not :) SkyWalking will add this method to all enhanced classes, we can't add an annotation belongs to Dubbo only, may trigger ClassNotFound in other scenarios.

Set the default value to not would bring lots of changes to Dubbo, many methods would need to add an annotation and enable injection. Can't SkyWalking just add an annotation when instrumenting Dubbo? 
Anyway, I think Dubbo need an annotation to flexibly control the injection action.

> Or, when could not find the inject way, just ignore. The auto set should not be active always from my perspective.

Sounds reasonable, I will consider the possibility of ignoring it when fails.

**Comment by ascrutae** [comment]
@chickenlj  What is The parameter `instance` about `injectExtension` method, an `MonitorFilter` object?

**Comment by wu-sheng** [comment]
> Set the default value to not would bring lots of changes to Dubbo, many methods would need to add an annotation and enable injection. Can't SkyWalking just add an annotation when instrumenting Dubbo?
Anyway, I think Dubbo need an annotation to flexibly control the injection action.

In theory, we can. But we haven't that kind of core API to do so.  So, I hope Dubbo can ignore that by the default mechanism. @chickenlj @diecui1202 Hope this could be fixed soon, and I will keep this open to track the status. If you have any solution, please leave the message here.

**Comment by chickenlj** [comment]
I have created a patch to fix this problem, briefly changes:
* Add optional Inject annotation for developers to decide open auto-injection or not.
* Printing log instead of throwing Exception in SpringExtensionFactory when multi-extension or no extension found.

**Comment by wu-sheng** [comment]
Both of these are great. Especially just log rather than throw exception. :) Thank so much for helping. @chickenlj .

FYI @3zamn @IcebergXTY @ascrutae  I think we just need to wait for new version of Dubbo. @chickenlj please info us after release done, then we can close this issue officially.

**Comment by IcebergXTY** [comment]
@wu-sheng That's great!Thank you for your work! 😊

**Comment by wu-sheng** [comment]
@IcebergXTY The credits belong to Dubbo team. @chickenlj

**Comment by chickenlj** [comment]
I think it will be released along with the upcoming Dubbo v2.6.5.

**Comment by wu-sheng** [comment]
> I think it will be released along with the upcoming Dubbo v2.6.5.

@chickenlj Great to know. @IcebergXTY When you have time, please help to test SkyWalking on their incoming 2.6.5, then provide the feedback here.

**Comment by IcebergXTY** [comment]
@wu-sheng @chickenlj I have updated to dubbo-2.6.5. It works well now. Excellent!

**Comment by wu-sheng** [comment]
@IcebergXTY @chickenlj 2.6.5 is already released or not?

**Comment by wu-sheng** [comment]
@ascrutae we need to add new dubbo version to our test cases. And we could remove some older ones.

**Comment by IcebergXTY** [comment]
@wu-sheng I‘m not sure whether dubbo has released officially but the maven repository has already contained the dubbo-2.6.5

**Comment by chickenlj** [comment]
The new Dubbo version 2.6.5 with this issue solution included has just been released.
Please help to check.
https://github.com/apache/incubator-dubbo/releases/tag/dubbo-2.6.5

**Comment by wu-sheng** [comment]
Great. Closing this. Supported is back in 2.6.5 release.

**Comment by qixiaobo** [comment]
@chickenlj  @wu-sheng Sad……Because dubbo 2.6.6 has bugs so I degrade to dubbo 2.6.4……But I meet this problem. I meet the problem as same as 2009 which QQ or 360 I must choose at most one……

https://github.com/apache/dubbo/issues/4612

**Comment by wu-sheng** [comment]
They are talking about 2.6.7 is available, is that a better choice? This is also a Dubbo bug... sadly.

**Comment by qixiaobo** [comment]
> They are talking about 2.6.7 is available, is that a better choice? This is also a Dubbo bug... sadly.

Sad……
2.6.X merges  my pr…… But 2.6.7 never …… 
![image](https://user-images.githubusercontent.com/2881751/62058205-a0b8b500-b253-11e9-99d6-d361112e879b.png)
![image](https://user-images.githubusercontent.com/2881751/62058277-c34ace00-b253-11e9-9607-5983fe9dfdfc.png)
Maybe 2.6.8…… I cannot wait for it

**Comment by wu-sheng** [comment]
Apache can't randomly release, and each release is unchangeable. So... I am afraid Dubbo community did the right thing. Only the next release is an option. We could ask a Dubbo committer do patch release, such as 2.6.7-patch1, if the community accepts that.

**Comment by qixiaobo** [comment]
You are right, so spring-cloud-alibaba comes back to alibaba repo.  Thanks for replying

**Comment by qixiaobo** [comment]
How about I add a spring bean named skyWalkingDynamicField to avoid this problem ?  @wu-sheng  In this mechanism maybe skywalking never need this field?

**Comment by wu-sheng** [comment]
SkyWalking plugin requires this field. I doubt this w/ highly possible risks.

**Comment by qixiaobo** [comment]
> SkyWalking plugin requires this field. I doubt this w/ highly possible risks.

I have no other choices since dubbo 2.6.5+ has a bug cannot  serialize and 2.6.8 is not release yet…… Maybe I can try?

**Comment by wu-sheng** [comment]
You could try :) I am just concerned that, it will break the SpringMVC plugin.

**Comment by qixiaobo** [comment]
> You could try :) I am just concerned that, it will break the SpringMVC plugin.

Or maybe I can delete the dubbo plugin?[It may works]
Also I consider about delete the dubbo Monitorfilter [Skywalking just enchace this class]--->The same result with delete dubbo plugin

**Comment by qixiaobo** [comment]
```java
/**
 * https://github.com/apache/skywalking/issues/1769
 */
@Bean
public String skyWalkingDynamicField() {
    return "avoid skywalking conflicts with dubbo 2.6.5-";
}
```
I add this  code to my spring config , and it works~

**Comment by wu-sheng** [comment]
That is luck :) Hope it would break other things.
