### ISSUE TITLE
The 'application index' of es of skywalk, can see the specific service name, but can't find the IP and port of the service?Or is there no record?

### ISSUE THREAD

**Issue by cdoewew** [apache/incubator-skywalking#1770]

**Comment by wu-sheng** [comment]
No. There is no such thing in our ES types.

**Comment by cdoewew** [comment]
Is the modified source code available?Is there any suggestion for modification?


dongweipeng_927@126.com
 
From: 吴晟 Wu Sheng
Date: 2018-10-16 21:35
To: apache/incubator-skywalking
CC: code; Author
Subject: Re: [apache/incubator-skywalking] The 'application index' of es of skywalk, can see the specific service name, but can't find the IP and port of the service?Or is there no record? (#1770)
No. There is no such thing in our ES types.
