### ISSUE TITLE
Some questions about the agent collecting data

### ISSUE THREAD

**Issue by cyejing** [apache/incubator-skywalking#1771]
Please answer these questions before submitting your issue.

- Why do you submit this issue?

- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- How often does the agent report data to the collector?Can it be configured?（探针发送数据的时间间隔是多少？是否能配置？）
- How big is the agent buffer setting? Can it be configured?（探针收集的数据缓存设置了多大？是否能配置？）

___
### Requirement or improvement
- Can you provide a custom collection strategy? Can do special requests will be collected。（能否提供自定义收集策略，可以做到指定特殊请求都会收集）

thank

**Comment by wu-sheng** [comment]
> How often does the agent report data to the collector? Can it be configured?

Consume per 20 ms. See `TraceSegmentServiceClient#L69`. We use DataCarrier's default settings. It is not open now.

> How big is the agent buffer setting? Can it be configured?

See `org.apache.skywalking.apm.agent.core.conf.Config#Buffer`. Default channelSize * bufferSize. You could set anything in Config through `agent.config`

**Comment by cyejing** [comment]
This helped me.
Consume per 20 ms. I think this is a problem. if 20ms have a lot of data into DataCarrier . datacarrier will be discarded data . datacarrier buffer strategy is `BufferStrategy.IF_POSSIBLE`. 
How improve？

**Comment by wu-sheng** [comment]
How many traces do you intend to add into the buffer in 20ms cycle? I am confusing.

**Comment by cyejing** [comment]
you are right .I mistakenly thought it was 20s
