### ISSUE TITLE
How does skywalking integrate with elk?Can I just install Kibana?

### ISSUE THREAD

**Issue by wangnanyang** [apache/incubator-skywalking#1796]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?

I want to search log with elk.I had install skywalking and elasticsearch.Can I just install Kibana?

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by peng-yongsheng** [comment]
Use Kibana to search who's log? SkyWalking or Logstash?

**Comment by wangnanyang** [comment]
>           Use Kibana to search who's log? SkyWalking or Logstash?

SkyWalking . I want more convenient query logs from SkyWalking . So I want to use Kibana to query logs from SkyWalking.

**Comment by wu-sheng** [comment]
SkyWalking provided querys based on GraphQL. Try that.

**Comment by wangnanyang** [comment]
Can skywalking-ui show the searching page ? Can you provide me with the related material ?

发送自 Windows 10 版邮件应用

发件人: 吴晟 Wu Sheng
发送时间: 2018年10月23日 11:57
收件人: apache/incubator-skywalking
抄送: wangnanyang; Author
主题: Re: [apache/incubator-skywalking] How does skywalking integrate withelk?Can I just install Kibana? (#1796)

SkyWalking provided querys based on GraphQL. Try that.

**Comment by wu-sheng** [comment]
What do you mean seaching page? I am not following. GraphQL query protocols are here, https://github.com/apache/incubator-skywalking/tree/5.x/apm-protocol/apm-ui-protocol/src/main/resources/ui-graphql
