### ISSUE TITLE
slowtraces与trace details差距很大

### ISSUE THREAD

**Issue by louislv** [apache/incubator-skywalking#1799]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
通过首页slow service找到对应的slow traces,点击traceid进入到detail页面.发现在slow trace页面的耗时为1181ms,但是点击进去后,发现耗时只有74ms
![image](https://user-images.githubusercontent.com/3906072/47340467-e945af80-d6d0-11e8-9ac1-13a746e21ca1.png)
![image](https://user-images.githubusercontent.com/3906072/47340512-0ed2b900-d6d1-11e8-9463-c7b3d950f8ce.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only, please. Slow service is based on aggregation. After clicking the service, then the page navigate to service page.
