### ISSUE TITLE
Question: whether skywalking can get the count of inject method call

### ISSUE THREAD

**Issue by jacky1193610322** [apache/incubator-skywalking#1807]
I want to count the inject method call times, for example, log every second or other, I don't know whether skywalking has the function. I mean javaagent output the count directly, not collector sum the count.

**Comment by wu-sheng** [comment]
No, we don't have that.  Why do we need that?

**Comment by jacky1193610322** [comment]
> No, we don't have that. Why do we need that?

Because the collector gets the data with sampling rate， it's not very accurate.
