### ISSUE TITLE
Spring-session not creating tables automatically and when running script manually for mysql db it shows unknow filed SESSION_ID exception

### ISSUE THREAD

**Issue by varun952** [apache/incubator-skywalking#1808]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [I think it is a bug ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why tables not created? and other thing is why exception is thrown if tables created using same script for mysql db 

___
### Bug
- Which version of SkyWalking, OS and JRE?
JRE - 1.8

- Which company or project?
Api Recorder
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
I can give teamviewer for u guys to check once
Error says:
PreparedStatementCallback; bad SQL grammar [INSERT INTO SPRING_SESSION_ATTRIBUTES(SESSION_ID, ATTRIBUTE_NAME, ATTRIBUTE_BYTES) VALUES (?, ?, ?)]; nested exception is java.sql.BatchUpdateException: Unknown column 'SESSION_ID' in 'field list'
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is very new to me. You could reach me in mail, qq group, or other channels. I definitely need more info to address this issue. We don't manipulate `PreparedStatementCallback` from my understanding. Which jdbc driver are you using?

@ascrutae What do you think?

**Comment by varun952** [comment]
com.mysql.jdbc.Driver

<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
</dependency>

Above is the deoendency that I am using

**Comment by wu-sheng** [comment]
If you could provide a demo project to reproduce this issue, we may help. This driver and mysql tracing are wide used, we can't locate your issue.
