### ISSUE TITLE
Whether SkyWalking-Collector's configuration file can be dynamically loaded?

### ISSUE THREAD

**Issue by BuQingYan** [apache/incubator-skywalking#1813]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Whether SkyWalking-Collector's configuration file can be dynamically loaded?Just like file:application.yml or the specific configuration of ES.
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
In 6.x(not released), we have https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/backend/backend-setting-override.md Also in 5.x, you could find the override from here, https://github.com/apache/incubator-skywalking/blob/5.x/docs/en/Setting-override.md#collector

If you want to contribute new mechanism, we are welcome of course.

**Comment by BuQingYan** [comment]
Thank you very much for your answer.
Bu how can i reload the Elasticsearch configuration in applicaction.yml and make these configuration work without reboot skywalking-collector?
Has API been provided to solve this problem?
