### ISSUE TITLE
Is this wrong note? 

### ISSUE THREAD

**Issue by psy-core** [apache/incubator-skywalking#1820]
https://github.com/apache/incubator-skywalking/blob/5e8410834de20254c2bdab2d86cdbfd79d600904/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/sampling/SamplingService.java#L82

I think it should be "Agent sampling mechanism started. Sample {} traces in 3 seconds.".

https://github.com/apache/incubator-skywalking/blob/e93b3f0d16fd1b28e6342e4e179f313922e33757/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/Config.java#L53
has the same question,

**Comment by wu-sheng** [comment]
PRs are welcome to master and 5.x branches.

**Comment by wu-sheng** [comment]
Yes, there are wrong logs.

**Comment by wu-sheng** [comment]
Fixed.
