### ISSUE TITLE
slow service 点击进去后的界面错误

### ISSUE THREAD

**Issue by kofwangshuai** [apache/incubator-skywalking#1837]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only. 

And since data is at your side, please try to find out which data trigger the error. We haven't this error based on our data.
