### ISSUE TITLE
Question: can skywalking pass on tag cross thread?

### ISSUE THREAD

**Issue by jacky1193610322** [apache/incubator-skywalking#1845]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The distributed tracing system need to pass the user's tag across threads, for example, I put a value in the http header, the system need to pass the value accross threads, and accross jvm, and try pass on in the whole trace. for example,  the user get the http request, we can set the value in the threadlocal, but if the user create a task submited to threadpool, which maybe lead to loss the value. 

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We can propagate skywalking internal info across threads and processes. But that mechanism is not open to end user in default. Business info propagation is very dangerous, in many cases, they cause memory leak, network traffic disaster. 

You could change our codes to supports that, but I wouldn't recommend to do that.

**Comment by jacky1193610322** [comment]
ok, thank you

**Comment by jacky1193610322** [comment]
you mean the apm-toolkit-trace-activation project implementation the feature which propagate skywalking internal info across threads and processes

**Comment by wu-sheng** [comment]
> you mean the apm-toolkit-trace-activation project implementation the feature which propagate skywalking internal info across threads and processes?

No. There no official API could do the propagation like you said.

**Comment by jacky1193610322** [comment]
I know, you said "We can propagate skywalking internal info across threads and processes", I am reading the source, so I want to know which project or class implement the feature you said. thank you

**Comment by wu-sheng** [comment]
> "We can propagate skywalking internal info across threads and processes

This means `#inject`, `#extract`, `#capture` and `#continued` in TracingContext.

**Comment by jacky1193610322** [comment]
Thank you.
