### ISSUE TITLE
getApplicationTopology error

### ISSUE THREAD

**Issue by Yuanxiangz** [apache/incubator-skywalking#1852]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 5.0.0RC  centos6.9   

- Which company or project?

- What happen?
Everything goes fine after an new app was added in skywalking. then I found follow error in "Application" menu. after several times, some other apps also display the same error.
it seems like when the trace fills into different indexs but lost something, which leads to this: can't find the calltype according targetid. 

after remove the new app, the error goes away.  any clues about it? thanks in advance.

error:
Cannot return null for non-nullable type: 'String' within parent 'Call' (/getApplicationTopology/calls[4]/callType)

request:
/api/application

{"variables":{"duration":{"start":"2018-10-31 1119","end":"2018-10-31 1134","step":"MINUTE"},"applicationId":"110"},"query":"  query Application($applicationId: ID!, $duration: Duration!) {    getSlowService(applicationId: $applicationId, duration: $duration, topN: 10) {      service {        key: id        label: name        applicationId        applicationName      }      value: avgResponseTime    }    getServerThroughput(applicationId: $applicationId, duration: $duration, topN: 999999) {      key: id      osName      host      pid      ipv4      value: cpm    }    getApplicationTopology(applicationId: $applicationId, duration: $duration) {      nodes {        id        name        type        ... on ApplicationNode {          sla          cpm          avgResponseTime          apdex          isAlarm          numOfServer          numOfServerAlarm          numOfServiceAlarm        }      }      calls {        source        target        isAlert        callType        cpm        avgResponseTime      }    }  }"}

response:
{"data":{"getSlowService":[{"service":{"key":"263","label":"/echo","applicationId":"110","applicationName":"chatbot-api"},"value":108},{"service":{"key":"270","label":"/chatBot/getAvatarUrl","applicationId":"110","applicationName":"chatbot-api"},"value":71},{"service":{"key":"-274","label":"/chatBot/queryChatHistory","applicationId":"110","applicationName":"chatbot-api"},"value":59},{"service":{"key":"265","label":"/callback/rl","applicationId":"110","applicationName":"chatbot-api"},"value":30},{"service":{"key":"271","label":"/chatBot/hasUnReadMessage","applicationId":"110","applicationName":"chatbot-api"},"value":22},{"service":{"key":"-269","label":"/chatBot/inManualSession","applicationId":"110","applicationName":"chatbot-api"},"value":19},{"service":{"key":"262","label":"/chatBot/getRLLastReplyTime","applicationId":"110","applicationName":"chatbot-api"},"value":17},{"service":{"key":"-265","label":"RocketMQ/RongLianCustomerServiceQueue/Consumer","applicationId":"110","applicationName":"chatbot-api"},"value":0}],"getServerThroughput":[{"key":"301","osName":"Linux","host":"l-chatbot-webapi1.rd.cn1","pid":32239,"ipv4":["172.31.30.43"],"value":4},{"key":"299","osName":"Linux","host":"l-chatbot-webapi3.rd.cn1","pid":516,"ipv4":["172.31.35.43"],"value":3},{"key":"309","osName":"Linux","host":"l-chatbot-webapi2.rd.cn1","pid":2834,"ipv4":["172.31.30.44"],"value":2},{"key":"298","osName":"Linux","host":"l-chatbot-webapi4.rd.cn1","pid":3017,"ipv4":["172.31.35.44"],"value":2}]},"errors":[{"message":"Cannot return null for non-nullable type: 'String' within parent 'Call' (/getApplicationTopology/calls[8]/callType)"},{"message":"Cannot return null for non-nullable type: 'String' within parent 'Call' (/getApplicationTopology/calls[9]/callType)"},{"message":"Cannot return null for non-nullable type: 'String' within parent 'Call' (/getApplicationTopology/calls[10]/callType)"},{"message":"Cannot return null for non-nullable type: 'String' within parent 'Call' (/getApplicationTopology/calls[11]/callType)"},{"message":"Cannot return null for non-nullable type: 'String' within parent 'Call' (/getApplicationTopology/calls[12]/callType)"},{"message":"Cannot return null for non-nullable type: 'String' within parent 'Call' (/getApplicationTopology/calls[13]/callType)"}]}

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by Yuanxiangz** [comment]
![getapperror](https://user-images.githubusercontent.com/11549125/47765171-a5236200-dd03-11e8-9f47-f85507b1423f.jpg)

**Comment by wu-sheng** [comment]
Have you tried GA or 6.0.0-alpha to see what happens?

**Comment by wu-sheng** [comment]
You need to check backend to see what there is some field is null. That will help on addressing this issue.

**Comment by Yuanxiangz** [comment]
i am using skywalking on our prod env, so it's not easy to upgrade to 6.0.0. now i am using a workaround to return empty string to avoid this error.but it's not a thorough way. i doubt whether it is cause by one application has mulitiple instances(i didn't meet this issue in our test env. in our test env, one application only has one instance, while on prod env, on application has more than one instance). it's not caused by some null field in es. sometimes in the same time bucket, we get source and target appids from application_reference_metric, but some source or target ids are not found in application_component. some data is missing which cause the error. i didn't find any suspicious errors in colloect or es. any clues on it?

**Comment by wu-sheng** [comment]
If your system is low throughputs, maybe. Ni component found in that duration. SkyWalking 6 uses the assumption that component not chang, until new one coming, also support no component app, based on istio metric, we don't know component.
