### ISSUE TITLE
How can I not display dubbo-monitor request  。。。e.g: com.alibaba.dubbo.monitor.MonitorService.collect(URL)

### ISSUE THREAD

**Issue by baiyun1102** [apache/incubator-skywalking#1859]
Please answer these questions before submitting your issue.
we use the dubbo RCP ， How can I not display dubbo-monitor info

![qq 20181101170915](https://user-images.githubusercontent.com/16332397/47842905-f3fef380-ddf8-11e8-85c4-5785c9987c53.png)

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by baiyun1102** [comment]
![qq 20181101170915](https://user-images.githubusercontent.com/16332397/47843005-44765100-ddf9-11e8-8967-bb4b3cc95df6.png)

**Comment by Yuanxiangz** [comment]
you can try this: https://github.com/apache/incubator-skywalking/blob/5.x/apm-sniffer/optional-plugins/trace-ignore-plugin/README_CN.md

**Comment by wu-sheng** [comment]
I am not sure ignore plugin supports this or not. You could try.

**Comment by baiyun1102** [comment]
yes    ignore plugin supports
config file：
trace.ignore_path=dubbo://xxx.xxx.xxx.xxx:7070/com.alibaba.dubbo.monitor.MonitorService.collect**
