### ISSUE TITLE
why  the ver：5.0.0-GA don't display SQL statement in log page。but ver：3.6.2 could

### ISSUE THREAD

**Issue by baiyun1102** [apache/incubator-skywalking#1864]
why  the skywalking ver：5.0.0-GA don't display SQL statement in log page。but ver：3.6.2 could

![qq 20181102102626](https://user-images.githubusercontent.com/16332397/47890439-cf9f2780-de89-11e8-9e10-6a684c1a0498.png)

**Comment by wu-sheng** [comment]
You need to use remote debug to find out why plugin doesn't work.

**Comment by baiyun1102** [comment]
does the ver 5.0.0-GA support oracle？    i‘m not found the oracle-plugin

**Comment by wu-sheng** [comment]
> does the ver 5.0.0-GA support oracle？ i‘m not found the oracle-plugin

You need to compile the source by yourself. In 5.x branch and https://github.com/OpenSkywalking/java-plugin-extensions , you could find the source codes. @ascrutae Could you publish a release at `java-plugin-extensions` repo for convenient?
