### ISSUE TITLE
Agent5.0GA not support SpringCloud2.x?

### ISSUE THREAD

**Issue by jiangweiliu** [apache/incubator-skywalking#1865]
Please answer these questions before submitting your issue.
I test SpringCloud1.5.4 project,is success.
But test SpringCloud2.0.4 project,error.
SpringBoot version 2.0.4
SpringCloud version Finchley.SR1
Use commond "nohup java -javaagent:/application/springcloud/agent/skywalking-agent.jar -jar dataservice.jar --spring.profiles.active=dev> dataservice.log 2>&1 &"
Error info:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000006c7360df0, pid=13871, tid=140704901814016
#
# JRE version: Java(TM) SE Runtime Environment (8.0_20-b26) (build 1.8.0_20-b26)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.20-b23 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x00000006c7360df0
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
  0x00000006c7360df0
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /application/springcloud/hs_err_pid13871.log
Compiled method (c1)   11416 2957       1       sun.invoke.util.ValueConversions::identity (2 bytes)
 total in heap  [0x00007ff8518e3510,0x00007ff8518e3780] = 624
 relocation     [0x00007ff8518e3638,0x00007ff8518e3658] = 32
 main code      [0x00007ff8518e3660,0x00007ff8518e36c0] = 96
 stub code      [0x00007ff8518e36c0,0x00007ff8518e3750] = 144
 scopes data    [0x00007ff8518e3750,0x00007ff8518e3758] = 8
 scopes pcs     [0x00007ff8518e3758,0x00007ff8518e3778] = 32
 dependencies   [0x00007ff8518e3778,0x00007ff8518e3780] = 8
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#

```

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0GA
jre:1.8.0_20-b26
os:CentOS release 6.5

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
From supported list, https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/Supported-list.md , we are not supported yet.

@ascrutae Any interest to support that? I think this is a very important plugin.

**Comment by jiangweiliu** [comment]
Thanks!

**Comment by jiangweiliu** [comment]
I wonder if I can.

[eureka_service.zip](https://github.com/apache/incubator-skywalking/files/2628375/eureka_service.zip)

**Comment by wu-sheng** [comment]
New Spring MVC 5 should be supported in beta release.
