### ISSUE TITLE
[Source code building]

### ISSUE THREAD

**Issue by Leomii** [apache/incubator-skywalking#1870]
hi,i got a problem!
The source code from 
**http://www.apache.org/dyn/closer.cgi/incubator/skywalking/5.0.0-GA/apache-skywalking-apm-incubating-5.0.0-GA-src.tgz**
got errors!
When I open some java files,it show:

**270 path=apache-skywalking-apm-incubating-5.0.0-GA/apm-collector/apm-collector-storage/collector-storage-shardingjdbc-provider/src/main/java/org/apache/skywalking/apm/collector/storage/shardingjdbc/dao/armp/ApplicationReferenceMonthMetricShardingjdbcPersistenceDAO.java
30 mtime=1538841978.043868511
30 ctime=1538841978.043868511
30 atime=1538841980.486141143
23 SCHILY.dev=16777221
23 SCHILY.ino=11210921
18 SCHILY.nlink=1**
.
Em,what is the problem?
And i want compare the file to github.com,but i can not find it,the source code from apache.org is diffent from github.com?
Can anybody expain this to me? 
Thanks!

**Comment by wu-sheng** [comment]
Switch to 5.x branch or 5.0.0-GA tag, I will find the code.

**Comment by wu-sheng** [comment]
That is a new error. Source codes have been built and checked by many people during releasing process in ASF.

**Comment by Leomii** [comment]
Ok,fixed this immediately plz.

**Comment by Leomii** [comment]
I built code from github.com,tag is 5.x ,got new error:
**org.apache.skywalking.apm.network.proto** does not exists.
I cannot find it from maven or github.

**Comment by wu-sheng** [comment]
No. You don't following document. Download from github is wrong. Download from Apache website or git clone.

**Comment by Leomii** [comment]
Got it,thanks!
Wait for the bug fixed.

**Comment by wu-sheng** [comment]
Again. This is not a bug. That GitHub download issue. We can't fix issue. 

We use submodule, GitHun download can't support. You could find the notice in release page.
