### ISSUE TITLE
Override default config by agent arguments

### ISSUE THREAD

**Issue by ScienJus** [apache/incubator-skywalking#1881]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

We use docker to deploy multiple java applications on each host. so we put the skywalking agent on the host and mount it to every container.

Each application has it's unique `application_code`, but they share the same agent jar and config file, so we need a more flexible config.

I noticed that skywalking already supports overriding the default config by system properties, I suggest that also add agent arguments(or options?) support, which is something just like `-javaagent:jarpath[=options]`.

In this way, not only we can overriding default config, but also more compact:

```
-javaagent:/path/to/skywalking/agent.jar=agent.application_code=backend
```

Finally, it's easy to implement, just parse the `agentArgs` parameter in `SkyWalkingAgent#premain`.

I‘d like to create a pull request if you agree with this optimization.

**Comment by wu-sheng** [comment]
We already have this but in different way. See here https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/Setting-override.md

**Comment by ScienJus** [comment]
@wu-sheng Yes, I saw this way, it can solve my problem, but why not support another, maybe more recommended way? For example, like jacoco https://www.eclemma.org/jacoco/trunk/doc/agent.html

**Comment by wu-sheng** [comment]
I think no one is blocking things like this. Just no one doesn't contribute this. If you want, welcome.

**Comment by wu-sheng** [comment]
In Apache, we don't block things like this. Just need contributor brings new feature to the code base. So, do if you like.

**Comment by wu-sheng** [comment]
PR merged. Thanks for your contributions. Welcome to take part in more.
