### ISSUE TITLE
Is it possible to use multithreading in this place?

### ISSUE THREAD

**Issue by psy-core** [apache/incubator-skywalking#1889]
https://github.com/apache/incubator-skywalking/blob/03824c2f8f43d55746ac466f0252bd78c1b48363/apm-collector/apm-collector-agent-stream/collector-agent-stream-provider/src/main/java/org/skywalking/apm/collector/agent/stream/worker/trace/TraceSegmentService.java#L37-L40

I'm trying to improve the processing speed for apm collector in skywalking version `3.2.6`.  Is it possible to run `send` method in a thread pool rather than invoke it directly? just like this:

```
private final ThreadPoolExecutor executor;
...
public void send(UpstreamSegment segment) {
    executor.execute(new TraceSegmentRunnable(moduleManager, segment));
}
...

public class TraceSegmentRunnable implements Runnable {

    private final ModuleManager moduleManager;
    UpstreamSegment segment;
    ....
    public void run() {
        SegmentParse segmentParse = new SegmentParse(moduleManager);
        segmentParse.parse(segment, SegmentParse.Source.Agent);
    }
}
``` 

Is there any problem or risk?

**Comment by wu-sheng** [comment]
You could use multiple threads to send. But make sure each one client has its own grpcStub.
