### ISSUE TITLE
5.0.0-GA cannot collect under centos7

### ISSUE THREAD

**Issue by xqxyxchy** [apache/incubator-skywalking#1890]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ √] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 5.0.0-GA
CnetOS 7（vmware machine）
JRE 1.8

- Which company or project?
my demo project.

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
collector running, no error,but it cannot collect agent message right.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean can't collect data? What does agent log say?

**Comment by wu-sheng** [comment]
I doubt there is related to os.

**Comment by xqxyxchy** [comment]
不会英文，有点变扭。
问题是这样：
5.0.0-GA部署在虚拟机中的CentOS7下，启动收集器、UI都没有问题；
结果无法收集到探针发来的数据；

其他因素：
同一个sky包在window7（本机）下部署是可以收集的；

**Comment by xqxyxchy** [comment]
collector的启动日志
[skywalking-collector-server.log](https://github.com/apache/incubator-skywalking/files/2560157/skywalking-collector-server.log)

**Comment by wu-sheng** [comment]
If you didn't reply this in English, I have to close this issue, Apache required. We need to make sure everyone in the world understand what is happening here. You could move to QQ Group, Chinese is welcome to here. But official issue and pull request are English only. Sorry.
