### ISSUE TITLE
Question aboout namespace

### ISSUE THREAD

**Issue by eoeac** [apache/incubator-skywalking#1893]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Do I need deploy multiple skywalking dashboard for eash namespace?

**Comment by wu-sheng** [comment]
Different UI and backend for the different namespace.

**Comment by a198720** [comment]
Is there any plan for this in the future?
