### ISSUE TITLE
Greenwich problem

### ISSUE THREAD

**Issue by NeilZZ** [apache/incubator-skywalking#1896]
hi，this is the problem i meet. 
when I using the skywalking and elasticSearch with this under version:
apache-skywalking-apm-incubating-5.0.0-GA
elasticsearch-5.6.8

after start all the application ,i found the system time become the Greenwich . 
i am in China ~ =- =

so~
i can't query data Within 8 hour. 

how to set the Time zone for skywalking and elasticSearch ???

**Comment by wu-sheng** [comment]
The data depends on your agent time zone and time. Try to set your os time right.

**Comment by wu-sheng** [comment]
You need restart your application. Then easy way, write a java app to read time, system current millionseconds. See what is happening. Linux has a lot of ways to set time. Make sure Jvm could read it

**Comment by NeilZZ** [comment]
i already resolved it. it is not the os problem, this issue is because install 2 kinds jdk. i need to add 
-Duser.timezone=Asia/Shanghai
into the JAVA_OPTS of the file: 
collectorService.sh
webappService.sh

**Comment by wu-sheng** [comment]
That is one way. You could set time zone in os too. Many ways to do this

**Comment by NeilZZ** [comment]
no. in my case , the second jdk can't able to read the os time zone. i don't know why .
but i think, maybe you can add the time zone into the setting properties file. 
it might be very helpful~

**Comment by wu-sheng** [comment]
No, we can't. Because we have users in global. We don't know the right time zone

**Comment by NeilZZ** [comment]
you can default read the os time zone . but have some options in the configuration file

**Comment by spark8103** [comment]
I add -Duser.timezone=UTC in webappService.sh
but not change UI timezone.

**Comment by wu-sheng** [comment]
You could choose UI timezone.
