### ISSUE TITLE
http options method cause too many service come out

### ISSUE THREAD

**Issue by edana-dev** [apache/incubator-skywalking#1898]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
Hi, I found the services in skywalking backend is very huge(figure 1), and I got a clue that it is cause by http options request(figure 2), request like that will not handle by spring mvc controller interceptors(in my case), and will not aggregate with mapping path, so I think it would be reasonable  to ignore requests like that. What do you think?

![image](https://user-images.githubusercontent.com/5830134/48246685-58d6d100-e42b-11e8-93f3-5e5851de6886.png)
![image](https://user-images.githubusercontent.com/5830134/48246826-db5f9080-e42b-11e8-89bc-926a56cc0942.png)

**Comment by wu-sheng** [comment]
What is this request for?

**Comment by wu-sheng** [comment]
No update for 14 days.
