### ISSUE TITLE
skywalking agent config support dynamic effective

### ISSUE THREAD

**Issue by ascrutae** [apache/incubator-skywalking#190]
Adding a config watcher and a notifier to support the config effective dynamically

**Comment by wu-sheng** [comment]
If we have #325, I think this feature isn't important anymore. At agent side, just need to set `applicationCode`, `collector discovery service address`, `log related configurations`(maybe) . 

Do you agree? @ascrutae

**Comment by wu-sheng** [comment]
Most configurations will downstream from OAP backend. So, right now, don't need more discussions.
