### ISSUE TITLE
Did skywalking support alert by mail 

### ISSUE THREAD

**Issue by ttting** [apache/incubator-skywalking#1906]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Did skywalking support alert by mail ?  
   I can not find anyway to config mail in skywalking document.

**Comment by wu-sheng** [comment]
V6 supported webhook now. You could send mail by your own.
