### ISSUE TITLE
CPM data is not allowed

### ISSUE THREAD

**Issue by AaronChenlin** [apache/incubator-skywalking#1908]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Hello, the number of requests I make per minute is 500, but the CPM shows that it's going on at 150. I've been measuring for a long time, and this question has puzzled me all the time.

___
### Bug
- version 5.0GA

**Comment by wu-sheng** [comment]
That depends, I don't know it is a bug or not yet. Haven't received any report about this before. But in theory, it could be less than 500. Traces are collected in your process by agent and transport by network, also with backend analysis, for keeping your application safe, we set a lot of mechanism to ignore traces if your backend, network and agent-side cpu are overloads.

You need to figure out, first thing, does the trace data support your 500cpm? 
Seconds, do you give the same(500cpm) payloads in your query duration? Also, check the trend graph, it should show you cpm in each minutes, which should verify this.
