### ISSUE TITLE
Is CPM Corrent ?

### ISSUE THREAD

**Issue by Sunlitkid** [apache/incubator-skywalking#1911]
- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
First of all ,  I think  cpm  means  【calls per minute】

I deployed  an application【name : APP】 with only one instance  
APP is registered to 【sky-walking】

Then  I  use a timer  to cycle call interface in APP

Then  I  got  some test Data about APP's  CPM;

cpm in sw         times/minute(timer call)
195                   600
77                     240
38                     120
19                     60
10                     30
7                       20
7                       15
6                       10

Test environment  ：  windows  jdk 1.8 
SkyWalking version :  5.0.0-GA

- What do you want to know?

I want to know  the test data is correct  .
If it is corrent ,what's worry with me .
I want a explanation of CPM .

-------------------------------
Thank you  very much

**Comment by wu-sheng** [comment]
Do you have enough traces? I have commented this before. https://github.com/apache/incubator-skywalking/issues/1908#issuecomment-438867830 

Another reason is, may some plugins are not compatible. But anyway, you need to know what is happening. 

Or you could try 6.0.0-alpha, to see is that right?

**Comment by Sunlitkid** [comment]
I don‘t konw what mean "enough traces"
In SkyWalking   I can saw all my timer called traces .
But  in elasticsearch-DB  ,such as  I called 100 times /minute, I can only saw 
index : 【application_metric_minute.t1】  t1 ≈ 33    in this minute;
in your resource code  【t1】means   transaction_calls

**Comment by Sunlitkid** [comment]
@wu-sheng

**Comment by wu-sheng** [comment]
Are all traces, like 100 traces per min, in the es?

**Comment by Sunlitkid** [comment]
Traces record in sw is  100 /minute  ,it is Complete ，but  calls_time in es  is around 1/3

**Comment by wu-sheng** [comment]
Not sure, why. 6.0.0-alpha does this in different mode. Try that? @peng-yongsheng

**Comment by Sunlitkid** [comment]
localhost:9200/application_metric_minute/_search?q=*&size=100

{
                "_index": "application_metric_minute",
                "_type": "type",
                "_id": "201811141702_-4_1",
                "_score": 1,
                "_source": {
                    "mi": "-4_1",
                    "ai": -4,
                    "a1": 6,
                    "a2": 0,
                    "a3": 0,
                    "tb": 201811141702,
                    "sv": 1,
                    "t1": 6,
                    "t2": 0,
                    "t3": 13,
                    "t4": 0,
                    "t5": 2,
                    "b1": 6,
                    "b2": 0,
                    "b3": 13,
                    "b4": 0,
                    "b5": 2,
                    "m1": 0,
                    "m2": 0,
                    "m3": 0,
                    "m4": 0,
                    "m5": 0
                }
            }


yesterday data   10times/minutes   but  t1 = 6

**Comment by Sunlitkid** [comment]
Thank you !
I have downloaded the latest version and testing

**Comment by Sunlitkid** [comment]
version 6.0 is Corrent  @wu-sheng

**Comment by wu-sheng** [comment]
FYI @peng-yongsheng a potential bug for old version.
