### ISSUE TITLE
multi ignore() calls in AgentBuilder.Default would be overrided by the last one

### ISSUE THREAD

**Issue by honganan** [apache/incubator-skywalking#1912]
In class SkyWalkingAgent, there is a code fragment like this:
```java
new AgentBuilder.Default(byteBuddy)
            .ignore(nameStartsWith("net.bytebuddy."))
            .ignore(nameStartsWith("org.slf4j."))
            .ignore(nameStartsWith("org.apache.logging."))
            .ignore(nameStartsWith("org.groovy."))
            .ignore(nameContains("javassist"))
            .ignore(nameContains(".asm."))
            .ignore(allSkyWalkingAgentExcludeToolkit())
            .type(pluginFinder.buildMatch())
            .transform(new Transformer(pluginFinder))
            .with(new Listener())
            .installOn(instrumentation);
```

I read the Bytebuddy source code and found every ignore() from the second invoke like above would create a new AgentBuilder.Default object, and the ElementMatcher does not merge with the previous one. Then only the last ignore ElementMatcher is worked, and the previous calls was overrided.
Here is what I read from Bytebuddy's logic:
1. AgentBuilder.Default(byteBuddy).ignore(...), returns a new Ignoring Object which  extends Delegator
2. the second ignore(...) calls in Delegator likes
`return materialize().ignore(ignoredTypes) `
the meterialize(implements in Ignoring class) returns a new Default object, and then the ignore(...) calls the new Default's ignore method, the overriding occurs.

We use skywalking's enhance model indirectly in our apm system in an attach agent way, and caught exception `java.lang.NoClassDefFoundError: java/lang/Throwable$WrappedPrintWriter`. After read the source code, We resolve it by use one ignore(...) with Disjunctions like the under fragment:
```java
new AgentBuilder.Default()
          .ignore(nameStartsWith("net.bytebuddy.")
                .or(nameStartsWith("org.slf4j."))
                .or(nameStartsWith("ch.qos.logback."))
                .or(nameStartsWith("org.apache.logging."))
                .or(nameStartsWith("org.groovy."))
                .or(nameContains("javassist"))
                .or(nameContains(".asm."))
                .or(allSkyWalkingAgentExcludeToolkit())
                .or(nameStartsWith("sun.reflect."))
                .or(isSynthetic())
            )
            .type(pluginFinder.buildMatch())
            .transform(new Transformer(pluginFinder))
            .with(new Listener())
            .installOnByteBuddyAgent();
```

My error occurs because lack of the `.or(nameStartsWith("sun.reflect."))` . 
Besides, Bytebuddy adds `isBootstrapClassLoader()` in the ignore and I am not sure how to use this in my code yet.

**Comment by wu-sheng** [comment]
OK. I got your point of the `ignore` usage. This should be a bug, could you send a pull request to fix this?

**Comment by wu-sheng** [comment]
For `java.lang.NoClassDefFoundError: java/lang/Throwable$WrappedPrintWriter`, have you tried to remove `.or(nameStartsWith("sun.reflect.")`?

**Comment by wu-sheng** [comment]
Look forward to your PR, and glad this could solve the issue. Keep this issue open until we got your PR merged.

**Comment by wu-sheng** [comment]
Fixed.
