### ISSUE TITLE
org.apache.skywalking.apm.network.language.agent.SpanType  is not exist.

### ISSUE THREAD

**Issue by laoguanjie** [apache/incubator-skywalking#1917]
i clone the latest master branch and view the source code .
and find org.apache.skywalking.oap.server.core.source.DetectPoint  import org.apache.skywalking.apm.network.language.agent.SpanType

but org.apache.skywalking.apm.network.language.agent.SpanType is not exist.

it make 'mvn clean package -Dmaven.test.skip=true' failed.

i also find package apm-network:6.0.0-beta-SNAPSHOT  has only three files,whose path is org.apache.skywalking.apm.network.trace.component, instead of org.apache.skywalking.apm.network.language.agent

org.apache.skywalking.apm.network.language.agent.SpanType is not in package apm-network:6.0.0-beta-SNAPSHOT.

so, where can i find the class org.apache.skywalking.apm.network.language.agent.SpanType.

**Comment by ascrutae** [comment]
Have you execute the `git submodule init && git submodule update` command?
