### ISSUE TITLE
missing traceId when commit transaction of mysql

### ISSUE THREAD

**Issue by domineerLong** [apache/incubator-skywalking#1922]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
    skywalking 5.0.0-GA
   CentOS Linux release 7.4.1708
   openjdk version "1.8.0_151"
- Which company or project?
  Shanghai YunLi Information Technology Co., Ltd.
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
missing traceId when commit transaction of mysql.
I  find some exception in  logs of skywalking-agent, like this picture :
![image](https://user-images.githubusercontent.com/2107434/48659979-19485e80-ea95-11e8-87b3-0ab81a350341.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ascrutae** [comment]
could you show me which version of the JDBC driver used, or give the demo to produce this issue?

**Comment by wu-sheng** [comment]
No update.
