### ISSUE TITLE
The pattern in log4j2's config in incorrect.

### ISSUE THREAD

**Issue by peng-yongsheng** [apache/incubator-skywalking#1926]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Log4j2's xml in assembly folder is different with resource folder, it lead the logs missing the line number.

**Comment by wu-sheng** [comment]
Fixed.
