### ISSUE TITLE
How to customize traceid in skywalking?

### ISSUE THREAD

**Issue by fantasyofjay** [apache/incubator-skywalking#1941]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Requirement
___
### Question
- I have a http header "x-requet-id:1b759901-d1b7-475e-ac4f-686280edecdf" whose function is the same with traceid, now I want to put this header into traceid, but I found the traceid format in skywalking is "version.threadnumber.seqnumber", is it possible to put "1b759901-d1b7-475e-ac4f-686280edecdf" into traceid? Is there any impact if I change the traceid format?  If can, how to do it? 

FYI. Because there are a lot of applications depends on  "x-requet-id", I can't change its format.

**Comment by wu-sheng** [comment]
Right now, you couldn't. Segment and trace IDs only include three Longs as unique ID. What do you need to do this?

**Comment by fantasyofjay** [comment]
> Right now, you couldn't. Segment and trace IDs only include three Longs as unique ID. What do you need to do this?

For now, we generate a x-requet-id where the fe model send request to backend service. In fact, the x-request-id is the traceid in our system.  But we don't have feature like span, we want to integrate skywalking to enable these features. we want to keep forward compatible with x-requet-id. 

BTW, can I put the x-requet-id to the tag and find the trace by this tag?

**Comment by fantasyofjay** [comment]
We want to establish 1-1 connection between x-requet-id and traceid, and we hope to find trace with  x-requet-id too

**Comment by wu-sheng** [comment]
If you want to search, there is no mechanism at SkyWalking side to support this. But with SkyWalking toolkit, you could easily get traceid from skywalking. Maybe you could save this mapping relation in your system?

**Comment by fantasyofjay** [comment]
> If you want to search, there is no mechanism at SkyWalking side to support this. But with SkyWalking toolkit, you could easily get traceid from skywalking. Maybe you could save this mapping relation in your system?

ok， do you have any plan to support Hbase or Table?

**Comment by wu-sheng** [comment]
No, and wouldn't by current committer. Didn't need such kind of complex storage to an APM system.

**Comment by BobDu** [comment]
Now, 3 years later, is there a different answer to this question? @wu-sheng

**Comment by wu-sheng** [comment]
> Now, 3 years later, is there a different answer to this question? @wu-sheng

About what?

**Comment by BobDu** [comment]
> > Now, 3 years later, is there a different answer to this question? @wu-sheng
> 
> About what?

Can I customize traceid use `apm-toolkit-trace` or another toolkit in my application.
I encountered the same problem.
already exists request-id from aliyun api getway, I want I want to make `trace id` and `request id` consistent.
Or are you have some auggest for me?

**Comment by wu-sheng** [comment]
> Can I customize traceid use apm-toolkit-trace or another toolkit in my application.

No, you can't. And I can't see why we should support that. SkyWalking trace could start from browser, I don't believe you can control that far.

**Comment by shelltea** [comment]
@wu-sheng   Hi, is there a different answer to this question now? `trace id ` associated with `x-request-id`.

**Comment by wu-sheng** [comment]
> @wu-sheng Hi, is there a different answer to this question now? `trace id ` associated with `x-request-id`.

No, at least Java agent doesn't follow that.

**Comment by wu-sheng** [comment]
I heard cpp2sky may adopt this, as it is integrated inside Envoy. But I haven't checked the latest status.

**Comment by shelltea** [comment]
@wu-sheng  Thanks, I'll check later.

**Comment by lusains** [comment]
@wu-sheng Hi, is there a different answer to this question now? trace id  associated with x-request-id.

**Comment by michaelwangwangwang** [comment]
I think the toolkit should have many rich APIs, so that we can easily get, modify, reset, stop traceId etc.

**Comment by wu-sheng** [comment]
> I think the toolkit should have many rich APIs, so that we can easily get, modify, reset, stop traceId etc.

There is no such thing about modify and reset. Once we do that, this is not a distributed tracing system. 
Don't consider SkyWalking to trace your business flow. It is out of our landscape.
I know many users thought they could, but we don't provide that.

**Comment by wu-sheng** [comment]
> @wu-sheng Hi, is there a different answer to this question now? trace id  associated with x-request-id.

AFAIK, there isn't.

**Comment by etertal** [comment]
> > I think the toolkit should have many rich APIs, so that we can easily get, modify, reset, stop traceId etc.
> 
> There is no such thing about modify and reset. Once we do that, this is not a distributed tracing system. Don't consider SkyWalking to trace your business flow. It is out of our landscape. I know many users thought they could, but we don't provide that.

Our current system generates traceId and spanId through Spring-cloud-sleuth. In the case of mobile devices, traceId and spanId are generated by the mobile device. The entire link and log are concatenated by sleuth's traceId. Now we want to introduce skywalking to visualize the entire request link and replace the default traceId-segmentId generated by skywalking with the original traceId-spanId, So Skywalking is still a distributed link tracking system, I'm not sure if there's a problem with what I described.

Based on the scenario I mentioned above, can Skywalking support custom traceIDs, so that our logging system and Skywalking can be unified.

**Comment by wu-sheng** [comment]
> > > I think the toolkit should have many rich APIs, so that we can easily get, modify, reset, stop traceId etc.
> > 
> > 
> > There is no such thing about modify and reset. Once we do that, this is not a distributed tracing system. Don't consider SkyWalking to trace your business flow. It is out of our landscape. I know many users thought they could, but we don't provide that.
> 
> Our current system generates traceId and spanId through Spring-cloud-sleuth. In the case of mobile devices, traceId and spanId are generated by the mobile device. The entire link and log are concatenated by sleuth's traceId. Now we want to introduce skywalking to visualize the entire request link and replace the default traceId-segmentId generated by skywalking with the original traceId-spanId, So Skywalking is still a distributed link tracking system, I'm not sure if there's a problem with what I described.
> 
> Based on the scenario I mentioned above, can Skywalking support custom traceIDs, so that our logging system and Skywalking can be unified. @wu-sheng

If the trace ID is generated in the downstream, then you need to follow [SkyWalking Cross Process Propagation Headers Protocol](https://skywalking.apache.org/docs/main/latest/en/api/x-process-propagation-headers-v3/). This is not about customizing the trace ID. We asked more than that.
Please open a new discussion if you want to do further discussion. This discussion is irrelative. This discussion was only about using x-request-id, but not link the traces from skywalking with the ones from your systems(such as Mobile).
