### ISSUE TITLE
recordDataTTL seem not work

### ISSUE THREAD

**Issue by yimison** [apache/incubator-skywalking#1942]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
i set 10 minute to the value of 'recordDataTTL',but i seem not work ,i wait for several hours ,the trace data was not deleted! even though the log print the tips。
![image](https://user-images.githubusercontent.com/10662789/48761913-c5cc4f80-ece4-11e8-8e62-6a57edc5f483.png)

i use the 6.0.0-alpha version。
can you answer my question?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yimison** [comment]
it is a bug or my configuration problem? @peng-yongsheng @wu-sheng

**Comment by wu-sheng** [comment]
I have just addressed this issue. The time bucket format in segment table is not right.

**Comment by wu-sheng** [comment]
Fixed
