### ISSUE TITLE
how to config elasticsearch with http basic auth, with user and password? and does skywalking support to use HTTP rest client to connect to es? 

### ISSUE THREAD

**Issue by fantasyofjay** [apache/incubator-skywalking#1944]
how to config elasticsearch with http basic auth, with user and password?

**Comment by wu-sheng** [comment]
@peng-yongsheng Are we supported in 6.0.0-alpha?

**Comment by peng-yongsheng** [comment]
At least, not supported now.

**Comment by peng-yongsheng** [comment]
What security plugin did you use for Elasticsearch.

**Comment by peng-yongsheng** [comment]
@fantasyofjay I knew how to use security with high level rest client. Too simply, add a key-value(Authorization: Basic <TOKEN>) into http header. You can check out master, add it into Elasticsearch client and package the project. Or wait our beta version.

**Comment by fantasyofjay** [comment]
> I knew how to use security with high level rest client. Too simply, add a key-value(Authorization: Basic ) into http header. You can check out master, add it into Elasticsearch client and package the project. Or wait our beta version.

great, another question, do you support to use HTTP client to connect to es? I capture the traffic in my localhost, it seems that it use tcp transport. https://my.oschina.net/u/3527296/blog/916612

**Comment by fantasyofjay** [comment]
if can,  how to configure it?

**Comment by fantasyofjay** [comment]
![image](https://user-images.githubusercontent.com/15532710/48842597-9f371300-edcf-11e8-992c-25793681fb4e.png)

**Comment by fantasyofjay** [comment]
I use 5.0.0.0-GA

**Comment by wu-sheng** [comment]
5.0.0 is using tcp for sure. No auth supported.

**Comment by fantasyofjay** [comment]
what about  6.0?

**Comment by fantasyofjay** [comment]
5.0.0-GA is compatible with es 5.5.0. 
I try it. 6.0.0 is only compatible with es 6.3.2 and it's not compatible with es 5.5.0. 
I have es 5.5.0  which don't support TCP transport. OMG!

**Comment by fantasyofjay** [comment]
any suggestion? tks?

**Comment by wu-sheng** [comment]
> what about 6.0?

Peng had replied in prev comments.

**Comment by fantasyofjay** [comment]
> Why are you trying to do that? You are confusing me.

we have another team who op es 5.5.0(only tcp)，  my team don't want to op a new es cluster.

**Comment by wu-sheng** [comment]
> we have another team who op es 5.5.0(only tcp)， my team don't want to op a new es cluster.

So, you want to use SkyWalking 6.0.0-alpha, but still in 5.5.0 tcp? My question is about, are you trying to use our 6.x or need auth on 5.x tcp?

**Comment by fantasyofjay** [comment]
> > we have another team who op es 5.5.0(only tcp)， my team don't want to op a new es cluster.
> 
> So, you want to use SkyWalking 6.0.0-alpha, but still in 5.5.0 tcp? My question is about, are you trying to use our 6.x or need auth on 5.x tcp?

I could fix the auth issue by using nginx or customizing client.

The current issue is about TCP or Rest.

I have es 5.5.0 with Rest only. But  SkyWalking 6.0.0-alpha is not compatible with es 5.5.0(rest).
SkyWalking 5.0.0-GA only support 5.5.0 with TCP.

So I can't adapt the skywalking version with my es 5.5.0 with Rest only

**Comment by wu-sheng** [comment]
> So I can't adapt the skywalking with my es 5.5.0 with Rest only.

Yes. We didn't support that.

**Comment by peng-yongsheng** [comment]
@fantasyofjay The rest client of elasticsearch 5.x is different with 6.x, not provide admin api to us. So I just provide a new project with the transport client of the elasticsearch 5.x.

**Comment by peng-yongsheng** [comment]
@fantasyofjay If you a interesting about it, you can take a look. [project site](https://github.com/OpenSkywalking/SkyWalking-With-Es5x-Storage)

**Comment by wu-sheng** [comment]
@fantasyofjay Could you read Chinese? If so, there is a blog just posted about how to do auth without changing codes.

http://skywalking.apache.org/zh/blog/2019-01-02-skywalking-elasticsearch-basic.html

**Comment by wu-sheng** [comment]
This blog is contributed by @yanmaipian . I think it is a great solution.
