### ISSUE TITLE
Multiple storage error.

### ISSUE THREAD

**Issue by yimison** [apache/incubator-skywalking#1945]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
i setup and start the skywalking serivce which is build from the new commit! but i issue error .
detail:
![image](https://user-images.githubusercontent.com/10662789/48827037-fa084480-eda6-11e8-91f0-d46b024d053c.png)
![image](https://user-images.githubusercontent.com/10662789/48827065-0a202400-eda7-11e8-9929-71383bfd1adf.png)

the new commit is that:
![image](https://user-images.githubusercontent.com/10662789/48827095-202de480-eda7-11e8-8efe-02ab7fbfc35a.png)

this is a bug or something wronge with the build?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Look like you set your setting file not right. Are you trying to use Elastic Search as storage, but haven't remove the old H2 storage setting?

**Comment by yimison** [comment]
o! yes,you are right ,this is my fault that i haven't remove the old h2!

**Comment by yimison** [comment]
but i happen another question. i run the backend and angent success.  the "service" has the jvm metrics and the "trace" has not data.
detail:
![image](https://user-images.githubusercontent.com/10662789/48828821-b6fca000-edab-11e8-9529-2437a6b3937e.png)

![image](https://user-images.githubusercontent.com/10662789/48828831-bcf28100-edab-11e8-977c-650cbd264866.png)

![image](https://user-images.githubusercontent.com/10662789/48828844-c24fcb80-edab-11e8-9331-175403276634.png)

**Comment by yimison** [comment]
i set the recordDataTTL to 10 minute, and i access my application by rest api , and i can't see the data in the "trace" all the time

**Comment by wu-sheng** [comment]
You need to make sure your VM's time and timezone are right. Also same with your local laptop.

**Comment by yimison** [comment]
it is the same timezone. 
![image](https://user-images.githubusercontent.com/10662789/48829472-376fd080-edad-11e8-8354-7908666808f1.png)

**Comment by wu-sheng** [comment]
Then check agent log and collector. Are they all right? If the time is right, only reason is segment has been reported.

**Comment by yimison** [comment]
the basic environment is the same, i just use the new build skywalking service and agent.  before this , i use 6.0.0-alpha , i can the "trace" data.

**Comment by wu-sheng** [comment]
That should only relate to settings.

**Comment by yimison** [comment]
i can't see any error for the log of agent the collector .
![image](https://user-images.githubusercontent.com/10662789/48830630-0349df00-edb0-11e8-8024-ef30c2a96924.png)

![image](https://user-images.githubusercontent.com/10662789/48830633-0775fc80-edb0-11e8-864e-787e30428851.png)

"That should only relate to settings." , What exactly are they？

**Comment by wu-sheng** [comment]
Can't know from me. Because 6 and 5 differences are only backend analysis modules.

**Comment by yimison** [comment]
i had send 10000 request to my service , i find that the "trace" is still no data ,but i can see the throughput data. is it wronge with the recordDataTTL?

![image](https://user-images.githubusercontent.com/10662789/48831475-dd253e80-edb1-11e8-9b53-dbd1ddde0aee.png)

**Comment by wu-sheng** [comment]
Ttl has bug, but it is can't delete right.

**Comment by yimison** [comment]
i see !  we use it in production environment，now we can only delete the segment by elasticsearch api because the trace data is more and more large. so what's your plan to fix  and  to release a new version?

**Comment by wu-sheng** [comment]
Already fixed in master.

**Comment by yimison** [comment]
i use the newest build just now, it is still no trace data.- -!!!

**Comment by wu-sheng** [comment]
We fixed ttl bug about why no trace, we don't know.
