### ISSUE TITLE
search_phase_execution_exception while query doc size greater than 10 thousand

### ISSUE THREAD

**Issue by simuhunluo** [apache/incubator-skywalking#1954]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking5&6, es5&6
- Which company or project?

- What happen?

#### 1. error:
```
Exception while fetching data (/queryBasicTraces) : Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
```
In fact, this problem also exists in the online demo.
#### 2. Scene recurrence
You can copy the following request content：
```
{
    "variables":{
        "condition":{
            "traceState":"ALL",
            "queryOrder":"BY_START_TIME",
            "paging":{
                "pageNum":53,
                "pageSize":200,
                "needTotal":true
            },
            "queryDuration":{
                "start":"2018-09",
                "end":"2018-11",
                "step":"MONTH"
            }
        }
    },
    "query":"
        query BasicTraces($condition: TraceQueryCondition) {
        queryBasicTraces(condition: $condition) {
        traces {
        key: segmentId
        endpointNames
        duration
        start
        isError
        traceIds
        }
        total
        }
        }"
}
```

Submitting the request will give an error. **This is a problem with ElasticSearch DB.** If the value of from+size exceeds 10000 when paging, the ES data will not be found. Request above 53*200+200>10000.

**Comment by wu-sheng** [comment]
Why do you want to go to this page?

**Comment by wu-sheng** [comment]
If you want, every database could be blocked by this kind of issue. Paging for every database, no matter NoSQL or traditional DB, can't survive. You could try:)

**Comment by wu-sheng** [comment]
Scala out your ElasticSearch cluster, or make timeout longer, is your only option.
