### ISSUE TITLE
[agent]java.lang.NullPointerException: null with apm-spring-annotation-plugin-6.0.0-alpha.jar

### ISSUE THREAD

**Issue by tian-github** [apache/incubator-skywalking#1965]
Please answer these questions before submitting your issue.
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking ver : 6.0.0-alpha
jre : 1.8

when I added optional-plugins/apm-spring-annotation-plugin-6.0.0-alpha.jar to plugins and then I get NPE !  maybe the **apm-spring-annotation-plugin-6.0.0-alpha.jar** has any problem 
`at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:93)`

**Comment by wu-sheng** [comment]
No update.
