### ISSUE TITLE
Beginning to remove expired metrics from the storage.

### ISSUE THREAD

**Issue by liliang8858** [apache/incubator-skywalking#1971]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [1] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Beginning to remove expired metrics from the storage.
![image](https://user-images.githubusercontent.com/38367404/49192116-a0aaa180-f3b4-11e8-8048-d1596065628f.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What is your question?

**Comment by liliang8858** [comment]
![image](https://user-images.githubusercontent.com/38367404/49192201-ff701b00-f3b4-11e8-92b2-9e2c2c00229a.png)

**Comment by wu-sheng** [comment]
There are ttl settings in your application.yml. Set them right. And make sure your VMs time and time zone right.
