### ISSUE TITLE
The CPU usage was high when I started the CollectorBootStartUp service

### ISSUE THREAD

**Issue by karhs** [apache/incubator-skywalking#1983]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ]Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The CPU usage was high when I started the CollectorBootStartUp service

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking ver : 5.0.0-GA
jre : 1.8
Linux：CentOS Linux release 7.4.1708 (Core)

- What happen?
This is the Thread dumps file [threadDump.txt](https://github.com/apache/incubator-skywalking/files/2632734/threadDump.txt)

**Comment by wu-sheng** [comment]
Have data input? Are your Elasticsearch cluster available? We need more info.

**Comment by wu-sheng** [comment]
We haven't received any of this report. So, you need to find which could cost CPU high.

**Comment by karhs** [comment]
> 有数据输入吗？您的Elasticsearch集群是否可用？我们需要更多信息。
This data is the test server
![image](https://user-images.githubusercontent.com/10909692/49284594-f9bb2800-f4cf-11e8-8f5b-7af2ee12c482.png)

The only configuration modified: agent.span_limit_per_segment=2000

**Comment by wu-sheng** [comment]
Not helpful. No one reported this, we really need you to find some by yourself. Do you have any guess?

No one can find what is happening at your side.

If your elasticsearch performance is low, would block the cluster.

**Comment by peng-yongsheng** [comment]
@karhs Your screenshot want to us there are less segments received by the backend, But the cpu usage of the backend server was high? I'am trying to fixed it, but in many way the effect is not good. Can't balance it between busy and idle of the backend server.

**Comment by wu-sheng** [comment]
Fixed in 6.1.
