### ISSUE TITLE
Grpc question

### ISSUE THREAD

**Issue by IanCao** [apache/incubator-skywalking#1984]
![image](https://user-images.githubusercontent.com/32847163/49285982-05a8e900-f4d4-11e8-950b-d8a0ea4b0650.png)

i found this part do not work.
managedChannel.isShutdown()   and managedChannel.isTerminated() are always false

**Comment by wu-sheng** [comment]
Yes. From I known. Still put this line, just depend on Grpc. Maybe sometime, they changed. We process the network by stub send exception. 😄 

Sorry to make you feel not clear.
