### ISSUE TITLE
compile fail

### ISSUE THREAD

**Issue by liujianyu4303** [apache/incubator-skywalking#2001]
could not compile skywalking, I clone project from github, when I execute command “mvn compile -Dmaven.test.skip=true” in master branch, get error as follows

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project server-core: Compilation failure: Compilation failure: 
[ERROR] /Users/liujianyu/project/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/query/TraceQueryService.java:[23,1] 程序包org.apache.skywalking.apm.network.language.agent不存在
[ERROR] /Users/liujianyu/project/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/query/TraceQueryService.java:[24,1] 程序包org.apache.skywalking.apm.network.language.agent.v2不存在
[ERROR] /Users/liujianyu/project/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/query/TraceQueryService.java:[138,14] 找不到符号
[ERROR]   符号:   类 SpanObjectV2
[ERROR]   位置: 类 org.apache.skywalking.oap.server.core.query.TraceQueryService
[ERROR] /Users/liujianyu/project/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/query/TraceQueryService.java:[243,14] 找不到符号
[ERROR]   符号:   类 SpanObject
[ERROR]   位置: 类 org.apache.skywalking.oap.server.core.query.TraceQueryService
[ERROR] /Users/liujianyu/project/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/source/DetectPoint.java:[21,56] 程序包org.apache.skywalking.apm.network.language.agent不存在
[ERROR] /Users/liujianyu/project/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/source/DetectPoint.java:[29,44] 找不到符号
[ERROR]   符号:   类 SpanType
[ERROR]   位置: 类 org.apache.skywalking.oap.server.core.source.DetectPoint
[ERROR] /Users/liujianyu/project/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/source/DetectPoint.java:[42,102] 程序包org.apache.skywalking.apm.network.common不存在
[ERROR] /Users/liujianyu/project/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/query/MetadataQueryService.java:[23,56] 程序包org.apache.skywalking.apm.network.language.agent不存

what should I do?

**Comment by wu-sheng** [comment]
Follow compiling document. https://github.com/apache/incubator-skywalking/blob/master/docs/en/guides/How-to-build.md#build-project
