### ISSUE TITLE
Exception while fetching data(queryBasicTraces): Elasticsearch exception [type=parsing_execption,reason=[match_phrase] query does not support [zero_terms_query]]

### ISSUE THREAD

**Issue by songningbo** [apache/incubator-skywalking#2007]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  skywalking 6-alpha   centos    jdk1.8.0_171-b11

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Which version of ElasticSearch are you using? 6.3+ should be supported.

**Comment by mattwmj** [comment]
FYI es 6.2.4 has this issue
