### ISSUE TITLE
springcloud gateway项目启动时，添加skywalking-agent.jar。但是访问代理接口时，出现以下异常

### ISSUE THREAD

**Issue by github24518** [apache/incubator-skywalking#2011]
springcloud gateway项目启动时，添加skywalking-agent.jar。但是访问代理接口时，出现以下异常，有哪位知道怎么解决吗？

使用springcloud gateway代理转发的时候，出现异常
Whitelabel Error Page
This application has no configured error view, so you are seeing this as a fallback.

Thu Dec 06 17:51:29 CST 2018
There was an unexpected error (type=Internal Server Error, status=500).
**org.springframework.cloud.gateway.filter.factory.HystrixGatewayFilterFactory$RouteHystrixCommand cannot be cast to org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance**

**Comment by wu-sheng** [comment]
Why submit duplicate issue?

**Comment by github24518** [comment]
大神，我就想知道什么时候可以兼容springcloud gateway呀！
