### ISSUE TITLE
Does skywalking 5.0.0 GA require springboot version

### ISSUE THREAD

**Issue by 18505551125** [apache/incubator-skywalking#2017]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Does skywalking 5.0.0 GA require springboot version?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We didn't require. Maybe some plugins need.
