### ISSUE TITLE
project cant startup

### ISSUE THREAD

**Issue by WentHao** [apache/incubator-skywalking#2019]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question or discussion
- Which version of SkyWalking, OS and JRE?
linux , 5.0.0-GA
- Which company or project?
spring boot 1.5.2
- What happen?
with skywalking ,sometimes my project can't start up.just like programmed death,but the progerss is on. 
 After opening  the skywalking-api.log ，I find some class not enhanced successful when it happen . and every time it happened with different class which not enhanced successful. 
can you help me?

> skywalking-api.log
> DEBUG 2018-12-07 17:04:48:231 AbstractClassEnhancePluginDefine :  enhance class org.springframework.web.method.HandlerMethod by > org.apache.skywalking.apm.plugin.spring.mvc.v4.define.HandlerMethodInstrumentation completely. 
> DEBUG 2018-12-07 17:04:48:231 SkyWalkingAgent :  Finish the prepare stage for org.springframework.web.method.HandlerMethod. 
> DEBUG 2018-12-07 17:04:48:239 SkyWalkingAgent :  On Transformation class org.springframework.web.method.HandlerMethod. 
> DEBUG 2018-12-07 17:04:48:555 AbstractClassEnhancePluginDefine :  prepare to enhance class org.springframework.web.method.support.InvocableHandlerMethod by org.apache.skywalking.apm.plugin.spring.mvc.v4.define.InvocableHandlerInstrumentation. 
> DEBUG 2018-12-07 17:04:50:759 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:CONNECTED. 
> DEBUG 2018-12-07 17:04:53:759 AppAndServiceRegisterClient :  AppAndServiceRegisterClient running, status:CONNECTED. 
> DEBUG 2018-12-07 17:04:56:756 GRPCChannelManager :  Selected collector grpc service running, reconnect:false.

**Comment by wu-sheng** [comment]
The logs look like good. Nothing special.
