### ISSUE TITLE
How does skywalking's monitoring interface set up login free

### ISSUE THREAD

**Issue by 18505551125** [apache/incubator-skywalking#2030]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How does skywalking's monitoring interface set up login free
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean set up login free? Deactive login password verification?

**Comment by 18505551125** [comment]
> 你是什​​么意思设置免费登录？无效的登录密码验证？

No account and password are required

**Comment by wu-sheng** [comment]
No. In our release, we require for that. If you want that, change the UI codes by yourself.
