### ISSUE TITLE
请问什么时候可以兼容spring cloud gateway呢？

### ISSUE THREAD

**Issue by github24518** [apache/incubator-skywalking#2034]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only. Requirement only accept when some contributor wants it.

**Comment by monkeyAlwaysWin** [comment]
spring cloud gateway 现在不兼容
