### ISSUE TITLE
Connection es failed NoNodeAvailableException

### ISSUE THREAD

**Issue by xiaoni157** [apache/incubator-skywalking#2038]
- Why do you submit this issue?
- [ ✅] Question or discussion
___
### Question
- What do you want to know?
Why is the connection abnormal
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking ：5.0.0-GA 
ElasticSearch version: 5.5 aliyun es server
jdk :1.8.0_171
OS:linux aliyun Ecs server
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
The error i am getting in collector.log:
<img width="1410" alt="third" src="https://user-images.githubusercontent.com/24448049/49859809-6ff64d80-fe33-11e8-9d6f-547d28acf4b0.png">

Here is my skywalking configuration file application.yml:
![firsh](https://user-images.githubusercontent.com/24448049/49859741-46d5bd00-fe33-11e8-9c62-aa36d17e62e7.jpeg)
<img width="1091" alt="second" src="https://user-images.githubusercontent.com/24448049/49859745-49d0ad80-fe33-11e8-9914-d8250ade1fe6.png">

elasticsearch.yml is the default configuration of es server

collector was in 172.16.12.192，ES was in 172.16.12.209。

**Comment by wu-sheng** [comment]
Version 5.x asked for ElasticSearch TCP ports, default in 9200. 

Follow document please.

**Comment by xiaoni157** [comment]
Oh, i found this error in the skywalking-collector-server.log

![error](https://user-images.githubusercontent.com/24448049/49911328-f60ca580-fec0-11e8-9189-41e9050a3d3a.jpeg)
I see these two problems #1395 and #1944 .Does this mean that skywalking5.0.0-ga does not support xpack parameter configuration and can only modify the code

**Comment by peng-yongsheng** [comment]
@wu-sheng 5.x is transport client, default is 9300 port, not 9200, 6.x is rest client, default is 9200.

**Comment by peng-yongsheng** [comment]
@xiaoni157 From you logs, I see a missing authentication exception. Our elasticsearch client not support authentication. This is a feature of XPack and XPack is not opensource license. So, you must change the dependency of the elasticsearch client from transport to XPack and setting the username and password by XPack client by yourself.

**Comment by xiaoni157** [comment]
ok, i see. thank you.
