### ISSUE TITLE
[OAP Server][Storage] A new Elasticsearch client supports 2.x, 5.x and 6.x version families.

### ISSUE THREAD

**Issue by peng-yongsheng** [apache/incubator-skywalking#2039]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X] Feature or performance improvement
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

### Reason
From our community, I seen different users prefer different Elasticsearch version. The demand for 5.x and 6.x is the greatest. But the startup mechanism of the storage plugin is not by independent class loader. So, we can't put the multiple Elasticsearch client version into single release package. 

### Solution
I think we can develop a rest client by ourself base on the docs provided by Elasticsearch team. 
* [2.x](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/index.html)
* [5.x](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/index.html) 
* [6.x](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html)

By my experience, we just use a little client api. So, the workload is not too much and no need to worry about the compatibility of this new client.

**Comment by peng-yongsheng** [comment]
I will try to implement the authentication of the Elasticsearch.

**Comment by wu-sheng** [comment]
Good plan to do this. Try to implement a prototype version in GA version, and let's take at least 3-4 months to make sure it could work well in production env. Then mark it production ready and default storage client, in SkyWalking 6.2 or 6.3. If anything goes well.

**Comment by peng-yongsheng** [comment]
### Step
1. Comparison of the differences from the request and response of the Elasticsearch API.
1. Design the Elasticsearch client API.
1. Develop and test.

### Which API our project used now.
1. Indices APIs: Create, Delete, Exists
1. Document APIs: Index, Get, Delete, Delete by query, Update, Bulk
1. Search APIs: Query, From/Size, Count
1. Metrics Aggregations: Avg, Max, Min, Sum

Elasticsearch have so many version. So, we can't comparison all of them one by one. First of all, we just comparison the differences from the last release of the 2.x, 5.x, 6.x.

**Comment by wu-sheng** [comment]
From our last discussion, this feature is uncertain, so I put this as **TBD** tagged, with no milestone. @peng-yongsheng Whenever you finish this, please set the milestone to the next release.

**Comment by wu-sheng** [comment]
I think this wouldn't be provided. We could use compiling solution to support different storage version.
