### ISSUE TITLE
doubt about grpc agent

### ISSUE THREAD

**Issue by admln** [apache/incubator-skywalking#2043]
Hello, I used the Grpc framework，client connect server, The IP, namespace, proto interface are the same, ideally should be a client to the server, why it is divided into the two lines? ? ?
![image](https://user-images.githubusercontent.com/6093870/49948003-7ff25800-ff2d-11e8-8119-d4998e0eeac1.png)

**Comment by wu-sheng** [comment]
Version os gRPC, or demo? I think this will help

**Comment by wu-sheng** [comment]
No update in 10days. Closing.
