### ISSUE TITLE
agent and collector connect error

### ISSUE THREAD

**Issue by xiaoni157** [apache/incubator-skywalking#2045]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why is the connection abnormal
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking ：5.0.0-GA aliyun ecs. ip:172.16.12.193
jar : aliyun ecs. ip:172.16.12.192
ElasticSearch version: 5.5 aliyun es server
jdk :1.8.0_171
OS:linux aliyun Ecs server

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Here is my skywalking configuration file application.yml:
![test](https://user-images.githubusercontent.com/24448049/49987676-187cec80-ffaf-11e8-8e6a-543b2f4d1f90.jpeg)
![test01](https://user-images.githubusercontent.com/24448049/49987737-672a8680-ffaf-11e8-9217-a42d3a935eb6.jpeg)

Here is my skywalking agent file agent.config:
![image](https://user-images.githubusercontent.com/24448049/49987765-80cbce00-ffaf-11e8-8d46-64da3bc4199f.png)

And here is my error： agent skywalking-api.log
![image](https://user-images.githubusercontent.com/24448049/49987891-ec15a000-ffaf-11e8-8cb8-8c2080554309.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Why do you submit an issue without any info? How could we help you?

**Comment by xiaoni157** [comment]
sorry, i commit so fast, now it has.

**Comment by peng-yongsheng** [comment]
@wu-sheng Seems he comment many info. I open it.

**Comment by peng-yongsheng** [comment]
@xiaoni157 But, I also suggest you give priority to ask such a question in QQ. It just a question about how to use, no need to commit issue.

**Comment by wu-sheng** [comment]
Do you deploy agent and collector in the same machine? Please follow this document to understand how the connection works, https://github.com/apache/incubator-skywalking/blob/5.x/docs/en/Architecture.md#multiple-connection-ways

@peng-yongsheng Please don't assign the issue to the closed milestone, it will break the changelog.

**Comment by peng-yongsheng** [comment]
@wu-sheng It just a question, fixed nothing, why assign to the other version which is not he use?

**Comment by xiaoni157** [comment]
In the same machine, it works well. i see document first.

**Comment by wu-sheng** [comment]
If you are using 0.0.0.0 for grpc, it only works in single node and in the same machine. You have several choices, such as use real IP, or try the direct link. Before you move to cluster mode, IP must not 0.0.0.0

**Comment by wu-sheng** [comment]
> It just a question, fixed nothing, why assign to the other version which is not he use?

@peng-yongsheng two major reasons
1. [Change log](https://github.com/apache/incubator-skywalking/blob/master/CHANGES.md) includes the issues(question tag) , so you shouldn't change it after this version had been released. Otherwise, no point to provide change log and milestone.
1. When you do Apache reports, you will need these numbers. Such as.
```
How has the project developed since the last report?

  The project has a diverse community, many users, contributors are from 
  different companies.
  There has been over 100 commits by more than 22 contributors in the three 
  months.
  In 5.0.0-RC2 release milestones, there are 130 issues and pull requests 
  solved.
  In 5.0.0-GA release milestones, there are 32 issues and pull requests 
  solved.
  In 6.0.0-alpha release milestones, there are 202 issues and pull requests 
  solved.
```

This is exact why we need this `question` label. Archive those issues in milestone, also keep the issues clear enough.

**Comment by xiaoni157** [comment]
@wu-sheng you are right. i use my real IP, and it works.thank you.
Here is my skywalking configuration file application.yml:
![image](https://user-images.githubusercontent.com/24448049/49998650-c7c9bb80-ffcf-11e8-9c9d-f64642b9d390.png)
