### ISSUE TITLE
use 5.0.0 GA cannot not collect cpu & gc

### ISSUE THREAD

**Issue by Weishibai** [apache/incubator-skywalking#2059]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
It is not about the version. It is about which JVM you are using? See `JVMService#run`, that is how it collects all JVM info. If your JVM is not supported, we are welcome you to contribute your JVM metric collection implementation.

**Comment by wu-sheng** [comment]
Closing. No update in 6 days.
