### ISSUE TITLE
On /monitor/service page show "Avg Response Time" = 9608.29ms, but all of the service in "Top 20 Slow Traces" show below 802ms?

### ISSUE THREAD

**Issue by lintghi** [apache/incubator-skywalking#2061]
Bug? why "Avg Response Time" = 9608.29ms, but all of the "Top 20 Slow Traces" below 802ms.
using:  Skywalking 5.0.0, CentOS 7, Java 8

![snip_20181217142426](https://user-images.githubusercontent.com/2133947/50070170-0d70c900-0208-11e9-8da3-a185e6ca2ff5.png)

**Comment by wu-sheng** [comment]
I think most likely your trace TTL is less than minute metric TTL? The slow trace have been deleted somehow.
