### ISSUE TITLE
Website generation codes should not be included in pull request.

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#2067]
@TinyAllen 

By reviewing this PR, https://github.com/apache/incubator-skywalking-website/pull/9/files . I noticed a very serious issue. Everytime, we asked for contributor to pull requests all generated codes, which makes people very hard to review.

We need the following feature before accepting this pr for long term benefits.
1. Make sure every time we generated images/htmls/css,  and all of old ones should be deleted. From my local tests, I don't find that. Look like the images become more and more. So is our delete script not right?
1. Set a jerkins or use some CI somewhere, to generate and push static pages automatically. @JaredTan95 should have direct access to website repo, and you should have an Apache account soon.

**Comment by JaredTan95** [comment]
New CI script works fine. And apache/incubator-skywalking-website#9  has been merged.
FYI @wu-sheng @TinyAllen
