### ISSUE TITLE
How do I optimize the connection between the collector and es?

### ISSUE THREAD

**Issue by xiaoni157** [apache/incubator-skywalking#2068]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [✅ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How do I optimize the connection between the collector and es?
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking ：5.0.0-GA aliyun ecs. ip:172.16.12.193
The jar package: aliyun ecs. ip:172.16.12.192
ElasticSearch version: 5.5 aliyun es server
jdk :1.8.0_171

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Question1:I read this article [https://github.com/SkywalkingTest/Agent-Benchmarks/blob/master/README.md](url) ,But I did not find the collector configuration connection es part, is it the default configuration?
![19f9bab0e41165777235b2e4ed00aa54](https://user-images.githubusercontent.com/24448049/50207139-8f97f380-03a8-11e9-8271-4a637daae2a5.jpg)

Question2:When I used jmeter to test, the CPU was stable around 25-30 without probes. After adding probes, the CPU in the first test could reach 100 in the first few minutes, and then dropped to about 35-40. The second test was normal, and there was no peak value, was it because of preheating? How do you optimize this?
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> Question1:I read this article https://github.com/SkywalkingTest/Agent-Benchmarks/blob/master/README.md ,But I did not find the collector configuration connection es part, is it the default configuration?

This article is using mock backend for performance tests, nothing about backend.

**Comment by wu-sheng** [comment]
> Question2:When I used jmeter to test, the CPU was stable around 25-30 without probes. After adding probes, the CPU in the first test could reach 100 in the first few minutes, and then dropped to about 35-40. The second test was normal, and there was no peak value, was it because of preheating? How do you optimize this?

First, the agent will make CPU a little higher in the first minutes, maybe because
1. More classes(agent's) loaded into JVM.
1. Instrumentation(change binary codes) in runtime costs CPU
1. The first few times access, trigger agent class loader working.
1. Some JIT works triggered.

**Comment by xiaoni157** [comment]
@wu-sheng I am worried about whether this online service will kill the previous online service directly, because the CPU is really high.
In addition, do you have real tests instead of mock tests?

**Comment by wu-sheng** [comment]
I don't understand what you are saying. Which online service?
What is your question? What do you mean kill?

**Comment by wu-sheng** [comment]
Mock tests are for isolate backend and agents tests. They are real tests.

**Comment by xiaoni157** [comment]
Can I understand it this way? Does it mean that you only tested the performance difference between agents or not? The collector and es are not in the scope of the test at all

**Comment by wu-sheng** [comment]
Yes. That depends on Elasticsearch cluster scale and performance. You could learn it from many places.
