### ISSUE TITLE
there is some bug in integration  with log4j2

### ISSUE THREAD

**Issue by pengchenxue** [apache/incubator-skywalking#2069]
https://github.com/pengchenxue/skywalking-demo

这是我的代码，实际上就是抄的
https://github.com/SkywalkingTest/spring-cloud-example

这个官方的例子，然后自己加上了log4j2的配置和包

然后奇怪的是

我在projectC的ServiceController中加了一句这个日志
        log.info("===============test============traceid={}",TraceContext.traceId());

![image](https://user-images.githubusercontent.com/37992644/50218488-18258c80-03c7-11e9-9d53-af3ee0d1bcb5.png)

这个现象很奇怪,TraceContext.traceId()  可以拿到，但是[TID:N/A]  居然是这个？？

我使用的5.0 GA版本，按照官方文档操作，为何会产生这种现象？

启动我也激活了
-Dskywalking.agent.application_code=project-c -javaagent:D:\skywalking-agent\agent\skywalking-agent.jar

并且在skywalking  的web ui查询到了调用记录了。。。。

麻烦帮忙看下，谢谢

**Comment by wu-sheng** [comment]
English only in GitHub and ml
