### ISSUE TITLE
there is some bug in integration  with log4j2

### ISSUE THREAD

**Issue by pengchenxue** [apache/incubator-skywalking#2070]
https://github.com/pengchenxue/skywalking-demo
this is my code  ,and actually it 's   a copy  of this Official repo and i  add log4j2 config  
https://github.com/SkywalkingTest/spring-cloud-example

Strangely enough

i  print this log on  ServiceController in the projectC
log.info("===============test============traceid={}",TraceContext.traceId());

![image](https://user-images.githubusercontent.com/37992644/50219087-0513bc00-03c9-11e9-8b44-5c34c6363485.png)

This is a strange phenomenon.  I can get traceId by  ,TraceContext.traceId() ，but [%traceId]  is [TID:N/A] ？？

my skywalking version is 5.0 GA  and i active jvm config 
-Dskywalking.agent.application_code=project-c -javaagent:D:\skywalking-agent\agent\skywalking-agent.jar

**Comment by pengchenxue** [comment]
I use this way to print traceId 
https://logging.apache.org/log4j/2.x/manual/thread-context.html

but it's not official method

**Comment by wu-sheng** [comment]
TID:N/A means, you agent is not active or not working, such as, no backend available. Remember, SkyWalking is not a log assist solution. It is an Observability Platform.
