### ISSUE TITLE
Telemetry data performance test and blog

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#2074]
Gao,

We should run a performance test for backend in k8s , by using mesh telemetry. As the result, we provide a blog for that. 

What do you think? Of source, this should be after #2073 done, an observability is important when do performance test.

FYI @peng-yongsheng I think for trace, we need this too.

**Comment by peng-yongsheng** [comment]
The performance test environment was ready. But script still testing.

**Comment by wu-sheng** [comment]
> The performance test environment was ready. But script still testing.

Good. Let's write a separated blog for trace based performance tests.

**Comment by wu-sheng** [comment]
Done.
