### ISSUE TITLE
spring-boot-starter-undertow-2.1.1.RELEASE.jar 无法跟踪异常日志 jetty可以正确获取到

### ISSUE THREAD

**Issue by hadoop835** [apache/incubator-skywalking#2077]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?
spring-boot-starter-undertow-2.1.1.RELEASE.jar 无法跟踪异常日志 jetty可以正确获取到
![image](https://user-images.githubusercontent.com/8055054/50323171-6e074b00-0513-11e9-99e5-998f0444e6c4.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only.
