### ISSUE TITLE
Why does a request have two transIds？

### ISSUE THREAD

**Issue by xiaoni157** [apache/incubator-skywalking#2086]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [✅ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why does a request have two transIds？
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 5.0.0-GA
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

Using spring's hessian, I requested the client url and returned it to the server successfully, but traceId generated two.
client:
![image](https://user-images.githubusercontent.com/24448049/50397152-5ba63f00-07a9-11e9-910d-125d076dc4c2.png)

server:
![image](https://user-images.githubusercontent.com/24448049/50397177-88f2ed00-07a9-11e9-9083-15723ecd593d.png)

![image](https://user-images.githubusercontent.com/24448049/50397192-aa53d900-07a9-11e9-80a6-a3fe2f5f7fed.png)

![image](https://user-images.githubusercontent.com/24448049/50397209-c22b5d00-07a9-11e9-84b8-5436aee5e928.png)
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Hession is not supported.
