### ISSUE TITLE
The method objInst.getSkyWalkingDynamicField()  alwayls  get null if objInst instanceof T4CStatement  in oracle plugin, is that right?

### ISSUE THREAD

**Issue by ni-ze** [apache/incubator-skywalking#2092]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

skywalking5.0.0-GA

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

The method objInst.getSkyWalkingDynamicField()  alwayls  get null if objInst instanceof T4CStatement  in oracle plugin, is that right?
 
<img width="926" alt="oracle-1" src="https://user-images.githubusercontent.com/31175234/50474963-e54e4a80-09fd-11e9-991f-1a575cdee9bf.png">

<img width="921" alt="oracle-2" src="https://user-images.githubusercontent.com/31175234/50474971-ef704900-09fd-11e9-91f7-55ba3960f257.png"> 

<img width="915" alt="oracle-3" src="https://user-images.githubusercontent.com/31175234/50474982-f6975700-09fd-11e9-8e8d-515db85467a5.png">

<img width="902" alt="oracle-4" src="https://user-images.githubusercontent.com/31175234/50474986-f8f9b100-09fd-11e9-9500-3a3c295912ae.png">

<img width="735" alt="oracle-6" src="https://user-images.githubusercontent.com/31175234/50474999-0151ec00-09fe-11e9-9372-55563138e67e.png">

**Comment by wu-sheng** [comment]
Oracle plugin doesn't belong to Apache. Please move this issue to openskywalking.
