### ISSUE TITLE
聚合查询

### ISSUE THREAD

**Issue by huluxiaojingang** [apache/incubator-skywalking#2094]
每次查询都是根据条件重新做聚合计算的吗？这样数据量大，会不会查询效率很慢？
能不能支持固定某些指标，自动按照时间段做聚合计算，查询的时候只查询聚合后的结果，而不是全量重新计算。不知道有没有这个特性？

**Comment by wu-sheng** [comment]
English only. If you want this, you need understand, there aren't based on many data. For one metric of one service in 5 minute, only aggregate 5 minutes data, means 5 rows data aggregation. 

Pre-aggregation already done per minute.

Are you still feeling too many data?

**Comment by wu-sheng** [comment]
Duration is uncertain, right?
