### ISSUE TITLE
apm-webapp compile failed.

### ISSUE THREAD

**Issue by JustinGedehuo** [apache/incubator-skywalking#2099]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
How to solve this problem.
___
### Bug
- Which version of SkyWalking, OS and JRE?
v5.0.0-RC2

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

[INFO] --- frontend-maven-plugin:1.6:npm (npm install) @ apm-webapp ---                                                                                                                        [INFO] Running 'npm install --registry=https://registry.npm.taobao.org/' in E:\incubator-skywalking\skywalking-ui                                                                              [WARNING] npm WARN @antv/g2-plugin-slider@2.0.1 requires a peer of @antv/g2@>=3.0.0 but none is installed. You must install peer dependencies yourself.                                        [WARNING] npm WARN @babel/plugin-proposal-export-default@7.0.0-beta.32 requires a peer of @babel/core@7.0.0-beta.32 but none is installed. You must install peer dependencies yourself.        [WARNING] npm WARN @babel/plugin-proposal-export-namespace@7.0.0-beta.32 requires a peer of @babel/core@7.0.0-beta.32 but none is installed. You must install peer dependencies yourself.      [WARNING] npm WARN @babel/plugin-syntax-export-extensions@7.0.0-beta.32 requires a peer of @babel/core@7.0.0-beta.32 but none is installed. You must install peer dependencies yourself.       [WARNING] npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.                                                        [INFO] up to date in 47.162s                                                                                                                                                                   [WARNING] npm WARN bizcharts-plugin-slider@2.0.1 requires a peer of react@>15 <16 but none is installed. You must install peer dependencies yourself.                                          [WARNING] npm WARN bizcharts-plugin-slider@2.0.1 requires a peer of react-dom@>15 <16 but none is installed. You must install peer dependencies yourself.                                      [WARNING] npm WARN bizcharts-plugin-slider@2.0.1 requires a peer of react-addons-transition-group@^15.0.0 but none is installed. You must install peer dependencies yourself.                  [WARNING] npm WARN eslint-config-react-app@2.1.0 requires a peer of babel-eslint@^7.2.3 but none is installed. You must install peer dependencies yourself.                                    [WARNING] npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.                          [WARNING] npm WARN eslint-config-umi@0.1.3 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.                                [WARNING] npm WARN react-fittext@1.0.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.                                                    [WARNING] npm WARN react-fittext@1.0.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.                                                [WARNING] npm WARN react-router-redux@5.0.0-alpha.6 requires a peer of react@^15 but none is installed. You must install peer dependencies yourself.                                           [WARNING] npm WARN ts-jest@22.4.0 requires a peer of jest@^22.4.0 \|\| ^22.5.0-alpha.1 \|\| ^23.0.0-alpha.1 but none is installed. You must install peer dependencies yourself.                    [WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):                                                                                              [WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})                    [ERROR]                                                                                                                                                                                        [INFO]                                                                                                                                                                                         [INFO] --- frontend-maven-plugin:1.6:npm (npm run build) @ apm-webapp ---                                                                                                                      [INFO] Running 'npm run build' in E:\incubator-skywalking\skywalking-ui                                                                                                                        [INFO]                                                                                                                                                                                         [INFO] > skywalking-ui@5.0.0-RC build E:\incubator-skywalking\skywalking-ui                                                                                                                    [INFO] > cross-env DISABLE_ESLINT=true roadhog build                                                                                                                                           [INFO]                                                                                                                                                                                         [ERROR] 'cross-env' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒                                                                                                                                              [ERROR] ▒▒▒▒▒▒▒▒▒ļ▒▒▒                                                                                                                                                                          [ERROR] npm ERR! code ELIFECYCLE                                                                                                                                                               [ERROR] npm ERR! errno 1                                                                                                                                                                       [ERROR] npm ERR! skywalking-ui@5.0.0-RC build: `cross-env DISABLE_ESLINT=true roadhog build`                                                                                                   [ERROR] npm ERR! Exit status 1                                                                                                                                                                 [ERROR] npm ERR!                                                                                                                                                                               [ERROR] npm ERR! Failed at the skywalking-ui@5.0.0-RC build script.                                                                                                                            [ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                     [ERROR]                                                                                                                                                                                        [ERROR] npm ERR! A complete log of this run can be found in:                                                                                                                                   [ERROR] npm ERR!     C:\Users\jingh\AppData\Roaming\npm-cache\_logs\2018-12-29T02_27_37_717Z-debug.log
--
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This because your network isn't well.

**Comment by wu-sheng** [comment]
Compile has been checked very time. Must pass ci to make merge happens.
