### ISSUE TITLE
Could I pass argument to java agent?

### ISSUE THREAD

**Issue by bomee** [apache/incubator-skywalking#2101]
I have a question for i need copy agent for every java app, and update `agent.service_name` for every app?
Could I pass the argument `agent.service_name` to java agent and reuse the agent ?

中文：
我是否需要拷贝agent文件夹给每个应用，然后修改文件夹下的配置文件`agent.service_name`设置我的服务名称？
是否可以通过参数的形式传递`agent.service_name`给 java agent 而做到agent的复用？

**Comment by wu-sheng** [comment]
You have many ways to do this. Through system env or properties. Please read setup document.

**Comment by bomee** [comment]
I did not find it in the document，I have many jar app in a vm host.  I don't know the loading mechanism of the config file. So I need your guide. Thank you!

**Comment by bomee** [comment]
@wu-sheng 
I think the config file loading in the same folder at runtime. so I need copy agent folder for each app, is that right?
```
java -javaagent:/path/to/agent.jar="agent.service_name=app1" -jar app1.jar
java -javaagent:/path/to/agent.jar="agent.service_name=app2" -jar app2.jar
```

**Comment by wu-sheng** [comment]
We have very detailed documents. Again, please read document. https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/Setting-override.md
