### ISSUE TITLE
有没有计划支持es 6.x

### ISSUE THREAD

**Issue by geercode** [apache/incubator-skywalking#2106]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
有没有计划支持es 6.x,因为现在大部分公司的环境是6.x,他们的接口有个兼容的表，只是支持5.x会导致方案直接被pass了，skywalking好的特性真的多，因为es的原因导致很多公司都用pinpoint了，我看到issue里的讨论是准备支持多个版本，我觉得es的开发人员真的很自由的，大版本也很跳跃，spring的方案就疲于奔命了，到现在也是只支持兼容接口，所以希望跟着主流接口快速更新一下就好了，没有必要去兼容多个版本
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
SkyWalking 6 has already fully supported ElasticSearch 6.3+. Please read the new release. Beta just landed in last week, which is highly closed to GA release.

**Comment by wu-sheng** [comment]
English is not allowed in issues. Thanks.

**Comment by geercode** [comment]
best regards
