### ISSUE TITLE
skywalking agent: hows to specify 'agent.application_code'  property while multi applications running on one machine ?

### ISSUE THREAD

**Issue by ldcsaa** [apache/incubator-skywalking#2112]
skywalking agent: hows to specify 'agent.application_code'  property while multi applications running on one machine ?
    Does it need to use different config file for every application, by system property "-Dskywalking_config=<my-conf-file>" ?

**Comment by wu-sheng** [comment]
There are several ways to do this, see the advanced features, https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#advanced-features-1
- Set the settings through system properties for config file override. Read setting override.
- If you want to specify the path of your agent.config file. Read set config file through system properties
