### ISSUE TITLE
The data is too much and the style is messy.

### ISSUE THREAD

**Issue by qibaichao** [apache/incubator-skywalking#2114]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
The data is too much and the style is messy.
data for example
{
    "data": {
        "queryTrace": {
            "spans": [
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "337.70.15464296600130618",
                    "spanId": 0,
                    "parentSpanId": -1,
                    "refs": [],
                    "serviceCode": "marketing-testb",
                    "startTime": 1546429660013,
                    "endTime": 1546429660188,
                    "endpointName": "/inviteFriendAugActivity/getInvitingAwardList",
                    "type": "Entry",
                    "peer": "",
                    "component": "SpringMVC",
                    "isError": false,
                    "layer": "Http",
                    "tags": [
                        {
                            "key": "url",
                            "value": "http://127.0.0.1:8580/inviteFriendAugActivity/getInvitingAwardList.j"
                        },
                        {
                            "key": "http.method",
                            "value": "GET"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "337.70.15464296600130618",
                    "spanId": 1,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-testb",
                    "startTime": 1546429660013,
                    "endTime": 1546429660188,
                    "endpointName": "com.test.inviteFriendAugActivity.service.AugustActivitySearchService.getInvitingAwardList(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:25880",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:25880/com.test.inviteFriendAugActivity.service.AugustActivitySearchService.getInvitingAwardList(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 0,
                    "parentSpanId": -1,
                    "refs": [
                        {
                            "traceId": "337.70.15464296600130619",
                            "parentSegmentId": "337.70.15464296600130618",
                            "parentSpanId": 1,
                            "type": "CROSS_PROCESS"
                        }
                    ],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660014,
                    "endTime": 1546429660185,
                    "endpointName": "com.test.inviteFriendAugActivity.service.AugustActivitySearchService.getInvitingAwardList(Integer)",
                    "type": "Entry",
                    "peer": "",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:25880/com.test.inviteFriendAugActivity.service.AugustActivitySearchService.getInvitingAwardList(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 1,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660014,
                    "endTime": 1546429660017,
                    "endpointName": "Mysql/JDBI/PreparedStatement/execute",
                    "type": "Exit",
                    "peer": "mysql.test.test.com:3306",
                    "component": "mysql-connector-java",
                    "isError": false,
                    "layer": "Database",
                    "tags": [
                        {
                            "key": "db.type",
                            "value": "sql"
                        },
                        {
                            "key": "db.instance",
                            "value": "marketing"
                        },
                        {
                            "key": "db.statement",
                            "value": "select\n         \n    id, user_id, invited_uid, invited_nick_name, invest_id, invest_amount, invest_product, \n    coupon_id, coupon_value, cash_value, total_reward, create_time, status, update_time, \n    version, event_period\n   \n        from user_invite_reward\n        order by id DESC\n        limit ?"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 2,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660022,
                    "endTime": 1546429660030,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 3,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660030,
                    "endTime": 1546429660035,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 4,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660035,
                    "endTime": 1546429660040,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 5,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660040,
                    "endTime": 1546429660045,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 6,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660045,
                    "endTime": 1546429660049,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 7,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660049,
                    "endTime": 1546429660055,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 8,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660056,
                    "endTime": 1546429660062,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 9,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660062,
                    "endTime": 1546429660067,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 10,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660067,
                    "endTime": 1546429660071,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 11,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660071,
                    "endTime": 1546429660076,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 12,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660076,
                    "endTime": 1546429660081,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 13,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660081,
                    "endTime": 1546429660085,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 14,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660086,
                    "endTime": 1546429660090,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 15,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660090,
                    "endTime": 1546429660104,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 16,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660104,
                    "endTime": 1546429660109,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 17,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660110,
                    "endTime": 1546429660114,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 18,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660114,
                    "endTime": 1546429660119,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 19,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660119,
                    "endTime": 1546429660124,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 20,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660124,
                    "endTime": 1546429660129,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 21,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660129,
                    "endTime": 1546429660135,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 22,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660135,
                    "endTime": 1546429660140,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 23,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660140,
                    "endTime": 1546429660145,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 24,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660146,
                    "endTime": 1546429660151,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 25,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660151,
                    "endTime": 1546429660156,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 26,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660156,
                    "endTime": 1546429660160,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 27,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660161,
                    "endTime": 1546429660165,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 28,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660165,
                    "endTime": 1546429660170,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 29,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660170,
                    "endTime": 1546429660174,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 30,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660174,
                    "endTime": 1546429660180,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                },
                {
                    "traceId": "337.70.15464296600130619",
                    "segmentId": "343.239.15464296600140726",
                    "spanId": 31,
                    "parentSpanId": 0,
                    "refs": [],
                    "serviceCode": "marketing-service",
                    "startTime": 1546429660180,
                    "endTime": 1546429660185,
                    "endpointName": "com.test.user.service.UserInfoService.getUserInfo(Integer)",
                    "type": "Exit",
                    "peer": "127.0.0.1:20888",
                    "component": "Dubbo",
                    "isError": false,
                    "layer": "RPCFramework",
                    "tags": [
                        {
                            "key": "url",
                            "value": "dubbo://127.0.0.1:20888/com.test.user.service.UserInfoService.getUserInfo(Integer)"
                        }
                    ],
                    "logs": []
                }
            ]
        }
    }
}

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by qibaichao** [comment]
![default](https://user-images.githubusercontent.com/6158920/50594203-8ba2c000-0ed6-11e9-84a1-32d8f9d5c95f.png)

**Comment by wu-sheng** [comment]
@TinyAllen This looks like the BUG of GA trace new feature.

**Comment by wu-sheng** [comment]
Fixed.
