### ISSUE TITLE
how to search tag in skywalking-ui?

### ISSUE THREAD

**Issue by lisong2010** [apache/incubator-skywalking#2118]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
how to search tag in skywalking-ui?
if use ELK,  Is it necessary for kibana to use a custom query to search my custom tag?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0.0-beta
mac os
jdk8

- Which company or project?

- What happen?

**Comment by wu-sheng** [comment]
We don't have that.

**Comment by LvBay** [comment]
I also want this feature. This can greatly improve the search efficiency of backtracking problems.
@wu-sheng

**Comment by wu-sheng** [comment]
Contributions are welcome, if you are doing this, you will know the challenges.
