### ISSUE TITLE
How get the request params from get or post

### ISSUE THREAD

**Issue by yuxiao97** [apache/incubator-skywalking#2121]
In trace，can not found the params，where see or not supported? version 5.0

**Comment by wu-sheng** [comment]
We don't support that. If you dive a little deeper for this requirements, you will find actually this is complex. Such as
- Decoding of the HTTP parameter is uncertain, if decode wrong, it will break the application.
- Some stream reader doesn't allow pre-read.
- Performance concern, this is possible only if you are a low throughput system. Tag this parameter will cost a lot of memory, network, and storage.

So, this requirement could be done only in your own env and change the certain plugin.
