### ISSUE TITLE
how to set a unique name for each service instance nodes?

### ISSUE THREAD

**Issue by foxracle** [apache/incubator-skywalking#2127]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
In the service map page, we find that all Host field's value is filled with [localhost], our question is that how to set a unique name for each service instance nodes? we can not find the related setting variable in the agent config file. or what determined the Host field's value in skywalking.

- Which version of SkyWalking, OS and JRE?
6.0.0-beta

**Comment by wu-sheng** [comment]
Hostname is based on your OS hostname, agent just collect it.

**Comment by foxracle** [comment]
Thanks for your quick reply!
Could you tell me the details about how to collect the OS hostname, because related the 'hostname' of OS, we may mean different things. the hostname showed in service map page is not the same as the output of hostname command of OS(ubuntu 14.04).

**Comment by wu-sheng** [comment]
No. That name would not show in service map. Service map is based on service code, not hostname. In real production env, hostname is unique for each vm or container.

**Comment by foxracle** [comment]
when service instance nodes is one vm like aliyun's ecs, what does the 'hostname' mean. we install sw into our services using javaagent method, and our service is run in one tomcat with war package.

**Comment by wu-sheng** [comment]
OS hostname has just one meanings.  What do you expect? I am confusing. I feel you are creating your own concept.

**Comment by foxracle** [comment]
As a user, we just want to know which service instance nodes the service is now running. but we now can only find string like this on service map page: [Ins:web-pid:32016@localhost Throughput]. [Ins:web-pid:32016@nodexxx Throughput] is what we expect. so we want to know where the [localhost] come from?

**Comment by wu-sheng** [comment]
It is OS hostname. You could find tons of documents about how to set OS hostname in Google or Baidu.

**Comment by foxracle** [comment]
the question is that we have a unique hostname for every machine, but on service map page all machine show as  localhost

**Comment by wu-sheng** [comment]
That depends on JVM. We use JVM API to get that. So you could easily test it by a simple demo java app.

**Comment by foxracle** [comment]
thank you, we will check it
