### ISSUE TITLE
Each method needs to add @Trace tracing. How to configure uniform interception in aop?

### ISSUE THREAD

**Issue by gantts** [apache/incubator-skywalking#2129]
Too many methods and @Trace annotations are too cumbersome. Hope to unify the interception configuration

**Comment by wu-sheng** [comment]
We are welcome to accept this as an optional plugin. We don't have that for now. 

But you need to be careful, instrumenting too many local methods will be a big payload to your application, which could cost long latency. Keep this in optional is acceptable to SkyWalking.

Right now, I don't know any committer is working on this. 

@apache/skywalking-committers If anyone wants to do this, please remove `help wanted` label, and assign to yourself.

**Comment by zhaoyuguang** [comment]
Assign to me

**Comment by wu-sheng** [comment]
@zhaoyuguang Good to know, ping me if you need help.
