### ISSUE TITLE
 Does Motan plugin support cross-thread call?

### ISSUE THREAD

**Issue by ywf4026** [apache/incubator-skywalking#2132]
I created a thread B from the main thread A, the thread B executed a motan rpc call, then I found the motan rpc call had a different traceid. 

Is the feature to be supported to solve the problem?

**Comment by wu-sheng** [comment]
Read https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-trace-cross-thread.md

This is nothing about Motan.

**Comment by ywf4026** [comment]
> Read https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/Application-toolkit-trace-cross-thread.md
> 
> This is nothing about Motan.

thanks, it works.

But I found another problem, if thread A call thread B and thread B call thread C, I can not find the span of B called C.

Looking forward to your reply,thanks.

**Comment by wu-sheng** [comment]
> But I found another problem, if thread A call thread B and thread B call thread C, I can not find the span of B called C.

This plugin only works if thread c created in thread b. If you are using a thread pool, you have to understand the Context#capture and Context#continued in our plugin APIs. Then make the context propagates across thread b-c

**Comment by ywf4026** [comment]
> > But I found another problem, if thread A call thread B and thread B call thread C, I can not find the span of B called C.
> 
> This plugin only works if thread c created in thread b. If you are using a thread pool, you have to understand the Context#capture and Context#continued in our plugin APIs. Then make the context propagates across thread b-c

@wu-sheng I got a question.

I use skywalking 6.0.0.beta, mysql as storage, standalone

My code like this:

`@TraceCrossThread
Class GetPartScore implements Callable;

Class GetMidFeature implements Callable{
    public void call(){
            featureServiceMotan.getMidsFeaturesWithRequestId();
    }
}

Thread A:
ExecutorService executorService = Executors.newFixedThreadPool(1);
executorService. submit(new GetPartScore());

Thread B:
ExecutorService executorService = Executors.newFixedThreadPool(1);
    executorService.submit(CallableWrapper.of(new GetMidFeature()));

Thread C:
execute GetMidFeature task

The trace graph is:
![image](https://user-images.githubusercontent.com/3722641/51233800-d972fa00-19a5-11e9-9f19-9e5c334f914d.png)

table segment adds two records
![image](https://user-images.githubusercontent.com/3722641/51233963-57370580-19a6-11e9-939d-29d821f3747a.png)

table endpoint_inventory adds two records
![image](https://user-images.githubusercontent.com/3722641/51234583-14762d00-19a8-11e9-8eee-00a2e1196f94.png)



The trace graph is not correct, I think it should be:
![image](https://user-images.githubusercontent.com/3722641/51234073-a846f980-19a6-11e9-977e-160b9fff1f58.png)

I  debug , the problem may be in the preBuild step :

ReferenceIdExchanger class#line 75:
![image](https://user-images.githubusercontent.com/3722641/51234268-3ae79880-19a7-11e9-9ab3-f4c651a6dd5a.png)

In table endpoint_inventory, the GetPartScore endpoint's detect_point is 3, but above code uses DetectPoint.SERVER.ordinal(), that is 0, So the parentEndpointId(=GetPartScore) can't be found, then the last sement parse fail.

If I change the value of the detect_point of the GetPartScore endpoint to 0, then the trace graph is right:
![image](https://user-images.githubusercontent.com/3722641/51234073-a846f980-19a6-11e9-977e-160b9fff1f58.png)


Is this my  code problem?

Thanks for your help

**Comment by wu-sheng** [comment]
This issue has been located, fixed and will be in GA release. See https://github.com/apache/incubator-skywalking/pull/2162
