### ISSUE TITLE
Hystrix  Or agent core  bug

### ISSUE THREAD

**Issue by langyan1022** [apache/incubator-skywalking#2134]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [X] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking:6.0.0GA-Snapshot
OS:linux
JRE:agent 1.6  server 1.8

- What happen?
**Environment Description:** System A accesses B system through Hystrix and Okhttp.
When I turn off the hystrix function. A application can be connected in series with B application tracking. However, after opening hystrix, the A application cannot be connected in series with the B application, and only the related information of the A system can be traced.
I tried to track the code and the log and found that the spanId in the ContextCarrier became 1 after hystrix.

And found that there is such a piece of code in the capture method of TracingContext
```
ContextSnapshot snapshot = new ContextSnapshot(segment.getTraceSegmentId(),
            this.activeSpan().getSpanId(),
            segment.getRelatedGlobalTraces());
```
 this.activeSpan().getSpanId() return 0 each time in the hystrix plugin.
But spanIdGenerator is indeed a value that looks correct

I added a code like this, which I can see from the log.
```
 logger.debug("activeSpanId:{};spanIdGenerator:{}",this.activeSpan().getSpanId(),spanIdGenerator);
```
___

**Comment by wu-sheng** [comment]
The topology is not related to `sw6` header and entry/exit spans. So you need to check
1. Exit span of service A still generated.
1. Header in HTTP is right.
1. Entry span of service B generated, with the valid ref.

@ascrutae From the description, this is very likely the hytrix bug.

**Comment by langyan1022** [comment]
I added a code like this,

![image](https://user-images.githubusercontent.com/5259422/50822053-b45e0600-136b-11e9-8fdd-115c22f4e00e.png)
And
I found that hystrix creates a new context every time.

like this：
![image](https://user-images.githubusercontent.com/5259422/50822435-af4d8680-136c-11e9-8ec3-b584fa9788fe.png)


I filtered the Hystrix keyword from the skywalking agent log.

**Comment by wu-sheng** [comment]
When thread changed, creating new context is expected and right.

**Comment by langyan1022** [comment]
> When thread changed, creating new context is expected and right.

ok，I will continue to try to solve.

**Comment by langyan1022** [comment]
> sw

when hystrix opening，Entry span of service B can't generated,

**Comment by langyan1022** [comment]
> The topology is not related to `sw6` header and entry/exit spans. So you need to check
> 
> 1. Exit span of service A still generated.
> 2. Header in HTTP is right.
> 3. Entry span of service B generated, with the valid ref.
> 
> @ascrutae From the description, this is very likely the hytrix bug.

when hystrix opening，Entry span of service B can't generated,

**Comment by wu-sheng** [comment]
What do you mean no entry span?

**Comment by langyan1022** [comment]
> What do you mean no entry span?

Entry span of service B generated（Seen from the agent log ），but in the skywalking ui can‘t found the trace of  service B

**Comment by wu-sheng** [comment]
Then you need to find out whether the segment including this span(service B) finish or not, and the segment is in the same trace id.

**Comment by langyan1022** [comment]
> Then you need to find out whether the segment including this span(service B) finish or not, and the segment is in the same trace id.


ok
But I found that when sw6 in the ttp header is empty, service B can create a trace.

**Comment by wu-sheng** [comment]
I am not sure why, but shouldn't. But creating span is a lightweight op, shouldn't be effected by header/ref.

**Comment by langyan1022** [comment]
Ok, I will keep trying.
I just found this situation：
when agent log has this debug info：
![image](https://user-images.githubusercontent.com/5259422/50870600-9a680600-13f3-11e9-89e5-db81ecc28618.png)
the oap server log has this info：
![image](https://user-images.githubusercontent.com/5259422/50870537-5ffe6900-13f3-11e9-9cd6-885be54b3ef9.png)

I think it will be related to this.

Please ignore the time point in the log. The two servers are not accurate.

**Comment by wu-sheng** [comment]
When this NPE happens, it mean there is agent register data deleted, but the agent doesn't reboot.

**Comment by langyan1022** [comment]
> When this NPE happens, it mean there is agent register data deleted, but the agent doesn't reboot.

Ok, I see

**Comment by langyan1022** [comment]
I added some logs, for example:
![image](https://user-images.githubusercontent.com/5259422/50944964-94465800-14cd-11e9-8e3d-2e413f6b0065.png)

![image](https://user-images.githubusercontent.com/5259422/50944930-70831200-14cd-11e9-8669-d4f2cbe5c9d2.png)

![image](https://user-images.githubusercontent.com/5259422/50944971-9c9e9300-14cd-11e9-8aea-526f3e2dada6.png)


And the logs is that:
![image](https://user-images.githubusercontent.com/5259422/50945002-b2ac5380-14cd-11e9-8e69-e7bc5f2f86c9.png)

**Comment by langyan1022** [comment]
when I debug the oap server

I found that:
![image](https://user-images.githubusercontent.com/5259422/51157530-35ad1f80-18bb-11e9-951d-b30dc7f4e7e2.png)

when I enabled the hystrix of A service
the  spanDecorator.getRefsCount() is 0,
when I disabled the hystrix of A service

the  spanDecorator.getRefsCount() will > 0

Can you give me some other debugging suggestions?
Where should I start?

**Comment by langyan1022** [comment]
ok
thank you very much
