### ISSUE TITLE
Tomcat plugin All nodes intercepted are user nodes?

### ISSUE THREAD

**Issue by cdoewew** [apache/incubator-skywalking#2136]

**Comment by cdoewew** [comment]
The user node of the topology map is the node intercepted by tomcat?

**Comment by wu-sheng** [comment]
User node means incoming request. If you are observing a Tomcat, if HTTP request comes from browser or other no-agent service, then there is a user node generated.

**Comment by cdoewew** [comment]
If the HTTP request comes from a browser or other agentless service, a user node will be generated. But check the code: "if(Const.USER_SERVICE_ID == serviceId){
return userService;
} "But" USER_SERVICE_ID = 1 "Only set in the tomcat plugin?

**Comment by cdoewew** [comment]
I may be mistaken.

**Comment by wu-sheng** [comment]
> "But" USER_SERVICE_ID = 1 "Only set in the tomcat plugin?

No. It will be set when entry span without ref

**Comment by cdoewew** [comment]
A user node is generated if the HTTP request comes from a browser or other agentless service. That is to set this node "service_id = 1", ask where is the judgment logic written? I can not find it
