### ISSUE TITLE
 Beginning to remove expired metrics from the storage

### ISSUE THREAD

**Issue by liliang8858** [apache/incubator-skywalking#2143]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [0] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
![image](https://user-images.githubusercontent.com/38367404/50955033-1137f880-14f3-11e9-836a-e8b53b7c3da2.png)
![image](https://user-images.githubusercontent.com/38367404/50955058-1e54e780-14f3-11e9-941a-91f4992cda18.png)

But skywalking deletes the current one!!!!!!
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by liliang8858** [comment]
![image](https://user-images.githubusercontent.com/38367404/50955132-4a706880-14f3-11e9-99c2-8af0d0acb42a.png)

**Comment by wu-sheng** [comment]
Could you describe your question? I can't understand your question just from screenshots.

**Comment by wu-sheng** [comment]
This data deleting based on backend OS time, is your OS setting right?
