### ISSUE TITLE
dubbo 使用hessian协议，在UI拓扑图中不会形成调用链

### ISSUE THREAD

**Issue by nengtangbunengxiayiba** [apache/incubator-skywalking#2145]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
bug

___
### Question
- What do you want to know?
解决问题
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking version: 6.0.0-beta 
OS: Red Hat Enterprise Linux Server release 6.6 
JRE: 1.7.0_79
- Which company or project?

- What happen?
当dubbo服务provider 为hessian协议时，在ui的拓扑图中不能形成调用链，配置如下：
<dubbo:protocol  name="hessian" port="${dubbo.protocol.hessian.servlet.port}" server="servlet" contextpath="${dubbo.protocol.hessian.contextpath}"/>

当protocl声明为 dubbo时，则无此问题，配置如下：
<dubbo:protocol name="dubbo" port="${basecmm.queue.dubbo.protocol.port}" />
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
hessian协议时，形成的拓扑图如下：
![image](https://user-images.githubusercontent.com/45586711/50973742-925bb380-1524-11e9-9a00-618295fba5ae.png)

**Comment by wu-sheng** [comment]
English only. Hessian protocol doesn't provide header to propagate, we can't provide the plugin.

**Comment by nileblack** [comment]
> English only. Hessian protocol doesn't provide header to propagate, we can't provide the plugin.

hessian protocol is http based. maybe the root cause is dubbo invoke thread pool.

**Comment by nileblack** [comment]
It's dubbo bug, here is a PATCH, use skywalking plugin enhance to fix the bug.
https://github.com/nileblack/dubbo25-hessian-patch

**Comment by wu-sheng** [comment]
> It's dubbo bug, I make a PATCH, using skywalking plugin enhance to fix the bug.
> 
> https://github.com/nileblack/dubbo25-hessian-patch

Thank you so much to finally close this thread. Well done.
