### ISSUE TITLE
Why is my link broken into two?

### ISSUE THREAD

**Issue by liyongfa0311** [apache/incubator-skywalking#2149]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x]  Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Why is my link disconnected on the global topology map?
___
### Bug
- Which version of SkyWalking, OS and JRE?
  SkyWalking version 6.0.0-beta  OS centos6.5  JRE 1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

project-mysql and 10.102.131.151:10008 is  same service? but it shows two,resulting in incomplete access links

![1547217909 1](https://user-images.githubusercontent.com/30169249/51041184-55f78880-15f4-11e9-96c8-e9c94fdb5646.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If `10.102.131.151:10008` is already instrumented by agent, it means the rpc between project-e and project-mysql is using the protocol SkyWalking doesn't support.

We need inject header at project-e client side, and propagate the context to project-mysql side, powered by SkyWalking plugins. 

You need to find out whether your rpc lib is supported in our `supported-list`. If yes, maybe your scenario is not supported in our plugin. Then you could
1. Submit an issue to report that with demo codes to reproduce the issue.
1. Or try to find out why it is not supported, why propagation doesn't happen

**Comment by liyongfa0311** [comment]
but the link is normal in the 5.0.0-GA version,

**Comment by liyongfa0311** [comment]
Because I just used a simple skywalking demo, so I  used a simple feign call.

**Comment by wu-sheng** [comment]
I didn't remember we have any update about feign plugin. It should be same as 5.

**Comment by liyongfa0311** [comment]
I just commented out the feign.hystrix.enabled=true in the configuration file, and the link is fine.why？

**Comment by wu-sheng** [comment]
Maybe feign has another retry mechanism? I am not familiar with.

**Comment by liyongfa0311** [comment]
First of all, thank you for your patience, I tried 5.0.0-GA did not have this problem, and the call chain of the spring cloud config configuration center in the 5 version also  will be displayed, but the 6.0 version does not show the service call configuration center, the service is Replaced by the user, Displays the user call configuration center.

**Comment by wu-sheng** [comment]
Do you upgrade all agents to v6? Because in default mode, v6 agent doesn't accept v5 header, needs manually open.

**Comment by liyongfa0311** [comment]
I'm sure I'm using the v6 agent all the time; I tried the 6.0.0-Apache version again today.Project-e calling project-mysql is normal even with hystrix, But the access configuration center display is consistent with the 6.0.0-beta version，this is different from 5.0.0-GA.

**Comment by wu-sheng** [comment]
We have just fixed a serious bug, https://github.com/apache/incubator-skywalking/pull/2162 , which could lose trace and break topology. But I don't know whether it is related to yours. You could try.

In this kind of issue, we really need to locate the possible point, like @langyan1022 did in https://github.com/apache/incubator-skywalking/issues/2134 . Otherwise, my help will be limited.
