### ISSUE TITLE
Want to know which version of ES and JDK is fitting for skywalking 5.0 GA 

### ISSUE THREAD

**Issue by neilyolol** [apache/incubator-skywalking#2155]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- 

- [ 1] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I'd like to know which version of JDK/Elasticsearch is fitting for skywalking GA5.0.0 RC2 ?

___
### Bug
- Which version of SkyWalking, OS and JRE?
GA5.0.0 RC2
CentOS Linux release 7.4.1708 (Core)
OpenJDK Runtime Environment (build 1.8.0_151-b12)

- Which company or project?
For tomcat 7/8 monitoring 
- What happen?
Cause I can not find any data in UI and always appears "Variable 'applicationId' has coerced Null value for NonNull type 'ID!'" error . 

If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Jre version 8 and elasticsearch 5.5+(Not 6)
