### ISSUE TITLE
Request Error 500: http://127.0.0.1:8080/api/graphql

### ISSUE THREAD

**Issue by xiaour** [apache/incubator-skywalking#2164]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ Request Error 500: http://127.0.0.1:8080/api/graphql] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Request Error 500: http://127.0.0.1:8080/api/graphql
Es5.6.x
how to fix?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Which version of skywalking?
I think you don't follow our documents.

**Comment by guyukou** [comment]
+1
version: 6.0.0-beta

**Comment by wu-sheng** [comment]
Release version has verified by many companies. Please follow the document, and read the logs.
