### ISSUE TITLE
公司技术调研汇报后，反馈的几个问题!!!

### ISSUE THREAD

**Issue by hotbain** [apache/incubator-skywalking#2167]
1. 采样比能在服务运行中时，动态设置吗?
2. 放到ES的链路信息数据,怎么做归档？ 还是说永久保存
3. agent上报链路追踪信息的时候，是同步还是异步上传?如果同步的话 ， 会影响业务性能的.
4. A调用B,A设置的采样比为100% ,而B设置的采样比为1%，那么当A决定对某次请求进行采样时，B端在被A调用时，一定会被采样还是按照B服务设置的采样比,进行呢?简而言之，skywalking-agent是对请求设置的采样比 还是按照服务设置的采样比?
5. collector对分布式部署的支持是怎样的?

**Comment by hotbain** [comment]
@wu-sheng @WillemJiang @gmcdonald  能回答下不? 拜托

**Comment by wu-sheng** [comment]
English only.
