### ISSUE TITLE
trace graph is confused if it is complex

### ISSUE THREAD

**Issue by ywf4026** [apache/incubator-skywalking#2170]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
Requirement or improvement
- Please describe about your requirements or improvement suggestions.

![image](https://user-images.githubusercontent.com/3722641/51292197-f0b4f480-1a44-11e9-9a69-c81905c43be4.png)

The trace graph is confused. 
Can it be drawed clearly in next release?

**Comment by wu-sheng** [comment]
The GA is already including a trace view.

**Comment by ywf4026** [comment]
> The GA is already including a trace view.

Is 6.0.0beta including the trace view?

**Comment by wu-sheng** [comment]
No.
