### ISSUE TITLE
how the oap server connects to a security elasticsearch

### ISSUE THREAD

**Issue by mark0614** [apache/incubator-skywalking#2193]
I have a Elasticsearch server ,which provides xpack security. my oap service uses elasticsearch plugin to persist the apm data. I follow the official document to config the elasticsearch
`storage:
  elasticsearch:
  # set the namespace in elasticsearch
    clusterNodes: ${SW_STORAGE_ES_CLUSTER_NODES:elasticsearch:9200}
    indexShardsNumber: ${SW_STORAGE_ES_INDEX_SHARDS_NUMBER:2}
    indexReplicasNumber: ${SW_STORAGE_ES_INDEX_REPLICAS_NUMBER:0}
    # Batch process setting, refer to https://www.elastic.co/guide/en/elasticsearch/client/java-api/5.5/java-docs-bulk-processor.html
    bulkActions: ${SW_STORAGE_ES_BULK_ACTIONS:2000} # Execute the bulk every 2000 requests
    bulkSize: ${SW_STORAGE_ES_BULK_SIZE:20} # flush the bulk every 20mb
    flushInterval: ${SW_STORAGE_ES_FLUSH_INTERVAL:10} # flush the bulk every 10 seconds whatever the number of requests
    concurrentRequests: ${SW_STORAGE_ES_CONCURRENT_REQUESTS:2} # the number of concurrent requests`

In this configuration, how do i config the elasticsearch username and password

**Comment by wu-sheng** [comment]
xpack is not supported because of license issue(commercial license), you need to change source codes by yourself.

If you just use basic auth, read this, http://skywalking.apache.org/zh/blog/2019-01-02-skywalking-elasticsearch-basic.html

**Comment by mark0614** [comment]
Thanks, I got it!
