### ISSUE TITLE
httpClient-4.x-plugin throw MalformedURLException

### ISSUE THREAD

**Issue by donbing007** [apache/incubator-skywalking#2199]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ * ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- 5.0.0-GA 6.0.0-GA

- Which company or project?

- What happen?
org.apache.skywalking.apm.plugin.httpClient.v4.HttpClientExecuteInterceptor.java  [102]
`
String requestPath = new URL(uri).getPath();
`

But the uri is passed when the call is made, and there is no protocol.
`
String uri = httpRequest.getRequestLine().getUri();
`
`
String requestURI = getRequestURI(uri);
`
So an exception is thrown.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by donbing007** [comment]
Unit tests, die of data is "http://127.0.0.1:8080/test-web/test"

**Comment by wu-sheng** [comment]
These codes don't show exception. Could you be more clear when the exception happens?

```
String requestPath = new URL("http://127.0.0.1:8080/test-web/test").getPath();
```

**Comment by donbing007** [comment]
`String requestPath = new URL("/test-web/test").getPath();`

But that throws an exception.

`String uri = httpRequest.getRequestLine().getUri();`

uri is "/test-web/test", not "http://127.0.0.1:8080/ test - web/test" .

**Comment by wu-sheng** [comment]
Could you help about why you could request a service without `http://xxx:123`?

**Comment by ouronghui** [comment]
for example:

exists url: `http://httpbin.org/base64/SFRUUEJJTiBpcyBhd2Vzb21l`

Running the normal code:
```java
import org.apache.commons.io.IOUtils;
import org.apache.http.HttpEntity;
import org.apache.http.HttpHost;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;

import java.io.IOException;

public class HttpClientTest {
    public static void main(String[] args) throws IOException {
        CloseableHttpClient client = HttpClients.createDefault();
        CloseableHttpResponse httpResponse = client.execute(new HttpHost("httpbin.org", 8081), new HttpGet("/base64/SFRUUEJJTiBpcyBhd2Vzb21l"));
        HttpEntity entity = httpResponse.getEntity();
        String string = IOUtils.toString(entity.getContent());
        System.out.println(string);
    }
}
```

make breakpoint at `org.apache.http.impl.client.InternalHttpClient#doExecute` method , then debug `HttpClientTest.java`:
![plugin-httpclient-bug](https://user-images.githubusercontent.com/46365806/51813091-88d99600-22ef-11e9-9b52-16678a9f5c46.png)

the uri seem not contains protocol、host、port etc.., but  the [testCase code](https://github.com/apache/incubator-skywalking/blob/master/apm-sniffer/apm-sdk-plugin/httpClient-4.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/httpClient/v4/HttpClientExecuteInterceptorTest.java#L112) contain its.

so ， [HttpClientExecuteInterceptor#getRequestURI](https://github.com/apache/incubator-skywalking/blob/master/apm-sniffer/apm-sdk-plugin/httpClient-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/httpClient/v4/HttpClientExecuteInterceptor.java#L55) may be throw exception.

**Comment by wu-sheng** [comment]
Thanks for explanation of the usage. I will check and see how to solve this. @JaredTan95 could you try to handle this?

**Comment by wu-sheng** [comment]
@ouronghui I think the easiest way to fix is, try to check whether the string starts with http: or https: before do url parse. Could you try to send a pull request to fix?

**Comment by donbing007** [comment]
I fix this, [78c2327cc6](https://github.com/donbing007/incubator-skywalking/tree/78c2327cc649a5334de20b6cadd4b9f0bc24ce48)

**Comment by donbing007** [comment]
String uri = httpRequest.getRequestLine().getUri();

**Comment by JaredTan95** [comment]
fixed.
