### ISSUE TITLE
how to set the collector.backend_service in cluster mode

### ISSUE THREAD

**Issue by foxracle** [apache/incubator-skywalking#2202]
___
### Question
- What do you want to know?
After we setup a cluster of 3 collector backend by using consul, how to set  the collector.backend_service field in agent configuration. it should be set to the value of consul's hostPort list(10.0.0.1:8500,10.0.0.2:8500,10.0.0.3:8500) or collector backend's list(10.0.0.1:11800,10.0.0.2:11800,10.0.0.3:11800) or any other?

**Comment by wu-sheng** [comment]
The short answer is, Consul is backend cluster, not for the agent. Read document, https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/backend/backend-ui-setup.md#deploy-backend-and-ui

And agent you could put a backend address list, or set a load balance between them and agent set the load balance address.

**Comment by WinsonOne** [comment]
hi,how can I put a backend address list in agent? set the agent.config "collector.backend_service"?,use xxx.x.x.1:11800,xxx.x.x.2:11800 replace the default value?
