### ISSUE TITLE
what is the search rule of EndpointName in trace page?

### ISSUE THREAD

**Issue by BuQingYan** [apache/incubator-skywalking#2204]
# Environment：
- SkyWalking: 6.0.0-GA
- JDK：1.8
- OS：RedHat 6.5
# Summarize
In order to fulfill a requirement that search a trace message by my own transaction flow number.
I develop a skywalking plugin to create a localSpan, and set this localSpan's operationName  to my own flow number.

But, when I search the trace message in trace page by my own flow number, there is no correspond span display in search result. Moreover, the official okHttp plugin have the same problem.

So, I want to know what is the search rule of EndpointName in trace page?
# Detail
### Trace detail
![tracedetail](https://user-images.githubusercontent.com/41894492/51722193-8da00f00-208f-11e9-95d5-71f0c6b089eb.png)
### Display result
When I search the trace message by default search condition, there is only 3 span show, customized span(localSpan) and okHttp span(exitSpan）is missing.

But the localSpan of hystrix is display!
![display](https://user-images.githubusercontent.com/41894492/51722476-77468300-2090-11e9-8f2f-58fedcd31b2c.png)
### OkHttp span detail
![okhttpspandetail](https://user-images.githubusercontent.com/41894492/51722491-7f062780-2090-11e9-924d-e07300ba6c0a.png)

**Comment by wu-sheng** [comment]
Endpoint is from entry span, which means the entry of your segment. Other spans would be used in query condition.

**Comment by likeonechild** [comment]
"EndpointName" does not support fuzzy query
