### ISSUE TITLE
The UI cannot be accessed when a collector  hangs

### ISSUE THREAD

**Issue by liyongfa0311** [apache/incubator-skywalking#2208]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
 I have deployed the cluster, I found that after a collector is hanged, the UI is inaccessible.Does deploying cluster mode also require all nodes to survive? When I configure the listOfServers option of the webapp.yml file to be a partial node，"com.netflix.zuul.exception.ZuulException: Forwarding error" error occurs in the webapp.log file,Also, the agent's collector.backend_service parameter configures all nodes. ,Will the data be lost when some nodes are hanged ?
___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6..0.0-GA
OS :centos 7.3
JRE:1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
How to configure can guarantee that my program is still normal when a node hangs, including page access
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
UI is querying the collector. So collector break down, UI would work.

**Comment by liyongfa0311** [comment]
I know  UI would work.But collector break down, it will have 500 errors.I want to know how to configure to avoid this problem. And will  the data uploaded by the agent  be lost when the cluster is normal and some collector break down？

**Comment by wu-sheng** [comment]
If the data is in the process, definitely they are lost. The easy way, put a load balance between agent and backend cluster could help.
