### ISSUE TITLE
Docker 6.0Beta: Can't connect  the oap server

### ISSUE THREAD

**Issue by laziobird** [apache/incubator-skywalking#2216]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:12800 [/127.0.0.1] failed: Connection refused (Connection refused)
`docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                NAMES
9e10976f0a11        ui:1.0              "sh docker-entrypoin…"   11 minutes ago      Up 11 minutes       0.0.0.0:8080->8080/tcp                               blissful_thompson
be84cc9707cd        oap:1.0             "sh docker-entrypoin…"   16 minutes ago      Up 16 minutes       0.0.0.0:11800->11800/tcp, 0.0.0.0:12800->12800/tcp   keen_blackwell
`
I run all method beta,release for 5.x,6.x by mac,nothing is able to run, why?
                                                                                Thanks for your reply                                 

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by hanahmily** [comment]
You should try it: https://github.com/apache/incubator-skywalking-docker/tree/master/6/6.0-beta/compose.
