### ISSUE TITLE
Separate the GRPC binding address from the service discovery registry address

### ISSUE THREAD

**Issue by peng-yongsheng** [apache/incubator-skywalking#2217]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [X] Requirement
- [] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

Some load balance product provide by cloud platform must connect to the OAP server by loop back address(localhost/127.0.0.01). But OAP servers could not connect to each other by the loop back address.

**Comment by wu-sheng** [comment]
I agree we could provide separated settings, but I am not sure the way in your commits is good.

This is service discovery related issue, we should provide an optional setting in cluster implemention. Like in consul or zookeeper.

Add in core will make users confused.

**Comment by wu-sheng** [comment]
Such as adding `exposeHost` in consul and zookeeper.

**Comment by wu-sheng** [comment]
Another question, what lb requires localhost? And does this cause by some deployment way?

**Comment by wu-sheng** [comment]
Another reason I propose this is, in container cluster discovery implementation, this is harder to understand, such as k8s. Discovery is not the responsibility of core, right?

**Comment by wu-sheng** [comment]
Fixed.
