### ISSUE TITLE
realtime get client ip address when call a service

### ISSUE THREAD

**Issue by GreyZeng** [apache/incubator-skywalking#2219]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
I visit the SW dashboard : 
http://106.75.237.45:8080
I can not see the realtime trace info about clien ip address,
how could I  get the  client info when call a service agent by skywalking,

**Comment by wu-sheng** [comment]
What do you mean calling a service agent? What in trace depends on the plugins. If you want to add more things, you could contribute to the plugin and be clear why you need that. In tracing, you could ask for any info, we need to prove it is good and useful to have it in major repo and release.
