### ISSUE TITLE
the content of sha512 file of version 6.0.0 GA in the download page is not correct

### ISSUE THREAD

**Issue by foxracle** [apache/incubator-skywalking#2223]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0.0 GA
the sha512sum of the gz file that we downloaded(we have downloaded several time in several location to check the sha512sum) as follow:
xxxx@ops-001:~$ sha512sum apache-skywalking-apm-incubating-6.0.0-GA.tar.gz
a19a24b790f41b1d7f93547104fbfc70a1dc208d855026b0c4696d1991518a952d031b62a76bfa923394042757dc92aa87e6cac6502d015f30258e9959e393bf  apache-skywalking-apm-incubating-6.0.0-GA.tar.gz

**Comment by wu-sheng** [comment]
You are generating sha, not check. If you want to know how to recheck, read our release document.

**Comment by foxracle** [comment]
I got. In the [6.0.0 GA download page](http://skywalking.apache.org/downloads/), the sha512 link for Windows and Linux is reversed.

**Comment by wu-sheng** [comment]
Could you send a pr to fix the website?

**Comment by foxracle** [comment]
@JaredTan95  thanks. you are so quick that I have no chance to take the action ;)
