### ISSUE TITLE
 apm-trace-ignore-plugin.config doesn't work

### ISSUE THREAD

**Issue by Aaronyu111** [apache/incubator-skywalking#2230]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
-  Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
 When I upgraded to skywalking6.0.0-GA  from 6.0.0-beta, the apm-trace-ignore-plugin.config doesn't work(these urls still can be found in traces UI) , this config file is placed in /config folder and it's content as below:

trace.ignore_path=${SW_AGENT_TRACE_IGNORE_PATH:/eureka/**,/swagger-resources/**}

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking6.0.0-GA, CentOS JRE1.8.62

- Which company or project?
China Life(Oversea)

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
It is an optional plugin, do you active the plugin? We don't change any codes for that plugim in this release.

**Comment by zender-projects** [comment]
i use 8.1, it also dose not work

**Comment by Memento1990** [comment]
Maybe you can try this:
`trace.ignore_path=/eureka/**,/eureka/**/,/swagger-resources/**`
