### ISSUE TITLE
I think there is a problem with the alarm system

### ISSUE THREAD

**Issue by liyongfa0311** [apache/incubator-skywalking#2232]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
When the threshold number of times is reached, there is no timely alarm.When I look at the source code, I find that the checkAlarm method needs to judge whether the count has reached the  count of alarm-settings.yml file , and the isMatch method also needs to judge whether the count has reached the  count of alarm-settings.yml file, resulting in alarm delay or no alarm.
![image](https://user-images.githubusercontent.com/30169249/52159256-6a531080-26dc-11e9-9a6e-43862cb65b34.png)
![image](https://user-images.githubusercontent.com/30169249/52159259-9a021880-26dc-11e9-9cf1-f1436cf745c2.png) checkAlarm

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Why do you think this is a bug? Match count is part of the alarm system, to avoid false alarm in an unstable system. You coukd set the count to 1, if you don't want this.
