### ISSUE TITLE
JVM exited with invalid ELF header error while trying to hook the agent

### ISSUE THREAD

**Issue by sattishv** [apache/incubator-skywalking#2233]
Hi team,

Need your help in resolving an issue while trying to attach the agent inside a docker container
- [ ] Question or discussion
Not able to attach the skywalk agent to the java process . Got the below listed error

Launching a JVM...
ERROR  | wrapper  | 2019/02/07 04:36:29 | JVM exited while loading the application.
INFO   | jvm 1    | 2019/02/07 04:36:29 | Error occurred during initialization of VM
INFO   | jvm 1    | 2019/02/07 04:36:29 | Could not find agent library /opt/apache-skywalking-apm-incubating/agent/skywalking-agent.jar in absolute path, with error: /opt/apache-skywalking-apm-incubating/agent/skywalking-agent.jar: invalid ELF header (Possible cause: endianness mismatch)
___
### Question
Not able to attach the java agent to our application 

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0.0 GA , Linux ubuntu 14.04  and JDK 1.8 update 60
- Which company or project?
PayPal

**Comment by wu-sheng** [comment]
From the log, can't find the agent jar in your path. Do you add the agent to the target path?

**Comment by wu-sheng** [comment]
Agent.jar is a jar file, not a elf format file. I am a little confused about this error. Do you set the java command right?

**Comment by sattishv** [comment]
Hi Sheng,

Sorry its my bad that i  used JVM option -agentpath instead of -javaagent . I changed it and i could start the JVM without any issues

Sattish.

**Comment by wu-sheng** [comment]
Thanks for the feedback.
