### ISSUE TITLE
No trace been recorded in Dashboard

### ISSUE THREAD

**Issue by sattishv** [apache/incubator-skywalking#2234]
- [ ] Question or discussion
Agent got connected successfully with the collector. But we couldn't collect any traces all we could see is number of endpoints.

Snippets from Agent log:
DEBUG 2019-02-07 23:35:25:562 GRPCChannelManager :  Selected collector grpc service running, reconnect:false.
DEBUG 2019-02-07 23:35:25:584 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED.
DEBUG 2019-02-07 23:35:28:584 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED.
DEBUG 2019-02-07 23:35:31:584 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED.
![screen shot 2019-02-08 at 2 32 01 pm](https://user-images.githubusercontent.com/7449241/52468343-75abad80-2bae-11e9-8546-eb1f7e541a29.png)

DEBUG 2019-02-07 23:35:34:584 ServiceAndEndpointRegisterClient :  ServiceAndEndpointRegisterClient running, status:CONNECTED.

Snippet from skywalk-oap-server.log

2019-02-07 17:51:23,275 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer - 77 [pool-10-thread-1] INFO  [] - Metrics in minute dimension before 201902071621, are going to be removed.
2019-02-07 17:51:23,275 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer - 78 [pool-10-thread-1] INFO  [] - Metrics in hour dimension before 2019020605, are going to be removed.
2019-02-07 17:51:23,276 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer - 79 [pool-10-thread-1] INFO  [] - Metrics in day dimension before 20181224, are going to be removed.
2019-02-07 17:51:23,276 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer - 80 [pool-10-thread-1] INFO  [] - Metrics in month dimension before 201708, are going to be removed.
2019-02-07 17:56:23,257 - org.apache.skywalking.oap.server.core.storage.ttl.DataTTLKeeperTimer - 76 [pool-10-thread-1] INFO  [] - Beginning to remove expired metrics from the storage.

Agent config details used:
agent.service_name=UBDS
# Backend service addresses.
collector.backend_service=10.57.208.27:11800
___
### Question
How to get the trace details.

___
### Bug
- Which version of SkyWalking, OS and JRE?
* 6.0.0 GA , Linux ubuntu 14.04  and JDK 1.8 update 60
- Which company or project?
PayPal

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
The most likely, your under monitoring service vm have a different time or timezone settings with your browser. If it is docker, I assume UTC timezone, you could change timezone in time selector.

**Comment by sattishv** [comment]
Hi Wu,

Thanks for the response. I could see few traces when i move ahead of time. But i am not able to drill down from the root transaction. It displays HTTP request took 1280 ms but not able to drill down from there. Have attached the snapshot. Is any config been not set in our agent

Sattish.
![screen shot 2019-02-11 at 12 22 27 pm](https://user-images.githubusercontent.com/7449241/52549206-0923ef00-2df8-11e9-93ce-90349a664f53.png)

**Comment by wu-sheng** [comment]
What do you have in this HTTP request? Calling another RPC or database? 

Please read https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#supported-middlewares-frameworks-and-libraries to find out whether your RPC framework or db driver is supported?

If just Spring java bean, consider to use `Trace Spring beans` in [optional plugin](https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#optional-plugins)

**Comment by sattishv** [comment]
Hi we are calling another remote REST API service. I believe they use resteasy template

**Comment by wu-sheng** [comment]
resteasy templete is not in our supported list yet. You could follow [develop guide](https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#plugin-development-guide) to build a new plugin, and contribute to us.
Then you could dive in the trace.

**Comment by wu-sheng** [comment]
Meanwhile, you could submit a new issue for `support resteasy`. Maybe others have interests to contribute too.
