### ISSUE TITLE
protoc did not exit cleanly

### ISSUE THREAD

**Issue by xiaoni157** [apache/incubator-skywalking#2242]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [✅] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I compiled 5. X source code according to this document（https://github.com/apache/incubator-skywalking/blob/5.x/docs/cn/How-to-build-CN.md
）. When I executed this command（./mvnw clean package -DskipTests）, there was an error
![image](https://user-images.githubusercontent.com/24448049/52621749-08b45280-2ee3-11e9-9321-ca3e94917131.png)
![image](https://user-images.githubusercontent.com/24448049/52622094-ecfd7c00-2ee3-11e9-807a-bac1bf8a8e16.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking ：5.0.0-GA
jdk :1.8.0_144
OS:mac
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This issue, you should submit to protobuf or grpc, I don't think we can deal with it. Also I notice this issue just happens in protoc on Windows.

**Comment by xiaoni157** [comment]
But my operating system is a MAC, which means I can't compile the source code?

**Comment by wu-sheng** [comment]
You reboot the OS, I think it will work again. I don't know why this happens, haven't faced this.

**Comment by Kenny-Tang** [comment]
> But my operating system is a MAC, which means I can't compile the source code?

i fixed this use `sudo`  before the build command
