### ISSUE TITLE
Ssw Alarm

### ISSUE THREAD

**Issue by FreeManNumOne** [apache/incubator-skywalking#2250]
SW是否告警通知的功能，比如某个接口500的时间就触发一条告警通知的信息，邮件，短信，通知到相关人员，使用版本是apache-skywalking-apm-incubating-5.0.0

**Comment by wu-sheng** [comment]
6 SkyWalking supported. And English only.

**Comment by FreeManNumOne** [comment]
Ok  Tahnk You

**Comment by FreeManNumOne** [comment]
Okay thank you

**Comment by FreeManNumOne** [comment]
Does it mean 6.1 alarm functions?

**Comment by wu-sheng** [comment]
6.0already have.
