### ISSUE TITLE
mvnw compile -Dmaven.test.skip=true with error: 程序包org.apache.skywalking.apm.netwo rk.language.agent不存在

### ISSUE THREAD

**Issue by xjpfox** [apache/incubator-skywalking#2256]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ V] Question or discussion
- [V ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
IDEA 编译6.0.0源码包时报错，请大神们帮忙看一下。
mvnw compile -Dmaven.test.skip=true

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project server-core: Compilation failure: Compilation failure:
[ERROR] /D:/AIOPS/SW/skywalking/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/source/DetectPoint.java:[21,56] 程序包org.apache.skywalking.apm.netwo
rk.language.agent不存在
[ERROR] /D:/AIOPS/SW/skywalking/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/source/DetectPoint.java:[29,44] 找不到符号
[ERROR]   符号:   类 SpanType
[ERROR]   位置: 类 org.apache.skywalking.oap.server.core.source.DetectPoint
[ERROR] /D:/AIOPS/SW/skywalking/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/source/DetectPoint.java:[42,102] 程序包org.apache.skywalking.apm.netw
ork.common不存在
[ERROR] /D:/AIOPS/SW/skywalking/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/query/TraceQueryService.java:[23,1] 程序包org.apache.skywalking.apm.n
etwork.language.agent不存在
[ERROR] /D:/AIOPS/SW/skywalking/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/query/TraceQueryService.java:[24,1] 程序包org.apache.skywalking.apm.n
etwork.language.agent.v2不存在
[ERROR] /D:/AIOPS/SW/skywalking/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/query/TraceQueryService.java:[138,14] 找不到符号
[ERROR]   符号:   类 SpanObjectV2
[ERROR]   位置: 类 org.apache.skywalking.oap.server.core.query.TraceQueryService
[ERROR] /D:/AIOPS/SW/skywalking/incubator-skywalking/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/query/TraceQueryService.java:[243,14] 找不到符号
[ERROR]   符号:   类 SpanObject
[ERROR]   位置: 类 org.apache.skywalking.oap.server.core.query.TraceQueryService
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :server-core

**Comment by wu-sheng** [comment]
English only, and compiling issue is already in README, please follow. https://github.com/apache/incubator-skywalking/blob/master/docs/en/guides/How-to-build.md
