### ISSUE TITLE
app error occured while query with parameters on replication mode of mysql 6.x

### ISSUE THREAD

**Issue by dsc6636926** [apache/incubator-skywalking#2258]
i use replication mode on mysql 6.x ,when i do query with parameters app throw Exception such as
java.sql.SQLSyntaxErrorException
![image](https://user-images.githubusercontent.com/7552492/53005345-08c9ca80-346e-11e9-9510-8d5c0a6d915d.png)
then i found the reason here, I think statement.execute don't need any argument
https://github.com/apache/incubator-skywalking/blob/0929ff3453c3178db82a4b5399054900ab84bba0/apm-sniffer/apm-sdk-plugin/mysql-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/mysql/wrapper/PreparedStatementWrapper.java#L156

**Comment by wu-sheng** [comment]
Could you send a pull request foe this?

**Comment by dsc6636926** [comment]
i have send the pull request #2260

**Comment by wu-sheng** [comment]
Fixed.
