### ISSUE TITLE
skywalking的traceid是否支持定制，能否与Spring Cloud Sleuth的traceid关联

### ISSUE THREAD

**Issue by zsq1314** [apache/incubator-skywalking#2262]
### Question
请问skywalking的traceid是否支持定制，我的spring cloud项目其日志服务使用的Spring Cloud Sleuth的traceid 作为请求的跟踪。我想把Sleuth 的traceid作为skywalking的traceid关联起来，不知道能否定制，该怎么做，或者是否有其他解决方案可以把两者关联起来？

**Comment by wu-sheng** [comment]
English only. If you want to integrate two different systems, if need to learn by yourself.

**Comment by WengyXu** [comment]
可以将 skywalking 的 traceId 设置在Sleuth 的 Baggage中传递下来，在原日志同时打印 slueth 的 traceId 以及 在Baggage 中记录的 skywalking 的 traceId
