### ISSUE TITLE
bug:Span custom component name,data cannot be collected

### ISSUE THREAD

**Issue by louisjiang** [apache/incubator-skywalking#2264]
span.setComponent("componentName");

19-02-19 15:33:45,257 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 111 [grpc-default-executor-8] ERROR [] - null
java.lang.NullPointerException: null

**Comment by wu-sheng** [comment]
This is not a bug. You need to set component at backend setting file.
