### ISSUE TITLE
No mysql trace info

### ISSUE THREAD

**Issue by mbao** [apache/incubator-skywalking#2267]
### Bug
- Which version of SkyWalking, OS and JRE?
  1.8.2
 mac os
 1.8

- What happen?

there is no mysql(using Mybatis) trace info,only  sometimes the validation-query: SELECT 1
<img width="1318" alt="wx20190220-201936 2x" src="https://user-images.githubusercontent.com/866459/53091499-0b4f2180-354d-11e9-9a89-5df9b399c564.png">

**Comment by wu-sheng** [comment]
I think we can't tell why you don't. But you have the env to reproduce the error, learn how to do remote debug(cn blog, http://skywalking.apache.org/zh/blog/2019-01-24-skywalking-remote-debug.html), then debug the mysql plugin, you will the cause.

**Comment by mbao** [comment]
> I think we can't tell why you don't. But you have the env to reproduce the error, learn how to do remote debug(cn blog, http://skywalking.apache.org/zh/blog/2019-01-24-skywalking-remote-debug.html), then debug the mysql plugin, you will the cause.

change mysql-connector-java from version 8.0.11 to 5.1.47 ,mysql trace info is ok. Thanks

**Comment by wu-sheng** [comment]
Thanks for the feedback. MySQL 8 driver is not supported yet.
