### ISSUE TITLE
mysql  varchar(300) needed?

### ISSUE THREAD

**Issue by mbao** [apache/incubator-skywalking#2270]
### Question
- What do you want to know?

I want to use mysql for storage. I see that create table sql use "id VARCHAR(300)", and mysql characterset is utf8mb4, so 300 * 4 > 767 and mysql returns "Index column size too large. The maximum column size is 767 bytes."

I wonder if I can change 300 smaller?

**Comment by wu-sheng** [comment]
If you are using dynamic row size, I think we should be fine `varchar(300)`. Otherwise, may be a problem. The reason we choose 300 is, the endpoint may be long, which should be saved as id in endpoint_inventory table.

**Comment by mbao** [comment]
> If you are using dynamic row size, I think we should be fine `varchar(300)`. Otherwise, may be a problem. The reason we choose 300 is, the endpoint may be long, which should be saved as id in endpoint_inventory table.

get it, thanks.
"dynamic row size"  is set at creating table ,so I have to change the code or create table manually, right?

**Comment by wu-sheng** [comment]
`dynamic row size` could be set at Database size, or SQL statement, if I remember this right.

**Comment by chpiter** [comment]
+1

**Comment by xshans** [comment]
mysql 5.6 is not supported！
