### ISSUE TITLE
on the web UI overview module ，Errors in filling out rules 

### ISSUE THREAD

**Issue by 446690578** [apache/incubator-skywalking#2276]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0GA,CentOs7,jdk1.8

- What happen?
![image](https://user-images.githubusercontent.com/30078295/53215866-83246580-368d-11e9-8a75-15ae32ee192b.png)
as you can see ,The number two can be specified only 1xxxxx, and  number2 can be less than 1 ？

**Comment by wu-sheng** [comment]
@TinyAllen could you check this?

**Comment by TinyAllen** [comment]
@wu-sheng It has this phenomenon ,I will try to fix it these day.

**Comment by wu-sheng** [comment]
Good to know, thanks.

**Comment by JaredTan95** [comment]
fixed https://github.com/apache/incubator-skywalking-ui/pull/235
