### ISSUE TITLE
Can skywalking ClassMatch support regex classname match?

### ISSUE THREAD

**Issue by kuko126** [apache/incubator-skywalking#2279]
Is there a way to match classes using regex expression like spring aop does?

what I wanted
```
  protected ClassMatch enhanceClass() {
        return new RegClassMatch("com.xxx.*Dao");
  }
```
by the way, all the dao classes didn't implement a common parent class, so I cannot use `HierarchyMatch` to match all the dao classes.

**Comment by wu-sheng** [comment]
You could, just implement a new ClassMatch, which is based on byte-buddy API. I think we are also welcome you contribute this.

**Comment by kuko126** [comment]
I implement a classmatch , but no class was instrumented.
```
public class RegClassNameMatch implements IndirectMatch {

    private List<String> matchClassNames;
    private Pattern pattern;

    public RegClassNameMatch(String regex) {
        if (regex == null) {
            throw new IllegalArgumentException("reg class names is null");
        }
        pattern = Pattern.compile(regex);
        matchClassNames = new ArrayList<String>();
    }

    @Override
    public ElementMatcher.Junction buildJunction() {
        ElementMatcher.Junction junction = null;
        for (String name : matchClassNames) {
            if (junction == null) {
                junction = named(name);
            } else {
                junction = junction.or(named(name));
            }
        }
        return junction;
    }

    @Override
    public boolean isMatch(TypeDescription typeDescription) {
        Matcher matcher = pattern.matcher(typeDescription.getTypeName());
        if (matcher.matches()) {
            matchClassNames.add(typeDescription.getTypeName());
            return true;
        }
        return false;
    }
}
```

Skywalking execute `buildJunction` first and then `isMatch` , therefore `matchClassNames` is empty. In my guess, method `buildJunction()` is responsible to match the class(cause I didnot find doc on the method). 
Am I doing this right?
Any suggestion on how to implement `buildJunction()`?

**Comment by wu-sheng** [comment]
`buildJunction` take charge for this. You need to look byte-buddy document to understand how to build it.
