### ISSUE TITLE
does not support spring cloud gagteway

### ISSUE THREAD

**Issue by dean-hu** [apache/incubator-skywalking#2281]
Hello,
I found in use that skywalking could not collect data from the Spring Cloud Gateway project (Spring Cloud Gateway is a gateway service through which all requests are routed to specific microservices with an official address of Https://spring.io/projects/spring-cloud-gateway). But for the spring boot project, it can be collected.

**Comment by wu-sheng** [comment]
Yes. Duplicate requirement #2126 cc @ascrutae
