### ISSUE TITLE
Question: How to get all the listed plugins for skywalking?

### ISSUE THREAD

**Issue by ychandu** [apache/incubator-skywalking#2285]
Please answer these questions before submitting your issue.

I am looking for following plugins, may i no where can i get them

1. Spring bean plugin (incubator-skywalking/docs/en/setup/service-agent/java-agent/agent-optional-plugins/Spring-bean-plugins.md)
2. Lettuce
3. Rabbitmq 3.x can be supported ?
4. how can i specify the list of packages for instrumentation instead of all.

Thank you.

**Comment by wu-sheng** [comment]
Spring bean plugin is already in release package, in agent optional folder.

**Comment by wu-sheng** [comment]
Lettue is provided by #2152 . And will be included in 6.1.0

**Comment by wu-sheng** [comment]
Rabbitmq other version supported should be contributed by the community. I don't know any one is working on this.

**Comment by wu-sheng** [comment]
> 4\. how can i specify the list of packages for instrumentation instead of all.

See #2129 , some one wants to contribute a dynamic plugin based on config file and spel expressions.

**Comment by ychandu** [comment]
Spring bean plugin - renamed ?

**Comment by wu-sheng** [comment]
These are default plugins. Spring bean plugin in optional-plugins folder. You nerd to copy it manually.

Read https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#optional-plugins

**Comment by ychandu** [comment]
These are the three in optional plugins
apm-spring-annotation-plugin-6.0.0-GA.jar
apm-trace-ignore-plugin-6.0.0-GA.jar
apm-gson-2.x-plugin-6.0.0-GA.jar

you mean to say apm-spring-annotation-plugin-6.0.0-GA.jar is the one ?

**Comment by wu-sheng** [comment]
Yes. Could you send a pull request to fix document about this?
