### ISSUE TITLE
Is there a way to avoid call chain separation when ActiveMQ use pull mode？

### ISSUE THREAD

**Issue by LyricsYo** [apache/incubator-skywalking#2289]
- Why do you submit this issue?
- [x] Question or discussion
___
### Question
- What do you want to know?
Is there a way to avoid call chain separation when ActiveMQ use pull mode？

**Comment by wu-sheng** [comment]
Yes, you could. You need to use `@Trace` or another way to create a local span, scoping the MQ pull and other OP(s) as child spans.
