### ISSUE TITLE
Execute the docker-compose file and throw an error

### ISSUE THREAD

**Issue by xichengliudui** [apache/incubator-skywalking#2293]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
docker-compose up 
```
Pulling oap (skywalking/oap:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling oap (skywalking/oap:)...
ERROR: pull access denied for skywalking/oap, repository does not exist or may require 'docker login'
```
I've already executed docker login
___
### Bug
- Which version of SkyWalking, OS and JRE?
Now the master branch

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Direct execution: `docker-compose up`
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Rebuild the skywalking/oap image and wonder if the following skywalking/ UI image will have the same problem.

**Comment by wu-sheng** [comment]
Image has moved to ASF. You can't get the skywalking org.

**Comment by wu-sheng** [comment]
@hanahmily do we have fixed this in master?

**Comment by xichengliudui** [comment]
Should we change docker-compose?

**Comment by wu-sheng** [comment]
Yes. If master branch hasn't changed, could you send a pull request to fix this?

**Comment by xichengliudui** [comment]
Thank you. Let me try.
/assign @xichengliudui

**Comment by hanahmily** [comment]
the docker folder in main project is a convenient  way to test source code in docker. So user should issue `make build` to build image before running `docker-compose up`

**Comment by xichengliudui** [comment]
@hanahmily Which directory should I go to?

**Comment by hanahmily** [comment]
docker/

**Comment by xichengliudui** [comment]
```
[root@localhost docker]# clear
[root@localhost docker]# make build
cd /home/liudui/incubator-skywalking/docker/oap; \
cp ../../dist/apache-skywalking-apm-incubating-bin.tar.gz ./ ; \
docker build -t skywalking/oap:latest .
cp: cannot stat ‘../../dist/apache-skywalking-apm-incubating-bin.tar.gz’: No such file or directory
Sending build context to Docker daemon   7.68kB
Step 1/9 : FROM openjdk:8u181-jdk-stretch
 ---> 5f8e49b0a018
Step 2/9 : ENV DIST_NAME=apache-skywalking-apm-incubating-bin     JAVA_OPTS=" -Xms256M "
 ---> Using cache
 ---> 358f3a037515
Step 3/9 : COPY "$DIST_NAME.tar.gz" /
COPY failed: stat /var/lib/docker/tmp/docker-builder746677751/apache-skywalking-apm-incubating-bin.tar.gz: no such file or directory
make: *** [oap] Error 1
```
Can you provide a link to this file? Thank you very much

**Comment by hanahmily** [comment]
In the root folder of the project, issue `./mvnw install` to generate `/dist/apache-skywalking-apm-incubating-bin.tar.gz`. 
Or you can use official docker image `apache/skywalking-oap-server` instead of building project.

**Comment by hanahmily** [comment]
and `apache/skywalking-ui`

**Comment by fishinhouse** [comment]
Why do docker-compose still not solved, so it is very unfriendly for beginners!
