### ISSUE TITLE
In SkyWalkingAgent class, why ignore the classes which start with org.apache.logging.?

### ISSUE THREAD

**Issue by cngdkxw** [apache/incubator-skywalking#2294]
___
### Question
- In SkyWalkingAgent class, why ignore the classes which start with org.apache.logging.? Because that，I can‘t enhance org.apache.logging.log4j.ThreadContext. With enhancing ThreadContext, I want to print traceId and traceSegmentId to log in async mode.

**Comment by wu-sheng** [comment]
Could you do that by a standard log4j formater? We recommend you do like other application toolkit did.

**Comment by cngdkxw** [comment]
Ok, I try it.
