### ISSUE TITLE
how to clean buffer

### ISSUE THREAD

**Issue by tinytigerchaos** [apache/incubator-skywalking#2305]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
* it said One trace segment has been abandoned, cause by buffer is full
* but i cant find anyway to set the time interval for buffer cleaning
* is there any setting for cleaning buffer when buffer is full

***

thanks

**Comment by wu-sheng** [comment]
We have timer to delete. If don't work well, you could try to find the bug
