### ISSUE TITLE
Top 20 Slow Traces show issue

### ISSUE THREAD

**Issue by Stephen-sen** [apache/incubator-skywalking#2310]
How can I see the Top 20 Slow data before today,now I only can see today data.

**Comment by wu-sheng** [comment]
It doesn't release yet. From I known, that is based on time duration of whole page. No difference. Also, it is affected by record ttl, so could be deleted because you set ttl short for segment.

**Comment by Stephen-sen** [comment]
where I can set ttl ?

**Comment by wu-sheng** [comment]
application.yml in config. You should know, this could make you storage huge data, if you set ttl long.

**Comment by Stephen-sen** [comment]
is recordDataTTL?from application.yml I see it is 90 minute

**Comment by wu-sheng** [comment]
Yes. Should be.

**Comment by Stephen-sen** [comment]
thank you,I've verify it's really this palce
