### ISSUE TITLE
agent 6.0.0GA is not compatible with tomcat 7.0.42

### ISSUE THREAD

**Issue by ywf4026** [apache/incubator-skywalking#2316]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ √] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

application is starting, exception occurs
![image](https://user-images.githubusercontent.com/3722641/53780104-c0b2a980-3f3d-11e9-9b16-706880382e4d.png)

the cause may be:
tomcat version is low, it doesnt support jdk9 module feature

Is there any solution to  support this version(tomcat 7.0.42)?

thanks!

**Comment by wu-sheng** [comment]
@ascrutae Could you check why this module file exists in our agent jar? I think it shouldn't.

**Comment by mawennan** [comment]
hi , my tomcat have same error, 

jdk8
Server version: Apache Tomcat/7.0.68

![企业微信截图_20190312174932](https://user-images.githubusercontent.com/4082983/54250004-165e0600-457d-11e9-937f-6bc6e76c3ad4.png)

**Comment by wu-sheng** [comment]
@candyleer Look like we have an unnecessary file in agent.jar. Could you help on why this happens? How could we remove it? And whether the agent.jar is still working in JVM 9+ after we remove it.

**Comment by candyleer** [comment]
Got it! I will take a look at what has happened in tomcat7 and jdk9

**Comment by wu-sheng** [comment]
`module-info.class` looks like an unexpected file.

**Comment by candyleer** [comment]
I found the file ,located in `bytebuddy-1.9.2.jar`,I tracked the bytebuddy release,this file is released since `1.9.0`,and this file will cause error in only in tomcat 7.0.42.
![image](https://user-images.githubusercontent.com/11530760/54541362-be882a80-49d4-11e9-8b74-895d6124c377.png)

I have tried to remove this version file in my local env, it works for tomcat 7.0.42 .
but sad effect haven't been known.

**Comment by wu-sheng** [comment]
Would you want submit an issue on bytebuddy and involved me in? Let's find out why bytebuddy add it, I think he know much more about JVM than us.

**Comment by candyleer** [comment]
good idea

**Comment by wu-sheng** [comment]
@candyleer From https://github.com/raphw/byte-buddy/issues/629#issuecomment-474058254, I think the safe action we should take, should be that remove it directly. Agree?

**Comment by candyleer** [comment]
Yes,I agree with that, since bytebuddy do not  rely on this file and  it is not usable in most environment .

**Comment by wu-sheng** [comment]
@candyleer Please submit pull request to fix this.

**Comment by candyleer** [comment]
PR submitted
