### ISSUE TITLE
what's the difference of ServiceHandler and ReportServiceHandler?

### ISSUE THREAD

**Issue by sidawei** [apache/incubator-skywalking#2317]
- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
what's the difference of TraceSegmentServiceHandler and TraceSegmentReportServiceHandler， JVMMetricsServiceHandler and JVMMetricReportServiceHandler?

**Comment by wu-sheng** [comment]
There are for different versions of protocol. We have upgraded the protocol, because of concept changed. One for v5 protocol, the other for v6 protocl, started at 6.0.0-beta release.
