### ISSUE TITLE
Can not find the view memory and CPU usage menu

### ISSUE THREAD

**Issue by liqihua** [apache/incubator-skywalking#2320]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I can't find a menu to view memory and CPU usage in Web ui. Where can I see it?

**Comment by liqihua** [comment]
I can't find a menu to view memory and CPU usage in Web ui. Where can I see it?

**Comment by wu-sheng** [comment]
I assume you are a Chinese, right? Read this. http://skywalking.apache.org/zh/blog/2018-12-18-Apache-SkyWalking-5-0-UserGuide.html

**Comment by liqihua** [comment]
是的是的，我是Chinese哈哈哈，终于找到了，谢谢你，原来在右下角小小的点击 more details ... 6.0的文档里面找不到，原来在5.0的手册里面。谢谢！
