### ISSUE TITLE
skywalking6.0提供了告警服务，文档中写到可以自行接服务。我想自行接告警服务，或者接webhook，但是相关文档太少了，包括官方文档对告警服务的描述也是极少，恳请官方完善文档，对于告警模块追加说明

### ISSUE THREAD

**Issue by lvzhekang** [apache/incubator-skywalking#2323]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English is only supported. We provide document about alarm, 
https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/backend/backend-alarm.md

What do you need for a webhook description?

Some one has open source a project for a dingding notification. 
https://github.com/yanmaipian/dingding-notify-for-skywalking

**Comment by brentoncao** [comment]
After the replacement version can work, thanks

**Comment by weiqiang333** [comment]
I wrote a complicated one.
https://github.com/weiqiang333/infra-skywalking-webhook.git

**Comment by wu-sheng** [comment]
@weiqiang333 I think you should submit a blog to official website for introducing your project, and how to use it, it should be welcome.

**Comment by wu-sheng** [comment]
Submit a pull request to here, https://github.com/apache/skywalking-website
