### ISSUE TITLE
OpenSkywalking-> SkyAPM

### ISSUE THREAD

**Issue by JaredTan95** [apache/incubator-skywalking#2326]
___
### Requirement or improvement
https://github.com/apache/incubator-skywalking/blob/master/docs/en/guides/storage-extention.md#redistribution-with-new-storage-implementation

` OpenSkywalking/SkyWalking-With-Es5x-Storage` ---> ` SkyAPM/SkyWalking-With-Es5x-Storage`

**Comment by wu-sheng** [comment]
Send your PR directly :) This doesn't need discussion.
