### ISSUE TITLE
Separation the remote gRPC server from the receiver gRPC server.

### ISSUE THREAD

**Issue by peng-yongsheng** [apache/incubator-skywalking#2327]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X] Feature or performance improvement
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

Receiver gRPC server is used to receive trace message from the agent. The remote gRPC server is used to receive L1 aggregated metric. But now they are mixed up. We don't known how high their respective loads are and whether they will interfere with each other.

**Comment by wu-sheng** [comment]
Do you plan to send this server setting optional or required one?

**Comment by peng-yongsheng** [comment]
Optional, just for advanced user.

**Comment by peng-yongsheng** [comment]
Done
