### ISSUE TITLE
gateway hystrix trace info error

### ISSUE THREAD

**Issue by mbao** [apache/incubator-skywalking#2330]
- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?

I know that gateway is not supported. But I wonder why gateway hystrix into  trace twice.
When debugging, I found that HystrixCommandRunInterceptor runs twice, one for HttpClientRibbonCommand and another for AbstractRibbonCommand.
Can someone explain it? Thanks.
![wx20190307-193651](https://user-images.githubusercontent.com/866459/53954201-79c8dd80-4110-11e9-93b5-6418ebb84442.png)
<img width="564" alt="wx20190307-193756 2x" src="https://user-images.githubusercontent.com/866459/53954215-8a795380-4110-11e9-9e43-04b425bf4119.png">

**Comment by wu-sheng** [comment]
First of all, how codes run based on how they write. Tracing agent has no magic, just show you the code path. If it says, it invoke twice, it most likely invokes twice. 

And your debug confirm that, what is your question? We can't tell why all codes wrote in this way.

**Comment by mbao** [comment]
> First of all, how codes run based on how they write. Tracing agent has no magic, just show you the code path. If it says, it invoke twice, it most likely invokes twice.
> 
> And your debug confirm that, what is your question? We can't tell why all codes wrote in this way.

the run method of HttpClientRibbonCommand is called once, but the beforeMethod of HystrixCommandRunInterceptor is called twice.  
Maybe I don't express clearly, sorry.

**Comment by wu-sheng** [comment]
That is mutiple instrumented, means there are instrument definitions, which match this single one class.
