### ISSUE TITLE
ClassNotFoundException net.bytebuddy.matcher.ElementMatcher

### ISSUE THREAD

**Issue by sunshinebaby00** [apache/incubator-skywalking#2337]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
-  Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I write a plugin of my own, bu it throw a ClassNotFoundException 
![image](https://user-images.githubusercontent.com/9410296/54065813-a5f37400-4260-11e9-8ecf-baff73a7ef3a.png)

![image](https://user-images.githubusercontent.com/9410296/54065726-f74f3380-425f-11e9-9540-7c1a95df04d4.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking 6.1
jdk 8
- Which company or project?
test project
- What happen?

I write a plugin of my own, bu it throw a ClassNotFoundException 
![image](https://user-images.githubusercontent.com/9410296/54065813-a5f37400-4260-11e9-8ecf-baff73a7ef3a.png)

![image](https://user-images.githubusercontent.com/9410296/54065726-f74f3380-425f-11e9-9540-7c1a95df04d4.png)

I debug other plugins.The classloader load class from dependences and it works well。
![image](https://user-images.githubusercontent.com/9410296/54065754-249be180-4260-11e9-8c27-7130491df6e4.png)
![image](https://user-images.githubusercontent.com/9410296/54065833-f4087780-4260-11e9-879d-a28e48ef732b.png)
I do not kown what make the diffrence and how can i fix it?

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
You use the wrong way package agent jar. Please follow SkyWalking's plugin module settings.
