### ISSUE TITLE
[Bug] Login button is still disabled after failure

### ISSUE THREAD

**Issue by kezhenxu94** [apache/incubator-skywalking#2338]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Bug
- Which version of SkyWalking, OS and JRE?
latest version on master branch(perhaps all versions), all OS and JRE

- What happen?
Start the frontend(UI) only, and try to login, after failure, the login button is still in loading mode
![image](https://user-images.githubusercontent.com/15965696/54072268-77eb4f80-42b3-11e9-8c4a-36aa094a0b4c.png)

___
### Requirement or improvement
Login button should be enable after failure

**Comment by wu-sheng** [comment]
It is a bug for sure. 😄 Welcome fix always. But notice, RocketBot UI is trying to move in as primary UI. I am working with @TinyAllen @JaredTan95 , to make that true. If we make it, the current UI should be abandoned.

**Comment by kezhenxu94** [comment]
I think this is a rarely-appeared bug and since the RocketBot UI is going to replace the current UI, I'll close this for now
