### ISSUE TITLE
Force fully qualified endpoint names

### ISSUE THREAD

**Issue by BFergerson** [apache/incubator-skywalking#2342]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I am working on an open-source programming assistant ([Source++](https://github.com/codebrig/source)) and I'm using SkyWalking as the flagship APM for the project. So far SkyWalking performs very well (so great job :P). However, I am running into an issue that I do not believe I can solve in my project so I'm willing to contribute these changes directly to SkyWalking.

Essentially SkyWalking can't tell the difference between these two endpoints:
```java
@RequestMapping(value = "/", method = RequestMethod.GET)
public Account getAccountById() {
    System.out.println("did get");
}

@RequestMapping(value = "/", method = RequestMethod.POST)
public Account createAccountById() {
    System.out.println("did post");
}
```
It will create a single endpoint for both of these methods even though they are distinct endpoints with distinct purposes. Looking at the traces in the SkyWalking UI I can further see that SkyWalking is merely merging them together. The endpoint `/` will contain traces for `getAccountById` and `createAccountById`.

The way that makes the most sense to me for solving this issue is to add a configuration option (like `Config.Agent.FORCE_FULLY_QUALIFIED_ENDPOINT_NAMES`) which would skip setting the endpoint name of `/` and instead set them as `ClassName.getAccountById()` and `Classname.createAccountById()`.

I've tested this out locally and modified the `org.apache.skywalking.apm.plugin.spring.mvc.commons.interceptor.AbstractMethodInterceptor.beforeMethod()` method to use the fully qualified method name and it works like I expected. You will end up with more endpoints in SkyWalking but my project automatically searches through the endpoints SkyWalking reports so I don't believe having tons of endpoints will be an issue for me.

Is this something SkyWalking would consider accepting if I created a pull request? Is there a different way I should be approaching this problem?

### Which version of SkyWalking, OS and JRE?
SkyWalking 6.0.0 GA, Ubuntu 18.04, Java 8

**Comment by wu-sheng** [comment]
This change should be easy, I want to know,  do you think, does `GET/` and `POST/` make more sense? Because I think the basic issue is how to make get/post difference. If YES, then I will support to make this as default, rather than using `Config.Agent.FORCE_FULLY_QUALIFIED_ENDPOINT_NAMES` setting.

> You will end up with more endpoints in SkyWalking

This is fine, I think. Millions of endpoints are supported in production env.

We are using the class name in some RPC frameworks, such as gRPC, Dubbo, etc. `Config.Agent.FORCE_FULLY_QUALIFIED_ENDPOINT_NAMES` looks like should be named as `Config.Plugin.SpringMVC.USE_CLASSNAME_AS_ENDPOINT_NAME`(so something like this)

**Comment by BFergerson** [comment]
@wu-sheng, thanks for the quick response. I do just want to tell the difference between the `GET` and `POST`. Having the request method type in the operation name would probably have been sufficient but I'm not sure if that's the only scenario that exists that could create a situation like this. I can implement both if you want but I primarily would like the qualified name as the endpoint. As you say, other services use the qualified name as the endpoint and that's what I've been using for those.

I completely missed the `Config.Plugin` section. That's a better place for this configuration, agreed. I'm thinking the name of `Config.Plugin.SpringMVC.USE_QUALIFIED_NAME_AS_ENDPOINT_NAME`. These are small changes so I'll see what you think about adding the request method in the endpoint name before opening a pull request.

**Comment by wu-sheng** [comment]
If the qualified name stays in optional, I am totally OK, also the GET/POST should be in operation name to ease some similar cases like yours.

> I'm thinking the name of Config.Plugin.SpringMVC.USE_QUALIFIED_NAME_AS_ENDPOINT_NAME

I think the name is fine, just please add this to agent document and have a clear description about what it is for.

**Comment by wu-sheng** [comment]
Also, in the PR, please notice, you should provide a pr in https://github.com/SkyAPMTest/agent-auto-integration-testcases too. Add new test scenario about `spring-with-qualified-op-name`, set the `USE_QUALIFIED_NAME_AS_ENDPOINT_NAME` to true through `-D` script. Also, You don't need all versions to recheck, just one or two should be enough.

**Comment by BFergerson** [comment]
@wu-sheng, would you mind taking a look at https://github.com/SkyAPMTest/agent-auto-integration-testcases/issues/54?

Also, when you say to create a new test scenario I'm guessing you mean another of those top level folders? Like https://github.com/SkyAPMTest/agent-auto-integration-testcases/tree/master/spring-scenario but instead https://github.com/SkyAPMTest/agent-auto-integration-testcases/tree/master/spring-with-qualified-op-name? I'm also a bit confused on which script I would be placing the `-D` option on.

**Comment by wu-sheng** [comment]
Yes. Another top level folder. For -D, I mean, the default setting of qualifiedname as endpoint is false, right? You need a way to open it in testing. SkyWalking could do settings in agent.conf and -D override through command argument. 

@ascrutae Is the agent.conf could be set in test repo? If Yes, please provide the way, thankd.

**Comment by ascrutae** [comment]
@BFergerson Just follow [this documents](https://github.com/SkyAPMTest/agent-auto-integration-testcases/blob/master/docs/how-to-write-a-plugin-testcase.md#run-test-cases) and please ping me if you have any question about how to run test cases.

**Comment by BFergerson** [comment]
@wu-sheng, I think another reason I originally went for the `Config.Agent.USE_QUALIFIED_NAME_AS_ENDPOINT_NAME` was because ideally this functionality could also be used with SkyWalking's `@Trace` annotations. Instead, I've added two configuration values `Config.Plugin.SpringMVC.USE_QUALIFIED_NAME_AS_ENDPOINT_NAME` and `Config.Plugin.Toolkit.USE_QUALIFIED_NAME_AS_ENDPOINT_NAME`.

Curious your thoughts here. Would you also be willing to add this to `@Trace` and if so, can it be one configuration value?

**Comment by wu-sheng** [comment]
For different plugin/toolkit, I prefer to use two configuration values, because it is more clear. But one thing needs to be clear, only SpringMVC's operation name would be endpoint name because it is an entry span. For `@Trace`, it is just an operation name.

**Comment by wu-sheng** [comment]
Provided.

**Comment by wu-sheng** [comment]
@BFergerson 

> I am working on an open-source programming assistant (Source++) and I'm using SkyWalking as the flagship APM for the project. 

Based on this, could you or I add CodeBrig Corp. and source++ project into the powered by page and user wall? I think this is an open case now, as it is described in GitHub.
