### ISSUE TITLE
load balance between agent and backend?

### ISSUE THREAD

**Issue by ywf4026** [apache/incubator-skywalking#2346]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

I want to put a load balance between agent and backend. I use nginx as load balance(roundrobin), but I found 100% requests were received by only one backend server.
Here is my nginx config

`
stream {

    upstream backend {

        server 127.0.0.1:11803            max_fails=0 fail_timeout=0s;
        server 127.0.0.1:11805            max_fails=0 fail_timeout=0s;
    }   

    server {
        listen 11808;
        proxy_connect_timeout 1s; 
        proxy_timeout 3s; 
        proxy_pass backend;
    }   
}
`

Here is Agent config:
collector.backend_service=${SW_AGENT_COLLECTOR_BACKEND_SERVICES:10.85.125.2:11808}

Is there any problem with my config?

I guess (may be wrong) 
the connection between agent and collector will not be changed util the network is error.
anyway, the connetion between agent and collector is only one, if so, which config param is used to set the connection value?

ps: is there any suggestion to put a load balance between agent and backend, thanks!

**Comment by wu-sheng** [comment]
This is how nginx use, not skywalking. The protocolis gRPC, HTTP2.

**Comment by Lovnx** [comment]
@ywf4026 do you solve this problem?

**Comment by Lovnx** [comment]
https://github.com/apache/skywalking/issues/4367
