### ISSUE TITLE
java  agent  tomcat

### ISSUE THREAD

**Issue by Hylijia** [apache/incubator-skywalking#2354]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by Hylijia** [comment]
13-Mar-2019 14:14:50.596 严重 [localhost-startStop-1] org.apache.catalina.startup.ContextConfig.processAnnotationsJar Unable to process Jar entry [META-INF/versions/9/module-info.class] from Jar [file:/opt/apache-skywalking-apm-incubating/agent/skywalking-agent.jar] for annotations
 org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
        at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97)
        at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:54)

**Comment by wu-sheng** [comment]
Nothing in this issue.

**Comment by wu-sheng** [comment]
Ref to #2316

**Comment by wu-sheng** [comment]
You could remove this file manually from jar file.

**Comment by Hylijia** [comment]
solved！ thank you！



李嘉
北京华宇信息技术有限公司

 
From: 吴晟 Wu Sheng
Date: 2019-03-13 14:49
To: apache/incubator-skywalking
CC: Hylijia; Author
Subject: Re: [apache/incubator-skywalking] java agent tomcat (#2354)
You could remove this file manually from jar file.
