### ISSUE TITLE
什么时候支持sqlserver啊？

### ISSUE THREAD

**Issue by pmq5205209** [apache/incubator-skywalking#2356]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only. Ref #2340 You could contribute plugin by yourself or wait others to do. Right now, I don't know no one is working on this.
