### ISSUE TITLE
skywalking cannot pass build in Intellij IDEA

### ISSUE THREAD

**Issue by guyukou** [apache/incubator-skywalking#2357]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Compile failed in Intellij IDEA due to imports resolution error in MetricServiceGRPCHandler.java, I resolve this by marking grpc-java and java folders in oap-server/server-receiver-plugin/envoy-metrics-receiver-plugin/target/generated-sources/protobuf as [Generated source Root]. 
It's suggested an update to How-to-build.md
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Could you work on a pull request to add this?
