### ISSUE TITLE
trace not work once the agent trace buffer was full

### ISSUE THREAD

**Issue by zhang98722** [apache/incubator-skywalking#2363]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion

once the agent meet the buffer limit and starting abandon segment like:

> TraceSegmentServiceClient :  One trace segment has been abandoned, cause by buffer is full. 

then all future data sent to oap is missing,even the log said it already send to oap:

>TraceSegmentServiceClient :  3748 trace segments have been sent to collector.

you cant find the data anywhere in the webui,all data submited , include trace, jvm metrics,,is gone,and this situation would last until the oap restarted

**Comment by wu-sheng** [comment]
> once the agent meet the buffer limit and starting abandon segment like:

This is our design, it should work in this way, otherwise, you will be facing memory leak and crash at this moment. Nothing about your further descriptions

Your further descriptions are hard to diagnose from your simple words. You really need to dig more in oap.log, oap telemetry, elasticsearch log and elasticsearch monitoring. You will find clue there.

**Comment by zhang98722** [comment]
> > once the agent meet the buffer limit and starting abandon segment like:
> 
> This is our design, it should work in this way, otherwise, you will be facing memory leak and crash at this moment. Nothing about your further descriptions
> 
> Your further descriptions are hard to diagnose from your simple words. You really need to dig more in oap.log, oap telemetry, elasticsearch log and elasticsearch monitoring. You will find clue there.

i checked,oap,es log is all right,and data confirmed in es
but you cant get anything through webapp ui

**Comment by wu-sheng** [comment]
If data is in ES, there should be never wrong. Query is very easy, you could simple debug by yourself. Focus on time bucket(including time zone) and service/instance/endpoint IDs.
