### ISSUE TITLE
Finding  out  error span stack pop

### ISSUE THREAD

**Issue by mbao** [apache/incubator-skywalking#2371]
- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?

Using skywalking  there is no more trace info after a short time and  I see "More than {} spans required to create" is my log.  I think there is error span stack pop, so after that there is no trace info for method running in the same thread. I don't have idea for  finding it out. Any suggestion ?
___

**Comment by wu-sheng** [comment]
`More than {} spans required to create` happens in two case.
1. The normal one, you create too many span(300 by default) in one request, so the agent core will ignore others.
1. The unnormal one, one(or more) of you plugin doesn't work well. One may create span, but don't close it right. So, the trace context can't be finished. You need to dig more about the plugin you are using.

I think you are facing (2)
