### ISSUE TITLE
trace search with dynamic endpoint name

### ISSUE THREAD

**Issue by guyukou** [apache/incubator-skywalking#2372]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
According to what I know, as in the 'Trace' perspective, 'EndpointName' query condition will exact match the input value with index field endpoint_name. What can I do to support a SQL like query, for instance, the endpoint_name field has value '/api/v1/user/name' in the segment index, however when I input '/backend/api/v1/user/name', search will still match the above record.
(For simplicity, The input value is like %endpoint_name)
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
If you are using ElasticSearch, `matchPhraseQuery` will separate words by `/`. So this endpoint will be matched.
