### ISSUE TITLE
trace data absent

### ISSUE THREAD

**Issue by guyukou** [apache/incubator-skywalking#2374]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
I build SkyWalking locally based on master branch, in which the latest commit on 2019/3/13.
OS: CentOS release 6.8 (Final)
JRE: 1.8
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
I set up my agent with 100% sample, however，after several times of API invoke, I cannot search out related trace yet. I don't know how to inspect to find out the solution.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
First of all, do your backend work well? Could you see service and service instance in your UI or index(service_inventory).

**Comment by guyukou** [comment]
OAPserver runs very well, 200+ services has been connected, and trace perspective, most recent trace records can be searched out.
but some specific service related traces were not the same case while service_inventory and endpoint_inventory indexes both contains the specific service records.
Besides these, is agent trace report logs available?
