### ISSUE TITLE
when supports jdk 11

### ISSUE THREAD

**Issue by fluffywar** [apache/incubator-skywalking#2379]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
什么时候支持 jdk 11

docker jdk 8 内存识别有问题
而11是 LTS版本
公司目前用的是11
___

**Comment by wu-sheng** [comment]
We don't know yet. JDK 11 is very new, I am not sure whether it is compatible or not.

**Comment by wu-sheng** [comment]
If you want to try JDK 11, you should be carefully.
