### ISSUE TITLE
oap docker file error

### ISSUE THREAD

**Issue by ywf4026** [apache/incubator-skywalking#2381]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

https://github.com/apache/incubator-skywalking-docker/blob/master/6/6.0-GA/oap/Dockerfile

the dockerfile may have an error here.
COPY docker-entrypoint.sh .

![image](https://user-images.githubusercontent.com/3722641/54595937-9f3ddb80-4a6e-11e9-99fc-dc58440c37df.png)

change to "COPY docker-entrypoint.sh ./ "  then build image ok

Is this a problem?

**Comment by wu-sheng** [comment]
@hanahmily issue?

**Comment by hanahmily** [comment]
works for macOS. Which os do you use to build the image?
By the way you don't need to build this by yourself more than pull the image from Dockerhub.

**Comment by ywf4026** [comment]
> works for macOS. Which os do you use to build the image?
> By the way you don't need to build this by yourself more than pull the image from Dockerhub.

@hanahmily 
CentOs 

The storage is default h2 in the image from Dockerhub. I want to change it to ES, so I must buid it by myself

**Comment by wu-sheng** [comment]
I think you should take our k8s config as an example, https://github.com/apache/incubator-skywalking-kubernetes/blob/master/6/6.0.0-GA/oap/03-deployment.yml#L55-L61

You could mount the volume to inject the config. The config files in k8s are here, https://github.com/apache/incubator-skywalking-kubernetes/blob/master/6/6.0.0-GA/oap/01-config.yml
