### ISSUE TITLE
How to set the expiration time of es data

### ISSUE THREAD

**Issue by xiaoni157** [apache/incubator-skywalking#2388]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
When I modify the collector's application.xml file, does changing the value of traceDataTTL mean that the es data is also deleted, rather than just that the UI is filtered
If I want to set the expiration time to one month, how do I set it?
![image](https://user-images.githubusercontent.com/24448049/54685217-3c714080-4b51-11e9-87e3-0606409b0292.png)

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking ：5.0.0-GA
jdk :1.8.0_144
OS:mac
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
This is the data deleting config. The oap would really delete the data.

**Comment by xiaoni157** [comment]
When I want to keep a month's worth of data, can I set it this way?
![image](https://user-images.githubusercontent.com/24448049/54730313-20a68280-4bc3-11e9-9d56-ceb5f888dd58.png)

**Comment by wu-sheng** [comment]
Yes.

**Comment by xiaoni157** [comment]
I set it up like this, but there's still no data on the UI from 90 minutes ago.Es is version 5.6.8
![image](https://user-images.githubusercontent.com/24448049/56009945-3582bb80-5d14-11e9-842b-7af8c61b9a65.png)

**Comment by wu-sheng** [comment]
What do you mean `no data on the UI from 90 minutes ago`? I am a little confused.

**Comment by xiaoni157** [comment]
I want to keep one month's data. I set it as normal as above in application.xml, but the call chain is still only 90 minutes' data

**Comment by xiaoni157** [comment]
just like this
![image](https://user-images.githubusercontent.com/24448049/56010856-e5a5f380-5d17-11e9-951b-e841433b0c84.png)

**Comment by wu-sheng** [comment]
> I want to keep one month's data. I set it as normal as above in application.xml, but the call chain is still only 90 minutes' data

We keep TTL in 7 days, and look like it is right. I think you need to verify the delete by yourself. By the way, we are using 6.0.0-GA

**Comment by xiaoni157** [comment]
How to configure 5.0.0-GA version for one month?
skywalking: 5.0.0-GA
es:aliyun 5.6.8
It looks right.
![image](https://user-images.githubusercontent.com/24448049/56015520-e779b200-5d2b-11e9-8870-7f9b4a1e6093.png)

**Comment by wu-sheng** [comment]
It should be same. Verify data in ES, make sure really delete incorrectly.
