### ISSUE TITLE
SmartSql provider setting is not complete

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#2390]
Ref #2387 

We have four component-libraries.yaml for different purposes, need to sync the change to all of them. Also, should the mapping be there?

**Comment by wu-sheng** [comment]
FYI @Ahoo-Wang

**Comment by Ahoo-Wang** [comment]
@wu-sheng ok. I will pr this later.

**Comment by Ahoo-Wang** [comment]
@wu-sheng I just find three component-libraries.yaml

oap-server\server-starter\src\main\resources\component-libraries.yml
oap-server\server-core\src\test\resources\component-libraries.yml
docker\config\component-libraries.yml

Can you help me find another one?

**Comment by wu-sheng** [comment]
Yes. Only 3.
