### ISSUE TITLE
Why JDBC4Connection implements EnhancedInstance?

### ISSUE THREAD

**Issue by guyukou** [apache/incubator-skywalking#2396]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Hello, I have a question about JDBC plugin. In our project, we introduce a third-party datasource management dependency, in which they proxy `com.mysql.jdbc.JDBC4Connection` then cause an `java.lang.ClassCastException` due to the proxy class's cast to `org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance` failure, at org.apache.skywalking.apm.plugin.jdbc.JDBCDriverInterceptor.afterMethod(JDBCDriverInterceptor.java:45).
I found that only com.mysql.jdbc.Driver implements `EnhancedInstance` at [code](https://github.com/apache/incubator-skywalking/blob/master/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/ClassEnhancePluginDefine.java#L119), how does `com.mysql.jdbc.JDBC4Connection` also implements `EnhancedInstance`? 
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
I don't know what happens in your `datasource management dependency`. But in my mind, the connection needs to be enhanced, because when trace happens, it will obtain the connection info(jdbc url, username...) from it, but the connection doesn't open method for this.

**Comment by guyukou** [comment]
> I don't know what happens in your `datasource management dependency`. But in my mind, the connection needs to be enhanced, because when trace happens, it will obtain the connection info(jdbc url, username...) from it, but the connection doesn't open method for this.

Thank you for your reply, more than that, I want to know the place where JDBC4Connection is identified to be enhanced, could you offer a guide.

**Comment by wu-sheng** [comment]
@dsc6636926 @ascrutae Do you know? I don't know this detail

**Comment by ascrutae** [comment]
@guyukou Which driver class of MySQL JDBC did you used in your project?  if the driver class is not in enhance list, the connection object that the driver object return will not an `EnhancedInstance` object.

**Comment by guyukou** [comment]
> @guyukou Which driver class of MySQL JDBC did you used in your project? if the driver class is not in enhance list, the connection object that the driver object return will not an `EnhancedInstance` object.

Indeed, we use the `com.mysql.jdbc.Driver`, however, the connection pool lib is one that encapsulates alibaba druid and set a proxy to JDBC4Connection.

**Comment by dsc6636926** [comment]
Which version of SkyWalking do you use? JDBC4Connection is subclass of com.mysql.jdbc.ConnectionImpl , and com.mysql.jdbc.ConnectionImpl has been enhanced . so JDBC4Connection is enhanced too. can you tell me the exactly problem you have met?

**Comment by ascrutae** [comment]
If this JDBC4Connection is a proxy object, it could not be enhanced by Skywalking.

**Comment by guyukou** [comment]
![image](https://user-images.githubusercontent.com/15632270/54808966-c5f15180-4cbc-11e9-8edd-63934ae844ab.png)
This is a screenshot from my local debug env, and it will cause a ClassCastException as beblow.
![image](https://user-images.githubusercontent.com/15632270/54809014-f0dba580-4cbc-11e9-956a-d45a0f93b77b.png)

**Comment by dsc6636926** [comment]
this issue looks like #1947 ,and i found you use LoadBalanced mode,this version of skywalking is not support multihost mode on mysqlconnector-5.x. it will be fixed on next version.
on multihost mode, Connection will be created by LoadBalancedConnectionProxy.createInstance, connection will be proxied,so  the connection could not be enhanced by Skywalking, then the ClassCastException will be thrown

**Comment by guyukou** [comment]
> this issue looks like #1947 ,and i found you use LoadBalanced mode,this version of skywalking is not support multihost mode on mysqlconnector-5.x. it will be fixed on next version.
> on multihost mode, Connection will be created by LoadBalancedConnectionProxy.createInstance, connection will be proxied,so the connection could not be enhanced by Skywalking, then the ClassCastException will be thrown

Thank you, I got it.
