### ISSUE TITLE
What will makes CPM less than the real 

### ISSUE THREAD

**Issue by mbao** [apache/incubator-skywalking#2410]
- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
- What do you want to know?

I see that  the DataCarrier in TraceSegmentServiceClient uses BufferStrategy.IF_POSSIBLE, so some segment will lose if there is too many segments to send.   So is there other situations in which segment will lose?

If I  change the sampleRate from 1000 to 100, only payload of segment persisting will reduce to 10%, right?

How many CPM can one backend server load(Simply 8 cpu), and how can I compute how many backend servers should the cluster include?

Maybe I should just ask one each, sorry.

**Comment by wu-sheng** [comment]
> I see that the DataCarrier in TraceSegmentServiceClient uses BufferStrategy.IF_POSSIBLE, so some segment will lose if there is too many segments to send. So is there other situations in which segment will lose?

No. 

> If I change the sampleRate from 1000 to 100, only payload of segment persisting will reduce to 10%, right?

If you are saying client sampling, yes. Also the metric values lose 90%.

> How many CPM can one backend server load(Simply 8 cpu), and how can I compute how many backend servers should the cluster include?

Depend on ElasticSearch performance. 8 CPU could reach 5k/s at least.

**Comment by wu-sheng** [comment]
For 6.0.0-GA, it is designed for >~16Core. And 6.1 release(haven't yet) will be good work at different CPU cores.

**Comment by mbao** [comment]
> > I see that the DataCarrier in TraceSegmentServiceClient uses BufferStrategy.IF_POSSIBLE, so some segment will lose if there is too many segments to send. So is there other situations in which segment will lose?
> 
> No.
> 
> > If I change the sampleRate from 1000 to 100, only payload of segment persisting will reduce to 10%, right?
> 
> If you are saying client sampling, yes. Also the metric values lose 90%.

I mean sampleRate  for backend .  I think sample_n_per_3_secs is the only parameter for me to change the sample rate in agent client, right?
What do you mean by metric values? I think CPM value is still the exact value as sampleRate just impacts SegmentSpanListener for segment persistence. 
> 
> > How many CPM can one backend server load(Simply 8 cpu), and how can I compute how many backend servers should the cluster include?
> 
> Depend on ElasticSearch performance. 8 CPU could reach 5k/s at least.

What about mysql?  I think mysql is not optimized .

Thank you very much.

**Comment by wu-sheng** [comment]
> I mean sampleRate for backend . I think sample_n_per_3_secs is the only parameter for me to change the sample rate in agent client, right?
What do you mean by metric values? I think CPM value is still the exact value as sampleRate just impacts SegmentSpanListener for segment persistence.

For server-side sampling, yes. Your description looks right.

> What about mysql? I think mysql is not optimized .

We are running over tens of millions segment per day, so elasticsearch is widely used by us. For MySQL, I have added some indexes. If you have any new suggestion, pull request is always welcome.
