### ISSUE TITLE
(6.0.0-GA Standalone deployment) Bug java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by snowThinker** [apache/incubator-skywalking#2412]
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0.0-GA Standalone deployment
CentOS Linux release 7.5.1804
Oracle JDK 1.8.0_111

- What happen?
The skywalking-oap-server were down.
___
### Requirement or improvement
I think it's your design issue, maybe you can try to use Elastatic partition feature, you know you can archive history data monthly partition, after that you just need write data from current partition, and read data from all partitions.  
For instance. skywalkingdb, your partition might be skywalkingdb201901, skywalkingdb201902, skywalkingdb201903

**Comment by wu-sheng** [comment]
I don't understand what you are saying. Your issue title looks like the cluster management issue. ElasticSearch has nothing related to the `java.lang.ArithmeticException: / by zero`.

**Comment by snowThinker** [comment]
你说是集群管理的问题，但我用的是单点部署的，不是集群部署。

java.lang.ArithmeticException: / by zero

**Comment by wu-sheng** [comment]
> 你说是集群管理的问题，但我用的是单点部署的，不是集群部署。
java.lang.ArithmeticException: / by zero

That is why I said, I don't understand. You provide very limit inform, I haven't a clue.
