### ISSUE TITLE
how setting ui timezone

### ISSUE THREAD

**Issue by spark8103** [apache/incubator-skywalking#2420]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [*] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I change UI timezone every open.
my server‘ timezone is utc timezone.
but UI display shanghai timezone.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by spark8103** [comment]
I add webappService.sh
eval exec "\"$_RUNJAVA\" ${JAVA_OPTS} -jar ${JAR_PATH}/skywalking-webapp.jar \
         --spring.config.location=${JAR_PATH}/webapp.yml \
         --logging.file=${LOG_FILE_LOCATION} \
	 **-Duser.timezone=UTC \**
        2>${WEBAPP_LOG_DIR}/webapp-console.log 1> /dev/null &"
but not change UI default timezone.

**Comment by wu-sheng** [comment]
UI based on your browser at now.
