### ISSUE TITLE
Is this a wrong or mistaken description?

### ISSUE THREAD

**Issue by PanKuanYew** [apache/incubator-skywalking#2421]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [1 ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

> 6.0.0-alpha
> SkyWalking 6 is totally new milestone for the project. At this point, we are not just a distributing tracing system with analysis and visualization capabilities. We are an **Observability Analysis Platform(OAL)**.
> 
> The core and most important features in v6 are
> 
> Support to collect telemetry data from different sources, such as multiple language agents and service mesh.
> Extensible stream analysis core. Make SQL and cache analysis available in core level, although haven't provided in this release.
> Provide **Observability Analysis Language(OAL)** to make analysis metric customization available.
> New GraphQL query protocol. Not binding with UI now.
> UI topology is better now.
> New alarm core provided. In alpha, only on service related metric.
> All issues and pull requests are here

Hi, Mr SkyWalking. Does the first OAL refer to OAP?
Here is the url. https://github.com/apache/incubator-skywalking/blob/master/CHANGES.md#600-alpha

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
No. OAL is real. Read our document, https://github.com/apache/incubator-skywalking/blob/master/docs/en/concepts-and-designs/README.md.
