### ISSUE TITLE
RabbitMQConsumerInterceptor intercept failure java.lang.NullPointerException

### ISSUE THREAD

**Issue by lxh1214** [apache/incubator-skywalking#2446]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?

     version: 6.0.0-GA
     OS: windows 10
     JRE: 1.8
- What happen?

         A service is a rabbitMq pruducer but there is no integration skywalking agent.
         B service  is a rabbitMq consumer integration skywalking agent. 
         A and B integrate the same rabbitMq.
         B consumer A‘s a message    throws npe .
         
![image](https://user-images.githubusercontent.com/8844312/55548892-1f1ea380-5707-11e9-9432-4226fdb4c26c.png)

i see and debug code RabbitMQConsumerInterceptor, find **RabbitMQConsumerInterceptor 
     line 54: properties.getHeaders().get(next.getHeadKey())** is null

![image](https://user-images.githubusercontent.com/8844312/55547910-e4b40700-5704-11e9-8273-18cae1ad08d4.png)

   
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
       RabbitMQConsumerInterceptor   line 54 `properties.getHeaders().get(next.getHeadKey())`  execute's  result is null deal

**Comment by wu-sheng** [comment]
@zhaoyuguang Could you check on this?

**Comment by zhaoyuguang** [comment]
> @zhaoyuguang Could you check on this?

OK ~

**Comment by wu-sheng** [comment]
@lxh1214 I think this should be fixed, could you test on the master codes again?
