### ISSUE TITLE
对docker不友好

### ISSUE THREAD

**Issue by duansheli** [apache/incubator-skywalking#2457]
Please answer these questions before submitting your issue.
skywalking/oap
- Why do you submit this issue?
- [ ] Question or discussion
- [x ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
# 如何通过docker进行安装
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
# 具体步骤
下载了 https://github.com/apache/incubator-skywalking/archive/v6.0.0-GA.tar.gz 安装包
进入目录 cd incubator-skywalking-6.0.0-GA/docker/
## 想偷懒
直接 docker-compose up 
等了一会   
ERROR: repository skywalking/oap not found: does not exist or no pull access  

## 不能逃避 
```
make build  
。。。
Step 4/10 : COPY "$DIST_NAME.tar.gz" /
COPY failed: stat /var/lib/docker/tmp/docker-builder332525918/apache-skywalking-apm-incubating.tar.gz: no such file or directory
make: *** [oap] Error 1
```

## 这个模块怎么装
教程过期了吧
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
English only.

**Comment by wu-sheng** [comment]
Docker file and docker compose are only for development, not for release. If you want to know how we use docker image, read https://github.com/apache/incubator-skywalking-kubernetes
