### ISSUE TITLE
Exception while fetching data (/serverAlarmList) : null

### ISSUE THREAD

**Issue by brentoncao** [apache/incubator-skywalking#2462]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
My project has been reporting this error, it seems that the alarm-related exceptions are abnormal. What is going on?
![image](https://user-images.githubusercontent.com/17850005/55783957-21577800-5ae2-11e9-903e-4a0b6475c61c.png)  

![image](https://user-images.githubusercontent.com/17850005/55783973-2c120d00-5ae2-11e9-938f-b6a52b602af1.png)

**Comment by brentoncao** [comment]
Also my jvm information is not displayed, the system time of all machines is consistent

**Comment by brentoncao** [comment]
I use SkyWalking-5.0.0-RC2

**Comment by wu-sheng** [comment]
Your backend is not deployed right.

**Comment by brentoncao** [comment]
But other information is monitorable. Performance logs, topology maps, interface error logs, etc.

**Comment by wu-sheng** [comment]
We only recommend you deploy GA in a new env. Why choose RC2?

**Comment by brentoncao** [comment]
I thought that GA is not a stable version.

**Comment by wu-sheng** [comment]
Why GA is not a stable version?

**Comment by brentoncao** [comment]
Ok, I am trying to change to the GA version.

**Comment by brentoncao** [comment]
After the replacement version can work, thanks
