### ISSUE TITLE
The number of agents that start microservices seems to be limited.

### ISSUE THREAD

**Issue by brentoncao** [apache/incubator-skywalking#2472]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Hello, I use the agent to start the microservice. When I start the 21st microservice, I will squeeze out other microservices.That is, when the microservice is started by the agent to the 21st, other microservices cannot be started.
Is this situation encountered, or can this number of startups be configured?

**Comment by wu-sheng** [comment]
No. We have nothing related to this. And I am not sure, what is your status of can't be started?

In our users, SkyWalking is monitoring hundred, even thousands services, nothing special.

**Comment by brentoncao** [comment]
OK，I got it. May be insufficient memory allocation, thank you~
