### ISSUE TITLE
Skywalking service count is 0,but endpoint has value in skywalking ui

### ISSUE THREAD

**Issue by jxttian** [apache/incubator-skywalking#2475]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0-GA,Kubernetes,Jre8

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
Skywalking service count is 0,but endpoint has value in skywalking ui!
 
![深度截图_选择区域_20190411155402](https://user-images.githubusercontent.com/5572456/55940120-0ddb1700-5c72-11e9-9d05-f1d9a7572250.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by jxttian** [comment]
使用的是Docker Hub上的镜像 apache/skywalking-oap-server

**Comment by liuhaoyang** [comment]
Please use English.

**Comment by wu-sheng** [comment]
Timezone is UTC, not UTC +8(Browser default timezone). You could switch in UI.
