### ISSUE TITLE
How to use skywalking in react. please give some documents related to this.

### ISSUE THREAD

**Issue by DineshRama** [apache/incubator-skywalking#2480]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
What do you mean react? JavaScript?

**Comment by DineshRama** [comment]
yeah exactly. Please help

**Comment by wu-sheng** [comment]
JavaScript project is here, https://github.com/SkyAPM/SkyAPM-nodejs . You could ask there.
