### ISSUE TITLE
how to connect es 6.1.4

### ISSUE THREAD

**Issue by albanyqq** [apache/incubator-skywalking#2481]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
how to connect es 6.1.4
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking 6.0GA  CentOS   jre 1.8
- Which company or project?

- What happen?
how to connect es 6.1.4
___

Connection error reporting 401
**logs:**
Exception in thread "main" ElasticsearchStatusException[method [HEAD], host [http://55.14.66.179:9200], URI [/lu51-tscf-cloud-dev_all_heatmap_hour?ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true], status line [HTTP/1.1 401 Unauthorized]]; nested

es 6.1.4 need Account and Password, So how to configure application.yml  to connect es?

**My configuration：**
  elasticsearch:
    nameSpace: name
    clusterNodes: IP:9200
    indexShardsNumber: 2
    indexReplicasNumber: 0

**Comment by wu-sheng** [comment]
Document said, 6.3+ only.

**Comment by albanyqq** [comment]
How can I use ES 6.1?

Can you give me some thought?

thanks

**Comment by wu-sheng** [comment]
Es6.1 has bugs which can't support aggregation query very well. So... That is why.
