### ISSUE TITLE
es Cluster configuration problem

### ISSUE THREAD

**Issue by brentoncao** [apache/incubator-skywalking#2486]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- SkyWalking 6.0.0GA

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Hello, due to insufficient processing resources, I want to deploy es cluster, then how to configure the cluster in SkyWalking configuration file, is it configured as in the picture?
![image](https://user-images.githubusercontent.com/17850005/56106305-103fb880-5f73-11e9-9a15-427fcd3b7687.png)

**Comment by zhaoyuguang** [comment]
Yes，IP:HOST,IP:HOST
Detail see: ElasticSearchClient::parseClusterNodes.

**Comment by brentoncao** [comment]
ok，thank you~
