### ISSUE TITLE
SkyWalking deployment issues

### ISSUE THREAD

**Issue by brentoncao** [apache/incubator-skywalking#2489]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- Hello, about 100 microservices with SkyWalking monitoring need to cluster SkyWalking deployment ? I have clustered es, and reduced the esqueque_size, flush related information configuration.

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___

**Comment by wu-sheng** [comment]
What is your question?

**Comment by brentoncao** [comment]
Hello, Do I need to cluster SkyWalking to monitor more than 100 microservices with SkyWalking?  I have clustered es, and reduced the esqueque_size, flush related information configuration.

**Comment by wu-sheng** [comment]
That depends on your serivce payload and how many CPUs and memory it could use. In normal case, you need, otherwise, why you set elasticsearch in cluster mode.

**Comment by brentoncao** [comment]
ok, thank you~
