### ISSUE TITLE
SkyWalking cluster deployment problem

### ISSUE THREAD

**Issue by brentoncao** [apache/incubator-skywalking#2490]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Hello, after the SkyWalking cluster deployment started, did you report this error?
![image](https://user-images.githubusercontent.com/17850005/56200301-1ae07780-6071-11e9-848a-7a8c0f681366.png)

**Comment by wu-sheng** [comment]
Your elasticsearch can't connect, I don't know why.

**Comment by brentoncao** [comment]
Okay thank you~
