### ISSUE TITLE
why Backend service list limit 100

### ISSUE THREAD

**Issue by qlql489** [apache/incubator-skywalking#2491]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I see the result of getAllServices  method in class MetadataQueryEsDAO  limit 100, how to unlimited, our service count is above 100
___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0-GA
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Welcome to submit pull request to query more, 5000? Maybe, and provide setting for max value.
