### ISSUE TITLE
i hope real metrics，not sampling， trace can sampling

### ISSUE THREAD

**Issue by jacky1193610322** [apache/incubator-skywalking#2493]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
希望skywalking 有些指标可以在javaagent完成统计，因为这样相当于全量统计，比如url调用量，一旦采样之后，计算的99线，在出现问题的时候，没有参考意义，以及对于long service等调用提供支持，就像点评的cat监控，有些设计我认为比较好，这是自己定位问题的一点见解。

**Comment by wu-sheng** [comment]
English only. If you want to contribute new feature we could discuss details.
