### ISSUE TITLE
Support config downstream from collector

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#325]
User can set configurations through UI for each application(Based on Code).

Collector will push them to the agent after some of them changed. Agent effects these configurations in the **Runtime**.

cc @ascrutae @pengys5

**Comment by zone1511** [comment]
Will this feature appear in 5.0?

**Comment by wu-sheng** [comment]
@zone1511 In 5.x , but not 5.0, I suppose.

**Comment by zone1511** [comment]
@wu-sheng what is the direction for implementing config downstream?

**Comment by wu-sheng** [comment]
it is to be decided.

**Comment by zone1511** [comment]
Do you have rough idea how it can be implement? Does the existing agent to collector protocol allows downstream communication?

**Comment by wu-sheng** [comment]
The idea is very simple. Every gRPC service has a Downstream response, of course it is NOTHING in it for now. So if the backend could provide a feature to set some settings of commands, you could use this response to send to client. At last,, client agent watches the downstream response, and react what it says.

The idea is easy, but the process is complex. Do you want to contribute this? If so, we have to set several milestone to make the feature provided.

**Comment by zone1511** [comment]
I’m interested to provide if I have more detail. Right now I use another framework to push config to agent which make the whole deployment very complicated

**Comment by zone1511** [comment]
One concern is if we could  actively push the config. Instead of waiting for agent request and send back a response.

**Comment by wu-sheng** [comment]
Why do you want to push the setting? Right now, the agent will send VM info every second, I think it is good enough.

**Comment by zone1511** [comment]
Because some plugin needs dynamic configuration. 
For agent configuration pushing. It needs to provide  several functions
- able to push config to agent when agent startup
- support on the fly pushing config to connected agent
- agent side support config change event listener
- agent should be able to dispatch plugin specific config to particular plugin

From UI side, need to provide a way for user to input the agent/plugin config

**Comment by wu-sheng** [comment]
push is just a concept, in network, except deal with TCP. directly, there is no real push. Also client ask server side for new settings. 

there is no different in features.

**Comment by wu-sheng** [comment]
This is WIP now. So I will shut down this issue.
