### ISSUE TITLE
建议：关于agent.application_code的自动获取

### ISSUE THREAD

**Issue by mmaxiaolei** [apache/incubator-skywalking#357]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.1
### 建议
agent.application_code没有配置的时候，建议尝试去获取一下spring boot项目的配置的spring.application.name的值

**Comment by wu-sheng** [comment]
This is a great suggestion. We will check our schedule, and decide how to support this. Thanks

**Comment by wu-sheng** [comment]
Not active, closing.
