### ISSUE TITLE
[Agent] ServiceComb Plugin

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#437]
ServiceComb Java Chassis is a Software Development Kit (SDK) for rapid development of microservices in Java, providing service registration, service discovery, dynamic routing, and service management features. It is provided by Huawei OpenSource Group.

I think we should support them on tracing, although they provide official zipkin integration, but clearly we can provide more features in tracing and APM.

This is feedback of ServiceComb team, about how to instrument the SDK. @ascrutae You can check the discussion on [Google mailist](https://groups.google.com/forum/#!topic/servicecomb-developers/fL612WnlTWI)
>I think all three may be achieve by instrumenting io.servicecomb.core.Invocation#next. A provider will assemble any request into an invocation and a consumer will pass request as invocation.
Invocation itself contains request headers and the next method of invocation has a response as its parameter.
The current zipkin integration also makes use of invocation to pass along trace and span ids.

**Comment by wu-sheng** [comment]
cc  @seanyinx @WillemJiang

**Comment by wu-sheng** [comment]
@WillemJiang Do your team still have people on doing this?

**Comment by WillemJiang** [comment]
Yeah, we want this kind of integration. Please connect me if you need any help from ServiceComb.

**Comment by wu-sheng** [comment]
@WillemJiang Do you need our committer to develop this plugin? Or just help some of your people to contribute this plugin?

To be honest, I am not sure we can handle all your scenarios and features, which are provided by servicecomb and saga. Because none of our committers is an expert of servicecomb eco-system. Our HTTP/gRPC/AsyncResttemplete/MQ(RocketMQ) plugins are all ready for demonstrate who we trace all kinds of RPC.

Otherwise, I have to ask @ascrutae to try,

**Comment by wu-sheng** [comment]
@lytscu Since the AsyncHttpClient plugin almost finished, please focus on building the integration with ServiceComb (Huawei open source project, accepted by Apache, too)

I will help you to make the contact with their team leader, @WillemJiang . We can work on this together.

**Comment by lytscu** [comment]
Ok ,I will make contact with Teacher Jiang.

**Comment by wu-sheng** [comment]
Closing. #771 has been merged.
