### ISSUE TITLE
webui能否支持用户名和密码登录 和 告警支持

### ISSUE THREAD

**Issue by lijunhaos** [apache/incubator-skywalking#496]

**Comment by lijunhaos** [comment]
同时，是否有预警功能，达到一个阈值，能发邮件或者发短信

**Comment by wu-sheng** [comment]
> webui能否支持用户名和密码登录

这个属于多租户隔离，目前里程碑没有这方面的计划。

> 是否有预警功能，达到一个阈值，能发邮件或者发短信

告警支持是第一个主版本 3.3 的规划主要功能。欢迎关注和参与。

**Comment by wu-sheng** [comment]
Alarm features will be provided in 5.0 . Multi-tenant is not an expected feature in our milestone.
