### ISSUE TITLE
webui能否支持用户名和密码登录 和 告警支持 

### ISSUE THREAD

**Issue by xianleizheng** [apache/incubator-skywalking#500]
Please answer these questions before submitting your issue.

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

**Comment by wu-sheng** [comment]
Check here for answer: https://github.com/OpenSkywalking/skywalking/issues/496#issuecomment-335653685

**Comment by wu-sheng** [comment]
Alarm features will be provided in 5.0 . Multi-tenant is not an expected feature in our milestone.
