### ISSUE TITLE
[Collector] provide sharding jdbc as storage

### ISSUE THREAD

**Issue by oracle219** [apache/incubator-skywalking#523]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.1

### What version of your OS?
Linux

### What version of your JRE?
1.8

### What company or project?
DangDang

**Provide sharding jdbc as storage**

**Comment by wu-sheng** [comment]
> Provide sharding jdbc as storage

Glad to know this from dangdang tech team. Hope this can be provided in Skywalking 3.3.x . If you need any help, you can call anyone from @OpenSkywalking/pmc and @hanahmily .

**Comment by wu-sheng** [comment]
@clevertension Can you export or provide a list of H2 table(Include columns, data type)? 

FYI @peng-yongsheng

**Comment by wu-sheng** [comment]
@oracle219 @chidaodezhongsheng Do you have news to update?

**Comment by chidaodezhongsheng** [comment]
I need some examples codes of strorage module,but these codes do not implements by @peng-yongsheng ,i still waiting him.

**Comment by wu-sheng** [comment]
@chidaodezhongsheng You want to ref the H2 implementations?

**Comment by chidaodezhongsheng** [comment]
Yes,i need 8 ui dao codes.

**Comment by wu-sheng** [comment]
Not active, closing. MySQL storage would be provided.
