### ISSUE TITLE
[Agent] Config.Logging.DIR may be invalid in WriterFactory

### ISSUE THREAD

**Issue by neeuq** [apache/incubator-skywalking#552]
### What version of sky-walking are you using?
The latest version.
-------------------------------------------------------------------
WriterFactory这个日志类是不是有点小问题？
主要是AgentPackagePath.isPathFound()和Config.Logging.DIR初始化不是原子操作，如果这两步中间记日志(org.skywalking.apm.agent.core.boot.AgentPackagePath.AGENT_PACKAGE_PATH不为空但Config.Logging.DIR还是空)，org.skywalking.apm.agent.core.logging.core.FileWriter（这应该是另一线程做的）假如初始化文件流，后续的Config.Logging.DIR就不产生效果了。

[https://github.com/OpenSkywalking/skywalking/blob/f03c36b20ca6f1d91124a380a572aec871fe30dd/apm-sniffer/apm-agent-core/src/main/java/org/skywalking/apm/agent/core/logging/core/WriterFactory.java](url)

**Comment by wu-sheng** [comment]
@neeuq 我还不是很确定，你描述的场景。`Config.Logging.DIR`只应该在初始阶段修改，后续不应该有人修改。你所描述的多线程场景在什么地方发生呢？

**Comment by neeuq** [comment]
见org.skywalking.apm.agent.core.conf.SnifferConfigInitializer.initialize()方法
configFileStream = loadConfigFromAgentFolder()方法里面：加载AGENT_PACKAGE_PATH
接下来才调用
ConfigInitializer.initialize代码处：加载Config
这期间Config.Logging.DIR从：空 --> AGENT_PACKAGE_PATH -->配置的路径的转换

假设中间每个阶段都写一条日志，FileWriter是基于Config.Logging.DIR创建文件流，一旦确认文件是
在AGENT_PACKAGE_PATH下，后续对Config.Logging.DIR的修改就无效的。

这个问题跟是否多线程关系不大，不管日志同步或异步写都会

**Comment by wu-sheng** [comment]
Config.Logging.DIR一旦通过env, properties或者config文件制定，根据AGENT_PACKAGE_PATH来生成日志的逻辑，将会失效。这是目前的设计策略。

**Comment by neeuq** [comment]
能理解当前设计的策略
org.skywalking.apm.agent.core.logging.core.FileWriter.hasWriteStream()方法中一旦用旧的AGENT_PACKAGE_PATH来生成日志，即fileOutputStream就不为null，后续Config.Logging.DIR再变化就失效了，是不是这样的？
---------------------------------------------------
    private boolean hasWriteStream() {
        if (fileOutputStream != null) {
            return true;
        }

**Comment by wu-sheng** [comment]
目前确实是这样，因为目前没有动态改变的渠道，比如服务端推送，或者监测配置文件变化。

**Comment by neeuq** [comment]
我目前是通过System.setProperty("skywalking.logging.dir", dir)来设置日志目录了，但是日志不是产生在这个目录上，而是在AGENT_PACKAGE_PATH里面

**Comment by wu-sheng** [comment]
那这个可能因为现在的初始化顺序的原因，造成这个初始化失效了，应该是个BUG。你可以尝试修复一下。我刚刚review了一下代码，应该无论通过哪种方式，复写`logging.dir`都会失败。

**Comment by wu-sheng** [comment]
目前我没有想到特别好的修复办法，因为如果强制让此属性生效，实际会在两个地方生成日志文件。除非让日志模块和初始化模块紧耦合。

**Comment by neeuq** [comment]
引入一个变量怎么样，标识下参数是否已初始化完毕，System.getProperty中的参数处理完才置为true。
具体写日志就先根据这个变更判断是写到控制台还是文件中。

**Comment by wu-sheng** [comment]
我的建议是移除`AgentPackagePath`和`SnifferConfigInitializer`中的`logger`。直接使用`SystemOutWriter#writer`进行输出。你可以看看这样是否好使？

**Comment by neeuq** [comment]
方案针对这个bug是可行的。
只是会有点奇怪，系统有参数加载过程中不允许打日志。

**Comment by wu-sheng** [comment]
Try to solve this in 5.0

**Comment by wu-sheng** [comment]
Fixed.
