### ISSUE TITLE
[Collector] 能否支持es数据删除（让es中每种数据都按日期建立索引名称来存储，删除时按日期，逻辑上改动貌似不大）

### ISSUE THREAD

**Issue by siyuan494** [apache/incubator-skywalking#568]
Please answer these questions before submitting your issue.

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

**Comment by wu-sheng** [comment]
after #547 merged, we can do this tiny adjustments.

**Comment by wu-sheng** [comment]
We will add time column in segments table.

**Comment by wu-sheng** [comment]
> We will add time column in segments table.

Done. But no mechanism to delete data automatically. cc @peng-yongsheng

**Comment by wu-sheng** [comment]
Closing this. Already supported.
