### ISSUE TITLE
[UI] Support TraceSegment batch merge(MQ) in trace stack detail

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#573]
When mq comuser works in batch mode, several trace segments are merged into a single new one, and only the first global trace id propagates to continue context. So in current UI, if you query other global trace ids except the first one, you can see the whole trace, and even don't know there is a one.

@peng-yongsheng You have to decide how to make the index and query work.

**Comment by young001** [comment]
hi,guys,how does this issue going?I wonder how to support this feature?what's the solution to support this batch merge traceid feature?If I want to get traceid from log,so I have log all the traceids to log? so maybe the log of the batch job is all traceids.

**Comment by wu-sheng** [comment]
This issue is about UI and query only. In log, you should focus on log application tool kits we provided already.

**Comment by wu-sheng** [comment]
Supported, will release soon.
