### ISSUE TITLE
[Agent] postsql插件在postgresql9.6上出错

### ISSUE THREAD

**Issue by chanwu79** [apache/incubator-skywalking#580]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
sky-walking 3.2.3

### What version of your OS?
centos 7

### What version of your JRE?
1.8

### What company or project?
spring boot

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
在收集postgresql9.6的数据查询相关日志时，出现以下：
java.lang.ClassCastException: org.skywalking.apm.plugin.jdbc.trace.SWPreparedStatement cannot be cast to org.postgresql.core.BaseStatement
错误。导致数据查询不出。
程序采用了spring boot+mybatis+posgresql结构

**Comment by ascrutae** [comment]
@chanwu79  这个跟目前JDBC插码有关系，能否提供一个demo给我们，让我们精确的定位这个问题呢？

**Comment by wu-sheng** [comment]
@chanwu79  最好能提供一下你们的使用方法，和完整堆栈，谢谢。

**Comment by wu-sheng** [comment]
@chanwu79 We still need a demo to check what is happening. Can you provide one? Otherwise we have to ignore this issue. This issue will stay in open in next 7 days.

**Comment by wu-sheng** [comment]
@chanwu79 Based on our integration tests, we are going to make sure most version are supported. You can see the status from here: https://github.com/SkywalkingTest/agent-integration-test-report#postgresql .
