### ISSUE TITLE
[Agent] Provide plugin for Apache Httpcomponent httpclient 4.4 and 4.5

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#589]
http://hc.apache.org/httpcomponents-client-4.5.x/index.html

Now we are supporting Apache httpcomponent HttpClient 4.2 and 4.3

**Comment by lytscu** [comment]
Plugin “apm-httpClient-4.x-plugin” already support  Apache Httpcomponent httpclient 4.4 and 4.5
See details：
[https://github.com/SkywalkingTest/agent-integration-test-report#httpclient](url)

**Comment by wu-sheng** [comment]
Based on [test reports](https://github.com/SkywalkingTest/agent-integration-test-report#httpclient), http client 4.4 , 4.5 have been supported.
