### ISSUE TITLE
ManagedChannel isShutdown() isTerminated() 状态不可用

### ISSUE THREAD

**Issue by li-ya** [apache/incubator-skywalking#596]
[GrpcTest.java.txt](https://github.com/OpenSkywalking/skywalking/files/1481780/GrpcTest.java.txt)
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
master

### What version of your OS?
linux
### What version of your JRE?
1.8

### What company or project?
pard

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

由于当 collector 关闭之后，managechannel 的 isShutdown() ，isTerminated() 还是返回false，这导致grpc 的 内部缓存会被持续写入，最后导致内存溢出

**Comment by wu-sheng** [comment]
What is your purpose of this sample codes? I make no sense for me. You are building channel again and again. 

你的示例代码，只是在不停的创建channel，这个目的是？

**Comment by siyuan494** [comment]
when you shutdown the server which this codes request, the result of isShutdown() is still false. it seems like that the method will never be true,event if the server is shutdown.Thus the agent of skywalking will still write data to the collector of skywalking,and the datas will be cached in the queue of grpc util  it run out of memory. 

估计isShutdown()这个方法感知不到服务端的断开，所以当服务但断开时，agent还会通过grpc继续往collect发送数据，貌似这些数据会被grpc的队列缓存起来指导内存溢出.

**Comment by li-ya** [comment]
在没有server 的情况下，客户端获取的channel 的 状态isShutdown isTerminated 返回的都是false，所以，我认为不能用channel 这两个状态来判断服务端是否存活。

**Comment by li-ya** [comment]
我现在是又加了个心跳的接口，永远判断collecotr是否可用。

**Comment by li-ya** [comment]
I can not reproduce the problem in my system,so I close the issure

**Comment by wu-sheng** [comment]
@li-ya Thanks for your feedback.
