### ISSUE TITLE
[Agent] Can skywalking support Hystrix

### ISSUE THREAD

**Issue by menglongfeihu** [apache/incubator-skywalking#612]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.2.4

### What company or project?
just learn
### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

**Comment by ascrutae** [comment]
I will support this plugin in next version

**Comment by KaiwenWang** [comment]
expect the Hystrix plugin

**Comment by wu-sheng** [comment]
@KaiwenWang Received your feedback. Hope @ascrutae will have time to do so. He is working on automatic tests now.

**Comment by wu-sheng** [comment]
@ascrutae Pay attention for the multi threads in **Hystrix**. This component is really important in Spring eco system. But be advised, create span for **Hystrix** is meaningless, but tracing retry by creating new thread and propagate context, also log the exception it triggers. those are really matter.

**Comment by ascrutae** [comment]
Hystrix plugin has been merged. Closing this issue
