### ISSUE TITLE
[Collector] The PreparedStatement of H2Client dosen't close

### ISSUE THREAD

**Issue by chidaodezhongsheng** [apache/incubator-skywalking#626]
In the client-component,the preparedStatement of H2Client dosen't close.
@peng-yongsheng

**Comment by peng-yongsheng** [comment]
@chidaodezhongsheng Can you help me to fix it?

**Comment by wu-sheng** [comment]
H2 storage implementation will not provide in 5.0.0 alpha. All codes have been removed.
