### ISSUE TITLE
[Vote][Discussion]New collector/ui API practices

### ISSUE THREAD

**Issue by hanahmily** [apache/incubator-skywalking#638]
In order to separate ui and collector modules, we need to implement following practices.

## Replacing RESTful API with [GraphQL](http://graphql.org/learn/)

[GraphQL](http://graphql.org/learn/) is presented as a revolutionary new way to think about APIs. It contains some features I'm interested in.

### Defining response fields by client

In REST, the response fields are defined by server. If some fields is not needed by client, they are also responded. In GraphQL, the client cloud `select` fields from the server just like the `SQL`. That is why the GraphQL is a query language.

### Route Handlers

![Route Handler vs Resoler](https://cdn-images-1.medium.com/max/1600/1*qpyJSVVPkd5c6ItMmivnYg.png)

In REST, each request usually calls exactly one route handler function. In GraphQL, one query can call many resolvers to construct a nested response with multiple resources.

### [Introspection](http://graphql.org/learn/introspection/)

GraphQL can give information about what queries it supports. The user can generate documents from GraphQL. This avoids inconsistencies between the actual situation and the document. 

## Versioning

Upgrading the APIs with some breaking change would also lead to breaking the existing products or services using your APIs.

http://api.yourservice.com/v1/companies is a good example, which has the version number of the API in the path. 

For the GraphQL, there is a little deferents. GraphQL only returns the data that's explicitly requested, so new capabilities can be added  without creating a breaking change.  Only deleting or updating will create breaking change.

**Comment by wu-sheng** [comment]
@hanahmily The link (http://api.yourservice.com/v1/companies) is invalid. I read articles, http://graphql.org/learn/introspection/ and https://blog.pusher.com/rest-versus-graphql/ , which are all using JSON format, To be honest, I prefer YML format.

And which frameworks do you prefer in collector side, in Java Stack?

**Comment by wu-sheng** [comment]
Generally +1 for GraphQL protocol between UI and collector.

**Comment by hanahmily** [comment]
[graphql-java](https://github.com/graphql-java/graphql-java) is java framework for building java server endpoint.

**Comment by hanahmily** [comment]
@wu-sheng GraphQL is a new language, not a `JSON`.The link (http://api.yourservice.com/v1/companies) is foo endpoint for example.

**Comment by wu-sheng** [comment]
@hanahmily Got it.

**Comment by peng-yongsheng** [comment]
@hanahmily Is there any tools or apis to make the schema to be a document.

**Comment by wu-sheng** [comment]
@peng-yongsheng @hanahmily Several days are gone. There is no objective opinion comes out. Do we agree to use GraphGL-API between collector and UI?

**Comment by wu-sheng** [comment]
Received @peng-yongsheng and @hanahmily feedbacks. We are going to GraphQL to implement these APIs.
