### ISSUE TITLE
[UI] The Span tree chaotic

### ISSUE THREAD

**Issue by alex8224** [apache/incubator-skywalking#652]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.2.5

### What version of your OS?
centos 6.4 64bit

### What version of your JRE?
jdk8

### What company or project?

###What framework?
SpringBoots + dubbo + mybatis
### What did you do?
![](https://raw.githubusercontent.com/alex8224/skywalking/master/bug.png)

**Comment by wu-sheng** [comment]
What is your scenario? From my perspective, this trace is combined by three trace segments, and one is ignored or missed by agent or somewhere. 

I am not sure. Do all the traces in this service display like this?

**Comment by alex8224** [comment]
@wu-sheng Not all time ,but sometimes does.
Skywalking ver v3.2.5.Call chain: web->dubbo->db, common scenario.

**Comment by wu-sheng** [comment]
@alex8224 I am not sure what trigger this. Maybe ,you should debug the UI, and find out the segments. By providing that, we may have a clue, or at least a guess.

Just seeing the snapshot, seems like the trace is broken somehow, but still using the same global trace id.

cc @peng-yongsheng Do you have any idea?

**Comment by wu-sheng** [comment]
@alex8224 For making this issue resolved, I recommend you to provide the segments about this traceid. That is the only chance to find out what is happening. We will keep the issue open at least 7 days for you.

**Comment by wu-sheng** [comment]
No active comments in 4 months, UI has updated to 5.x. Closing this.
