### ISSUE TITLE
[Agent] how to specify which logger to be use by java agent

### ISSUE THREAD

**Issue by zone1511** [apache/incubator-skywalking#654]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.2.6

### What version of your OS?
windows

### What version of your JRE?
1.8

From the code LogManager.setLogResolver, seems no one call it at all and it is always using the easyLogResolver. How to switch to other logging framework? do I need to implement a LogResolver?

**Comment by wu-sheng** [comment]
Yes, you are. And because of compiling and class loader problems, you will find out, you must make sure the log implementation and all dependencies must be inside agent. So no one will call it, except the agent itself.

**Comment by zone1511** [comment]
After I implemented a Log Resolver, how does LogManager pick it up? Since JUL is a build in logger for JDK, will you consider use it so there is no classloading issue?

**Comment by wu-sheng** [comment]
@zone1511 Sorry for delay. Apache stuffs take me a lot of energy in these days. 

> After I implemented a Log Resolver, how does LogManager pick it up? Since JUL is a build in logger for JDK, 

After you implement the LogResolver, you must change the initial codes by calling `LogManager#setLogResolver`. I would recommend you to do that by adding a static block in `LogManager`.

> will you consider use it so there is no classloading issue?

If you are using all JDK codes, it will not trigger classloader issue. But if your application is also using JUL, the logging config will be influenced. That is why we only use our own implementation, rather than any other log components.

**Comment by zone1511** [comment]
@wu-sheng congrad for moving the project into apache.

if you extend those standard JUL logger then you can attach a configuration which config the agent's logger log to your JUL logger implementation and other applications which use  JUL will not be affected.

**Comment by wu-sheng** [comment]
> congrad for moving the project into apache

Thanks. But the moving is still on going. Something is not right so far.

> if you extend those standard JUL logger then you can attach a configuration which config the agent's logger log to your JUL logger implementation and other applications which use JUL will not be affected.

If they know JUL configuration well. you definitely can. So here is my proposal, if you are interested in JUL so much, I welcome you provide implementation by using JUL, and allow people to use config(file/system properties/sys env) to switch it.

But pay attention about some `LogManager#getLogger` execute before SnifferConfigInitializer, maybe you can't override those logs by now.

**Comment by wu-sheng** [comment]
No more updates in a month. Closing it.
