### ISSUE TITLE
collector window script fail to start

### ISSUE THREAD

**Issue by zone1511** [apache/incubator-skywalking#677]
### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

the file apm-collector/apm-collector-boot/bin/collectorService.bat should invoke org.apache.skywalking.apm.collector.boot.CollectorBootStartUp instead of CollectorBootStartUp # #

**Comment by ascrutae** [comment]
which version are you used？

**Comment by ascrutae** [comment]
This is an issue If you use the `5.0-2018-prevision` version. and I try to fix is in PR #678.

**Comment by wu-sheng** [comment]
#678 has been merged.
