### ISSUE TITLE
[Agent] oracle agant exception

### ISSUE THREAD

**Issue by flydish2017** [apache/incubator-skywalking#680]

**Comment by ascrutae** [comment]
Could you show me the demo, and which version of agent are you used?

**Comment by flydish2017** [comment]
oracle： 11.2.0.4.0

**Comment by flydish2017** [comment]
oracle version ： 11.2.0.4.0

**Comment by flydish2017** [comment]
oracle version： 11.2.0.4.0， skywalking version： 3.2.6
spring executes the insert operation through the mybatis mapper：

public interface AppLockMapper {
    int insert(AppLock record);
}

**Comment by ascrutae** [comment]
@flydish2017  this issue will fixed in PR: #786

**Comment by ascrutae** [comment]
The PR had been merged, close this issue
