### ISSUE TITLE
Guide for build custom plugin

### ISSUE THREAD

**Issue by zone1511** [apache/incubator-skywalking#692]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
5.0.0

### What did you do?
If I want to build a custom plugin, any coding convention, topology, naming convention I need to follow? Do I need to register the define in ComponentsDefine  and need someone to assign me an ID?

**Comment by wu-sheng** [comment]
If you want to contribute a plugin, we can discuss that. We will allocate you an available id  after you send the pull request.

 otherwise, choose  an  unused one  is OK.
