### ISSUE TITLE
还是c/c++ 的 register关键字问题

### ISSUE THREAD

**Issue by songzhian** [apache/incubator-skywalking#696]
非常感谢 采纳我上次提 "c/c++ 的 register关键字问题"
已经修改了应用注册服务 中的
`service ApplicationRegisterService {`
   ` rpc batchRegister (Applications) returns (ApplicationMappings) {
   }`
`}`
但是  应用实例发现服务 proto/DiscoveryService.proto#L11-L12 中的
`service InstanceDiscoveryService {`
    `rpc register (ApplicationInstance) returns (ApplicationInstanceMapping) {
   }`
}`
还是有  register  关键字 
以下是 github的链接
[https://github.com/apache/incubator-skywalking/blob/master/apm-network/src/main/proto/DiscoveryService.proto](url)
麻烦看下 是否能改成 大写开头 或者成其它名称

**Comment by wu-sheng** [comment]
@songzhian Changing the service name will break things already built in the community. Although it should be fixed, please help us check, do other services have the compatible issues in C/C++?

FYI @peng-yongsheng

**Comment by wu-sheng** [comment]
@songzhian Fix in #719
