### ISSUE TITLE
[Agent]Can we config the same agent jar/folder in different applications?

### ISSUE THREAD

**Issue by WangHouLing** [apache/incubator-skywalking#698]
Hi, 
I want to run multiple agents on one box from the same skywalking agent installation. There is a problem is `agent.application_code` in `agent.config`. Can I config different `agent.application_code` for same skywalking agent?
I'd appreciate it if you can help me.

### What version of sky-walking are you using?
3.2.6

### What version of your OS?
windows10

### What version of your JRE?
1.8

### What company or project?
springboot project

**Comment by wu-sheng** [comment]
What is your meaning about multi agents in on box? which agents? 

And what is the box?

**Comment by zone1511** [comment]
he means in single os, running multiple application which want to monitor by the skywalking agent. Any way to specify the agent application name from JVM argument instead of reading from agent config.

**Comment by WangHouLing** [comment]
@wu-sheng I'm sorry to give you a reply so late!
 zone1511 has already expressed what I mean :)

**Comment by WangHouLing** [comment]
@wu-sheng I'm sorry to give you a reply so late!
 zone1511 has already expressed what I mean :)

**Comment by wu-sheng** [comment]
The easy answer is **YES, you can**.

But you should aware of these:
1. Follow this document(assume you need cn version) : [link](https://github.com/apache/incubator-skywalking/blob/master/docs/cn/Deploy-skywalking-agent-CN.md#高级特性) . You can use `-Dskywalking.*` to override any config in file as you wish.
1. When two application use the same agent folder, by default, your logs output into the same file. This is hard to read and understand, but these is a bug in this version(3.2.6) to override it. I already try to fix it, see #697.

So, that is why I just recommend use separated agent jars. OK?

BTW, I just change the issue title.

Hope these can help you.

**Comment by WangHouLing** [comment]
Ok, I see. Thank you!

**Comment by zone1511** [comment]
Hi PMC,
  So the agent will read the config file related to its absolute location? In this way, we don't need to share one agent per machine and we can have many agent plus config plus log folder so each monitored application. As different agent may need to load different plugin for performance reason. If use same folder for multiple app. It is difficult to manage.

**Comment by wu-sheng** [comment]
> So the agent will read the config file related to its absolute location? In this way, we don't need to share one agent per machine and we can have many agent plus config plus log folder so each monitored application. As different agent may need to load different plugin for performance reason. If use same folder for multiple app. It is difficult to manage.

+1

**Comment by wangxiang5050** [comment]
> 
> 
> The easy answer is **YES, you can**.
> 
> But you should be aware of these:
> 
>     1. Follow this document(assume you need cn version) : [link](https://github.com/apache/incubator-skywalking/blob/master/docs/cn/Deploy-skywalking-agent-CN.md#%E9%AB%98%E7%BA%A7%E7%89%B9%E6%80%A7) . You can use `-Dskywalking.*` to override any config in file as you wish.
> 
>     2. When two application use the same agent folder, by default, your logs output into the same file. This is hard to read and understand, but these is a bug in this version(3.2.6) to override it. I already try to fix it, see #697.
> 
> 
> So, that is why I just recommend use separated agent jars. OK?
> 
> BTW, I just change the issue title.
> 
> Hope these can help you.

I have the same problem. And [link](https://github.com/apache/incubator-skywalking/blob/master/docs/cn/Deploy-skywalking-agent-CN.md#%E9%AB%98%E7%BA%A7%E7%89%B9%E6%80%A7) is now 404. Where can i find it?

**Comment by wangxiang5050** [comment]
Thank you!

**Comment by JayeshMuley** [comment]
Hi,
I have two  services are running on same host and setup using two separate folders. I can see both the services are present in topology but not on the Service Filter list. 

I have setup separate agent folder for each service. How to fix this problem or if there is another way to avoid using two separate folders.

folders - 
drwxr-xr-x. 9 Jayesh Jayesh   176 Jan  5 13:11 agent_solution
drwxr-xr-x. 9 Jayesh Jayesh   176 Jan  5 13:11 agent_edge
  
![image](https://user-images.githubusercontent.com/75727262/104182047-dba5ad00-5435-11eb-8d35-77313472ebc2.png)


Thanks and Regards,
Jayesh Muley
