### ISSUE TITLE
mvn compile error

### ISSUE THREAD

**Issue by wengangJi** [apache/incubator-skywalking#705]
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile-custom (default) on project apm-network: Unable to copy the file to C:\workspace\incub
ator-skywalking\apm-network\target\protoc-plugins: C:\workspace\incubator-skywalking\apm-network\target\protoc-plugins\protoc-3.3.0-windows-x86_64.exe (另一个程序正在使用此文件，进
程无法访问。) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apm-network

**Comment by wu-sheng** [comment]
@wengangJi This is not an error triggered by SkyWalking project. This depends on Google gRPC/Protobuf tools: `protoc`. So if you have any problem to run it, you should submit an issue in Protobuf or gRPC project.

I just can share with you about that, I can run this tool in my windows 7. Most of our known developers are using Mac OS.

**Comment by wu-sheng** [comment]
Oh, this is totally new to me. I think you should provide a FAQ document in English, and link it to here: https://github.com/apache/incubator-skywalking/blob/master/docs/README.md 

In that document, please provide specific versions, which you are aware of, and didn't support no glibc. Then, you can provide your solutions/suggestions, and the solutions should be more explicit then above.

Thanks.

I will be glad to accept that. @wengangJi

**Comment by wengangJi** [comment]
@wu-sheng The error log is “另一个程序正在使用此文件，进程无法访问”.
