### ISSUE TITLE
skywalking无法对sun.net.www.protocol.http.HttpURLConnection进行增强

### ISSUE THREAD

**Issue by haofeiL** [apache/incubator-skywalking#708]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.1.x

### What version of your OS?
win10

### What version of your JRE?
jdk1.8

### What did you do?
我们在使用skywalking时发现，对jdk原生的一些类无法增强，比如：sun.net.www.protocol.http.HttpURLConnection#connect。看了bytebuddy的源码，感觉是被拦截掉了，怀疑的代码截图如下：org.apache.skywalking.apm.agent.SkyWalkingAgent
![image](https://user-images.githubusercontent.com/24569072/34384404-eae867d0-eb56-11e7-92bc-a174b8992a53.png)
请您能否告诉我，如何才能拦截到sun.net.www.protocol.http.HttpURLConnection#connect。万分感激！！

**Comment by wu-sheng** [comment]
My design does not intend to intercept the jre classes. So I am not sure. Can you show me your plugin codes?

btw, your tagged codes are just for matching plugin target classes. I dont think that excludes any jre codes

**Comment by haofeiL** [comment]
您好，这是我的插件代码：
public class HttpjdkInstrumentation extends ClassInstanceMethodsEnhancePluginDefine {

    private static final String ENHANCE_CLASS = "sun.net.www.protocol.http.HttpURLConnection";
    private static final String INTERCEPT_CLASS = "com.mobanker.snowwalking.apm.plugin.httpjdk.HttpjdkInterceptor";

    @Override
    protected ClassMatch enhanceClass() {
        return NameMatch.byName(ENHANCE_CLASS);
    }

    @Override
    protected ConstructorInterceptPoint[] getConstructorsInterceptPoints() {
        return null;
    }

    @Override
    protected InstanceMethodsInterceptPoint[] getInstanceMethodsInterceptPoints() {
        return new InstanceMethodsInterceptPoint[] {
                new InstanceMethodsInterceptPoint() {
                    @Override
                    public ElementMatcher<MethodDescription> getMethodsMatcher() {
                        return named("connect");
                    }

                    @Override
                    public String getMethodsInterceptor() {
                        return INTERCEPT_CLASS;
                    }

                    @Override
                    public boolean isOverrideArgs() {
                        return false;
                    }
                }
        };
    }
}

public class HttpjdkInterceptor implements InstanceMethodsAroundInterceptor {
    @Override
    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, MethodInterceptResult result) throws Throwable {
        System.out.println("xueyou is http testing");
    }

    @Override
    public Object afterMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, Object ret) throws Throwable {
        return null;
    }

    @Override
    public void handleMethodException(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, Throwable t) {
    }
}

**Comment by haofeiL** [comment]
您好，下面是我的插件代码：

public class HttpjdkInstrumentation extends ClassInstanceMethodsEnhancePluginDefine {
    private static final String ENHANCE_CLASS = "sun.net.www.protocol.http.HttpURLConnection";
    private static final String INTERCEPT_CLASS = "com.mobanker.snowwalking.apm.plugin.httpjdk.HttpjdkInterceptor";

    @Override
    protected ClassMatch enhanceClass() {
        return NameMatch.byName(ENHANCE_CLASS);
    }

    @Override
    protected ConstructorInterceptPoint[] getConstructorsInterceptPoints() {
        return null;
    }

    @Override
    protected InstanceMethodsInterceptPoint[] getInstanceMethodsInterceptPoints() {
        return new InstanceMethodsInterceptPoint[] {
                new InstanceMethodsInterceptPoint() {
                    @Override
                    public ElementMatcher<MethodDescription> getMethodsMatcher() {
                        return named("connect");
                    }

                    @Override
                    public String getMethodsInterceptor() {
                        return INTERCEPT_CLASS;
                    }

                    @Override
                    public boolean isOverrideArgs() {
                        return false;
                    }
                }
        };
    }
}
public class HttpjdkInterceptor implements InstanceMethodsAroundInterceptor {
    @Override
    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, MethodInterceptResult result) throws Throwable {
        System.out.println("xueyou is http testing");
    }

    @Override
    public Object afterMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, Object ret) throws Throwable {
        return null;
    }

    @Override
    public void handleMethodException(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, Throwable t) {
    }
}

**Comment by haofeiL** [comment]
您好，下面是我的插件代码：
public class HttpjdkInstrumentation extends ClassInstanceMethodsEnhancePluginDefine {
    private static final String ENHANCE_CLASS = "sun.net.www.protocol.http.HttpURLConnection";
    private static final String INTERCEPT_CLASS = "com.mobanker.snowwalking.apm.plugin.httpjdk.HttpjdkInterceptor";

    @Override
    protected ClassMatch enhanceClass() {
        return NameMatch.byName(ENHANCE_CLASS);
    }

    @Override
    protected ConstructorInterceptPoint[] getConstructorsInterceptPoints() {
        return null;
    }

    @Override
    protected InstanceMethodsInterceptPoint[] getInstanceMethodsInterceptPoints() {
        return new InstanceMethodsInterceptPoint[] {
                new InstanceMethodsInterceptPoint() {
                    @Override
                    public ElementMatcher<MethodDescription> getMethodsMatcher() {
                        return named("connect");
                    }

                    @Override
                    public String getMethodsInterceptor() {
                        return INTERCEPT_CLASS;
                    }

                    @Override
                    public boolean isOverrideArgs() {
                        return false;
                    }
                }
        };
    }
}
public class HttpjdkInterceptor implements InstanceMethodsAroundInterceptor {
    @Override
    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, MethodInterceptResult result) throws Throwable {
        System.out.println("xueyou is http testing");
    }

    @Override
    public Object afterMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, Object ret) throws Throwable {
        return null;
    }

    @Override
    public void handleMethodException(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, Throwable t) {
    }
}

**Comment by haofeiL** [comment]
您好，下面是我的插件代码：
```
public class HttpjdkInstrumentation extends ClassInstanceMethodsEnhancePluginDefine {
    private static final String ENHANCE_CLASS = "sun.net.www.protocol.http.HttpURLConnection";
    private static final String INTERCEPT_CLASS = "com.mobanker.snowwalking.apm.plugin.httpjdk.HttpjdkInterceptor";

    @Override
    protected ClassMatch enhanceClass() {
        return NameMatch.byName(ENHANCE_CLASS);
    }

    @Override
    protected ConstructorInterceptPoint[] getConstructorsInterceptPoints() {
        return null;
    }

    @Override
    protected InstanceMethodsInterceptPoint[] getInstanceMethodsInterceptPoints() {
        return new InstanceMethodsInterceptPoint[] {
                new InstanceMethodsInterceptPoint() {
                    @Override
                    public ElementMatcher<MethodDescription> getMethodsMatcher() {
                        return named("connect");
                    }

                    @Override
                    public String getMethodsInterceptor() {
                        return INTERCEPT_CLASS;
                    }

                    @Override
                    public boolean isOverrideArgs() {
                        return false;
                    }
                }
        };
    }
}

public class HttpjdkInterceptor implements InstanceMethodsAroundInterceptor {
    @Override
    public void beforeMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, MethodInterceptResult result) throws Throwable {
        System.out.println("xueyou is http testing");
    }

    @Override
    public Object afterMethod(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, Object ret) throws Throwable {
        return null;
    }

    @Override
    public void handleMethodException(EnhancedInstance objInst, Method method, Object[] allArguments, Class<?>[] argumentsTypes, Throwable t) {
    }
}

**Comment by wu-sheng** [comment]
@haofeiL I have explained this offline, right? So, I am closing this issue.

**Comment by 1923982924** [comment]
@haofeiL ,你解决这个问题了吗？我增强的时候直接报了异常
java.lang.IllegalStateException: Injecting classes into the bootstrap class loader was not enabled
我的版本是6.0-GA
