### ISSUE TITLE
access AbstractTracerContext from ContextManager

### ISSUE THREAD

**Issue by zone1511** [apache/incubator-skywalking#720]
For some plugin, it may only process its function if certain span is created in the current trace, right now, there is no way to access the tracer context from context manager. Even context manager can return the tracer context, TracingContext class didnt expose the function to obtain the complete tracer stack.

**Comment by wu-sheng** [comment]
@zone1511 Can you provide some scenario about why should access the `active span stack`? I think this is your asking, right?

**Comment by wu-sheng** [comment]
IMO, the active span is the only right span and object, which you should manipulate in the plugin or interceptor. Because you can't make sure which spans are in the `active stack` now.

**Comment by zone1511** [comment]
Just image a case if I only want to trace sql performance for certain url only, the jdbc plugin has to check if in the stack there is a span which is a web url type span and check if the url is match or not. 
Since the active span only tells you the current span, if you want to trace the whole call stack, there is no option right now unless the contextmanager provides function to expose the `active stack`

**Comment by wu-sheng** [comment]
I understand your scenario now. Here is my suggestion:

The real thing you want is a `RuntimeTracingContext` inside the TracingContext, which I proposal to implement in a commercial product, but didn't add it to SkyWalking agent module yet.
* **RuntimeTracingContext** will not be serialized to collector, just to propagate the context in the thread.
* By using that, you can add the service url into it, then you can access the url from anywhere inside the context.

**Comment by wu-sheng** [comment]
@zone1511 We haven't implemented or intend to implement any feature, which need the `RuntimeTracingContext`. Do you want to extend SkyWalking analysis features?

**Comment by zone1511** [comment]
yes, im interest to extend skywalking to add more analytic functions.

**Comment by wu-sheng** [comment]
The official core don't find any real scenario, which need this access way. Your requirements look like a custom way, maybe in order to improve performance( cost less network brand ).

**Comment by wu-sheng** [comment]
As I mentioned here : https://github.com/apache/incubator-skywalking/issues/721#issuecomment-355174368

> The project core only provides and maintains the community features (ASF requirements). So unless we are going to do some open source plugins/features together, this feature will stay in could be added rather than should be added.

**Comment by zone1511** [comment]
Can I make a pull request for this requirement so that plugins has ability to access the span stack?

**Comment by wu-sheng** [comment]
You can try. But I doubt whether you can get enough committor or PMC member support. Because they will ask for real use case for SkyWalking itselft, rather than your custom requirements.

**Comment by wu-sheng** [comment]
@zone1511 Do you have anything to update?

**Comment by zone1511** [comment]
I will create a pull request for this. Although this may be a customize requirement, but if the core is not able to open up the access to the whole span stack, there is no way to add customization based on the span history

**Comment by wu-sheng** [comment]
# Vote Requirement
Participators: All PPMC members, @ascrutae @hanahmily  @peng-yongsheng @wu-sheng

Content: @zone1511 asks for open the span stack inside TracingContext to plugin developer, for some custom requirements:
> Just image a case if I only want to trace sql performance for certain url only, the jdbc plugin has to check if in the stack there is a span which is a web url type span and check if the url is match or not.
Since the active span only tells you the current span, if you want to trace the whole call stack, there is no option right now unless the contextmanager provides function to expose the active stack

Vote open for at least 3 days.

**Comment by wu-sheng** [comment]
-1 (binding)

Reason:
1. TracingContext an inside concept, if plugin need to know how core works, make the plugin development harder than before, and also hard to test in all scenario. Either open `TracingContext` or providing `RuntimeContext` is all segment context related, any conjecture codes without fully check may cause a fatal in tracing.
1. It's hard to say how to config these URLs, because we don't have Config downstream(from collector) for now.

**Comment by zone1511** [comment]
It is ok not to openup `TracingContext` and we just need to a a configurable switch which specify which implementation of tracingContext should be used in `ContextManager`
````java
private static AbstractTracerContext getOrCreate(String operationName, boolean forceSampling) {
        AbstractTracerContext context = CONTEXT.get();
        if (context == null) {
            if (StringUtil.isEmpty(operationName)) {
                if (logger.isDebugEnable()) {
                    logger.debug("No operation name, ignore this trace.");
                }
                context = new IgnoredTracerContext();
            } else {
                if (RemoteDownstreamConfig.Agent.APPLICATION_ID != DictionaryUtil.nullValue()
                    && RemoteDownstreamConfig.Agent.APPLICATION_INSTANCE_ID != DictionaryUtil.nullValue()
                    ) {
                    int suffixIdx = operationName.lastIndexOf(".");
                    if (suffixIdx > -1 && Config.Agent.IGNORE_SUFFIX.contains(operationName.substring(suffixIdx))) {
                        context = new IgnoredTracerContext();
                    } else {
                        SamplingService samplingService = ServiceManager.INSTANCE.findService(SamplingService.class);
                        if (forceSampling || samplingService.trySampling()) {
                            context = new TracingContext(); 
                            // ^-- let the actual implementation configurable at runtime
                        } else {
                            context = new IgnoredTracerContext();
                        }
                    }
                } else {
                    /**
                     * Can't register to collector, no need to trace anything.
                     */
                    context = new IgnoredTracerContext();
                }
            }
            CONTEXT.set(context);
        }
        return context;
    }
````

**Comment by wu-sheng** [comment]
@zone1511 can you take an example about how to switch and your context implementation can fit your requirements.

**Comment by zone1511** [comment]
@wu-sheng  to implement this feature, there are two approaches
1. open up activespace from TracingContext
add the following method to `TracingContext`
```java
    public LinkedList<AbstractSpan> getActiveSpanStack() {
        return activeSpanStack;
    }
```
and add the following method to `ContextManager`
```java
    public static AbstractTracerContext get() {
        return CONTEXT.get();
    }
```
2. let the context implementation configurable in `TracingContext`
replace
```java
    context = new TracingContext();
```
with
```java
 try {
  context= (AbstractTracerContext)Class.forName("TracingContextImplementation").newInstance();
 } catch (InstantiationException e) {
   e.printStackTrace();
 } catch (IllegalAccessException e) {
  e.printStackTrace();
  } catch (ClassNotFoundException e) {
  e.printStackTrace();
 }


```

**Comment by wu-sheng** [comment]
@zone1511 Even we do that, `TracingContext` or `YourImplementContext` can't be guaranteed existing. e.g. ignored trace.

**Comment by zone1511** [comment]
From plugin side just check if the context is TracingContext or not. If not. Just handle it.

**Comment by ascrutae** [comment]
-1 (binding)

Reason:

1. Span creation depends on other Span, the logic of the code can be complicated. And because of the uncertainty of the applications being monitored, this will lead to functional anomalies and unpredictable performance costs

**Comment by hanahmily** [comment]
-1 (binding)

Reason:
     SkyWalking‘s design philosophy is to tackle the most important tracing issues.  This issue is not a most important one.

**Comment by peng-yongsheng** [comment]
I can't understand the real things you want. If you only want to trace sql performance for certain url only, you can setting the url matcher. Then the trace from those url are filtered, but you want to filter the sql only. What are your concerns? Save the network io performance?

**Comment by wu-sheng** [comment]
> Some framework like JSF is hard to set the url filter. But I can create a jsf plugin so when a jsf action is called. It will create a span and if this action call a sql then I can correctly only log sql's related to that jsf action. Which it is mvc framework dependent. So there is a must for the plugin to check the span stack to see if the sql is originate from a target web action.

Still, trace sql based on certain URLs or actions. @peng-yongsheng

**Comment by peng-yongsheng** [comment]
> Some framework like JSF is hard to set the url filter. But I can create a jsf plugin so when a jsf action is called. It will create a span and if this action call a sql then I can correctly only log sql's related to that jsf action. Which it is mvc framework dependent. So there is a must for the plugin to check the span stack to see if the sql is originate from a target web action.

If network io performance is not the concerns for you. I think do something in collector module to collect those sql is a good idea.

**Comment by zone1511** [comment]
current filter approach can work on url filtering only. If i want to filter from MVC framework point of view, it is not able to do by setting url filter only

**Comment by wu-sheng** [comment]
@peng-yongsheng The vote is going to end so. Please take a vote.

**Comment by peng-yongsheng** [comment]
-1 (binding)
>Do something in collector module to collect those sql is a good idea.

**Comment by wu-sheng** [comment]
@zone1511  Vote result, no support yet. Unless have  new scenario,  I close this thread for now.
