### ISSUE TITLE
Require custom trace ignore

### ISSUE THREAD

**Issue by xjr100419** [apache/incubator-skywalking#731]
### What version of sky-walking are you using?
v3.2.6

### What version of your OS?
window

### What version of your JRE?
java8

我看 agent.config 里面有一个配置项
Ignore the segments if their operation names start with these suffix.
agent.ignore_suffix=.jpg,.jpeg,.js,.css,.png,.bmp,.gif,.ico,.mp3,.mp4,.html,.svg

而且开代码 好像只能过滤后缀。。
不能按照路径过滤。（因为 spring cloud 有大量的 心跳注册信息 我想是可以过滤掉的）

看是否可以 添加按路径过滤规则

**Comment by wu-sheng** [comment]
Hi @xjr100419 , You can see how we ignore the url by suffix, so there are too options:
1. Using the current mechanism, put the whole URLs(e.g. hear beat url) in the `agent.ignore_suffix`. The ignore works, I suppose.
1. Alter the agent codes in your fork, like the current mechanism did. Then recompile the 3.2.6 to provide this feature.

It is up to you.

**Comment by 18474475** [comment]
many guys may need  "pattern ignore" config to ignore 
/eureka/apps/delta
/health
/info
...

**Comment by wu-sheng** [comment]
@xjr100419 @18474475 I am aware of your requirements. But the core team has no time on this in this two months. So if any of you is interested, I am happy to work with you on a pull request.

**Comment by wu-sheng** [comment]
@xjr100419 @18474475 As usual, I will keep this issue open more than 7 days, in case you want to discuss more. Or you are going to work on the pull request. I can provide further helps.

**Comment by wu-sheng** [comment]
@xjr100419 @18474475 Closing this, because no further updates. If you are going to send the pull request, please reopen this issue and relate this to your pull request. Thanks.
