### ISSUE TITLE
maven error

### ISSUE THREAD

**Issue by wolfelven** [apache/incubator-skywalking#740]
[ERROR] Failed to execute goal on project client-component: Could not resolve dependencies for project org.apache.skywalking:client-component:jar:5.0.0-alpha: Failure to find org.apache.skywalking:apm-network:jar:5.0.0-alpha in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
When I execute mvn compile -Dmaven.test.skip=true in apm-collector，terminal shows this error

**Comment by wu-sheng** [comment]
First of all, CI passed, means the compile status is health. Then we didn't expect you to compile a single module of the project. See https://github.com/apache/incubator-skywalking/blob/master/docs/en/How-to-build.md to know how to compile.

And then, 5.0 is our next release, and branch `master` is for development. So I didn't recommend you to use it, else you want to contribute somethings.

We haven't release version after we accepted by Apache. So 3.x is not an Apache release.
