### ISSUE TITLE
[Agent] Don't support MondoDB 3.2.2 client

### ISSUE THREAD

**Issue by 906827215** [apache/incubator-skywalking#744]
我目前的MongoDb 驱动是3.2.2，我之前询问过新版本已经支持 2.x.x +  3.x.x+ 了。不过在实际使用当中，存在驱动包版本错误，如下：
![qq 20180112101546](https://user-images.githubusercontent.com/24824256/34856700-93a6874a-f781-11e7-9a41-8c5746a4deb8.jpg)

**Comment by wu-sheng** [comment]
This is a requirement. We haven't supported yet.

**Comment by zgyrush** [comment]
Is there a plan to supported mongodb 3.2.2?

**Comment by wu-sheng** [comment]
You could try to contribute one. The plugin supports come from the whole community. Even we want, I am not sure we have enough resources to test all.

**Comment by zgyrush** [comment]
OK, i will try
