### ISSUE TITLE
How to find apm-toolkit-trace jar file?

### ISSUE THREAD

**Issue by lijialing888** [apache/incubator-skywalking#745]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.2.6

### What version of your OS?
any

### What version of your JRE?
8.0

### What company or project?
Top 500 company

### What did you do?
I want use opentracing API, but how to download the adapter jar file?

I could not find it in maven repository.

```xml
<dependency>
      <groupId>org.apache.skywalking</groupId>
      <artifactId>apm-toolkit-trace</artifactId>
      <version>${skywalking.version}</version>
</dependency>
```

**Comment by wu-sheng** [comment]
@lijialing888 SkyWalking has just join the ASF, so we haven't release any version under `org.apache`. You can't download `org.apache.skywalking` from anywhere.

If you want to try our old version, latest 3.2.6, if can download it from release pages,  or you can find from **jcenter**. check here: https://bintray.com/wu-sheng/skywalking/org.skywalking.apm-toolkit-trace
