### ISSUE TITLE
How to read span tag in elasticsearch?

### ISSUE THREAD

**Issue by lijialing888** [apache/incubator-skywalking#746]
Please answer these questions before submitting your issue.

### What version of sky-walking are you using?
3.2.6

### What version of your OS?
any

### What version of your JRE?
8.0

### What company or project?
Top 500 company

### What did you do?
Hi, I use open-tracing API add some tags to my span:
```java
Tracer tracer = new SkywalkingTracer();
try (ActiveSpan span = tracer.buildSpan("service").startActive()) {
    span.setTag("tenant", "T3");
    span.setTag("id", input);
    // Do things.
    Thread.sleep(Math.round(50 * Math.random()));
} 
catch (Exception e) {
    // ignore
}
```

I found something like base64 code in sgement index, looks like:
```json
{
    "data_binary": "CgwKCgE0gK2Bgq6s9hoaWggBGPn/oL+OLCCUgKG/jiwyCUplZGlzL2dldEIOMTI3LjAuMC4xOjYzNzlIAVABWAdyEAoHZGIudHlwZRIFUmVkaXNyFQoMZGIuc3RhdGVtZW50EgVnZXQgNxpeCAIYrYChv44sIMWAob+OLCj///////////8BOAJIAVABWAdyEAoHZGIudHlwZRIFUmVkaXNyJwoMZGIuc3RhdGVtZW50EhdzZXQgNzAuNjAxOTc3NzI5MzUxMzQ5MxplEP///////////wEY7/+gv44sIMmAob+OLCgCUANYDnIwCgN1cmwSKWh0dHA6Ly9sb2NhbGhvc3Q6MTgwODAvYmVuY2htYXJrLTEvdXNlci83chIKC2h0dHAubWV0aG9kEgNHRVQg////////////ASgB",
    "time_bucket": 201801120907
  }
```

I want do some analyze on the spans. How could I read it? Is there any API can do it?

Or is there anyway to add new attributes to span/segment index?

**Comment by wu-sheng** [comment]
This is String based on BASE64 encode, because Elastic Search only accepts bytes in this format. And the bytes are in Protobuf format, after you do the un-BASE64.

SkyWalking segment format is here: https://github.com/apache/incubator-skywalking/blob/master/apm-protocol/apm-network/src/main/proto/TraceSegmentService.proto

**Comment by wangyunchuan2012** [comment]
hi, bro, I still can't parse the data_binary clearly, 还是乱码

**Comment by wu-sheng** [comment]
You just need to read codes. This is an open source project, right?

**Comment by wangyunchuan2012** [comment]
> You just need to read codes. This is an open source project, right?

thanks, I'm reading it now, it's a little difficult for a fresh man, thanks anyway!
