### ISSUE TITLE
Support for MicroProfile OpenTracing?

### ISSUE THREAD

**Issue by johnament** [apache/incubator-skywalking#748]
Most of the template doesn't apply, but I'm leaving it here.

I'm wondering if the Apache SkyWalking team is interested in implementing the MicroProfile OpenTracing spec?  I had sent an [email on the dev list,](https://lists.apache.org/thread.html/c943de8e13824fe9baf83fbca324742aed43b46b202ce1f1331ebfd6@%3Cdev.skywalking.apache.org%3E) but I suspect you may not be using your dev list (yet).  Please check that email for more information.

Please answer these questions before submitting your issue.

### What did you do?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

**Comment by wu-sheng** [comment]
Sorry for missing your mail. Too many automatic sent mail in our maillist, because we are using GitHub issues to discuss. So free feel to start any discussions here, even the template doesn't fit.

As an OpenTracing supported tracer, also a member of OTIAB, I am not familiar with `MicroProfile OpenTracing spec`. But I saw a familiar name, [@Pavol Loffay](https://github.com/pavolloffay), so I assume some OpenTracing friends are working on the spec.

I just did a quick read about the spec. I am not sure about `How should we support the spec?`. 

Quote from the spec:
```
This specification defines an easy way to allow an application running in a MicroProfile container to take advantage of distributed tracing by using an OpenTracing Tracer implementation.
```

Already as an OpenTracing Tracer implementation, what should we do further more?

@pavolloffay Feel free to join us.

**Comment by pavolloffay** [comment]
First, I am not very familiar with this project. Is it sort of agent-based tracer right? 

Microprofile basically defines what data (tags, logs) instrumentation should report via OpenTracing tracer. The implementation can use arbitrary OT vendor. 

I think to make it work, users have to just use sky-walking OT tracer :)

**Comment by wu-sheng** [comment]
> First, I am not very familiar with this project. Is it sort of agent-based tracer right?

Yes, agent based. `@Trace` annotation supported and OpenTracing tracer implementation bridge supported.

**Comment by johnament** [comment]
Well, there's another piece to it, which is the required CDI/JAX-RS instrumentation.

**Comment by johnament** [comment]
@wu-sheng  BTW:

> Sorry for missing your mail. Too many automatic sent mail in our maillist, because we are using GitHub issues to discuss. So free feel to start any discussions here, even the template doesn't fit.

A lot of newer apache projects see this issue, you may want to create a `notifications@` mail alias to receive all of the github, jira notifications.  This would allow real development discussions to happen on dev@

**Comment by wu-sheng** [comment]
@johnament At spec level, we should only follow OT APIs, CDI is not a part of agent or tracer should do.

In another way, if you are proposaling to support JAX-RS annotations, that should provide a new plugin. I am interesting. If you want to take part in, welcome. I and our PPMC member will help ypu.

**Comment by johnament** [comment]
Hi @wu-sheng yes, I think at the core having support for the OT APIs make sense.  Looking at the spec, everything else seems more closely related to JAX-RS support.  I'd be happy to help you out with a CDI extension and JAX-RS support, as it could be of use to other users.

**Comment by wu-sheng** [comment]
Welcome to help us in CDI and JAX-RS. Maybe you can start a pull request for each one or both? Then we can discuss the details.

If you have any issue, when working on the pull request, please let me know. Glad to help.

**Comment by wu-sheng** [comment]
@johnament Do you have anything to update?

**Comment by wu-sheng** [comment]
Closing this. Because More than 3 months, no active comments at all.
