### ISSUE TITLE
Please add DISCLAIMER about the skywalking website

### ISSUE THREAD

**Issue by WillemJiang** [apache/incubator-skywalking#752]
As Skywalking is in the Padding of Apache incubator, according to ASF  podling branding guidelines it's important to use the word incubating in the website as Apache SkyWalking (incubating) and add DISCLAIMER file in the Git repository.
Please check out  [here](https://incubator.apache.org/guides/branding.html#disclaimers) for more information.

**Comment by wu-sheng** [comment]
> add DISCLAIMER file in the Git repository.

Add file in all repositories? this, UI and website?

**Comment by WillemJiang** [comment]
yeah， you can take the ServiceComb JIRA as an example.https://issues.apache.org/jira/browse/SCB-123

**Comment by wu-sheng** [comment]
@WillemJiang DISCLAIMER files have been added. Please review: #753 , https://github.com/apache/incubator-skywalking-ui/pull/91 . And website repositories didn't ask for review, pushed already. Commit is: https://github.com/apache/incubator-skywalking-website/commit/ad67da4c447dabf46ea5f5d6853b4d2b99ed60ca

**Comment by wu-sheng** [comment]
For website, where do you prefer to add `incubating`? Could you give a screenshot and tag the location?

**Comment by WillemJiang** [comment]
It's the header, I think you can seach "Apache Skywalking"  for it.

**Comment by wu-sheng** [comment]
@WillemJiang website is updated. http://skywalking.incubator.apache.org/ . Please review the two pull requests, if OK, please improve and merge them.

**Comment by peng-yongsheng** [comment]
^_^
