### ISSUE TITLE
Decouple JDBCURL parser logic from URLParser

### ISSUE THREAD

**Issue by zone1511** [apache/incubator-skywalking#763]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X] Feature or performance improvement
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Currently, all JDBC url parser are hardcoded in class `URLParser`. I suggest to introduce java service api so each JDBC plugin provides its own URL parsing logic and URLParser just lookup the JDBC parser implementation using java service loader api.

**Comment by wu-sheng** [comment]
@zone1511 Good proposal. And welcome and glad to accept pull request about this. But notice, when you use SPI, please you are using the right classloader, I think should be `AgentClassLoader#getDefault()`

**Comment by zone1511** [comment]
@wu-sheng how do I write the test case to verify the modification works or not?

**Comment by ascrutae** [comment]
@zone1511  you can do the following test scenario on you local machine, the first scenario is operate one of supported DB framework by using Spring boot and the other is by using Tomcat, we will provider a report that it container other DB framework test result by using automated test platfrom

**Comment by wu-sheng** [comment]
@zone1511 You could follow @ascrutae 's mentor. He did a lot of contributions in Agent and its automatic tests. See here:  https://github.com/SkywalkingTest/agent-integration-test-report

**Comment by zone1511** [comment]
So I just pull request and it will trigger the test or I run junit test locally? but I didnt see any junit test cover spring boot + mysql?

**Comment by zone1511** [comment]
@wu-sheng I found if I use `AgentClassLoader.getDefault()` in the service loader, it will throws 
```java
java.util.ServiceConfigurationError: org.apache.skywalking.apm.plugin.jdbc.connectionurl.parser.ConnectionURLParser: Provider org.apache.skywalking.apm.plugin.jdbc.h2.parser.H2URLParser not a subtype
```
where `ConnectionURLParser` is the SPI interface and `H2URLParser` is the SPI implementation
and debug shows the Concrete class and Service interface are not loaded from `AgentClassLoader.getDefault()` but loaded by another instance of AgentClassLoader
Is this expected?  or I should use the default `load()` method instead specifying the class loader?

**Comment by wu-sheng** [comment]
@zone1511 Sorry for misleading you. You need to push the SPI init later,  maybe use a double-check lock in Interceptor can avoid the classloader problem.

And don't use `AgentClassLoader#getDefault()`, choose to use `Interceptor.class.getClassLoader()` instead(my best guess for now).

**Comment by wu-sheng** [comment]
> So I just pull request and it will trigger the test or I run junit test locally? but I didnt see any junit test cover spring boot + mysql?

Normal junit test cases doesn't fit most of java agent tests. That is why @ascrutae contribute his auto test solution with docker(-compose) isolation. If @ascrutae hasn't finished all guides/documents, you can ask him directly for guidances.

**Comment by zone1511** [comment]
As the parser moved to individual database plugin     . The original test case in jdbc common is no longer valid. Should I remove it? And move the case to individual plugin test folder?

**Comment by zone1511** [comment]
@wu-sheng I just found that if the parser is moved to each db plugin, some other class's test case will failed due to the assumption that `URLParser.parser` is not able to parse the corresponding jdbcurl. To make the test run, it must reference to myssql plugin which will cause cyclic reference. Please suggest how to handle those test case which depends on `URLParser.parser`

**Comment by ascrutae** [comment]
@zone1511  all concrete  DB plugin project dependency `jdbc-commons` project, just move the test cases about concrete `URLParser` to concrete plugin project

**Comment by zone1511** [comment]
@ascrutae there are some test cases in `jdbc-common` which required URLParser.parser for mysql url. Do you want to move all those `SW*` test cases to mysql plugin?

**Comment by zone1511** [comment]
Consider the following code fragment from `SWConnectionTest`
```java
@Before
    public void setUp() throws Exception {
        swConnection = new SWConnection("jdbc:mysql://127.0.0.1:3306/test", new Properties(), jdbcConnection);
        multiHostConnection = new SWConnection("jdbc:mysql://127.0.0.1:3306,127.0.0.1:3309/test", new Properties(), jdbcConnection);
        when(jdbcConnection.prepareStatement(anyString())).thenReturn(mysqlPreparedStatement);
    }
```

Before refactor the `URLParser` it can handle parsing the mysql url inside jdbc-common project. so the above code works fine in jdbc-common project. However, after moving each plugin's parser back to its own project, the above code will fail, as due to the urlparser SPI, the jdbc-common project will not able to handle mysql's jdbc parsing and cause some code return NPE afterward.

**Comment by ascrutae** [comment]
Maybe you can also mock `URLParser` class under the test case. and then You can get the mock `URLParser` instance by using the SPI API, and then you can use the instance to parse the URL.

**Comment by wu-sheng** [comment]
@ascrutae I don't think that means anything if you have removed `URLParser`. The URL parser should be tested, but in separated plugins.

**Comment by wu-sheng** [comment]
Closing this, no active comments in 3 months.
