### ISSUE TITLE
Jedis LETTUCE client plugin

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#766]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
A popular Jedis client, included in Spring. Repository is here: https://github.com/lettuce-io/lettuce-core.

Ask for volunteer to contribute.

**Comment by wu-sheng** [comment]
I move this pr to 5.0.0 beta, because our codes of 5.0.0 alpha is about to be frozen. Same as #832

**Comment by zhaoyuguang** [comment]
I wrote the 5.x version of the plugin. If you still need to pay attention to https://github.com/apache/incubator-skywalking/pull/2152

**Comment by wu-sheng** [comment]
Provided.
