### ISSUE TITLE
[collector]how to set es auth configure?

### ISSUE THREAD

**Issue by cyberdak** [apache/incubator-skywalking#773]
- Why do you submit this issue?
- [x] Question or discussion

___
### Question
- What do you want to know?
how to set es auth configure?
___

### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

 at https://github.com/apache/incubator-skywalking/blob/master/docs/cn/Deploy-collector-in-standalone-mode-CN.md this doc , i can't find how to set auth info with es which installed x-pack or search-guard.

**Comment by wu-sheng** [comment]
@peng-yongsheng I think this is not supported yet, right? @cyberdak Do you have interests to submit a pull request to add this feature?

**Comment by cyberdak** [comment]
I think this is a ***BIG*** move switch es client from high-api client (use 9300 port) to http rest client (use 9200 via http) which can support ssl / TLS and x-pack or search-guard or nginx basic-auth.

btw , elastic plan **deprecat**  high-api client in the future.

i think we can use okhttp as es client like zipkin.

Give me some time to read the code about skywalking's es client.

**Comment by wu-sheng** [comment]
Yes, it is **BIG**. But it depends on which one is better. Let's list something.
* `x-pack` is commercial related, so, many open source users can't use it. 
* SSL or nginx-auth is for security reason, right? But do that worth about adding security features in ES connection. 
* `elastic plan deprecat high-api client in the future`. This is important, where can we confirm that information? and which library does the ElasticSearch recommend officially?

**Comment by peng-yongsheng** [comment]
> We plan on deprecating the TransportClient in Elasticsearch 7.0 and removing it completely in 8.0. Instead, you should be using the Java High Level REST Client, which executes HTTP requests rather than serialized Java requests. The migration guide describes all the steps needed to migrate.
Change the client from java to rest is necessary. The rest api is exactly similar to the java api. And from this notice, I didn't see any reason about performance, and the version 7.0 to be deprecating, 8.0 removed, that maybe one year later. So I think we can't do it in a short time or you can help us to do it on 5.0 version. This version will release next month.
> When you initially install X-Pack, a 30 day license is generated that allows access to X-Pack features.
 I don't think provide the x-pack is necessary. To be a stand alone plugin project maybe better.

**Comment by cyberdak** [comment]
x-pack is commercial .but es has some free security solutions.like search-guard[https://github.com/floragunncom/search-guard] and elasticsearch-readonlyrest-plugin[https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin].

**Comment by wu-sheng** [comment]
@cyberdak Yes. it has. If you truly want to support that in our codes. I think you should send a pull request to make this happen. And we are welcome for that.

**Comment by wu-sheng** [comment]
@cyberdak Of source, I think the no-auth and no-security should stay in default, since not all end users need this feature.

**Comment by cyberdak** [comment]
Already started work on this.

**Comment by wu-sheng** [comment]
Cool. But ASF didn't allow commercial libraries dependencies. So must keep x-pack out of it. Default and open source auth and security things are good.

**Comment by cyberdak** [comment]
yes, we did't need x-pack.I use Jest for rest client.

**Comment by cyberdak** [comment]
coding done.I hava some trouble with test.can someone help me test this?

**Comment by wu-sheng** [comment]
What's your problem about tests? How can we help?

**Comment by cyberdak** [comment]
my fork : https://github.com/cyberdak/incubator-skywalking

issue is when i use elasticsearch-http,collector's 12800 api will be 404.but i can't found any error in log.

now it did't support ssl now.only test http is ok.

**Comment by wu-sheng** [comment]
@peng-yongsheng Do you have any clue about this?

**Comment by cyberdak** [comment]
I think it may be version's problem. i use 3.2.6 web-ui to connect alpha-5.0.0 collecter.
So how can i build a 5.0.0 web-ui.
i can't found a build & dev manual in web-ui'doc .

**Comment by wu-sheng** [comment]
There are two options
1. use 3.2.6 to do tests, because same connect and client mechanism in 3.x and 5.x
2. wait several days, 5.0.0-alpha will be ready.

**Comment by peng-yongsheng** [comment]
@wu-sheng close this issue?

**Comment by wu-sheng** [comment]
Yes, further discussion stays in the pr. Closing this.
