### ISSUE TITLE
啥时候能发布Spring Cloud的分布式应用模拟场景？

### ISSUE THREAD

**Issue by tanjianhui1979** [apache/incubator-skywalking#776]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion

___
### Question
看2017年9月的新闻说大神们会“使用Spring生态组件: Spring Cloud Config,Netflix Eureka, Spring Stream, Spring Cloud Bus, 构建一个模拟的分布式应用，并使用sky-walking展示秒级的分布式追踪”，啥时候能膜拜一下？

**Comment by tanjianhui1979** [comment]
已经找到，不知道是不是：）先谢谢了！
https://github.com/SkywalkingTest/spring-cloud-example

相关的测试都在这里：https://github.com/SkywalkingTest

Agent-Benchmarks（https://github.com/SkywalkingTest/Agent-Benchmarks）中的Benchmark-4对我很大帮助。

再次感谢！

**Comment by wu-sheng** [comment]
Glad you find your own answers. Need any help, let me know.
