### ISSUE TITLE
Grpc trace throw exception

### ISSUE THREAD

**Issue by douwanglong** [apache/incubator-skywalking#783]
Grpc 1.8   Skywalking 3.2.6 
ERROR 2018-01-30 11:28:30 InstMethodsInterWithOverrideArgs :  class[class io.grpc.internal.ClientCallImpl] before method[start] intercept failure 
java.lang.ClassCastException: io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1 cannot be cast to org.skywalking.apm.agent.core.plugin.interceptor.enhance.EnhancedInstance

**Comment by wu-sheng** [comment]
@ascrutae Please make sure the automatic tests run for gRPC plugins. This cast exception seems strange. @douwanglong Can you provide a demo app to reproduce this exception?

**Comment by ascrutae** [comment]
Can you give me an demo ? @douwanglong

**Comment by douwanglong** [comment]
@ascrutae  
This exception occur when  Grpc version 1.7+ , I change  grpc'version 1.6,  trace is correct ,  the demo which used is official example of grpc ，you can try and check  by  use  vesion 1.8 of grpc

**Comment by ascrutae** [comment]
OK, I will try it. Thx

**Comment by wu-sheng** [comment]
Resolved by #790 , here is the test report: https://github.com/SkywalkingTest/agent-integration-test-report/blob/master/2018/2/ascrutae/testReport-master-2018-02-06-17-05.md
