### ISSUE TITLE
agent  spring-plugins  aop

### ISSUE THREAD

**Issue by xjr100419** [apache/incubator-skywalking#784]
version>3.2.6-2017

 Question 

- What happen:

我本地 加了aop 引用了自定义业务类
现在 探针报错 报找不到类
java.lang.ClassCastException: org.skywalking.apm.plugin.spring.mvc.commons.EnhanceRequireObjectCache cannot be cast to com.*.*.framework.response.RspData

这个要怎么处理好吗

___
Translation by @wu-sheng

When use AOP to a custom class, trigger the following exception:
> java.lang.ClassCastException: org.skywalking.apm.plugin.spring.mvc.commons.EnhanceRequireObjectCache cannot be cast to com.*.*.framework.response.RspData

Why?

**Comment by wu-sheng** [comment]
@xjr100419 All question must be in English. Please follow Apache rule.

**Comment by wu-sheng** [comment]
Can you provide `RspData` source code? Why is its source code manipulated by SkyWalking? Exist an annotation or what?

**Comment by xjr100419** [comment]
RspData.java
`package com.candao.dms2.gps.aop;

/**
 * 响应数据
 * @author xiao
 */
public class RspData {
	
	/**
	 * 响应状态 {link RspStatus}
	 */
	public int status;
	
	/**
	 * 响应状态描述
	 */
	public String msg;
	
	/**
	 * 响应具体数据
	 */
	public Object data;
	
	// 默认成功

	public RspData(Object data) {
		this.data = data;
	}

	public RspData() {
	}
	

	/**
	 * 返回一个失败的RspData<br/>
	 * @param status-自定义状态
	 * @param msg-自定义信息
	 * @return
	 */
	public static RspData getFailRspData(int status, String msg) {
		RspData rspData = new RspData();
		rspData.status = status;
		rspData.msg = msg;
		return rspData;
	}
	

	@Override
	public String toString() {
		return "RspData [status=" + status + ", msg=" + msg + ", data=" + data + "]";
	}
	
}`

ExceptionInterceptorAspect.java
`package com.candao.dms2.gps.aop;

import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Pointcut;
import org.springframework.stereotype.Component;

/**
 *  拦截器  处理异常包装类
 * 
 * @author xiao
 * @date 2017年12月27日 下午7:30:55
 */
@Aspect  
@Component 
public class ExceptionInterceptorAspect {
	
	@Pointcut("execution(* com.candao.dms2.gps.controller..*(..)) and @annotation(org.springframework.web.bind.annotation.RequestMapping)")
	public void controllerMethodPointcut(){}
	
	@Around("controllerMethodPointcut()")
	public Object handlerControllerMethod(ProceedingJoinPoint pjp) {
		
		long startTime = System.currentTimeMillis();
		
		RspData repData;
		
		try {
			repData = (RspData) pjp.proceed();
			
			System.out.println(pjp.getSignature() + "use time:" + (System.currentTimeMillis() - startTime));
			
		} catch (Throwable e) {
			repData = handlerException(pjp, e);
			e.printStackTrace();
		}
		
		return repData;
	}
	
	private RspData handlerException(ProceedingJoinPoint pjp, Throwable e) {
		RspData result = new RspData();
		

		return result;
	}
}
`

**Comment by wu-sheng** [comment]
@xjr100419 Thanks. @ascrutae will check for you. The first step is that make sure whether it fixed in 5.0-alpha. We already did a lot of compatible adjustments.

**Comment by clevertension** [comment]
<aop:aspectj-autoproxy  proxy-target-class="true"/>

please add **proxy-target-class=true**, the default proxy way in spring is jdk proxy, so it can't cast down to the specific class

**Comment by wu-sheng** [comment]
@clevertension I think that is the reason. Your way may help @xjr100419 to fix this in 3.2.6 . And further, we did a patch for the plugin to make sure the compatible with Spring core. That is why I want @ascrutae to run some tests under 5.0-alpha develop branch.

**Comment by xjr100419** [comment]
when I add  **proxy-target-class=true**
that was invalid

`spring.aop.proxy-target-class=true`

**Comment by clevertension** [comment]
can you add 
@EnableAspectJAutoProxy(proxyTargetClass=true) in your GpsApplication?

i see you are using the aspectj proxy

**Comment by xjr100419** [comment]
I check again
`@EnableAspectJAutoProxy(proxyTargetClass=true)`

that was the same problem

**Comment by clevertension** [comment]
please change your controllerMethodPointcut()

```
	@Pointcut("execution(@org.springframework.web.bind.annotation.RequestMapping * com.candao.dms2.gps.controller..*(..))")
	public void controllerMethodPointcut(){}
```

your annotation hook is not work, you can refer to this

http://forum.spring.io/forum/spring-projects/aop/59391-pointcut-with-annotation-does-not-work

@wu-sheng , i think this is not the skywalking issue, it is the aop pointcut configuration

**Comment by ascrutae** [comment]
@xjr100419  I cannot reproduce this issue in the latest version. 

BTW, I found an issue in your demo
the annotation in `ExceptionInterceptorAspect` class
`@Pointcut("execution(* com.candao.dms2.gps.controller..*(..)) and 
@annotation(org.springframework.web.bind.annotation.RequestMapping)")`

should be like this:

`@Pointcut("execution(* com.candao.dms2.gps.controller..*(..)) && @annotation(org.springframework.web.bind.annotation.RequestMapping)")`


if you don't have any question. I'm going to close this issue three days later

**Comment by xjr100419** [comment]
@ascrutae  @clevertension 
it was done
thank you very much
