### ISSUE TITLE
docker-compose.yml version is out of date

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#799]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
The current and official version for next release is `5.0.0-alpha`, and you still use `5.0-preview`. Please fix it.

**Comment by ascrutae** [comment]
This issue has fixed in PR #800
