### ISSUE TITLE
Support Apache ServiceComb by using its snapshot

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#825]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
The Snapshot of servicecomb's apache version has been released under ASF nexus: https://repository.apache.org/content/repositories/snapshots/org/apache/servicecomb/ . So I think we can provide the plugin for it.

**Comment by wu-sheng** [comment]
FYI @WillemJiang

**Comment by WillemJiang** [comment]
Current servicecomb-java-chassis version is 1.0.0-m1-SNAPSHOT.  Please use it to verify the plugin.

**Comment by wu-sheng** [comment]
Closing this. Plugin provided.
