### ISSUE TITLE
Add support for mssql jdbc monitoring

### ISSUE THREAD

**Issue by zone1511** [apache/incubator-skywalking#858]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [X] Feature or performance improvement
### Requirement or improvement
Currently H2,mysql,oracle and postgresql jdbc monitoring are supported. I can contribute the mssql jdbc monitoring component

**Comment by wu-sheng** [comment]
sure. welcome. And i think you are familiar with our plugin process. 

BTW, because rocketmq 3.x plugin has been merged, please send a pr to update supported list document.

**Comment by zone1511** [comment]
Does the 5.0 ui ready to use or I have to use old ui to test the plugin?

**Comment by wu-sheng** [comment]
@zone1511 The test just begin, follow #855  for update. And you should join gitter for our discussions and news post.

**Comment by wu-sheng** [comment]
@zone1511 And https://github.com/SkywalkingTest/skywalking-agent-testcases/blob/master/docs/how-to-write-a-plugin-testcase-cn.md this is a plugin test guide, if any plugin merged into master, you should follow.

**Comment by zone1511** [comment]
@wu-sheng after I run the local scenario test, I make a pr to https://github.com/SkywalkingTest/skywalking-agent-testcases as well?

**Comment by wu-sheng** [comment]
There is a cn document to guide you to provide test cases. https://github.com/SkywalkingTest/skywalking-agent-testcases/blob/master/docs/how-to-write-a-plugin-testcase-cn.md

All cases in that repo will run automatically daily.

**Comment by wu-sheng** [comment]
Not active, closing.
