### ISSUE TITLE
Alarm for calls between applications

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#862]
In 5.0.0-alpha, we provide alarm for nodes, but there is another type of alarm, which is about calls between application. The type of alarm will visualize as red line in topology graph, which means this kind of alarm is detected at client side RPCs.

**Comment by peng-yongsheng** [comment]
Is there anybody want to help me!!!!! Hard work.

**Comment by wu-sheng** [comment]
Alarm features are not the core features for now. Move to 5.1 for further evaluation.

**Comment by wu-sheng** [comment]
Not provide in v5
