### ISSUE TITLE
Build Error - Missing Proto

### ISSUE THREAD

**Issue by sdanzo** [apache/incubator-skywalking#874]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Is there another build step that's been added to generate the protobuf classes?
___
### Bug
- Which version of SkyWalking, OS and JRE?
Master

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
[build-issue.txt](https://github.com/apache/incubator-skywalking/files/1778979/build-issue.txt)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
We have document to guide you to build the project, https://github.com/apache/incubator-skywalking/blob/master/docs/en/How-to-build.md

**Comment by zone1511** [comment]
the protocol buffer code has moved to submodule, so not just clone the project, also need to clone the submodule

**Comment by sdanzo** [comment]
thank you
