### ISSUE TITLE
missing call in topology of micro-service developed by apache servicecomb

### ISSUE THREAD

**Issue by zhengyangyong** [apache/incubator-skywalking#877]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking:5.0.0-alpha-SNAPSHO
OS:win7
JRE:oracle jdk 1.8
Elasticsearch:5.6.8

- Which company or project?
ServiceComb

- What happen?
Consumer side call two service:
```java
  @GetMapping(path = "/audit")
  public Boolean audit(double amount) {
    if (amount <= 10000) {
      boolean resultSupervisor = restTemplate.getForObject("cse://Supervisor/audit?amount=" +
          String.format("%.2f", amount), Boolean.class);

      boolean resultFinance = restTemplate.getForObject("cse://Finance/audit?amount=" +
          String.format("%.2f", amount), Boolean.class);
      return resultFinance && resultSupervisor;
    }
    return false;
  }
```
Then in topology finance call is missing:
![tim 20180305113704](https://user-images.githubusercontent.com/374335/36956475-93e9d07a-2069-11e8-8f81-f8c8b3d197d8.png)

But in Trace we can see Span had correct record:
![tim 20180305111351](https://user-images.githubusercontent.com/374335/36956536-d99709bc-2069-11e8-9234-b2bacb58ff14.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
Great, thanks for you testing, I think we need your es data. Can you send me a `.zip` file? Or post it here?

**Comment by wu-sheng** [comment]
And I saw an `error` in your trace, and alarm in your topology, do you have any error in this distributed call?

**Comment by zhengyangyong** [comment]
[elasticsearch-data.zip](https://github.com/apache/incubator-skywalking/files/1779443/elasticsearch-data.zip)
[elasticsearch-logs.zip](https://github.com/apache/incubator-skywalking/files/1779445/elasticsearch-logs.zip)

**Comment by zhengyangyong** [comment]
There is no any error in this distributed call,also may incorrect notice of alarm:
![tim 20180305111851](https://user-images.githubusercontent.com/374335/36956900-dcbce150-206b-11e8-8a09-9f36115ca890.png)

**Comment by peng-yongsheng** [comment]
@zhengyangyong Hi.
* The topology is belongs to OverViewLayer or application?
* Should you give me the input of topology and alarm service like this? 
```
getClusterTopology(duration: {start: "2017-06-01 1002", end: "2017-06-01 1005", step: MINUTE})
```

**Comment by wu-sheng** [comment]
@zhangkewei You can find this query ini your browser, we are using graphQL query format.

**Comment by zhengyangyong** [comment]
I just use jmeter make requests with light pressure:
![tim 20180305143724](https://user-images.githubusercontent.com/374335/36960675-0629a084-2083-11e8-8eca-05ead2a3f97f.png)
Seems webapp ui problem ?

**Comment by wu-sheng** [comment]
The **User** is based on conjecture, so this graph is possible, such as: Approver agent register after Supervisor agent, at that moment, Superviosr agent will treat the incoming request as from **User**.

But all these explanations based on data. So we need you provide your graphql parameter in browser when you open this page.

**Comment by zhengyangyong** [comment]
@wu-sheng you mean this ?
![tim 20180305200007](https://user-images.githubusercontent.com/374335/36973960-ddbf211e-20af-11e8-80cd-156c9f880072.png)
I will do more test tomorrow

**Comment by wu-sheng** [comment]
No, it related to the implementation. Easy way is maybe happen on first several seconds, my guess 30-40seconds.
