### ISSUE TITLE
Sort segment in more sensible way

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#901]
In 5.0.0 alpha, when Kafka client consumes some messages from Server, they pull message, so in order to keep segment as expected, we suggest to add a local span in fetching message loop.

expected like this:
```
Kafka producer
   + - Local Span in the fetching loop
         + - Kafka consume
         + - Kafka consume
```

Actually, the `Local Span` is not our of the tree, before of no parent span, and no ref, like this:
```
    - Local Span in the fetching loop
Kafka producer
         + - Kafka consume
         + - Kafka consume
```

Hope to fix in beta.

**Comment by peng-yongsheng** [comment]
This is a bit complex implementation. Let me think about it. So many works have to do.

**Comment by wu-sheng** [comment]
I will move this into RC, considering this is not a functional issue, just for experience.

**Comment by wu-sheng** [comment]
@peng-yongsheng RC is not allowed to, or should say hope don't need, to add new feature. 

@hanahmily Can you confirm, do you want to do the new trace detail visualization based on segment in 5.1.0? If so, I think this issue will be not much useful.

**Comment by wu-sheng** [comment]
> This is not the responsibility of the collector which processes data from real nodes. The virtual nodes should be generated by the frontend one that has enough information about the trace.

> In conclusion, I prefer to close this issue.

@hanahmily I don't object to close this issue. But I want to make sure the requirement is tracked by the team. Are you saying, you prefer to optimize this in frontend? Even we do this, the graphql query protocol and backend trace query service need to adjust. 

So, could you open one  or two issues to track the requirement?

**Comment by wu-sheng** [comment]
Replace by #1336
