### ISSUE TITLE
Enhance apm-webapp log 

### ISSUE THREAD

**Issue by hanahmily** [apache/incubator-skywalking#931]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

### Requirement or improvement
- Enhance apm-webapp log. Redirect log to a rotating file.

**Comment by wu-sheng** [comment]
I hope this feature could be a part of #843
