### ISSUE TITLE
Support override config from system.properties and system.env

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#933]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

Collector should support config override from system.properties and system.env, which will support dynamic deployment well, especially in container env.

**Comment by peng-yongsheng** [comment]
Finish it after tomorrow.

**Comment by wu-sheng** [comment]
Provided and done by me. Closing it.
