### ISSUE TITLE
 Click the Application Menu, Topological graph may Invalid

### ISSUE THREAD

**Issue by bai-yang** [apache/incubator-skywalking#937]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Bug
SkyWalking Version: 5.0.0-alpha
OS: MacOs Sierra 10.12.1
JRE: 1.8.0_131

SkyWalking Web UI Bug：When I click the Application Menu, I have an occasional problem，Topological graph may Invalid；
<img width="710" alt="bug1" src="https://user-images.githubusercontent.com/20091216/37341971-39435f1a-26fe-11e8-9eac-61a13cb13beb.png">
<img width="1045" alt="bug2" src="https://user-images.githubusercontent.com/20091216/37342040-672aab5e-26fe-11e8-9cb6-9134cdb7afa7.png">

Request：
`http://127.0.0.1:8080/api/application`
param：
`{"variables":{"duration":{"start":"2018-03-13 1956","end":"2018-03-13 2056","step":"MINUTE"},"applicationId":"-1"},"query":"\n  query Application($applicationId: ID!, $duration: Duration!) {\n    getSlowService(applicationId: $applicationId, duration: $duration, topN: 10) {\n      key: id\n      name\n      avgResponseTime\n    }\n    getServerThroughput(applicationId: $applicationId, duration: $duration, topN: 10) {\n      key: id\n      name\n      callsPerSec\n    }\n    getApplicationTopology(applicationId: $applicationId, duration: $duration) {\n      nodes {\n        id\n        name\n        type\n        ... on ApplicationNode {\n          sla\n          callsPerSec\n          avgResponseTime\n          apdex\n          isAlarm\n          numOfServer\n          numOfServerAlarm\n          numOfServiceAlarm\n        }\n      }\n      calls {\n        source\n        target\n        isAlert\n        callType\n        callsPerSec\n        avgResponseTime\n      }\n    }\n  }\n"}`

Response：
`{
 "data": {
  "getSlowService": [{
   "key": "-3",
   "name": "/test/queryTest",
   "avgResponseTime": 876
  }],
  "getServerThroughput": [{
   "key": "2",
   "name": "by-test_130.30.184.150",
   "callsPerSec": 0
  }],
  "getApplicationTopology": {
   "nodes": [{
    "id": "-1",
    "name": "by-test",
    "type": "SpringMVC",
    "sla": 100,
    "callsPerSec": 0,
    "avgResponseTime": 876,
    "apdex": 100,
    "isAlarm": false,
    "numOfServer": 1,
    "numOfServerAlarm": 0,
    "numOfServiceAlarm": 0
   }, {
    "id": "2",
    "name": "rm-postgre.net:5544",
    "type": "PostgreSQL"
   }, {
    "id": "1",
    "name": "User",
    "type": "USER"
   }],
   "calls": [{
    "source": "-1",
    "target": "2",
    "isAlert": false,
    "callType": "PostgreSQL",
    "callsPerSec": 0,
    "avgResponseTime": 69
   }, {
    "source": "1",
    "target": "-1",
    "isAlert": false,
    "callType": "",
    "callsPerSec": 0,
    "avgResponseTime": 876
   }]
  }
 }
}`

**Comment by wu-sheng** [comment]
Wait and see what happens in beta release.

**Comment by wu-sheng** [comment]
I will close this for now. No further report since alpha release.
