### ISSUE TITLE
PostgreSql Plugin Icon missing 

### ISSUE THREAD

**Issue by bai-yang** [apache/incubator-skywalking#938]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
SkyWalking Version: 5.0.0-alpha
OS: MacOs Sierra 10.12.1
JRE: 1.8.0_131
PostgreSql:  9.4.12.12

Topological graph lost PostgreSql Plugin Icon,
<img width="942" alt="bug3" src="https://user-images.githubusercontent.com/20091216/37342625-206b018a-2700-11e8-936e-7786ae5e5f2f.png">

**Comment by ascrutae** [comment]
Ref PR: apache/incubator-skywalking-ui#159
