### ISSUE TITLE
[skywalking-ui]Application log can't append to webapp.log

### ISSUE THREAD

**Issue by zhangkewei** [apache/incubator-skywalking#941]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

__
### Bug
- Which version of SkyWalking, OS and JRE?
 SkyWalking：5.0.0-alpha
 JRE: 1.8.0_131
 OS: CentOS release 6.7 x64
 Storage: elasticsearch 5.5
- What happen?
  You can set '--logging.file=xxxx ' in webappService.sh

**Comment by wu-sheng** [comment]
Same as https://github.com/apache/incubator-skywalking/issues/931
