### ISSUE TITLE
[collector]Support the newest elasticsearch version

### ISSUE THREAD

**Issue by zhangkewei** [apache/incubator-skywalking#942]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [] Question or discussion
- [ ] Bug
- [x] Requirement
- [] Feature or performance improvement

___
When i use elasticsearch 5.6.2 in 5.0.0-alpha, I got error message in es like this 

```
java.lang.IllegalStateException: Received message from unsupported version: [5.5.0] minimal compatible version is: [5.6.0]
```
Can you update elasticsearch client from 5.5 to 5.6?

**Comment by peng-yongsheng** [comment]
I don't think update the elasticsearch version to 5.6.2 is a good idea. 
I think we have two choice: 
1. Update to 5.6.8, this is 5.x.x's final version.
1. Update to 6.x.x, use the http rest client, because of transport client will be disappear when 7.x release.

**Comment by wu-sheng** [comment]
I prefer to update after our features stable.

**Comment by wu-sheng** [comment]
Support in v6
