### ISSUE TITLE
[help] when release 5.0.0

### ISSUE THREAD

**Issue by myoss** [apache/incubator-skywalking#943]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [Question ] Question or discussion

___
### Question
- when release 5.0.0?
There are too many bugs in the current version(v3.2.6)

**Comment by wu-sheng** [comment]
Test for 5.0.0 alpha should use tag **apm-5.0.0-alpha **. If you are interested for release, please subcribe `dev@skywalking.apache.org` mail list. Send a mail to dev-subscribe@skywalking.apache.org` and follow the reply.

**Comment by wu-sheng** [comment]
You will see [ANNOUNCE] [VOTE] titles mails. Those are what are really happening in Apache Incubator. More things are not just about codes, they are about Apache Way.

**Comment by wu-sheng** [comment]
Test release is here : https://repository.apache.org/content/repositories/orgapacheskywalking-1002/org/apache/skywalking/apm-dist/5.0.0-alpha/  But the url will not be valid all the time.
