### ISSUE TITLE
Related traces can't display

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#947]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
5.0.0-alpha , live demo env

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
1. Can't open the other batch consume side trace segment at the same time, and no tip.
1. Nothing shows up in `Related Trace`.

**Comment by hanahmily** [comment]
Fix in https://github.com/apache/incubator-skywalking-ui/commit/d4a0ee8c4955c06f924a139b09b7037a38beffee
