### ISSUE TITLE
skywalking集成logback日志问题

### ISSUE THREAD

**Issue by shanShanKate** [apache/incubator-skywalking#948]
集成logback` ， 如果配置了 异步输出加载

`<appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">`
	`<queueSize>512</queueSize>`
	`<appender-ref ref="FILE" />`
`</appender>`

探针TID就不会输出，  如果去掉这块配置TID正常， 请问是什么原因？

**Comment by wu-sheng** [comment]
First of all, the issue must be in English for global people.

**Comment by wu-sheng** [comment]
And `ch.qos.logback.classic.AsyncAppender` is new to me, maybe you can give us a demo application to reproduce the error?

You should answers the questions in issue templete, which you deleted.

**Comment by candyleer** [comment]
This problem can be solved by slf4j `MDC` mechanism， `put and get method`like a `threadlocal map`, in async or sync log env, they have their own logic to guarantee `MDC.get(key)` can get the right value.
