### ISSUE TITLE
localhost:10800 404 error

### ISSUE THREAD

**Issue by Sidneyxt** [apache/incubator-skywalking#962]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
question
___
### quesion
- Which version of SkyWalking, OS and JRE?
3.2.6
- Which company or project?
skywalking-controller
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
I just follow this [doc](https://github.com/apache/incubator-skywalking/blob/master/docs/en/Deploy-backend-in-standalone-mode.md).  8080, 10800, 11800, 12800 are free.My system is macos.
![image](https://user-images.githubusercontent.com/20471875/37585271-85fb2c4a-2b93-11e8-95ee-76364bc72a61.png)
I visit localhost:10800 get this
![image](https://user-images.githubusercontent.com/20471875/37585351-cf1bfd5a-2b93-11e8-9d72-5a972ca973f0.png)
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
UI is a separated process which listens 8080 by default. 10800 is providing the query service, not for the web page.

**Comment by Sidneyxt** [comment]
![image](https://user-images.githubusercontent.com/20471875/37586412-36023464-2b97-11e8-804c-84a051d433e8.png)
运行了skywalking-web 之后才能访问 localhost:8080 感觉文档中好像没有提到这个.
或许是写在别处,我没有注意到吧.
