### ISSUE TITLE
Jedis error

### ISSUE THREAD

**Issue by xyydcoo** [apache/incubator-skywalking#972]
log:
ERROR 2018-03-21 09:54:57 SkyWalkingAgent :  Enhance class redis.clients.jedis.JedisCluster error. 
org.apache.skywalking.apm.agent.core.plugin.PluginException: Can't create InstanceConstructorInterceptor.

Caused by: java.lang.ClassNotFoundException: Can't find Jorg.apache.skywalking.apm.plugin.jedis.v2.edisClusterConstructorWithListHostAndPortArgInterceptor

redis version:jedis 2.9.0 

On the page, the IP is shown to be null

skywalking version:5.0

**Comment by wu-sheng** [comment]
@ascrutae Hi Xin, I think you should notice Jedis 2.9.0 is using in our end user. And we haven't run test cases in here: https://github.com/SkywalkingTest/agent-integration-test-report#jedis . I assume it will go to fail based on this report.

**Comment by candyleer** [comment]
haha ,this is the same issue for spell error in #1021  which has been fixed right now in latest master branch

**Comment by wu-sheng** [comment]
:) Yes, you are right. Closing this.
