### ISSUE TITLE
Topology show  error

### ISSUE THREAD

**Issue by xyydcoo** [apache/incubator-skywalking#973]
Display errors, the number of instances when an application is used is shown to be 0, with multiple instances beginning to show normal and then 0.

version:apache-skywalking5.0

**Comment by wu-sheng** [comment]
@peng-yongsheng You should pay attention about this in your automatic backend test cases. 

@xyydcoo Please provide es data, and query in Browser, in order to help us reproduce the scenario.

**Comment by xyydcoo** [comment]
[参数.txt](https://github.com/apache/incubator-skywalking/files/1836779/default.txt)
es数据链接：https://pan.baidu.com/s/19t_L02m3iMQRzevDS8y3SQ 密码：s04q

**Comment by wu-sheng** [comment]
FYI @hanahmily I think you may be interested in the topology based on this data.

**Comment by wu-sheng** [comment]
We will see what happens in beta release.
