### ISSUE TITLE
Purpose of tag method in AbstractSpan

### ISSUE THREAD

**Issue by zone1511** [apache/incubator-skywalking#978]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [X] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
in `AbstractSpan` there is a tag method,  will the tag value pass to collector and ui? Can we add the `getTags` method in `AbstractSpan` as well?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
why do you need gettag in span? can you provide scenario?

**Comment by zone1511** [comment]
Need to pass data around before and after method invokation. Does the span a go place to store? If not, where to store the temp data appear in the before/after method invocation? And what’s the original purpose of tag in span?

**Comment by wu-sheng** [comment]
Yes, that depends how does your intercepted object use in thread? if no concurrency situation, you can use dynamic field to propagate. If has, use your own thread local, or proposal to add runtime context for TracingContext.

**Comment by zone1511** [comment]
Does the before and after method interceptor guarantee to run on same thread?
What is the original purpose of Tag in span?

**Comment by wu-sheng** [comment]
Yes, they are always in one thread, guarantee by Javs stack module, not by SkyWalking. But you must be careful of concurrency. For tags, those are from OpenTracing, which tag the info for backend analysis, aggregation and visualization.

**Comment by zone1511** [comment]
@wu-sheng for adding runtime context for TracingContext, where should I get start from?

**Comment by wu-sheng** [comment]
@zone1511 contextmanager should the entrance, add a method there. The context interface and implementations  also need to change.

**Comment by zone1511** [comment]
@wu-sheng while implementing the tracing context, I just raise a question about the possbility for the inteceptor code to pass data to the app code (not the class being intercepted) which being monitoring?

**Comment by wu-sheng** [comment]
@zone1511 This is a separated issue, we should start a new issue to discuss that. Changing appcode in runtime is a complex process.
